// libs/gui/vue/src/lib/components/Dropdown.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useDebounceCallback, useInputWidget, useVueFormContext } from '@golemui/vue';
import type { DropdownProps, ListItem, OptionValue } from '@golemui/gui-shared/internals';
import { computed, onMounted, onUnmounted, ref, watch, type Component } from 'vue';
import DefaultListItemRenderer from './item-renderers/DefaultListItemRenderer.vue';
import '@golemui/gui-components/label';
import '@golemui/gui-components/list';
import '@golemui/gui-components/errors';

interface GuiListElement extends HTMLElement {
  focusItemAtIndex(index: number): void;
  scrollToSelectedIndex(): void;
}
interface GuiLabelElement extends HTMLElement {
  targetElement?: HTMLElement | HTMLElement[];
}

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<string | null>;
const { uid, errors, value, isTouched, templateData, onFilter, onValueChanged, onBlur } =
  useInputWidget<string | number | null, DropdownProps<never>>(widget);

const rangeStart = ref(0);
const rangeEnd = ref(10);
const listItems = ref<ListItem<never>[]>([]);
const filteredItems = ref<ListItem<never>[]>([]);
const focusedIndex = ref<number>(-1);
const isFiltering = ref(false);
const isListVisible = ref(false);
const selectedItem = ref<ListItem<never> | undefined>(undefined);

const listRef = ref<GuiListElement | null>(null);
const panelRef = ref<HTMLDivElement | null>(null);
const inputRef = ref<HTMLInputElement | null>(null);
const labelRef = ref<GuiLabelElement | null>(null);
const widgetRef = ref<HTMLDivElement | null>(null);

const visibleItems = computed(() => listItems.value.slice(rangeStart.value, rangeEnd.value));

const required = computed(() => (templateData.value.validator as Validator)?.required);
const isDisabled = computed(() => templateData.value.disabled as boolean);
const isReadOnly = computed(() => templateData.value.readonly as boolean);
const asyncFiltering = computed(() => !!widget.on?.filter);
const showErrors = computed(() => isTouched.value && errors.value && errors.value.length > 0);

const closeList = () => {
  onBlur();
  isListVisible.value = false;
  isFiltering.value = false;
};

const handleValueChange = (newValue: OptionValue | null) => {
  onValueChanged(newValue);
  if (inputRef.value) {
    const items = templateData.value.items || [];
    const match = items.find((item: any) =>
      templateData.value.valueField
        ? item[templateData.value.valueField] === newValue
        : item === newValue,
    );
    if (match) {
      const displayValue = templateData.value.valueField
        ? (match as any)[templateData.value.valueField]
        : match;
      inputRef.value.value = String(displayValue);
    } else if (!newValue) {
      inputRef.value.value = '';
    }
  }
  isListVisible.value = false;
  isFiltering.value = false;
};

const handleClickItem = (item: ListItem<never>, index: number) => {
  if (templateData.value.readonly || item.disabled) return;
  handleValueChange(item.value);
  onFilter('' as never);
  focusedIndex.value = index;
  selectedItem.value = item;
  isFiltering.value = false;
  isListVisible.value = false;
  listRef.value?.focusItemAtIndex(index);
};

const handleRangeChange = (e: Event) => {
  const { startIndex, endIndex } = (e as CustomEvent).detail;
  rangeStart.value = startIndex;
  rangeEnd.value = endIndex;
};

const handleUpdateItems = (e: Event) => {
  const items = (e as CustomEvent).detail;
  listItems.value = items ? [...items] : [];
  if (!selectedItem.value && value.value != null && items) {
    const match = items.find((item: ListItem<never>) => item.value === value.value);
    if (match) selectedItem.value = match;
  }
};

const handleFocusChange = (e: Event) => {
  focusedIndex.value = (e as CustomEvent).detail.index;
};

const handleListChange = (e: Event) => {
  const val = (e as CustomEvent).detail.value;
  handleValueChange(val);
  selectedItem.value = listItems.value.find((item) => item.value === val);
  isFiltering.value = false;
  isListVisible.value = false;
};

const handlePanelMouseDown = (event: MouseEvent) => {
  const target = event.target as Node;
  if (listRef.value && listRef.value.contains(target)) return;
  event.preventDefault();
};

const handleDocumentClick = (event: MouseEvent) => {
  if (!isListVisible.value) return;
  const target = event.target as Node;
  const clickedInput = inputRef.value && inputRef.value.contains(target);
  const clickedPanel = panelRef.value && panelRef.value.contains(target);
  if (!clickedInput && !clickedPanel) closeList();
};

onMounted(() => {
  document.addEventListener('click', handleDocumentClick);
  if (labelRef.value && inputRef.value && listRef.value) {
    labelRef.value.targetElement = [inputRef.value, listRef.value];
  }
  if (inputRef.value) {
    inputRef.value.value = String(value.value ?? '');
  }
});

onUnmounted(() => {
  document.removeEventListener('click', handleDocumentClick);
});

watch([selectedItem, () => templateData.value.labelField], () => {
  const item = selectedItem.value;
  const isObject = item?.template !== null && typeof item?.template === 'object';
  const referenceField = isObject ? (templateData.value.labelField ?? 'label') : null;
  const val = referenceField ? (item?.template as any)[referenceField] : item?.template;
  if (inputRef.value) inputRef.value.value = (val ?? '') as string;
});

const handleInputKeyDown = (event: KeyboardEvent) => {
  switch (event.key) {
    case 'ArrowDown':
      event.preventDefault();
      isListVisible.value = true;
      setTimeout(() => {
        listRef.value?.focus();
        listRef.value?.scrollToSelectedIndex();
      }, 0);
      break;
    case 'Enter':
      if (!inputRef.value?.value) handleValueChange(null);
      break;
  }
};

const filterItems = (filterValue: string) => {
  const async = !!widget.on?.filter;
  onFilter(filterValue as never);

  if (filterValue && !async) {
    isFiltering.value = true;
    isListVisible.value = true;

    const searchFields =
      templateData.value.searchFields ??
      ([templateData.value.labelField!, templateData.value.valueField!].filter(
        (f) => !!f,
      ) as string[]);
    const hasSearchFields = searchFields.length > 0;
    const items = templateData.value.items || [];
    const filtered = items.filter((item: any) => {
      const isPrimitive = item === null || typeof item !== 'object';

      if (isPrimitive) {
        return item != null && item.toString().toLowerCase().includes(filterValue.toLowerCase());
      }

      const keys = Object.keys(item);
      const reduceFn = (acc: boolean, prop: string) =>
        acc || item[prop].toString().toLowerCase().includes(filterValue.toLowerCase());

      return hasSearchFields
        ? keys.filter((p: string) => searchFields.includes(p)).reduce(reduceFn, false)
        : keys.reduce(reduceFn, false);
    });
    filteredItems.value = filtered;
  } else {
    isFiltering.value = false;
    filteredItems.value = [...(templateData.value.items || [])];
  }
};

const debouncedFilter = useDebounceCallback(filterItems, templateData.value.inputDebounce ?? 500);

const handleInputFilter = (event: Event) => {
  const target = event.target as HTMLInputElement;
  if (!isListVisible.value) isListVisible.value = true;
  debouncedFilter(target.value);
};

const handleInputFocus = () => {
  if (ignoreNextFocus) return;
  if (isListVisible.value) return;
  isListVisible.value = true;
  setTimeout(() => listRef.value?.scrollToSelectedIndex(), 0);
};

let ignoreNextFocus = false;
const handleWidgetKeyDown = (event: KeyboardEvent) => {
  if (event.key !== 'Escape' || !isListVisible.value) return;
  event.preventDefault();
  event.stopPropagation();
  isListVisible.value = false;
  isFiltering.value = false;
  ignoreNextFocus = true;
  inputRef.value?.focus();
  setTimeout(() => {
    ignoreNextFocus = false;
  });
};

const handleFocusOut = (e: FocusEvent) => {
  const newFocus = e.relatedTarget as Node;
  if (newFocus && widgetRef.value?.contains(newFocus)) return;
  closeList();
};

const handleToggleMouseDown = (event: MouseEvent) => {
  event.preventDefault();
};

const handleToggleClick = (event: MouseEvent) => {
  event.stopPropagation();
  if (isListVisible.value) {
    isListVisible.value = false;
    isFiltering.value = false;
    ignoreNextFocus = true;
    inputRef.value?.focus();
    setTimeout(() => {
      ignoreNextFocus = false;
    });
  } else {
    inputRef.value?.focus();
    handleInputFocus();
  }
};

const formContext = useVueFormContext();
const ItemRenderer = computed<Component>(() => {
  const renderers = formContext.itemRenderers as Record<string, Component>;
  return (
    renderers[templateData.value.itemRenderer as string] || (DefaultListItemRenderer as Component)
  );
});
</script>

<template>
  <div class="gui-dropdown gui-field" :style="{ flex: templateData.size }">
    <gui-label
      ref="labelRef"
      :uid="uid"
      :label="templateData.label"
      :hint="templateData.hint"
      :errors="errors"
      :touched="isTouched"
      :required="required"
      :native="false"
    ></gui-label>

    <div
      ref="widgetRef"
      class="gui-widget"
      @keydown="handleWidgetKeyDown"
      @focusout="handleFocusOut"
    >
      <span
        v-if="templateData.icon"
        class="gui-widget-icon"
        :class="templateData.icon"
        :data-icon="templateData.icon"
        aria-hidden="true"
      ></span>
      <input
        ref="inputRef"
        type="text"
        role="combobox"
        :id="uid"
        :data-cy="`${uid}_textinput`"
        class="gui-widget-input"
        :class="{ 'gui-dropdown--icon': !!templateData.icon }"
        :required="required"
        :disabled="isDisabled"
        :readonly="isReadOnly"
        :placeholder="templateData.placeholder ?? ''"
        :autocomplete="templateData.autocomplete ?? undefined"
        :aria-expanded="isListVisible ? 'true' : 'false'"
        :aria-controls="`${uid}-list`"
        aria-autocomplete="list"
        :aria-labelledby="templateData.label ? `${uid}_label` : undefined"
        :aria-describedby="templateData.hint ? `${uid}_hint` : undefined"
        @keydown="handleInputKeyDown"
        @input="handleInputFilter"
        @focus="handleInputFocus"
      />
      <button
        type="button"
        class="gui-dropdown__arrow"
        :aria-label="templateData.toggleAriaLabel ?? 'Show options'"
        aria-haspopup="listbox"
        :aria-expanded="isListVisible ? 'true' : 'false'"
        :aria-controls="`${uid}-list`"
        :disabled="isDisabled"
        @mousedown="handleToggleMouseDown"
        @click="handleToggleClick"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="16"
          height="16"
          viewBox="0 0 256 256"
          aria-hidden="true"
        >
          <path
            d="M213.66,101.66l-80,80a8,8,0,0,1-11.32,0l-80-80A8,8,0,0,1,53.66,90.34L128,164.69l74.34-74.35a8,8,0,0,1,11.32,11.32Z"
          ></path>
        </svg>
      </button>

      <div
        class="gui-picker__panel"
        :hidden="!isListVisible"
        ref="panelRef"
        @mousedown="handlePanelMouseDown"
      >
        <gui-list
          ref="listRef"
          :id="`${uid}-list`"
          :uid="uid"
          :value="value ?? ''"
          :valueField="templateData.valueField"
          :items="isFiltering && !asyncFiltering ? filteredItems : templateData.items"
          :itemHeight="templateData.itemHeight"
          :height="templateData.height"
          :required="required"
          :touched="isTouched"
          :disabled="isDisabled || isReadOnly"
          :readOnly="isReadOnly"
          :hidden="!isListVisible"
          @focus="handleInputFocus"
          @change="handleListChange"
          @gui-update-items="handleUpdateItems"
          @gui-range-change="handleRangeChange"
          @gui-focus-change="handleFocusChange"
        >
          <div
            v-for="(item, idx) in visibleItems"
            :key="rangeStart + idx"
            role="option"
            tabindex="-1"
            class="gui-list__item-wrapper"
            :id="`${uid}-item-${rangeStart + idx}`"
            :style="{ height: `${templateData.itemHeight || 40}px` }"
            :aria-selected="value === item.value"
            :aria-disabled="isDisabled || item.disabled ? 'true' : 'false'"
            @click="handleClickItem(item, rangeStart + idx)"
          >
            <component
              :is="ItemRenderer"
              :template="
                (() => {
                  const labelField = templateData.labelField ?? 'label';
                  const isObject = item.template !== null && typeof item.template === 'object';
                  return isObject && labelField && !templateData.itemRenderer
                    ? (item.template as any)[labelField]
                    : item.template;
                })()
              "
              :value="item.value"
              :index="rangeStart + idx"
              :selected="value === item.value"
              :disabled="isDisabled || isReadOnly || !!item.disabled"
              :focused="focusedIndex === rangeStart + idx"
            />
          </div>
        </gui-list>
        <gui-errors
          v-if="showErrors"
          :panel.prop="true"
          :uid="uid"
          :errors="errors"
          :touched="isTouched"
        ></gui-errors>
      </div>
    </div>

    <gui-errors v-if="showErrors" :uid="uid" :errors="errors" :touched="isTouched"></gui-errors>
  </div>
</template>

// libs/gui/angular/src/lib/components/dropdown/dropdown.component.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  computed,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  HostListener,
  inject,
  type OnDestroy,
  type OnInit,
  signal,
  viewChild,
} from '@angular/core';
import { type AngularItemRenderer, InputWidgetAdapter } from '@golemui/angular';
import type { InputWidget, WithWidget } from '@golemui/core';
import type { DropdownProps, ListItem } from '@golemui/gui-shared/internals';
import { debounceTime, Subject, type Subscription } from 'rxjs';
import { DefaultListItemRenderer } from '../list/default-list.item-renderer';
import '@golemui/gui-components/label';
import '@golemui/gui-components/list';
import '@golemui/gui-components/errors';

@Component({
  standalone: true,
  selector: 'gui-dropdown-control',
  imports: [CommonModule],
  providers: [InputWidgetAdapter],
  templateUrl: './dropdown.component.html',
  host: {
    class: 'gui-dropdown gui-field',
    '[style.flex]': 'this.adapter.templateData().size',
  },
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class DropdownComponent implements OnInit, OnDestroy, WithWidget {
  widget!: InputWidget<string>;

  protected adapter: InputWidgetAdapter<string, DropdownProps<never>> = inject(InputWidgetAdapter);
  private el = inject(ElementRef);

  inputRef = viewChild.required<ElementRef>('inputRef');
  listRef = viewChild.required<ElementRef>('listRef');

  protected defaultListItemRenderer: AngularItemRenderer<string> = DefaultListItemRenderer;

  protected currentRange = signal({ start: 0, end: 10 });
  protected listItems = signal<ListItem<never>[]>([]);
  protected focusedIndex = signal<number>(-1);
  protected isListVisible = signal(false);
  protected isFiltering = signal(false);
  private ignoreNextFocus = false;

  protected selectedItem = signal<ListItem<never> | undefined>(undefined);
  protected filteredItems = signal<ListItem<never>[]>([]);

  protected asyncFiltering = computed(() => {
    return !!this.widget.on?.filter;
  });

  protected displayItems = computed(() => {
    const data = this.adapter.templateData();
    if (this.isFiltering() && !this.asyncFiltering()) {
      return this.filteredItems();
    }
    return data.items || [];
  });

  protected visibleItems = computed(() => {
    const items = this.listItems();
    const { start, end } = this.currentRange();
    return items.slice(start, end);
  });

  protected selectedItemValue = computed(() => {
    const data = this.adapter.templateData();
    const isObject =
      this.selectedItem()?.template !== null && typeof this.selectedItem()?.template === 'object';
    const referenceField = isObject ? (data.labelField ?? 'label') : null;

    return referenceField
      ? this.selectedItem()?.template[referenceField]
      : this.selectedItem()?.template;
  });

  protected debouncer = new Subject<string>();
  protected subscriptions: Subscription[] = [];

  ngOnInit(): void {
    this.adapter.init(this.widget);

    this.subscriptions.push(
      this.debouncer
        .pipe(debounceTime(this.adapter.templateData().inputDebounce ?? 500))
        .subscribe((value: string) => {
          this.inputValue(value);
        }),
    );
  }

  ngOnDestroy(): void {
    this.subscriptions.forEach((s) => s.unsubscribe());
    this.adapter.destroy();
  }

  @HostListener('document:click', ['$event'])
  onDocumentClick(event: MouseEvent) {
    if (!this.isListVisible()) return;

    if (!this.el.nativeElement.contains(event.target)) {
      this.closeList();
    }
  }

  protected onPanelMouseDown(event: MouseEvent) {
    const target = event.target as Node;
    if (this.listRef()?.nativeElement?.contains(target)) return;
    event.preventDefault();
  }

  protected onInputFocus() {
    if (this.ignoreNextFocus) return;
    this.isListVisible.set(true);

    setTimeout(() => {
      if (this.listRef()?.nativeElement) {
        this.listRef().nativeElement.scrollToSelectedIndex();
      }
    }, 0);
  }

  protected onWidgetKeyDown(event: KeyboardEvent) {
    if (event.key !== 'Escape' || !this.isListVisible()) return;
    event.preventDefault();
    event.stopPropagation();
    this.isListVisible.set(false);
    this.isFiltering.set(false);
    this.ignoreNextFocus = true;
    this.inputRef().nativeElement.focus();
    setTimeout(() => {
      this.ignoreNextFocus = false;
    });
  }

  protected onInputKeyDown(event: KeyboardEvent) {
    const key = event.key;

    switch (key) {
      case 'ArrowDown':
        event.preventDefault();
        this.isListVisible.set(true);

        setTimeout(() => {
          if (this.listRef()?.nativeElement) {
            this.listRef().nativeElement.focus();
            this.listRef().nativeElement.scrollToSelectedIndex();
          }
        }, 0);
        break;
      case 'Enter':
        event.preventDefault();
        if (!this.inputRef().nativeElement.value) {
          // Field is empty and enter pressed, we clear the selection
          this.adapter.valueChanged(null);
          this.isListVisible.set(false);
          this.isFiltering.set(false);
        }
        break;
    }
  }

  protected onInput(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.debouncer.next(filterValue);
  }

  protected inputValue(filterValue: string) {
    const templateData = this.adapter.templateData();

    this.adapter.filterChanged(filterValue);

    if (filterValue && !this.asyncFiltering()) {
      this.isFiltering.set(true);
      this.isListVisible.set(true);

      const searchFields =
        templateData.searchFields ??
        ([templateData.labelField!, templateData.valueField!].filter(
          (field) => !!field,
        ) as string[]);
      const hasSearchFields = searchFields.length > 0;
      const items = templateData.items || [];
      const filtered = items.filter((item: any) => {
        const isPrimitiveValue = item === null || typeof item !== 'object';

        if (isPrimitiveValue) {
          return item != null && item.toString().toLowerCase().includes(filterValue.toLowerCase());
        }

        const keys = Object.keys(item);
        const reduceFunc = (acc: boolean, prop: string) =>
          acc || item[prop].toString().toLowerCase().includes(filterValue.toLowerCase());

        return hasSearchFields
          ? keys.filter((prop: string) => searchFields.includes(prop)).reduce(reduceFunc, false)
          : keys.reduce(reduceFunc, false);
      });
      this.filteredItems.set(filtered);
    } else {
      this.isFiltering.set(false);
      this.filteredItems.set([...(templateData.items || [])]);
    }
  }

  protected onFocusOutInput(event: FocusEvent) {
    const newFocusTarget = event.relatedTarget as Node;

    if (newFocusTarget && this.el.nativeElement.contains(newFocusTarget)) {
      return;
    }

    this.closeList();
  }

  protected onClickItem(item: ListItem<never>, index: number) {
    const templateData = this.adapter.templateData();

    if (templateData.readonly || item.disabled) return;

    this.adapter.valueChanged(item.value);
    this.adapter.filterChanged('');

    this.focusedIndex.set(index);
    this.selectedItem.set(item);
    this.isFiltering.set(false);
    this.isListVisible.set(false);

    if (this.listRef()?.nativeElement) {
      this.listRef().nativeElement.focusItemAtIndex(index);
    }
  }

  protected onFocusChange(event: Event) {
    const index = (event as CustomEvent).detail.index;
    this.focusedIndex.set(index);
  }

  protected onUpdateItems(event: Event) {
    const items = (event as CustomEvent).detail;
    this.listItems.set(items ? [...items] : []);

    // Resolve selected item on initial load when a default value is set
    if (!this.selectedItem() && this.adapter.templateData().value != null) {
      const match = (items ?? []).find(
        (item: ListItem<never>) => item.value === this.adapter.templateData().value,
      );
      if (match) {
        this.selectedItem.set(match);
      }
    }
  }

  protected onRangeChange(event: Event) {
    const { startIndex, endIndex } = (event as CustomEvent).detail;
    this.currentRange.set({ start: startIndex, end: endIndex });
  }

  protected onListBlur() {
    this.closeList();
  }

  protected onValueChange(event: Event) {
    const value = (event as CustomEvent).detail.value;
    this.adapter.valueChanged(value);
    this.adapter.filterChanged('');
    this.selectedItem.set(this.listItems().find((item) => item.value === value));
    this.isListVisible.set(false);
    this.isFiltering.set(false);
  }

  private closeList() {
    this.adapter.onBlur();
    this.isListVisible.set(false);
    this.isFiltering.set(false);
  }
}

@let templateData = adapter.templateData();
@let itemRenderer = adapter.getItemRenderer(templateData.itemRenderer, defaultListItemRenderer);
@let showErrors = templateData.touched && templateData.errors && templateData.errors.length > 0;

<gui-label
  [targetElement]="[inputRef, listRef]"
  [uid]="widget.uid"
  [label]="templateData.label"
  [hint]="templateData.hint"
  [errors]="templateData.errors"
  [touched]="templateData.touched"
  [required]="templateData.validator?.required"
  [native]="false"
></gui-label>

<div
  class="gui-widget"
  tabindex="-1"
  (keydown)="onWidgetKeyDown($event)"
  (focusout)="onFocusOut($event)"
>
  @if (templateData.icon) {
    <span
      class="gui-widget-icon {{ templateData.icon }}"
      [attr.data-icon]="templateData.icon"
      aria-hidden="true"
    ></span>
  }
  <input
    #inputRef
    type="text"
    role="combobox"
    class="gui-widget-input"
    [class.gui-dropdown--icon]="templateData.icon"
    [id]="widget.uid"
    [attr.data-cy]="widget.uid + '_textinput'"
    [required]="templateData.validator?.required"
    [disabled]="templateData.disabled"
    [readonly]="templateData.readonly"
    [placeholder]="templateData.placeholder ?? ''"
    [attr.autocomplete]="templateData.autocomplete"
    [value]="selectedItemValue() ?? templateData.value ?? ''"
    (keydown)="onInputKeyDown($event)"
    (input)="onInput($event)"
    (focus)="onInputFocus()"
    [attr.aria-expanded]="isListVisible() ? 'true' : 'false'"
    [attr.aria-controls]="widget.uid + '-list'"
    aria-autocomplete="list"
    [attr.aria-labelledby]="templateData.label ? widget.uid + '_label' : null"
    [attr.aria-describedby]="templateData.hint ? widget.uid + '_hint' : null"
  />
  <button
    type="button"
    class="gui-dropdown__arrow"
    [attr.aria-label]="templateData.toggleAriaLabel ?? 'Show options'"
    aria-haspopup="listbox"
    [attr.aria-expanded]="isListVisible() ? 'true' : 'false'"
    [attr.aria-controls]="widget.uid + '-list'"
    [disabled]="templateData.disabled"
    (mousedown)="onToggleMouseDown($event)"
    (click)="onToggleClick($event)"
  >
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="16"
      height="16"
      viewBox="0 0 256 256"
      aria-hidden="true"
    >
      <path
        d="M213.66,101.66l-80,80a8,8,0,0,1-11.32,0l-80-80A8,8,0,0,1,53.66,90.34L128,164.69l74.34-74.35a8,8,0,0,1,11.32,11.32Z"
      ></path>
    </svg>
  </button>
  <div class="gui-picker__panel" [hidden]="!isListVisible()" (mousedown)="onPanelMouseDown($event)">
    <gui-list
      #listRef
      [id]="widget.uid + '-list'"
      [uid]="widget.uid"
      [value]="templateData.value ?? ''"
      [valueField]="templateData.valueField"
      [items]="displayItems()"
      [itemHeight]="templateData.itemHeight"
      [height]="templateData.height"
      [required]="templateData.validator?.required"
      [touched]="templateData.touched"
      [disabled]="templateData.disabled"
      [readonly]="templateData.readonly"
      [hidden]="!isListVisible()"
      (gui-update-items)="onUpdateItems($event)"
      (gui-range-change)="onRangeChange($event)"
      (gui-focus-change)="onFocusChange($event)"
      (focus)="onInputFocus()"
      (change)="onValueChange($event)"
    >
      @for (item of visibleItems(); track $index) {
        @let absoluteIndex = currentRange().start + $index;
        @let labelField = templateData.labelField ?? 'label';
        @let isObject = item.template !== null && typeof item.template === 'object';
        @let template =
          isObject && labelField && !templateData.itemRenderer
            ? item.template[labelField]
            : item.template;

        <!-- eslint-disable-next-line @angular-eslint/template/click-events-have-key-events -->
        <div
          role="option"
          tabindex="-1"
          class="gui-list__item-wrapper"
          [id]="widget.uid + '-item-' + absoluteIndex"
          [style.height.px]="templateData.itemHeight || 40"
          [attr.aria-selected]="templateData.value === item.value"
          [attr.aria-disabled]="templateData.disabled || !!item.disabled"
          (click)="onClickItem(item, absoluteIndex)"
        >
          <ng-container
            *ngComponentOutlet="
              itemRenderer;
              inputs: {
                template: template,
                value: item.value,
                disabled: templateData.disabled || !!item.disabled,
                selected: templateData.value === item.value,
                focused: focusedIndex() === absoluteIndex,
                index: absoluteIndex,
              }
            "
          >
          </ng-container>
        </div>
      }
    </gui-list>
    @if (showErrors) {
      <gui-errors
        [panel]="true"
        [uid]="widget.uid"
        [errors]="templateData.errors"
        [touched]="templateData.touched"
      ></gui-errors>
    }
  </div>
</div>

@if (showErrors) {
  <gui-errors
    [uid]="widget.uid"
    [errors]="templateData.errors"
    [touched]="templateData.touched"
  ></gui-errors>
}
