// demos/react-demo/src/app/custom-widgets/heading.component.tsx
import * as Core from '@golemui/core';
import { useDisplayWdiget } from '@golemui/react';
import { createElement, PropsWithChildren } from 'react';

type HeadingWidgetProps = {
  text: string;
  level?: number;
};

export function HeadingComponent(fieldInstance: Core.WithWidget) {
  const field = fieldInstance.widget as Core.DisplayWidget;
  const { uid, templateData } = useDisplayWdiget<HeadingWidgetProps>(field);

  return (
    <div id={uid}>
      <DynamicHeading level={templateData.level || 1}>{templateData.text}</DynamicHeading>
    </div>
  );
}

function DynamicHeading({ level, children }: PropsWithChildren<{ level: number }>) {
  return createElement(`h${level}`, null, children);
}

// apps/vue-playground/src/app/custom-fields/heading/HeadingComponent.vue
<script setup lang="ts">
import type { DisplayWidget, WithWidget } from '@golemui/core';
import { useDisplayWidget } from '@golemui/vue';
import { computed, h } from 'vue';

type OwnWidgetProps = {
  text: string;
  level?: number;
};

const props = defineProps<WithWidget>();
const widget = props.widget as DisplayWidget;
const { uid, templateData } = useDisplayWidget<OwnWidgetProps>(widget);

const Heading = computed(() => {
  const level = templateData.value.level || 1;
  const tag = `h${level}`;
  return h(tag, { class: 'heading' }, templateData.value.text);
});
</script>

<template>
  <div class="gui-widget" :id="uid">
    <component :is="Heading" />
  </div>
</template>

<style scoped>
.heading {
  color: var(--gui-color-primary);
  margin: 0;
}
</style>
