// libs/react-vanilla/src/lib/components/Number.tsx
import * as Core from '@golemui/core';
import { useControlField } from '@golemui/react';
import { NumberinputProps } from '@golemui/shared-vanilla';
import { useCallback } from 'react';
import '../styles.scss';

export function NumberInput(fieldInstance: Core.WithWidget) {
  const field = fieldInstance.widget as Core.InputWidget<number>;
  const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useControlField<
    number,
    NumberinputProps
  >(field);

  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) =>
      onValueChanged((e.nativeEvent as CustomEvent).detail.value),
    [onValueChanged],
  );

  const label = templateData.label as string;
  const hint = templateData.hint;
  const placeholder = templateData.placeholder;
  const step = templateData.step;
  const icon = templateData.icon;
  const iconPosition = templateData.iconPosition;
  const isDisabled = templateData.disabled as boolean;
  const isReadonly = templateData.readonly as boolean;
  const isRequired = (templateData.validator as Core.Validator)?.required;

  return (
    <div className="gui-number" style={{ flex: templateData.size }}>
      <gui-number
        uid={uid}
        label={label}
        hint={hint}
        errors={errors}
        touched={isTouched}
        required={isRequired}
        disabled={isDisabled}
        readOnly={isReadonly}
        value={value}
        step={step}
        icon={icon}
        iconPosition={iconPosition}
        placeholder={placeholder ?? undefined}
        onInput={handleChange}
        onBlur={onBlur}
      ></gui-number>
    </div>
  );
}

// libs/angular-vanilla/src/lib/components/number/number.component.ts
import { CommonModule } from '@angular/common';
import { Component, CUSTOM_ELEMENTS_SCHEMA, inject, OnDestroy, OnInit } from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import { NumberinputProps } from '@golemui/shared-vanilla';

@Component({
  standalone: true,
  selector: 'gui-number-control',
  imports: [CommonModule],
  providers: [Angular.ControlFieldAdapter],
  templateUrl: './number.component.html',
  host: {
    class: 'gui-number',
    '[style.flex]': 'this.adapter.templateData().size',
  },
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class NumberComponent implements OnInit, OnDestroy, Core.WithWidget {
  widget!: Core.InputWidget<number>;
  protected adapter: Angular.ControlFieldAdapter<number, NumberinputProps> = inject(
    Angular.ControlFieldAdapter,
  );

  ngOnInit(): void {
    this.adapter.init(this.widget);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }

  valueChanged(event: Event) {
    const value = (event as CustomEvent).detail.value;
    this.adapter.valueChanged(value);
  }
}

@let templateData = adapter.templateData();

<gui-number
  [uid]="widget.uid"
  [label]="templateData.label"
  [hint]="templateData.hint"
  [errors]="templateData.errors"
  [touched]="templateData.touched"
  [required]="templateData.validator?.required"
  [disabled]="templateData.disabled"
  [readonly]="templateData.readonly"
  [value]="templateData.value ?? ''"
  [step]="templateData.step"
  [icon]="templateData.icon"
  [iconPosition]="templateData.iconPosition"
  [placeholder]="templateData.placeholder"
  (input)="valueChanged($event)"
  (blur)="adapter.onBlur()"
></gui-number>
