// libs/gui/react/src/lib/components/Button.tsx
import type { ActionWidget, WithWidget } from '@golemui/core';
import { useActionWidget } from '@golemui/react';
import { GuiButtonReact } from '../web-components';
import '../styles.scss';
import type { ButtonProps } from '@golemui/gui-shared/internals';

export function Button(widgetInstance: WithWidget) {
  const widget = widgetInstance.widget as ActionWidget;
  const { uid, templateData, onClick } = useActionWidget<ButtonProps>(widget);
  const invalid = templateData.invalid === true && templateData.actionType === 'submit';

  return (
    <div
      className={invalid ? 'gui-button gui-field gui-button--invalid' : 'gui-button gui-field'}
      style={{ flex: templateData.size }}
    >
      <GuiButtonReact
        uid={uid}
        type={templateData.actionType ?? 'button'}
        label={templateData.label as string}
        disabled={templateData.disabled as boolean}
        variant={templateData.variant}
        icon={templateData.icon}
        iconPosition={templateData.iconPosition}
        onClick={onClick}
      />
    </div>
  );
}

// libs/gui/vue/src/lib/components/Button.vue
<script setup lang="ts">
import type { ActionWidget, WithWidget } from '@golemui/core';
import { useActionWidget } from '@golemui/vue';
import type { ButtonProps } from '@golemui/gui-shared/internals';
import { computed } from 'vue';
import '@golemui/gui-components/button';

const props = defineProps<WithWidget>();
const widget = props.widget as ActionWidget;
const { uid, templateData, invalid, onClick } = useActionWidget<ButtonProps>(widget);

// Mirror the Lit element's class-field defaults so Vue never sends '' or undefined
// to an enum prop (which Lit's String converter would coerce to '', overriding the default).
const variant = computed(() => templateData.value.variant || 'filled');
const iconPosition = computed(() => templateData.value.iconPosition || 'left');
</script>

<template>
  <div
    class="gui-button gui-field"
    :class="{ 'gui-button--invalid': invalid && templateData.actionType === 'submit' }"
    :style="{ flex: templateData.size }"
  >
    <gui-button
      :uid="uid"
      :type="templateData.actionType ?? 'button'"
      :label="templateData.label"
      :disabled="templateData.disabled"
      :variant.prop="variant"
      :icon="templateData.icon"
      :iconPosition.prop="iconPosition"
      @click="onClick"
    />
  </div>
</template>
