// libs/gui/react/src/lib/components/DatePicker.tsx
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/react';
import type { DatePickerProps } from '@golemui/gui-shared/internals';
import { useCallback } from 'react';
import '../styles.scss';
import { GuiDatePickerReact } from '../web-components';

export function DatePicker(widgetInstance: WithWidget) {
  const widget = widgetInstance.widget as InputWidget<string>;
  const {
    uid,
    errors,
    value,
    isTouched,
    templateData,
    onValueChanged,
    onBlur,
    injectValidationIssues,
  } = useInputWidget<string, DatePickerProps>(widget);

  const handleChange = useCallback(
    (e: Event) => {
      injectValidationIssues(null);
      onValueChanged((e as CustomEvent).detail.value);
    },
    [injectValidationIssues, onValueChanged],
  );

  const handleInputError = useCallback(
    (e: Event) => {
      injectValidationIssues([(e as CustomEvent).detail.message]);
    },
    [injectValidationIssues],
  );

  const isRequired = (templateData.validator as Validator)?.required;

  return (
    <div className="gui-date-picker gui-field" style={{ flex: templateData.size }}>
      <GuiDatePickerReact
        uid={uid}
        label={templateData.label as string}
        hint={templateData.hint}
        errors={errors}
        touched={isTouched}
        required={isRequired}
        disabled={templateData.disabled as boolean}
        readOnly={templateData.readonly as boolean}
        value={value}
        icon={templateData.icon}
        localeId={templateData.lang}
        toggleAriaLabel={templateData.toggleAriaLabel}
        dayAriaLabel={templateData.dayAriaLabel}
        monthAriaLabel={templateData.monthAriaLabel}
        yearAriaLabel={templateData.yearAriaLabel}
        prevMonthIcon={templateData.prevMonthIcon}
        nextMonthIcon={templateData.nextMonthIcon}
        prevMonthAriaLabel={templateData.prevMonthAriaLabel}
        nextMonthAriaLabel={templateData.nextMonthAriaLabel}
        selectYearAriaLabel={templateData.selectYearAriaLabel}
        yearGridAriaLabel={templateData.yearGridAriaLabel}
        dayFormat={templateData.dayFormat}
        weekdayFormat={templateData.weekdayFormat}
        monthFormat={templateData.monthFormat}
        minDate={templateData.minDate}
        maxDate={templateData.maxDate}
        disabledRanges={templateData.disabledRanges}
        numberOfMonths={templateData.numberOfMonths}
        invalidDateMessage={templateData.invalidDateMessage as string}
        minDateMessage={templateData.minDateMessage as string}
        maxDateMessage={templateData.maxDateMessage as string}
        disabledDateRangeMessage={templateData.disabledDateRangeMessage as string}
        incompleteMessage={templateData.incompleteMessage as string}
        onGuiInput={handleChange}
        onGuiBlur={onBlur}
        onGuiInputError={handleInputError}
      />
    </div>
  );
}

// libs/gui/vue/src/lib/components/DatePicker.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/vue';
import type { DatePickerProps } from '@golemui/gui-shared/internals';
import { computed, onUnmounted, ref, watch } from 'vue';
import '@golemui/gui-components/date-picker';

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<string>;
const {
  uid,
  errors,
  value,
  isTouched,
  templateData,
  onValueChanged,
  onBlur,
  injectValidationIssues,
} = useInputWidget<string, DatePickerProps>(widget);

const required = computed(() => (templateData.value.validator as Validator)?.required);
const dayFormat = computed(() => templateData.value.dayFormat || 'numeric');
const weekdayFormat = computed(() => templateData.value.weekdayFormat || 'narrow');
const monthFormat = computed(() => templateData.value.monthFormat || 'long');
const numberOfMonths = computed(() => templateData.value.numberOfMonths ?? 1);

const pickerRef = ref<HTMLElement | null>(null);
const changeHandler = (e: Event) => {
  injectValidationIssues(null);
  onValueChanged((e as CustomEvent).detail.value);
};
const errorHandler = (e: Event) => {
  injectValidationIssues([(e as CustomEvent).detail.message]);
};

let currentEl: HTMLElement | null = null;
watch(pickerRef, (el) => {
  if (currentEl) {
    currentEl.removeEventListener('gui-input', changeHandler);
    currentEl.removeEventListener('gui-input-error', errorHandler);
    currentEl.removeEventListener('gui-blur', onBlur);
  }
  currentEl = el;
  if (el) {
    el.addEventListener('gui-input', changeHandler);
    el.addEventListener('gui-input-error', errorHandler);
    el.addEventListener('gui-blur', onBlur);
  }
});

onUnmounted(() => {
  currentEl?.removeEventListener('gui-input', changeHandler);
  currentEl?.removeEventListener('gui-input-error', errorHandler);
  currentEl?.removeEventListener('gui-blur', onBlur);
});
</script>

<template>
  <div class="gui-date-picker gui-field" :style="{ flex: templateData.size }">
    <gui-date-picker
      ref="pickerRef"
      :uid="uid"
      :label="templateData.label"
      :hint="templateData.hint"
      :errors="errors"
      :touched="isTouched"
      :required="required"
      :disabled="templateData.disabled"
      :readOnly="templateData.readonly"
      :value="value"
      :icon="templateData.icon"
      :localeId="templateData.lang"
      :toggleAriaLabel="templateData.toggleAriaLabel"
      :dayAriaLabel="templateData.dayAriaLabel"
      :monthAriaLabel="templateData.monthAriaLabel"
      :yearAriaLabel="templateData.yearAriaLabel"
      :prevMonthIcon="templateData.prevMonthIcon"
      :nextMonthIcon="templateData.nextMonthIcon"
      :prevMonthAriaLabel="templateData.prevMonthAriaLabel"
      :nextMonthAriaLabel="templateData.nextMonthAriaLabel"
      :selectYearAriaLabel="templateData.selectYearAriaLabel"
      :yearGridAriaLabel="templateData.yearGridAriaLabel"
      :dayFormat.prop="dayFormat"
      :weekdayFormat.prop="weekdayFormat"
      :monthFormat.prop="monthFormat"
      :minDate="templateData.minDate"
      :maxDate="templateData.maxDate"
      :disabledRanges.prop="templateData.disabledRanges"
      :numberOfMonths.prop="numberOfMonths"
      :invalidDateMessage="templateData.invalidDateMessage"
      :minDateMessage="templateData.minDateMessage"
      :maxDateMessage="templateData.maxDateMessage"
      :disabledDateRangeMessage="templateData.disabledDateRangeMessage"
      :incompleteMessage="templateData.incompleteMessage"
    />
  </div>
</template>
