// libs/gui/angular/src/lib/components/date-picker/date-picker.component.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  inject,
  type OnDestroy,
  type OnInit,
  signal,
  viewChild,
} from '@angular/core';
import { InputWidgetAdapter } from '@golemui/angular';
import type { InputWidget, WithWidget } from '@golemui/core';
import { type DatePickerProps } from '@golemui/gui-shared';
import { ErrorsComponent } from '../../utils/templates/errors.component';
import { LabelComponent } from '../../utils/templates/label.component';
import '@golemui/gui-components/date-input';
import '@golemui/gui-components/calendar';

@Component({
  standalone: true,
  selector: 'gui-date-picker-control',
  imports: [CommonModule, ErrorsComponent, LabelComponent],
  providers: [InputWidgetAdapter],
  templateUrl: './date-picker.component.html',
  host: {
    class: 'gui-date-picker gui-field',
    '[style.flex]': 'this.adapter.templateData().size',
    '(document:click)': 'onDocumentClick($event)',
    '(focusout)': 'onFocusOut($event)',
  },
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class DatePickerComponent implements OnInit, OnDestroy, WithWidget {
  widget!: InputWidget<string>;
  protected adapter: InputWidgetAdapter<string, DatePickerProps> = inject(InputWidgetAdapter);
  private el = inject(ElementRef);
  currentDate = new Date();

  dateControl = viewChild<ElementRef>('dateControlRef');
  calendarControl = viewChild<ElementRef>('calendarControlRef');

  readonly isCalendarOpen = signal(false);

  onFocusOut(event: FocusEvent) {
    if (!this.isCalendarOpen()) return;

    const newFocusTarget = event.relatedTarget as Node;
    if (newFocusTarget && this.el.nativeElement.contains(newFocusTarget)) {
      return;
    }

    this.closeCalendar();
  }

  onDocumentClick(event: MouseEvent) {
    const targetElement = event.target as HTMLElement;
    if (
      targetElement &&
      !this.dateControl()?.nativeElement.contains(targetElement) &&
      !this.calendarControl()?.nativeElement.contains(targetElement)
    ) {
      this.closeCalendar();
    }
  }

  ngOnInit(): void {
    this.adapter.init(this.widget);
  }

  onChangeDate(event: Event) {
    this.adapter.injectValidationIssues(null);
    this.adapter.valueChanged((event as CustomEvent).detail.value);
  }

  // Selecting a day in the calendar commits a single date, so close the
  // calendar afterwards. The range picker intentionally stays open so the user
  // can select multiple ranges and closes it themselves.
  onCalendarChange(event: Event) {
    this.onChangeDate(event);
    this.closeCalendar();
  }

  onInputError(event: Event) {
    this.adapter.injectValidationIssues([(event as CustomEvent).detail.message]);
  }

  onBlurCalendar() {
    this.adapter.onBlur();
    this.closeCalendar();
  }

  toggleCalendar(event: Event) {
    const target = event.target as HTMLElement;
    const isInputClick = target.closest('.gui-date-input__part');
    const isCalendarClick = target.closest('gui-calendar');
    if (isInputClick || isCalendarClick) {
      this.openCalendar();
    } else {
      this.isCalendarOpen.set(!this.isCalendarOpen());
    }
  }

  openCalendar() {
    this.isCalendarOpen.set(true);
  }

  closeCalendar() {
    this.isCalendarOpen.set(false);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

@let templateData = adapter.templateData();
@let showErrors = templateData.touched && templateData.errors && templateData.errors.length > 0;

@if (templateData.label) {
  <label gui-label [for]="widget.uid" [uid]="widget.uid" [templateData]="templateData"></label>
}

<div
  role="button"
  tabindex="-1"
  class="gui-widget"
  [attr.aria-expanded]="isCalendarOpen()"
  (keyup.space)="$event.target === $event.currentTarget && isCalendarOpen.set(!isCalendarOpen())"
  (keyup.enter)="$event.target === $event.currentTarget && isCalendarOpen.set(!isCalendarOpen())"
  (click)="toggleCalendar($event)"
>
  <gui-date
    #dateControlRef
    [uid]="widget.uid"
    [hint]="templateData.hint"
    [showErrors]="false"
    [errors]="templateData.errors"
    [touched]="templateData.touched"
    [required]="templateData.validator?.required"
    [disabled]="templateData.disabled"
    [readonly]="templateData.readonly"
    [value]="templateData.value"
    [icon]="templateData.icon"
    [localeId]="templateData.lang"
    (change)="onChangeDate($event)"
    (inputError)="onInputError($event)"
    (focus)="openCalendar()"
    (blur)="adapter.onBlur()"
  ></gui-date>
  <span class="gui-date-picker__arrow"
    ><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 256 256">
      <path
        d="M213.66,101.66l-80,80a8,8,0,0,1-11.32,0l-80-80A8,8,0,0,1,53.66,90.34L128,164.69l74.34-74.35a8,8,0,0,1,11.32,11.32Z"
      ></path></svg
  ></span>

  @if (isCalendarOpen()) {
    <gui-calendar
      #calendarControlRef
      [uid]="widget.uid"
      [hint]="templateData.hint"
      [touched]="templateData.touched"
      [required]="templateData.validator?.required"
      [disabled]="templateData.disabled"
      [readonly]="templateData.readonly"
      [value]="templateData.value"
      [prevMonthIcon]="templateData.prevMonthIcon"
      [nextMonthIcon]="templateData.nextMonthIcon"
      [nextMonthAriaLabel]="templateData.nextMonthAriaLabel"
      [prevMonthAriaLabel]="templateData.prevMonthAriaLabel"
      [dayFormat]="templateData.dayFormat"
      [weekdayFormat]="templateData.weekdayFormat"
      [monthFormat]="templateData.monthFormat"
      [minDate]="templateData.minDate"
      [maxDate]="templateData.maxDate"
      [disabledRanges]="templateData.disabledRanges"
      [numberOfMonths]="templateData.numberOfMonths"
      [localeId]="templateData.lang"
      (change)="onChangeDate($event)"
      (blur)="onBlurCalendar()"
    ></gui-calendar>
  }
</div>

@if (showErrors) {
  <ul
    gui-errors
    [uid]="widget.uid"
    [templateData]="templateData"
    [attr.data-cy]="widget.uid + '_validator-errors'"
  ></ul>
}

// libs/gui/vue/src/lib/components/DatePicker.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/vue';
import type { DatePickerProps } from '@golemui/gui-shared';
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';
import Errors from './shared/Errors.vue';
import '@golemui/gui-components/date-input';
import '@golemui/gui-components/calendar';

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<string>;
const {
  uid,
  errors,
  value,
  isTouched,
  templateData,
  onValueChanged,
  onBlur,
  injectValidationIssues,
} = useInputWidget<string, DatePickerProps>(widget);

const required = computed(() => (templateData.value.validator as Validator)?.required);
const showErrors = computed(() => isTouched.value && errors.value && errors.value.length > 0);

// Default to the same values as the Lit element's class-field initializers so
// we never pass undefined or '' (which Intl.DateTimeFormat rejects with a RangeError).
const dayFormat = computed(() => templateData.value.dayFormat || 'numeric');
const weekdayFormat = computed(() => templateData.value.weekdayFormat || 'narrow');
const monthFormat = computed(() => templateData.value.monthFormat || 'long');
const numberOfMonths = computed(() => templateData.value.numberOfMonths ?? 1);

const isCalendarOpen = ref(false);
const containerRef = ref<HTMLDivElement | null>(null);
const dateControlRef = ref<HTMLElement | null>(null);
const calendarControlRef = ref<HTMLElement | null>(null);

const dateChange = (e: Event) => {
  injectValidationIssues(null);
  onValueChanged((e as CustomEvent).detail.value);
};
const dateFocus = () => {
  isCalendarOpen.value = true;
};
const dateError = (e: Event) => {
  injectValidationIssues([(e as CustomEvent).detail.message]);
};
let currentDate: HTMLElement | null = null;
watch(dateControlRef, (el) => {
  if (currentDate) {
    currentDate.removeEventListener('change', dateChange);
    currentDate.removeEventListener('focus', dateFocus);
    currentDate.removeEventListener('blur', onBlur);
    currentDate.removeEventListener('inputError', dateError);
  }
  currentDate = el;
  if (el) {
    el.addEventListener('change', dateChange);
    el.addEventListener('focus', dateFocus);
    el.addEventListener('blur', onBlur);
    el.addEventListener('inputError', dateError);
  }
});

const calChange = (e: Event) => {
  injectValidationIssues(null);
  onValueChanged((e as CustomEvent).detail.value);
  // Selecting a day in the calendar commits a single date, so close the
  // calendar afterwards. The range picker intentionally stays open so the user
  // can select multiple ranges and closes it themselves.
  isCalendarOpen.value = false;
};
const calBlur = () => {
  onBlur();
  isCalendarOpen.value = false;
};
let currentCal: HTMLElement | null = null;
watch(calendarControlRef, (el) => {
  if (currentCal) {
    currentCal.removeEventListener('blur', calBlur);
    currentCal.removeEventListener('change', calChange);
  }
  currentCal = el;
  if (el) {
    el.addEventListener('blur', calBlur);
    el.addEventListener('change', calChange);
  }
});

const onDocumentClick = (event: MouseEvent) => {
  if (!isCalendarOpen.value) return;
  const path = event.composedPath();
  const inDate = dateControlRef.value && path.includes(dateControlRef.value);
  const inCal = calendarControlRef.value && path.includes(calendarControlRef.value);
  if (!inDate && !inCal) isCalendarOpen.value = false;
};

onMounted(() => document.addEventListener('click', onDocumentClick));
onUnmounted(() => {
  document.removeEventListener('click', onDocumentClick);
  currentDate?.removeEventListener('change', dateChange);
  currentDate?.removeEventListener('focus', dateFocus);
  currentDate?.removeEventListener('blur', onBlur);
  currentDate?.removeEventListener('inputError', dateError);
  currentCal?.removeEventListener('blur', calBlur);
  currentCal?.removeEventListener('change', calChange);
});

const onFocusOut = (event: FocusEvent) => {
  if (!isCalendarOpen.value) return;
  const newFocus = event.relatedTarget as Node;
  if (newFocus && containerRef.value?.contains(newFocus)) return;
  isCalendarOpen.value = false;
};

const toggleCalendar = (event: MouseEvent) => {
  const target = event.target as HTMLElement;
  const isInputClick = target.closest('.gui-date-input__part');
  const isCalendarClick = target.closest('gui-calendar');
  if (isInputClick || isCalendarClick) {
    if (!isCalendarOpen.value) isCalendarOpen.value = true;
  } else {
    isCalendarOpen.value = !isCalendarOpen.value;
  }
};

const onKeyUp = (event: KeyboardEvent) => {
  if (event.target !== event.currentTarget) return;
  if (event.key === 'Enter' || event.key === ' ') {
    isCalendarOpen.value = !isCalendarOpen.value;
  }
};
</script>

<template>
  <div
    ref="containerRef"
    class="gui-date-picker gui-field"
    :style="{ flex: templateData.size }"
    @focusout="onFocusOut"
  >
    <label v-if="templateData.label" class="gui-label" :for="uid" :data-cy="`${uid}_label`">
      {{ templateData.label }}{{ required ? ' *' : '' }}
      <div v-if="templateData.hint" class="gui-widget-hint" :id="`${uid}_hint`">
        {{ templateData.hint }}
      </div>
    </label>
    <div
      role="button"
      tabindex="-1"
      class="gui-widget"
      :aria-expanded="isCalendarOpen"
      @click="toggleCalendar"
      @keyup="onKeyUp"
    >
      <gui-date
        ref="dateControlRef"
        :uid="uid"
        :hint="templateData.hint"
        :showErrors="false"
        :errors="errors"
        :touched="isTouched"
        :required="required"
        :disabled="templateData.disabled"
        :readOnly="templateData.readonly"
        :value="value"
        :icon="templateData.icon"
        :localeId="templateData.lang"
      />
      <span class="gui-date-picker__arrow">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 256 256">
          <path
            d="M213.66,101.66l-80,80a8,8,0,0,1-11.32,0l-80-80A8,8,0,0,1,53.66,90.34L128,164.69l74.34-74.35a8,8,0,0,1,11.32,11.32Z"
          ></path>
        </svg>
      </span>
      <gui-calendar
        v-if="isCalendarOpen"
        ref="calendarControlRef"
        :uid="uid"
        :hint="templateData.hint"
        :touched="isTouched"
        :required="required"
        :disabled="templateData.disabled"
        :readOnly="templateData.readonly"
        :value="value"
        :prevMonthIcon="templateData.prevMonthIcon"
        :nextMonthIcon="templateData.nextMonthIcon"
        :prevMonthAriaLabel="templateData.prevMonthAriaLabel"
        :nextMonthAriaLabel="templateData.nextMonthAriaLabel"
        :dayFormat.prop="dayFormat"
        :weekdayFormat.prop="weekdayFormat"
        :monthFormat.prop="monthFormat"
        :minDate="templateData.minDate"
        :maxDate="templateData.maxDate"
        :disabledRanges="templateData.disabledRanges"
        :numberOfMonths.prop="numberOfMonths"
        :localeId="templateData.lang"
      />
    </div>
    <Errors v-if="showErrors" :errors="errors" :uid="uid" />
  </div>
</template>
