// libs/gui/react/src/lib/components/Flex.tsx
import * as Core from '@golemui/core';
import { useLayoutWidget, WidgetRenderer } from '@golemui/react';
import { FlexProps } from '@golemui/gui-shared';
import { useCallback } from 'react';
import '../styles.scss';

export function Flex(widgetInstance: Core.WithWidget) {
  const widget = widgetInstance.widget as Core.LayoutWidget;
  const { uid, children, templateData } = useLayoutWidget<FlexProps>(widget);

  const renderWidgets = useCallback(() => {
    if (!children) return null;
    return children.map((widget) => (
      <WidgetRenderer key={widget.uid} widget={widget as Core.NonFunctionWidget<string>} />
    ));
  }, [children]);

  const direction = `gui-flex__widget--${templateData.direction ?? 'column'}`;
  const justify = `gui-flex__widget--justify-${(templateData.justify as string) ?? 'stretch'}`;
  const align = `gui-flex__widget--align-${(templateData.align as string) ?? 'start'}`;
  return (
    <div className="gui-flex gui-field" style={{ flex: templateData.size }}>
      <div className={`gui-flex__widget ${direction} ${justify} ${align}`} style={templateData.gap ? { gap: `${templateData.gap}px`} : {}} id={uid}>
        {renderWidgets()}
      </div>
    </div>
  );
}

// libs/gui/vue/src/lib/components/Flex.vue
<script setup lang="ts">
import type { LayoutWidget, NonFunctionWidget, WithWidget } from '@golemui/core';
import { useLayoutWidget, WidgetRenderer } from '@golemui/vue';
import type { FlexProps } from '@golemui/gui-shared';
import { computed } from 'vue';

const props = defineProps<WithWidget>();
const widget = props.widget as LayoutWidget;
const { uid, children, templateData } = useLayoutWidget<FlexProps>(widget);

const widgetClass = computed(() => {
  const direction = `gui-flex__widget--${templateData.value.direction ?? 'column'}`;
  const justify = `gui-flex__widget--justify-${(templateData.value.justify as string) ?? 'stretch'}`;
  const align = `gui-flex__widget--align-${(templateData.value.align as string) ?? 'start'}`;
  return `gui-flex__widget ${direction} ${justify} ${align}`;
});

const gapStyle = computed(() =>
  templateData.value.gap ? { gap: `${templateData.value.gap}px` } : {},
);
</script>

<template>
  <div class="gui-flex gui-field" :style="{ flex: templateData.size }">
    <div :class="widgetClass" :style="gapStyle" :id="uid">
      <WidgetRenderer
        v-for="child in children as NonFunctionWidget<string>[]"
        :key="child.uid"
        :widget="child"
      />
    </div>
  </div>
</template>
