// libs/gui/angular/src/lib/components/form/form.component.ts
import { CommonModule } from '@angular/common';
import { Component, computed, input, output, type Type, viewChild } from '@angular/core';
import { type AngularItemRenderer, FormCoreComponent } from '@golemui/angular';
import type { FormEvent, FormHealth, WidgetLoaders, WithWidget } from '@golemui/core';
import { type FormInitConfig } from '@golemui/core';
import { type GuiFormInitConfig } from '@golemui/gui-shared';
import { resolveFormInput } from '@golemui/gui-shared/internals';
import { initValidators } from '@golemui/gui-validators';
import { widgetLoaders } from '../../widget.loaders';

@Component({
  imports: [CommonModule, FormCoreComponent],
  selector: 'gui-form',
  templateUrl: './form.component.html',
})
export class FormComponent {
  config = input.required<GuiFormInitConfig>();
  autocomplete = input<string | undefined>(undefined);

  private coreForm = viewChild(FormCoreComponent);

  protected resolved = computed(() =>
    resolveFormInput(this.config().formDef, this.config().formSelectors, this.config().formConfig),
  );

  protected coreConfig = computed((): FormInitConfig<Type<WithWidget>> => {
    const c = this.config();
    const r = this.resolved();
    return {
      formDef: r.formDef as string | Record<string, any>,
      widgetLoaders: {
        ...widgetLoaders,
        ...((r.widgetLoaders ?? {}) as WidgetLoaders<Type<WithWidget>>),
        ...((c.customWidgetLoaders ?? {}) as WidgetLoaders<Type<WithWidget>>),
      },
      dependencies: { ...(r.dependencies ?? {}), ...(c.dependencies ?? {}) },
      validateOn: c.validateOn ?? r.validateOn ?? 'eager',
      itemRenderers: {
        ...((r.itemRenderers ?? {}) as Record<string, AngularItemRenderer<any>>),
        ...((c.itemRenderers ?? {}) as Record<string, AngularItemRenderer<any>>),
      },
      localization: c.localization,
      middlewares: c.middlewares ?? [],
      data: c.data,
      meta: c.meta,
      formName: c.formName,
    };
  });

  protected allValidators = computed(() =>
    initValidators({ ...(this.config().customValidators ?? {}) }),
  );

  formHealth = output<FormHealth>();
  formEvent = output<FormEvent>();

  protected onCoreFormEvent(event: FormEvent): void {
    this.resolved().formEvent?.(event);
    this.formEvent.emit(event);
  }

  setData(data: Record<string, any>): void {
    this.coreForm()?.setData(data);
  }

  setMeta(meta: Record<string, any>): void {
    this.coreForm()?.setMeta(meta);
  }
}

<gui-core-form
  [formDef]="resolvedFormDef()"
  [data]="data()"
  [meta]="meta()"
  [widgetLoaders]="allWidgetLoaders()"
  [middlewares]="middlewares()"
  [validators]="allValidators()"
  [validateOn]="resolvedValidateOn()"
  [itemRenderers]="allItemRenderers()"
  [localization]="localization()"
  [dependencies]="allDependencies()"
  [autocomplete]="autocomplete()"
  (formHealth)="formHealth.emit($event)"
  (formEvent)="onCoreFormEvent($event)"
></gui-core-form>

// libs/gui/vue/src/lib/components/Form.vue
<script setup lang="ts">
import type {
  FormEvent,
  FormHealth,
  FormInitConfig,
  WidgetLoaders,
  WithWidget,
} from '@golemui/core';
import { resolveFormInput } from '@golemui/gui-shared/internals';
import { initValidators } from '@golemui/gui-validators';
import { FormComponent, type FormComponentHandle, type VueItemRenderer } from '@golemui/vue';
import { computed, ref, type Component } from 'vue';
import { widgetLoaders as golemWidgetLoaders } from '../widget.loaders';
import type { GuiFormEmits, GuiFormHandle, GuiFormProps } from './Form.types';

const props = defineProps<GuiFormProps>();
const emit = defineEmits<GuiFormEmits>();

const formRef = ref<FormComponentHandle | null>(null);

const resolved = computed(() =>
  resolveFormInput(props.config.formDef, props.config.formSelectors, props.config.formConfig),
);

const coreConfig = computed<FormInitConfig<Component<WithWidget>>>(() => {
  const r = resolved.value;
  return {
    formDef: r.formDef as string | Record<string, any>,
    widgetLoaders: {
      ...golemWidgetLoaders,
      ...(r.widgetLoaders as WidgetLoaders<Component<WithWidget>>),
      ...((props.config.customWidgetLoaders ?? {}) as WidgetLoaders<Component<WithWidget>>),
    },
    dependencies: { ...(r.dependencies ?? {}), ...(props.config.dependencies ?? {}) },
    validateOn: props.config.validateOn ?? r.validateOn ?? 'eager',
    itemRenderers: {
      ...((r.itemRenderers ?? {}) as Record<string, VueItemRenderer<any>>),
      ...((props.config.itemRenderers ?? {}) as Record<string, VueItemRenderer<any>>),
    },
    localization: props.config.localization,
    middlewares: props.config.middlewares ?? [],
    data: props.config.data,
    meta: props.config.meta,
    formName: props.config.formName,
  };
});

const allValidators = computed(() => initValidators({ ...(props.config.customValidators ?? {}) }));

const onInnerFormEvent = (event: FormEvent) => {
  resolved.value.formEvent?.(event);
  emit('form-event', event);
};

const onInnerFormHealth = (health: FormHealth) => emit('form-health', health);

defineExpose<GuiFormHandle>({
  setData: (data) => formRef.value?.setData(data),
  setMeta: (meta) => formRef.value?.setMeta(meta),
});
</script>

<template>
  <FormComponent
    ref="formRef"
    :config="coreConfig"
    :validators="allValidators"
    :autocomplete="autocomplete"
    @form-event="onInnerFormEvent"
    @form-health="onInnerFormHealth"
  />
</template>
