// libs/gui/react/src/lib/components/MarkdownText.tsx
import * as Core from '@golemui/core';
import { useDisplayWdiget } from '@golemui/react';
import { MarkdownTextProps } from '@golemui/gui-shared';
import '@golemui/gui-components/markdown-text';

export function MarkdownText(widgetInstance: Core.WithWidget) {
  const widget = widgetInstance.widget as Core.DisplayWidget;
  const { uid, templateData } = useDisplayWdiget<MarkdownTextProps>(widget);

  return (
    <div className="gui-markdown-text gui-field" style={{ flex: templateData.size }}>
      <div className="gui-widget" id={uid}>
        <gui-markdown-text md={templateData.md} dependencies={templateData.deps} />
      </div>
    </div>
  );
}

// libs/gui/vue/src/lib/components/MarkdownText.vue
<script setup lang="ts">
import type { DisplayWidget, WithWidget } from '@golemui/core';
import { useDisplayWidget } from '@golemui/vue';
import type { MarkdownTextProps } from '@golemui/gui-shared';
import '@golemui/gui-components/markdown-text';

const props = defineProps<WithWidget>();
const widget = props.widget as DisplayWidget;
const { uid, templateData } = useDisplayWidget<MarkdownTextProps>(widget);
</script>

<template>
  <div class="gui-markdown-text gui-field" :style="{ flex: templateData.size }">
    <div class="gui-widget" :id="uid">
      <gui-markdown-text :md="templateData.md" :dependencies="templateData.deps" />
    </div>
  </div>
</template>
