// libs/gui/angular/src/lib/components/multi-file-upload/multi-file-upload.component.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  inject,
  type OnDestroy,
  type OnInit,
} from '@angular/core';
import { InputWidgetAdapter } from '@golemui/angular';
import type { InputWidget, WithWidget } from '@golemui/core';
import type { FileItem, MultiFileUploadProps } from '@golemui/gui-shared/internals';
import '@golemui/gui-components/multi-file-upload';
import { deferHydrationAttr } from '../../utils/defer-hydration';

@Component({
  standalone: true,
  selector: 'gui-multi-file-upload-control',
  imports: [CommonModule],
  providers: [InputWidgetAdapter],
  templateUrl: './multi-file-upload.component.html',
  host: {
    class: 'gui-multi-file-upload gui-field',
    '[style.flex]': 'this.adapter.templateData().size',
  },
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class MultiFileUploadComponent implements OnInit, OnDestroy, WithWidget {
  widget!: InputWidget<FileItem[]>;
  protected adapter: InputWidgetAdapter<FileItem[], MultiFileUploadProps> =
    inject(InputWidgetAdapter);
  protected readonly deferHydration = deferHydrationAttr();

  ngOnInit(): void {
    this.adapter.init(this.widget);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }

  valueChanged(event: Event) {
    const value = (event as CustomEvent).detail.value as FileItem[];
    this.adapter.valueChanged(value);
  }

  onInputError(event: Event) {
    const message = (event as CustomEvent).detail.message as string | null;
    this.adapter.injectValidationIssues(message ? [message] : null);
  }
}

@let templateData = adapter.templateData();

<gui-multi-file-upload
  [attr.defer-hydration]="deferHydration"
  [uid]="widget.uid"
  [path]="widget.path"
  [label]="templateData.label"
  [hint]="templateData.hint"
  [errors]="templateData.errors"
  [touched]="templateData.touched"
  [required]="templateData.validator?.required"
  [disabled]="templateData.disabled"
  [readOnly]="templateData.readonly"
  [values]="templateData.value ?? []"
  [dependencies]="templateData.deps"
  [icon]="templateData.icon"
  [accept]="templateData.accept"
  [maxSize]="templateData.maxSize"
  [buttonLabel]="templateData.buttonLabel"
  [removeAriaLabel]="templateData.removeAriaLabel"
  [cancelAriaLabel]="templateData.cancelAriaLabel"
  [retryAriaLabel]="templateData.retryAriaLabel"
  [removeIcon]="templateData.removeIcon"
  [retryIcon]="templateData.retryIcon"
  [maxSizeMessage]="templateData.maxSizeMessage"
  [acceptMessage]="templateData.acceptMessage"
  [missingServiceMessage]="templateData.missingServiceMessage"
  [uploadedMessage]="templateData.uploadedMessage"
  [removedMessage]="templateData.removedMessage"
  [failedMessage]="templateData.failedMessage"
  (change)="valueChanged($event)"
  (blur)="adapter.onBlur()"
  (inputError)="onInputError($event)"
></gui-multi-file-upload>

// libs/gui/vue/src/lib/components/MultiFileUpload.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/vue';
import type { FileItem, MultiFileUploadProps } from '@golemui/gui-shared/internals';
import { computed } from 'vue';
import '@golemui/gui-components/multi-file-upload';

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<FileItem[]>;
const {
  uid,
  errors,
  value,
  isTouched,
  templateData,
  onValueChanged,
  onBlur,
  injectValidationIssues,
} = useInputWidget<FileItem[], MultiFileUploadProps>(widget);

const handleChange = (e: Event) => onValueChanged((e as CustomEvent).detail.value as FileItem[]);

const handleInputError = (e: Event) => {
  const message = (e as CustomEvent).detail.message as string | null;
  injectValidationIssues(message ? [message] : null);
};

const required = computed(() => (templateData.value.validator as Validator)?.required);
</script>

<template>
  <div class="gui-multi-file-upload gui-field" :style="{ flex: templateData.size }">
    <gui-multi-file-upload
      :uid="uid"
      :path="widget.path"
      :label="templateData.label"
      :hint="templateData.hint"
      :errors="errors"
      :touched="isTouched"
      :required="required"
      :disabled="templateData.disabled"
      :readOnly="templateData.readonly"
      :values="value ?? []"
      :dependencies="templateData.deps"
      :icon="templateData.icon"
      :accept="templateData.accept"
      :maxSize="templateData.maxSize"
      :buttonLabel="templateData.buttonLabel"
      :removeAriaLabel="templateData.removeAriaLabel"
      :cancelAriaLabel="templateData.cancelAriaLabel"
      :retryAriaLabel="templateData.retryAriaLabel"
      :removeIcon="templateData.removeIcon"
      :retryIcon="templateData.retryIcon"
      :maxSizeMessage="templateData.maxSizeMessage"
      :acceptMessage="templateData.acceptMessage"
      :missingServiceMessage="templateData.missingServiceMessage"
      :uploadedMessage="templateData.uploadedMessage"
      :removedMessage="templateData.removedMessage"
      :failedMessage="templateData.failedMessage"
      @change="handleChange"
      @blur="onBlur"
      @inputError="handleInputError"
    ></gui-multi-file-upload>
  </div>
</template>
