// libs/gui/react/src/lib/components/MultiList.tsx
import { GuiErrorsReact, GuiLabelReact, GuiMultiListReact } from '../web-components';
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget, useItemRenderer } from '@golemui/react';
import type { ListItem, MultiListProps, OptionValue } from '@golemui/gui-shared/internals';
import { DefaultMultiListItemRenderer } from './item-renderers/DefaultMultiListItemRenderer';
import { type ListItemRendererProps } from './item-renderers/props';
import type { GuiMultiList } from '@golemui/gui-components/multi-list';

export function MultiList(widgetInstance: WithWidget) {
  const widget = widgetInstance.widget as InputWidget<OptionValue[]>;

  const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useInputWidget<
    OptionValue[],
    MultiListProps<unknown>
  >(widget);

  const handleBlur = useCallback(
    (e: React.FocusEvent) => {
      if (listRef.current && e.relatedTarget && listRef.current.contains(e.relatedTarget as Node)) {
        return;
      }

      onBlur();
    },
    [onBlur],
  );

  const [range, setRange] = useState({ start: 0, end: 10 });
  const [listItems, setListItems] = useState<ListItem<any>[]>([]);
  const [focusedIndex, setFocusedIndex] = useState<number>(-1);

  const listRef = useRef<GuiMultiList>(null);

  const currentValues = useMemo(() => (Array.isArray(value) ? value : []), [value]);

  const visibleItems = useMemo(() => {
    const items = listItems.length > 0 ? listItems : templateData.items || [];
    return items.slice(range.start, range.end);
  }, [listItems, templateData.items, range]);

  const toggleValue = useCallback(
    (val: OptionValue) => {
      if (templateData.disabled || templateData.readonly) return;

      if (currentValues.includes(val)) {
        onValueChanged(currentValues.filter((v) => v !== val));
        return;
      }
      if (templateData.limit !== undefined && currentValues.length >= templateData.limit) return;
      onValueChanged([...currentValues, val]);
    },
    [
      currentValues,
      onValueChanged,
      templateData.disabled,
      templateData.readonly,
      templateData.limit,
    ],
  );

  useEffect(() => {
    const element = listRef.current;
    if (!element) return;

    const handleRangeChange = (e: Event) => {
      const { startIndex, endIndex } = (e as CustomEvent).detail;
      setRange({ start: startIndex, end: endIndex });
    };

    const handleUpdateItems = (e: Event) => {
      const items = (e as CustomEvent).detail;
      setListItems(items ? [...items] : []);
    };

    const handleFocusChange = (e: Event) => {
      const index = (e as CustomEvent).detail.index;
      setFocusedIndex(index);
    };

    const handleChange = (e: Event) => {
      const val = (e as CustomEvent).detail.value;
      toggleValue(val);
    };

    // Binding
    element.addEventListener('change', handleChange);
    element.addEventListener('gui-update-items', handleUpdateItems);
    element.addEventListener('gui-range-change', handleRangeChange);
    element.addEventListener('gui-focus-change', handleFocusChange);

    return () => {
      // Cleanup
      element.removeEventListener('change', handleChange);
      element.removeEventListener('gui-update-items', handleUpdateItems);
      element.removeEventListener('gui-range-change', handleRangeChange);
      element.removeEventListener('gui-focus-change', handleFocusChange);
    };
  }, [toggleValue]);

  const handleClickItem = useCallback(
    (item: ListItem<any>, index: number) => {
      if (templateData.disabled || item.disabled) return;

      toggleValue(item.value);
      setFocusedIndex(index);

      if (listRef.current) {
        listRef.current.focusItemAtIndex(index);
      }
    },
    [templateData.disabled, toggleValue],
  );

  const ItemRenderer = (useItemRenderer(templateData.itemRenderer as string) ||
    DefaultMultiListItemRenderer) as React.ComponentType<ListItemRendererProps<any>>;
  const label = templateData.label as string;
  const isRequired = (templateData.validator as Validator)?.required;
  const isDisabled = templateData.disabled as boolean;
  const isReadOnly = templateData.readonly as boolean;
  const showErrors = isTouched && errors && errors.length > 0;

  return (
    <div className="gui-multi-list-widget gui-field" style={{ flex: templateData.size }}>
      <GuiLabelReact
        targetElement={listRef.current || undefined}
        uid={uid}
        label={label}
        hint={templateData.hint}
        errors={errors}
        touched={isTouched}
        required={isRequired}
        native={false}
      ></GuiLabelReact>

      <div className="gui-widget">
        <GuiMultiListReact
          ref={listRef}
          id={uid}
          uid={uid}
          values={currentValues}
          valueField={templateData.valueField}
          items={templateData.items}
          itemHeight={templateData.itemHeight}
          height={templateData.height}
          required={isRequired}
          touched={isTouched}
          disabled={isDisabled}
          readOnly={isReadOnly}
          onBlur={handleBlur}
        >
          {visibleItems.map((item, index) => {
            const absoluteIndex = range.start + index;
            const isSelected = currentValues.includes(item.value);
            const isFocused = focusedIndex === absoluteIndex;
            const isItemDisabled = isDisabled || !!item.disabled;

            const labelField = templateData.labelField ?? 'label';
            const isObject = item.template !== null && typeof item.template === 'object';
            const template =
              isObject && labelField && !templateData.itemRenderer
                ? item.template[labelField]
                : item.template;

            return (
              <div
                key={absoluteIndex}
                role="option"
                tabIndex={-1}
                id={`${uid}-item-${absoluteIndex}`}
                className="gui-list__item-wrapper"
                style={{ height: `${templateData.itemHeight || 40}px` }}
                aria-selected={isSelected}
                aria-disabled={isItemDisabled ? 'true' : 'false'}
                onClick={() => handleClickItem(item, absoluteIndex)}
              >
                <ItemRenderer
                  template={template}
                  value={item.value}
                  index={index}
                  selected={isSelected}
                  disabled={isItemDisabled}
                  focused={isFocused}
                />
              </div>
            );
          })}
        </GuiMultiListReact>
      </div>

      {showErrors && (
        <GuiErrorsReact uid={uid} errors={errors} touched={isTouched}></GuiErrorsReact>
      )}
    </div>
  );
}

// libs/gui/vue/src/lib/components/MultiList.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget, useVueFormContext } from '@golemui/vue';
import type { ListItem, MultiListProps, OptionValue } from '@golemui/gui-shared/internals';
import { computed, onUnmounted, ref, watch, type Component } from 'vue';
import DefaultMultiListItemRenderer from './item-renderers/DefaultMultiListItemRenderer.vue';
import type { GuiMultiList } from '@golemui/gui-components/multi-list';
import '@golemui/gui-components/label';
import '@golemui/gui-components/multi-list';
import '@golemui/gui-components/errors';

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<OptionValue[]>;
const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useInputWidget<
  OptionValue[],
  MultiListProps<unknown>
>(widget);

const rangeStart = ref(0);
const rangeEnd = ref(10);
const listItems = ref<ListItem<any>[]>([]);
const focusedIndex = ref<number>(-1);
const listRef = ref<GuiMultiList | null>(null);

const currentValues = computed(() => (Array.isArray(value.value) ? value.value : []));

const visibleItems = computed(() => {
  const items = listItems.value.length > 0 ? listItems.value : templateData.value.items || [];
  return items.slice(rangeStart.value, rangeEnd.value);
});

const required = computed(() => (templateData.value.validator as Validator)?.required);
const isDisabled = computed(() => templateData.value.disabled as boolean);
const isReadOnly = computed(() => templateData.value.readonly as boolean);
const showErrors = computed(() => isTouched.value && errors.value && errors.value.length > 0);

const toggleValue = (val: OptionValue) => {
  if (templateData.value.disabled || templateData.value.readonly) return;

  const current = currentValues.value;
  if (current.includes(val)) {
    onValueChanged(current.filter((v) => v !== val));
    return;
  }
  if (templateData.value.limit !== undefined && current.length >= templateData.value.limit) return;
  onValueChanged([...current, val]);
};

const handleRangeChange = (e: Event) => {
  const { startIndex, endIndex } = (e as CustomEvent).detail;
  rangeStart.value = startIndex;
  rangeEnd.value = endIndex;
};
const handleUpdateItems = (e: Event) => {
  const items = (e as CustomEvent).detail;
  listItems.value = items ? [...items] : [];
};
const handleFocusChange = (e: Event) => {
  focusedIndex.value = (e as CustomEvent).detail.index;
};
const handleChange = (e: Event) => {
  toggleValue((e as CustomEvent).detail.value);
};

let currentList: GuiMultiList | null = null;
watch(listRef, (el) => {
  if (currentList) {
    currentList.removeEventListener('change', handleChange);
    currentList.removeEventListener('gui-update-items', handleUpdateItems);
    currentList.removeEventListener('gui-range-change', handleRangeChange);
    currentList.removeEventListener('gui-focus-change', handleFocusChange);
  }
  currentList = el;
  if (el) {
    el.addEventListener('change', handleChange);
    el.addEventListener('gui-update-items', handleUpdateItems);
    el.addEventListener('gui-range-change', handleRangeChange);
    el.addEventListener('gui-focus-change', handleFocusChange);
  }
});

onUnmounted(() => {
  currentList?.removeEventListener('change', handleChange);
  currentList?.removeEventListener('gui-update-items', handleUpdateItems);
  currentList?.removeEventListener('gui-range-change', handleRangeChange);
  currentList?.removeEventListener('gui-focus-change', handleFocusChange);
});

const handleBlur = (e: FocusEvent) => {
  if (listRef.value && e.relatedTarget && listRef.value.contains(e.relatedTarget as Node)) return;
  onBlur();
};

const handleClickItem = (item: ListItem<any>, index: number) => {
  if (templateData.value.disabled || item.disabled) return;
  toggleValue(item.value);
  focusedIndex.value = index;
  listRef.value?.focusItemAtIndex(index);
};

const formContext = useVueFormContext();
const ItemRenderer = computed<Component>(() => {
  const renderers = formContext.itemRenderers as Record<string, Component>;
  return (
    renderers[templateData.value.itemRenderer as string] ||
    (DefaultMultiListItemRenderer as Component)
  );
});
</script>

<template>
  <div class="gui-multi-list-widget gui-field" :style="{ flex: templateData.size }">
    <gui-label
      :uid="uid"
      :label="templateData.label"
      :hint="templateData.hint"
      :errors="errors"
      :touched="isTouched"
      :required="required"
      :native="false"
    ></gui-label>

    <div class="gui-widget">
      <gui-multi-list
        ref="listRef"
        :id="uid"
        :uid="uid"
        :values="currentValues"
        :valueField="templateData.valueField"
        :items="templateData.items"
        :itemHeight="templateData.itemHeight"
        :height="templateData.height"
        :required="required"
        :touched="isTouched"
        :disabled="isDisabled"
        :readOnly="isReadOnly"
        @blur="handleBlur"
      >
        <div
          v-for="(item, idx) in visibleItems"
          :key="rangeStart + idx"
          role="option"
          tabindex="-1"
          :id="`${uid}-item-${rangeStart + idx}`"
          class="gui-list__item-wrapper"
          :style="{ height: `${templateData.itemHeight || 40}px` }"
          :aria-selected="currentValues.includes(item.value)"
          :aria-disabled="isDisabled || item.disabled ? 'true' : 'false'"
          @click="handleClickItem(item, rangeStart + idx)"
        >
          <component
            :is="ItemRenderer"
            :template="
              (() => {
                const labelField = templateData.labelField ?? 'label';
                const isObject = item.template !== null && typeof item.template === 'object';
                return isObject && labelField && !templateData.itemRenderer
                  ? (item.template as any)[labelField]
                  : item.template;
              })()
            "
            :value="item.value"
            :index="idx"
            :selected="currentValues.includes(item.value)"
            :disabled="isDisabled || !!item.disabled"
            :focused="focusedIndex === rangeStart + idx"
          />
        </div>
      </gui-multi-list>
    </div>

    <gui-errors v-if="showErrors" :uid="uid" :errors="errors" :touched="isTouched"></gui-errors>
  </div>
</template>
