// libs/react-vanilla/src/lib/components/Password.tsx
import * as Core from '@golemui/core';
import { useInputWidget } from '@golemui/react';
import { PasswordProps } from '@golemui/shared-vanilla';
import { useCallback } from 'react';
import '../styles.scss';

export function Password(widgetInstance: Core.WithWidget) {
  const widget = widgetInstance.widget as Core.InputWidget<string>;
  const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useInputWidget<
    string,
    PasswordProps
  >(widget);

  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) =>
      onValueChanged((e.nativeEvent as CustomEvent).detail.value),
    [onValueChanged],
  );

  const label = templateData.label as string;
  const hint = templateData.hint;
  const placeholder = templateData.placeholder;
  const showPasswordIcon = templateData.showPasswordIcon;
  const hidePasswordIcon = templateData.hidePasswordIcon;
  const showPasswordLabel = templateData.showPasswordLabel;
  const hidePasswordLabel = templateData.hidePasswordLabel;
  const icon = templateData.icon;
  const isDisabled = templateData.disabled as boolean;
  const isReadonly = templateData.readonly as boolean;
  const isRequired = (templateData.validator as Core.Validator)?.required;

  return (
    <div className="gui-password" style={{ flex: templateData.size }}>
      <gui-password
        uid={uid}
        label={label}
        hint={hint}
        errors={errors}
        touched={isTouched}
        required={isRequired}
        disabled={isDisabled}
        readOnly={isReadonly}
        value={value}
        icon={icon}
        placeholder={placeholder ?? undefined}
        showPasswordIcon={showPasswordIcon}
        hidePasswordIcon={hidePasswordIcon}
        showPasswordLabel={showPasswordLabel}
        hidePasswordLabel={hidePasswordLabel}
        onInput={handleChange}
        onBlur={onBlur}
      ></gui-password>
    </div>
  );
}

// libs/gui/vue/src/lib/components/Password.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/vue';
import type { PasswordProps } from '@golemui/gui-shared';
import { computed } from 'vue';
import '@golemui/gui-components/password';

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<string>;
const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useInputWidget<
  string,
  PasswordProps
>(widget);

const handleInput = (e: Event) => onValueChanged((e as CustomEvent).detail.value);
const required = computed(() => (templateData.value.validator as Validator)?.required);
</script>

<template>
  <div class="gui-password gui-field" :style="{ flex: templateData.size }">
    <gui-password
      :uid="uid"
      :label="templateData.label"
      :hint="templateData.hint"
      :errors="errors"
      :touched="isTouched"
      :required="required"
      :disabled="templateData.disabled"
      :readOnly="templateData.readonly"
      :value="value"
      :icon="templateData.icon"
      :placeholder="templateData.placeholder ?? undefined"
      :autocomplete="templateData.autocomplete ?? undefined"
      :showPasswordIcon="templateData.showPasswordIcon"
      :hidePasswordIcon="templateData.hidePasswordIcon"
      :showPasswordLabel="templateData.showPasswordLabel"
      :hidePasswordLabel="templateData.hidePasswordLabel"
      @input="handleInput"
      @blur="onBlur"
    ></gui-password>
  </div>
</template>
