// libs/gui/react/src/lib/components/RadioGroup.tsx
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/react';
import { type OptionValue, type RadiogroupProps } from '@golemui/gui-shared';
import { useCallback } from 'react';
import { GuiRadiogroupReact } from '../web-components';
import '../styles.scss';


export function RadioGroup(widgetInstance: WithWidget) {
  const widget = widgetInstance.widget as InputWidget<string>;
  const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useInputWidget<
    OptionValue,
    RadiogroupProps
  >(widget);

  const handleChange = useCallback(
    (e: Event) => onValueChanged((e as CustomEvent).detail.value),
    [onValueChanged],
  );

  const label = templateData.label as string;
  const hint = templateData.hint;
  const options = templateData.options;
  const labelField = templateData.labelField;
  const valueField = templateData.valueField;
  const direction = templateData.direction;
  const isDisabled = templateData.disabled as boolean;
  const isReadonly = templateData.readonly as boolean;
  const isRequired = (templateData.validator as Validator)?.required;

  return (
    <div className="gui-radiogroup gui-field" style={{ flex: templateData.size }}>
      <GuiRadiogroupReact
        uid={uid}
        label={label}
        errors={errors}
        touched={isTouched}
        required={isRequired}
        disabled={isDisabled}
        readOnly={isReadonly}
        value={value}
        hint={hint}
        options={options}
        labelField={labelField}
        valueField={valueField}
        direction={direction}
        onChange={handleChange}
        onBlur={onBlur}
      ></GuiRadiogroupReact>
    </div>
  );
}

// libs/gui/vue/src/lib/components/RadioGroup.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/vue';
import type { OptionValue, RadiogroupProps } from '@golemui/gui-shared';
import { computed } from 'vue';
import '@golemui/gui-components/radiogroup';

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<string>;
const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useInputWidget<
  OptionValue,
  RadiogroupProps
>(widget);

const handleChange = (e: Event) => onValueChanged((e as CustomEvent).detail.value);
const required = computed(() => (templateData.value.validator as Validator)?.required);
// Mirror Lit class-field default to avoid Vue coercing undefined → '' on the enum prop.
const direction = computed(() => templateData.value.direction || 'column');
</script>

<template>
  <div class="gui-radiogroup gui-field" :style="{ flex: templateData.size }">
    <gui-radiogroup
      :uid="uid"
      :label="templateData.label"
      :errors="errors"
      :touched="isTouched"
      :required="required"
      :disabled="templateData.disabled"
      :readOnly="templateData.readonly"
      :value="value"
      :hint="templateData.hint"
      :options="templateData.options"
      :labelField="templateData.labelField"
      :valueField="templateData.valueField"
      :direction.prop="direction"
      @change="handleChange"
      @blur="onBlur"
    ></gui-radiogroup>
  </div>
</template>
