// libs/gui/react/src/lib/components/RangeDateTimePicker.tsx
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/react';
import type { DateTimeRange, RangeDateTimePickerProps } from '@golemui/gui-shared/internals';
import { useCallback } from 'react';
import { GuiRangeDateTimePickerReact } from '../web-components';
import '../styles.scss';

export function RangeDateTimePicker(widgetInstance: WithWidget) {
  const widget = widgetInstance.widget as InputWidget<DateTimeRange[]>;
  const {
    uid,
    errors,
    value,
    isTouched,
    templateData,
    onBlur,
    onValueChanged,
    injectValidationIssues,
  } = useInputWidget<DateTimeRange[], RangeDateTimePickerProps>(widget);

  const handleChange = useCallback(
    (e: Event) => {
      injectValidationIssues(null);
      onValueChanged((e as CustomEvent).detail.value);
    },
    [injectValidationIssues, onValueChanged],
  );

  const handleInputError = useCallback(
    (e: Event) => {
      injectValidationIssues([(e as CustomEvent).detail.message]);
      // Surface the error immediately on a completed selection.
      onBlur();
    },
    [injectValidationIssues, onBlur],
  );

  const isRequired = (templateData.validator as Validator)?.required;

  return (
    <div className="gui-range-date-time-picker gui-field" style={{ flex: templateData.size }}>
      <GuiRangeDateTimePickerReact
        uid={uid}
        label={templateData.label as string}
        hint={templateData.hint}
        icon={templateData.icon}
        errors={errors}
        touched={isTouched}
        required={isRequired}
        disabled={templateData.disabled as boolean}
        readOnly={templateData.readonly as boolean}
        value={value}
        separator={templateData.separator as string}
        removePillAriaLabel={templateData.removePillAriaLabel}
        startDateTimeAriaLabel={templateData.startDateTimeAriaLabel as string}
        endDateTimeAriaLabel={templateData.endDateTimeAriaLabel as string}
        invalidDateMessage={templateData.invalidDateMessage as string}
        prevMonthIcon={templateData.prevMonthIcon}
        nextMonthIcon={templateData.nextMonthIcon}
        prevMonthAriaLabel={templateData.prevMonthAriaLabel}
        nextMonthAriaLabel={templateData.nextMonthAriaLabel}
        selectYearAriaLabel={templateData.selectYearAriaLabel}
        yearGridAriaLabel={templateData.yearGridAriaLabel}
        dayFormat={templateData.dayFormat}
        weekdayFormat={templateData.weekdayFormat}
        monthFormat={templateData.monthFormat}
        numberOfMonths={templateData.numberOfMonths}
        localeId={templateData.lang}
        toggleAriaLabel={templateData.toggleAriaLabel}
        dayAriaLabel={templateData.dayAriaLabel}
        monthAriaLabel={templateData.monthAriaLabel}
        yearAriaLabel={templateData.yearAriaLabel}
        hourAriaLabel={templateData.hourAriaLabel}
        minuteAriaLabel={templateData.minuteAriaLabel}
        dayPeriodAriaLabel={templateData.dayPeriodAriaLabel}
        hourFormat={templateData.hourFormat}
        minuteStep={templateData.minuteStep}
        allowCustomTime={templateData.allowCustomTime}
        startTimeLabel={templateData.startTimeLabel as string}
        endTimeLabel={templateData.endTimeLabel as string}
        minDateTime={templateData.minDateTime}
        maxDateTime={templateData.maxDateTime}
        disabledRanges={templateData.disabledRanges}
        minDateTimeMessage={templateData.minDateTimeMessage as string}
        maxDateTimeMessage={templateData.maxDateTimeMessage as string}
        disabledRangeMessage={templateData.disabledRangeMessage as string}
        noAvailableTimesMessage={templateData.noAvailableTimesMessage as string}
        incompleteMessage={templateData.incompleteMessage as string}
        allowEdit={templateData.allowEdit}
        editLabel={templateData.editLabel as string}
        editAriaLabel={templateData.editAriaLabel as string}
        confirmEditLabel={templateData.confirmEditLabel as string}
        cancelEditLabel={templateData.cancelEditLabel as string}
        editStartedMessage={templateData.editStartedMessage as string}
        editCommittedMessage={templateData.editCommittedMessage as string}
        editCancelledMessage={templateData.editCancelledMessage as string}
        dayCountAriaLabel={templateData.dayCountAriaLabel as string}
        disabledDayCountAriaLabel={templateData.disabledDayCountAriaLabel as string}
        onGuiInput={handleChange}
        onGuiBlur={onBlur}
        onGuiInputError={handleInputError}
      />
    </div>
  );
}

// libs/gui/vue/src/lib/components/RangeDateTimePicker.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/vue';
import type { DateTimeRange, RangeDateTimePickerProps } from '@golemui/gui-shared/internals';
import { computed, onUnmounted, ref, watch } from 'vue';
import '@golemui/gui-components/range-date-time-picker';

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<DateTimeRange[]>;
const {
  uid,
  errors,
  value,
  isTouched,
  templateData,
  onValueChanged,
  onBlur,
  injectValidationIssues,
} = useInputWidget<DateTimeRange[], RangeDateTimePickerProps>(widget);

const required = computed(() => (templateData.value.validator as Validator)?.required);

const dayFormat = computed(() => templateData.value.dayFormat || 'numeric');
const weekdayFormat = computed(() => templateData.value.weekdayFormat || 'narrow');
const monthFormat = computed(() => templateData.value.monthFormat || 'long');
const numberOfMonths = computed(() => templateData.value.numberOfMonths ?? 1);

const pickerRef = ref<HTMLElement | null>(null);
const changeHandler = (e: Event) => {
  injectValidationIssues(null);
  onValueChanged((e as CustomEvent).detail.value);
};
const errorHandler = (e: Event) => {
  injectValidationIssues([(e as CustomEvent).detail.message]);
  onBlur();
};

let currentEl: HTMLElement | null = null;
watch(pickerRef, (el) => {
  if (currentEl) {
    currentEl.removeEventListener('gui-input', changeHandler);
    currentEl.removeEventListener('gui-input-error', errorHandler);
    currentEl.removeEventListener('gui-blur', onBlur);
  }
  currentEl = el;
  if (el) {
    el.addEventListener('gui-input', changeHandler);
    el.addEventListener('gui-input-error', errorHandler);
    el.addEventListener('gui-blur', onBlur);
  }
});

onUnmounted(() => {
  currentEl?.removeEventListener('gui-input', changeHandler);
  currentEl?.removeEventListener('gui-input-error', errorHandler);
  currentEl?.removeEventListener('gui-blur', onBlur);
});
</script>

<template>
  <div class="gui-range-date-time-picker gui-field" :style="{ flex: templateData.size }">
    <gui-range-date-time-picker
      ref="pickerRef"
      :uid="uid"
      :label="templateData.label"
      :hint="templateData.hint"
      :icon="templateData.icon"
      :errors="errors"
      :touched="isTouched"
      :required="required"
      :disabled="templateData.disabled"
      :readOnly="templateData.readonly"
      :value.prop="value"
      :separator="templateData.separator"
      :removePillAriaLabel="templateData.removePillAriaLabel"
      :startDateTimeAriaLabel="templateData.startDateTimeAriaLabel"
      :endDateTimeAriaLabel="templateData.endDateTimeAriaLabel"
      :invalidDateMessage="templateData.invalidDateMessage"
      :prevMonthIcon="templateData.prevMonthIcon"
      :nextMonthIcon="templateData.nextMonthIcon"
      :prevMonthAriaLabel="templateData.prevMonthAriaLabel"
      :nextMonthAriaLabel="templateData.nextMonthAriaLabel"
      :selectYearAriaLabel="templateData.selectYearAriaLabel"
      :yearGridAriaLabel="templateData.yearGridAriaLabel"
      :dayFormat.prop="dayFormat"
      :weekdayFormat.prop="weekdayFormat"
      :monthFormat.prop="monthFormat"
      :numberOfMonths.prop="numberOfMonths"
      :localeId="templateData.lang"
      :toggleAriaLabel="templateData.toggleAriaLabel"
      :dayAriaLabel="templateData.dayAriaLabel"
      :monthAriaLabel="templateData.monthAriaLabel"
      :yearAriaLabel="templateData.yearAriaLabel"
      :hourAriaLabel="templateData.hourAriaLabel"
      :minuteAriaLabel="templateData.minuteAriaLabel"
      :dayPeriodAriaLabel="templateData.dayPeriodAriaLabel"
      :hourFormat="templateData.hourFormat"
      :minuteStep="templateData.minuteStep"
      :allowCustomTime="templateData.allowCustomTime"
      :startTimeLabel="templateData.startTimeLabel"
      :endTimeLabel="templateData.endTimeLabel"
      :minDateTime="templateData.minDateTime"
      :maxDateTime="templateData.maxDateTime"
      :disabledRanges.prop="templateData.disabledRanges"
      :minDateTimeMessage="templateData.minDateTimeMessage"
      :maxDateTimeMessage="templateData.maxDateTimeMessage"
      :disabledRangeMessage="templateData.disabledRangeMessage"
      :noAvailableTimesMessage="templateData.noAvailableTimesMessage"
      :incompleteMessage="templateData.incompleteMessage"
      :allowEdit="templateData.allowEdit"
      :editLabel="templateData.editLabel"
      :editAriaLabel="templateData.editAriaLabel"
      :confirmEditLabel="templateData.confirmEditLabel"
      :cancelEditLabel="templateData.cancelEditLabel"
      :editStartedMessage="templateData.editStartedMessage"
      :editCommittedMessage="templateData.editCommittedMessage"
      :editCancelledMessage="templateData.editCancelledMessage"
      :dayCountAriaLabel="templateData.dayCountAriaLabel"
      :disabledDayCountAriaLabel="templateData.disabledDayCountAriaLabel"
    />
  </div>
</template>
