// libs/gui/react/src/lib/components/RangeDateTimeInput.tsx
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/react';
import type { DateTimeRange, RangeDateTimeInputProps } from '@golemui/gui-shared/internals';
import { useCallback } from 'react';
import { GuiRangeDateTimeReact } from '../web-components';
import '../styles.scss';

export function RangeDateTimeInput(widgetInstance: WithWidget) {
  const widget = widgetInstance.widget as InputWidget<DateTimeRange[]>;
  const {
    uid,
    errors,
    value,
    isTouched,
    templateData,
    onBlur,
    onValueChanged,
    injectValidationIssues,
  } = useInputWidget<DateTimeRange[], RangeDateTimeInputProps>(widget);

  const handleRef = useCallback(
    (node: HTMLElement | null) => {
      const target = node as any;
      const changeHandler = (e: CustomEvent) => {
        injectValidationIssues(null);
        onValueChanged(e.detail.value);
      };
      const blurHandler = () => {
        onBlur();
      };
      const errorHandler = (e: CustomEvent) => {
        injectValidationIssues([e.detail.message]);
      };

      if (node) {
        target.addEventListener('blur', blurHandler);
        target.addEventListener('change', changeHandler);
        target.addEventListener('inputError', errorHandler);
      }

      return () => {
        target.removeEventListener('blur', blurHandler);
        target.removeEventListener('change', changeHandler);
        target.removeEventListener('inputError', errorHandler);
      };
    },
    [onValueChanged, onBlur, injectValidationIssues],
  );

  const label = templateData.label as string;
  const hint = templateData.hint;
  const icon = templateData.icon;
  const lang = templateData.lang;
  const separator = templateData.separator;
  const removePillAriaLabel = templateData.removePillAriaLabel;
  const startDateTimeAriaLabel = templateData.startDateTimeAriaLabel;
  const endDateTimeAriaLabel = templateData.endDateTimeAriaLabel;
  const isDisabled = templateData.disabled as boolean;
  const isReadonly = templateData.readonly as boolean;
  const isRequired = (templateData.validator as Validator)?.required;

  return (
    <div className="gui-range-date-time-input gui-field" style={{ flex: templateData.size }}>
      <GuiRangeDateTimeReact
        ref={handleRef}
        uid={uid}
        label={label}
        hint={hint}
        errors={errors}
        touched={isTouched}
        required={isRequired}
        disabled={isDisabled}
        readOnly={isReadonly}
        value={value}
        icon={icon}
        localeId={lang}
        dayAriaLabel={templateData.dayAriaLabel}
        monthAriaLabel={templateData.monthAriaLabel}
        yearAriaLabel={templateData.yearAriaLabel}
        hourAriaLabel={templateData.hourAriaLabel}
        minuteAriaLabel={templateData.minuteAriaLabel}
        dayPeriodAriaLabel={templateData.dayPeriodAriaLabel}
        separator={separator}
        removePillAriaLabel={removePillAriaLabel}
        startDateTimeAriaLabel={startDateTimeAriaLabel}
        endDateTimeAriaLabel={endDateTimeAriaLabel}
        hourFormat={templateData.hourFormat}
        minuteStep={templateData.minuteStep}
        minDateTime={templateData.minDateTime}
        maxDateTime={templateData.maxDateTime}
        invalidDateMessage={templateData.invalidDateMessage as string}
        minDateTimeMessage={templateData.minDateTimeMessage as string}
        maxDateTimeMessage={templateData.maxDateTimeMessage as string}
        incompleteMessage={templateData.incompleteMessage as string}
        allowEdit={templateData.allowEdit}
        editLabel={templateData.editLabel as string}
        editAriaLabel={templateData.editAriaLabel as string}
        confirmEditLabel={templateData.confirmEditLabel as string}
        cancelEditLabel={templateData.cancelEditLabel as string}
        editStartedMessage={templateData.editStartedMessage as string}
        editCommittedMessage={templateData.editCommittedMessage as string}
        editCancelledMessage={templateData.editCancelledMessage as string}
      />
    </div>
  );
}

// libs/gui/vue/src/lib/components/RangeDateTimeInput.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/vue';
import type { DateTimeRange, RangeDateTimeInputProps } from '@golemui/gui-shared/internals';
import { computed, onUnmounted, ref, watch } from 'vue';
import '@golemui/gui-components/range-date-time-input';

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<DateTimeRange[]>;
const {
  uid,
  errors,
  value,
  isTouched,
  templateData,
  onValueChanged,
  onBlur,
  injectValidationIssues,
} = useInputWidget<DateTimeRange[], RangeDateTimeInputProps>(widget);

const required = computed(() => (templateData.value.validator as Validator)?.required);

const elRef = ref<HTMLElement | null>(null);
const changeHandler = (e: Event) => {
  injectValidationIssues(null);
  onValueChanged((e as CustomEvent).detail.value);
};
const blurHandler = () => onBlur();
const errorHandler = (e: Event) => {
  injectValidationIssues([(e as CustomEvent).detail.message]);
};

let currentEl: HTMLElement | null = null;
watch(elRef, (el) => {
  if (currentEl) {
    currentEl.removeEventListener('blur', blurHandler);
    currentEl.removeEventListener('change', changeHandler);
    currentEl.removeEventListener('inputError', errorHandler);
  }
  currentEl = el;
  if (el) {
    el.addEventListener('blur', blurHandler);
    el.addEventListener('change', changeHandler);
    el.addEventListener('inputError', errorHandler);
  }
});

onUnmounted(() => {
  currentEl?.removeEventListener('blur', blurHandler);
  currentEl?.removeEventListener('change', changeHandler);
  currentEl?.removeEventListener('inputError', errorHandler);
});
</script>

<template>
  <div class="gui-range-date-time-input gui-field" :style="{ flex: templateData.size }">
    <gui-range-date-time
      ref="elRef"
      :uid="uid"
      :label="templateData.label"
      :hint="templateData.hint"
      :errors="errors"
      :touched="isTouched"
      :required="required"
      :disabled="templateData.disabled"
      :readOnly="templateData.readonly"
      :value="value"
      :icon="templateData.icon"
      :localeId="templateData.lang"
      :dayAriaLabel="templateData.dayAriaLabel"
      :monthAriaLabel="templateData.monthAriaLabel"
      :yearAriaLabel="templateData.yearAriaLabel"
      :hourAriaLabel="templateData.hourAriaLabel"
      :minuteAriaLabel="templateData.minuteAriaLabel"
      :dayPeriodAriaLabel="templateData.dayPeriodAriaLabel"
      :separator="templateData.separator"
      :removePillAriaLabel="templateData.removePillAriaLabel"
      :startDateTimeAriaLabel="templateData.startDateTimeAriaLabel"
      :endDateTimeAriaLabel="templateData.endDateTimeAriaLabel"
      :hourFormat="templateData.hourFormat"
      :minuteStep="templateData.minuteStep"
      :minDateTime="templateData.minDateTime"
      :maxDateTime="templateData.maxDateTime"
      :invalidDateMessage="templateData.invalidDateMessage"
      :minDateTimeMessage="templateData.minDateTimeMessage"
      :maxDateTimeMessage="templateData.maxDateTimeMessage"
      :incompleteMessage="templateData.incompleteMessage"
      :allowEdit="templateData.allowEdit"
      :editLabel="templateData.editLabel"
      :editAriaLabel="templateData.editAriaLabel"
      :confirmEditLabel="templateData.confirmEditLabel"
      :cancelEditLabel="templateData.cancelEditLabel"
      :editStartedMessage="templateData.editStartedMessage"
      :editCommittedMessage="templateData.editCommittedMessage"
      :editCancelledMessage="templateData.editCancelledMessage"
    />
  </div>
</template>
