// libs/gui/react/src/lib/components/RangeCalendar.tsx
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/react';
import type { DateRange, RangeCalendarProps } from '@golemui/gui-shared/internals';
import { useCallback } from 'react';
import { GuiRangeCalendarReact } from '../web-components';
import '../styles.scss';

export function RangeCalendar(widgetInstance: WithWidget) {
  const widget = widgetInstance.widget as InputWidget<DateRange[]>;
  const {
    uid,
    errors,
    value,
    isTouched,
    templateData,
    onBlur,
    onValueChanged,
    injectValidationIssues,
  } = useInputWidget<DateRange[], RangeCalendarProps>(widget);

  const handleRef = useCallback(
    (node: HTMLElement | null) => {
      const target = node as any;
      const changeHandler = (e: CustomEvent) => {
        injectValidationIssues(null);
        onValueChanged(e.detail.value);
      };
      const blurHandler = () => {
        onBlur();
      };
      const errorHandler = (e: CustomEvent) => {
        injectValidationIssues([e.detail.message]);
        onBlur();
      };
      if (node) {
        target.addEventListener('gui-blur', blurHandler);
        target.addEventListener('gui-input', changeHandler);
        target.addEventListener('gui-input-error', errorHandler);
      }

      return () => {
        target.removeEventListener('gui-blur', blurHandler);
        target.removeEventListener('gui-input', changeHandler);
        target.removeEventListener('gui-input-error', errorHandler);
      };
    },
    [onValueChanged, onBlur, injectValidationIssues],
  );

  const label = templateData.label as string;
  const hint = templateData.hint;
  const prevMonthIcon = templateData.prevMonthIcon;
  const nextMonthIcon = templateData.nextMonthIcon;
  const prevMonthAriaLabel = templateData.prevMonthAriaLabel;
  const nextMonthAriaLabel = templateData.nextMonthAriaLabel;
  const selectYearAriaLabel = templateData.selectYearAriaLabel;
  const yearGridAriaLabel = templateData.yearGridAriaLabel;
  const dayFormat = templateData.dayFormat;
  const weekdayFormat = templateData.weekdayFormat;
  const monthFormat = templateData.monthFormat;
  const minDate = templateData.minDate;
  const maxDate = templateData.maxDate;
  const disabledRanges = templateData.disabledRanges;
  const numberOfMonths = templateData.numberOfMonths;
  const removePillAriaLabel = templateData.removePillAriaLabel;
  const lang = templateData.lang;
  const isDisabled = templateData.disabled as boolean;
  const isReadonly = templateData.readonly as boolean;
  const isRequired = (templateData.validator as Validator)?.required;

  return (
    <div className="gui-range-calendar gui-field" style={{ flex: templateData.size }}>
      <GuiRangeCalendarReact
        ref={handleRef}
        uid={uid}
        label={label}
        hint={hint}
        errors={errors}
        touched={isTouched}
        required={isRequired}
        disabled={isDisabled}
        readOnly={isReadonly}
        value={value}
        prevMonthIcon={prevMonthIcon}
        nextMonthIcon={nextMonthIcon}
        prevMonthAriaLabel={prevMonthAriaLabel}
        nextMonthAriaLabel={nextMonthAriaLabel}
        selectYearAriaLabel={selectYearAriaLabel}
        yearGridAriaLabel={yearGridAriaLabel}
        dayFormat={dayFormat}
        weekdayFormat={weekdayFormat}
        monthFormat={monthFormat}
        minDate={minDate}
        maxDate={maxDate}
        disabledRanges={disabledRanges}
        disabledDateRangeMessage={templateData.disabledDateRangeMessage as string}
        numberOfMonths={numberOfMonths}
        hidePills={false}
        removePillAriaLabel={removePillAriaLabel}
        localeId={lang}
        allowEdit={templateData.allowEdit}
        editLabel={templateData.editLabel as string}
        editAriaLabel={templateData.editAriaLabel as string}
        confirmEditLabel={templateData.confirmEditLabel as string}
        cancelEditLabel={templateData.cancelEditLabel as string}
        editStartedMessage={templateData.editStartedMessage as string}
        editCommittedMessage={templateData.editCommittedMessage as string}
        editCancelledMessage={templateData.editCancelledMessage as string}
      />
    </div>
  );
}

// libs/gui/vue/src/lib/components/RangeCalendar.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/vue';
import type { DateRange, RangeCalendarProps } from '@golemui/gui-shared/internals';
import { computed, onUnmounted, ref, watch } from 'vue';
import '@golemui/gui-components/range-calendar';

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<DateRange[]>;
const {
  uid,
  errors,
  value,
  isTouched,
  templateData,
  onValueChanged,
  onBlur,
  injectValidationIssues,
} = useInputWidget<DateRange[], RangeCalendarProps>(widget);

const required = computed(() => (templateData.value.validator as Validator)?.required);

// Default to the same values as the Lit element's class-field initializers so
// we never pass undefined or '' (which Intl.DateTimeFormat rejects with a RangeError).
const dayFormat = computed(() => templateData.value.dayFormat || 'numeric');
const weekdayFormat = computed(() => templateData.value.weekdayFormat || 'narrow');
const monthFormat = computed(() => templateData.value.monthFormat || 'long');
const numberOfMonths = computed(() => templateData.value.numberOfMonths ?? 1);

const elRef = ref<HTMLElement | null>(null);
const changeHandler = (e: Event) => {
  injectValidationIssues(null);
  onValueChanged((e as CustomEvent).detail.value);
};
const blurHandler = () => onBlur();
const errorHandler = (e: Event) => {
  injectValidationIssues([(e as CustomEvent).detail.message]);
  onBlur();
};

let currentEl: HTMLElement | null = null;
watch(elRef, (el) => {
  if (currentEl) {
    currentEl.removeEventListener('gui-blur', blurHandler);
    currentEl.removeEventListener('gui-input', changeHandler);
    currentEl.removeEventListener('gui-input-error', errorHandler);
  }
  currentEl = el;
  if (el) {
    el.addEventListener('gui-blur', blurHandler);
    el.addEventListener('gui-input', changeHandler);
    el.addEventListener('gui-input-error', errorHandler);
  }
});

onUnmounted(() => {
  currentEl?.removeEventListener('gui-blur', blurHandler);
  currentEl?.removeEventListener('gui-input', changeHandler);
  currentEl?.removeEventListener('gui-input-error', errorHandler);
});
</script>

<template>
  <div class="gui-range-calendar gui-field" :style="{ flex: templateData.size }">
    <gui-range-calendar
      ref="elRef"
      :uid="uid"
      :label="templateData.label"
      :hint="templateData.hint"
      :errors="errors"
      :touched="isTouched"
      :required="required"
      :disabled="templateData.disabled"
      :readOnly="templateData.readonly"
      :value="value"
      :prevMonthIcon="templateData.prevMonthIcon"
      :nextMonthIcon="templateData.nextMonthIcon"
      :prevMonthAriaLabel="templateData.prevMonthAriaLabel"
      :nextMonthAriaLabel="templateData.nextMonthAriaLabel"
      :selectYearAriaLabel="templateData.selectYearAriaLabel"
      :yearGridAriaLabel="templateData.yearGridAriaLabel"
      :dayFormat.prop="dayFormat"
      :weekdayFormat.prop="weekdayFormat"
      :monthFormat.prop="monthFormat"
      :minDate="templateData.minDate"
      :maxDate="templateData.maxDate"
      :disabledRanges="templateData.disabledRanges"
      :disabledDateRangeMessage="templateData.disabledDateRangeMessage"
      :numberOfMonths.prop="numberOfMonths"
      :hidePills="false"
      :removePillAriaLabel="templateData.removePillAriaLabel"
      :localeId="templateData.lang"
      :allowEdit="templateData.allowEdit"
      :editLabel="templateData.editLabel"
      :editAriaLabel="templateData.editAriaLabel"
      :confirmEditLabel="templateData.confirmEditLabel"
      :cancelEditLabel="templateData.cancelEditLabel"
      :editStartedMessage="templateData.editStartedMessage"
      :editCommittedMessage="templateData.editCommittedMessage"
      :editCancelledMessage="templateData.editCancelledMessage"
    />
  </div>
</template>
