// libs/gui/react/src/lib/components/Renderer.tsx
import type * as Core from '@golemui/core';
import { useDisplayWdiget } from '@golemui/react';
import { type RendererProps } from '@golemui/gui-shared';
import { type ReactNode } from 'react';

export function Renderer(widgetInstance: Core.WithWidget) {
  const widget = widgetInstance.widget as Core.DisplayWidget;
  const { uid, templateData } = useDisplayWdiget<RendererProps<ReactNode>>(widget);
  const renderedElement = templateData?.render;
  return (
    <div className="gui-renderer gui-field" style={{ flex: templateData.size }}>
      <div className="gui-widget" id={uid}>
        {renderedElement}
      </div>
    </div>
  );
}

// libs/gui/vue/src/lib/components/Renderer.vue
<script setup lang="ts">
import type { DisplayWidget, WithWidget } from '@golemui/core';
import { useDisplayWidget } from '@golemui/vue';
import type { RendererProps } from '@golemui/gui-shared';
import type { VNode } from 'vue';

const props = defineProps<WithWidget>();
const widget = props.widget as DisplayWidget;
const { uid, templateData } = useDisplayWidget<RendererProps<VNode | string>>(widget);
</script>

<template>
  <div class="gui-renderer gui-field" :style="{ flex: templateData.size }">
    <div class="gui-widget" :id="uid">
      <template v-if="typeof templateData.render === 'string'">
        {{ templateData.render }}
      </template>
      <template v-else-if="templateData.render">
        <component :is="templateData.render" />
      </template>
    </div>
  </div>
</template>
