// libs/gui/react/src/lib/components/Tags.tsx
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/react';
import type { TagsProps } from '@golemui/gui-shared/internals';
import { useCallback } from 'react';
import { GuiTagsReact } from '../web-components';
import '../styles.scss';

export function Tags(widgetInstance: WithWidget) {
  const widget = widgetInstance.widget as InputWidget<string[]>;
  const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useInputWidget<
    string[],
    TagsProps
  >(widget);

  const handleChange = useCallback(
    (e: Event) => onValueChanged((e as CustomEvent).detail.value),
    [onValueChanged],
  );

  const label = templateData.label as string;
  const hint = templateData.hint;
  const placeholder = templateData.placeholder;
  const icon = templateData.icon;
  const separators = templateData.separators;
  const allowDuplicates = templateData.allowDuplicates ?? true;
  const trim = templateData.trim ?? true;
  const removeAriaLabel = templateData.removeAriaLabel;
  const removeIcon = templateData.removeIcon;
  const isDisabled = templateData.disabled as boolean;
  const isReadonly = templateData.readonly as boolean;
  const isRequired = (templateData.validator as Validator)?.required;

  return (
    <div className="gui-tags gui-field" style={{ flex: templateData.size }}>
      <GuiTagsReact
        uid={uid}
        label={label}
        hint={hint}
        errors={errors}
        touched={isTouched}
        required={isRequired}
        disabled={isDisabled}
        readOnly={isReadonly}
        value={value}
        placeholder={placeholder ?? undefined}
        icon={icon}
        separators={separators}
        allowDuplicates={allowDuplicates}
        trim={trim}
        removeAriaLabel={removeAriaLabel}
        removeIcon={removeIcon}
        onChange={handleChange}
        onBlur={onBlur}
      ></GuiTagsReact>
    </div>
  );
}

// libs/gui/vue/src/lib/components/Tags.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/vue';
import type { TagsProps } from '@golemui/gui-shared/internals';
import { computed } from 'vue';
import '@golemui/gui-components/tags';

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<string[]>;
const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useInputWidget<
  string[],
  TagsProps
>(widget);

const handleChange = (e: Event) => onValueChanged((e as CustomEvent).detail.value as string[]);

const required = computed(() => (templateData.value.validator as Validator)?.required);
</script>

<template>
  <div class="gui-tags gui-field" :style="{ flex: templateData.size }">
    <gui-tags
      :uid="uid"
      :label="templateData.label"
      :hint="templateData.hint"
      :errors="errors"
      :touched="isTouched"
      :required="required"
      :disabled="templateData.disabled"
      :readOnly="templateData.readonly"
      :value="value"
      :placeholder="templateData.placeholder ?? undefined"
      :icon="templateData.icon"
      :separators="templateData.separators"
      :allowDuplicates="templateData.allowDuplicates ?? true"
      :trim="templateData.trim ?? true"
      :removeAriaLabel="templateData.removeAriaLabel"
      :removeIcon="templateData.removeIcon"
      @gui-input="handleChange"
      @gui-blur="onBlur"
    ></gui-tags>
  </div>
</template>
