// libs/gui/angular/src/lib/components/tags/tags.component.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  inject,
  type OnDestroy,
  type OnInit,
} from '@angular/core';
import { InputWidgetAdapter } from '@golemui/angular';
import type { InputWidget, WithWidget } from '@golemui/core';
import { type TagsProps } from '@golemui/gui-shared';
import '@golemui/gui-components/tags';

@Component({
  standalone: true,
  selector: 'gui-tags-control',
  imports: [CommonModule],
  providers: [InputWidgetAdapter],
  templateUrl: './tags.component.html',
  host: {
    class: 'gui-tags gui-field',
    '[style.flex]': 'this.adapter.templateData().size',
  },
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class TagsComponent implements OnInit, OnDestroy, WithWidget {
  widget!: InputWidget<string[]>;
  protected adapter: InputWidgetAdapter<string[], TagsProps> = inject(InputWidgetAdapter);

  ngOnInit(): void {
    this.adapter.init(this.widget);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }

  valueChanged(event: Event) {
    const value = (event as CustomEvent).detail.value as string[];
    this.adapter.valueChanged(value);
  }
}

@let templateData = adapter.templateData();

<gui-tags
  [uid]="widget.uid"
  [label]="templateData.label"
  [hint]="templateData.hint"
  [errors]="templateData.errors"
  [touched]="templateData.touched"
  [required]="templateData.validator?.required"
  [disabled]="templateData.disabled"
  [readOnly]="templateData.readonly"
  [value]="templateData.value ?? []"
  [placeholder]="templateData.placeholder"
  [icon]="templateData.icon"
  [separators]="templateData.separators"
  [allowDuplicates]="templateData.allowDuplicates ?? true"
  [trim]="templateData.trim ?? true"
  [limit]="templateData.limit"
  [removeAriaLabel]="templateData.removeAriaLabel"
  [removeIcon]="templateData.removeIcon"
  (change)="valueChanged($event)"
  (blur)="adapter.onBlur()"
></gui-tags>

// libs/gui/vue/src/lib/components/Tags.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/vue';
import type { TagsProps } from '@golemui/gui-shared';
import { computed } from 'vue';
import '@golemui/gui-components/tags';

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<string[]>;
const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useInputWidget<
  string[],
  TagsProps
>(widget);

const handleChange = (e: Event) =>
  onValueChanged((e as CustomEvent).detail.value as string[]);

const required = computed(() => (templateData.value.validator as Validator)?.required);
</script>

<template>
  <div class="gui-tags gui-field" :style="{ flex: templateData.size }">
    <gui-tags
      :uid="uid"
      :label="templateData.label"
      :hint="templateData.hint"
      :errors="errors"
      :touched="isTouched"
      :required="required"
      :disabled="templateData.disabled"
      :readOnly="templateData.readonly"
      :value="value"
      :placeholder="templateData.placeholder ?? undefined"
      :icon="templateData.icon"
      :separators="templateData.separators"
      :allowDuplicates="templateData.allowDuplicates ?? true"
      :trim="templateData.trim ?? true"
      :limit="templateData.limit"
      :removeAriaLabel="templateData.removeAriaLabel"
      :removeIcon="templateData.removeIcon"
      @change="handleChange"
      @blur="onBlur"
    ></gui-tags>
  </div>
</template>
