// libs/gui/react/src/lib/components/TextInput.tsx
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/react';
import type { TextinputProps } from '@golemui/gui-shared/internals';
import { useCallback } from 'react';
import { GuiTextinputReact } from '../web-components';
import '../styles.scss';

export function TextInput(widgetInstance: WithWidget) {
  const widget = widgetInstance.widget as InputWidget<string>;
  const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useInputWidget<
    string,
    TextinputProps
  >(widget);

  const handleChange = useCallback(
    (e: Event) => onValueChanged((e as CustomEvent).detail.value),
    [onValueChanged],
  );

  const label = templateData.label as string;
  const hint = templateData.hint;
  const placeholder = templateData.placeholder;
  const autocomplete = templateData.autocomplete;
  const icon = templateData.icon;
  const isDisabled = templateData.disabled as boolean;
  const isReadonly = templateData.readonly as boolean;
  const isRequired = (templateData.validator as Validator)?.required;

  return (
    <div className="gui-textinput gui-field" style={{ flex: templateData.size }}>
      <GuiTextinputReact
        uid={uid}
        label={label}
        hint={hint}
        errors={errors}
        touched={isTouched}
        required={isRequired}
        disabled={isDisabled}
        readOnly={isReadonly}
        value={value}
        icon={icon}
        placeholder={placeholder ?? undefined}
        autocomplete={autocomplete ?? undefined}
        onInput={handleChange}
        onBlur={onBlur}
      ></GuiTextinputReact>
    </div>
  );
}

// libs/gui/vue/src/lib/components/TextInput.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/vue';
import type { TextinputProps } from '@golemui/gui-shared/internals';
import { computed } from 'vue';
import '@golemui/gui-components/textinput';

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<string>;
const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useInputWidget<
  string,
  TextinputProps
>(widget);

const handleInput = (e: Event) => onValueChanged((e as CustomEvent).detail.value);

const required = computed(() => (templateData.value.validator as Validator)?.required);
</script>

<template>
  <div class="gui-textinput gui-field" :style="{ flex: templateData.size }">
    <gui-textinput
      :uid="uid"
      :label="templateData.label"
      :hint="templateData.hint"
      :errors="errors"
      :touched="isTouched"
      :required="required"
      :disabled="templateData.disabled"
      :readOnly="templateData.readonly"
      :value="value"
      :icon="templateData.icon"
      :placeholder="templateData.placeholder ?? undefined"
      :autocomplete="templateData.autocomplete ?? undefined"
      @gui-input="handleInput"
      @gui-blur="onBlur"
    ></gui-textinput>
  </div>
</template>
