// libs/react-vanilla/src/lib/components/TextArea.tsx
import * as Core from '@golemui/core';
import { useInputWidget } from '@golemui/react';
import { TextareaProps } from '@golemui/shared-vanilla';
import { useCallback } from 'react';
import '../styles.scss';

export function TextArea(widgetInstance: Core.WithWidget) {
  const widget = widgetInstance.widget as Core.InputWidget<string>;
  const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useInputWidget<
    string,
    TextareaProps
  >(widget);

  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLTextAreaElement>) =>
      onValueChanged((e.nativeEvent as CustomEvent).detail.value),
    [onValueChanged],
  );

  const label = templateData.label as string;
  const hint = templateData.hint;
  const placeholder = templateData.placeholder;
  const icon = templateData.icon;
  const maxLength = (templateData.validator as Core.Validator)?.maxLength;
  const counterMode = templateData.counterMode;
  const autoGrow = templateData.autoGrow;
  const minimumHeight = templateData.minimumHeight;
  const isDisabled = templateData.disabled as boolean;
  const isReadonly = templateData.readonly as boolean;
  const isRequired = (templateData.validator as Core.Validator)?.required;

  return (
    <div className="gui-textarea" style={{ flex: templateData.size }}>
      <gui-textarea
        uid={uid}
        label={label}
        errors={errors}
        touched={isTouched}
        required={isRequired}
        disabled={isDisabled}
        readOnly={isReadonly}
        value={value}
        hint={hint}
        placeholder={placeholder}
        icon={icon}
        counterMode={counterMode}
        minimumHeight={minimumHeight}
        autoGrow={autoGrow}
        maxLength={maxLength}
        onInput={handleChange}
        onBlur={onBlur}
      ></gui-textarea>
    </div>
  );
}

// libs/gui/vue/src/lib/components/TextArea.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/vue';
import type { TextareaProps } from '@golemui/gui-shared';
import { computed } from 'vue';
import '@golemui/gui-components/textarea';

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<string>;
const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useInputWidget<
  string,
  TextareaProps
>(widget);

const handleInput = (e: Event) => onValueChanged((e as CustomEvent).detail.value);
const required = computed(() => (templateData.value.validator as Validator)?.required);
const maxLength = computed(() => (templateData.value.validator as Validator)?.maxLength);
// Mirror Lit element's internal `?? 'remaining'` / `?? 120` fallbacks so an
// empty string from Vue→Lit attribute coercion can't slip past the `??` operator.
const counterMode = computed(() => templateData.value.counterMode || 'remaining');
const minimumHeight = computed(() => templateData.value.minimumHeight ?? 120);
</script>

<template>
  <div class="gui-textarea gui-field" :style="{ flex: templateData.size }">
    <gui-textarea
      :uid="uid"
      :label="templateData.label"
      :errors="errors"
      :touched="isTouched"
      :required="required"
      :disabled="templateData.disabled"
      :readOnly="templateData.readonly"
      :value="value"
      :hint="templateData.hint"
      :placeholder="templateData.placeholder"
      :autocomplete="templateData.autocomplete ?? undefined"
      :counterMode.prop="counterMode"
      :minimumHeight.prop="minimumHeight"
      :autoGrow="templateData.autoGrow"
      :maxLength="maxLength"
      @input="handleInput"
      @blur="onBlur"
    ></gui-textarea>
  </div>
</template>
