// libs/react/src/lib/WidgetRenderer.tsx
import { type NonFunctionWidget, type WithWidget, errorCodes } from '@golemui/core';
import { useEffect, useRef, useState } from 'react';
import WidgetErrorBoundary from './WidgetErrorBoundary';
import { useReactFormContext } from './ReactFormContext';

type Props = {
  widget: NonFunctionWidget<string>;
};

type WidgetComponent = React.ComponentType<WithWidget>;

// Repeater rows and layout children arrive from the store with their row indexes already applied to `uid` and `path`, so the renderer takes the widget as it is
function WidgetRenderer(props: Props) {
  const { formContext } = useReactFormContext();
  const [Component, setComponent] = useState<WidgetComponent | null>(null);
  const isMounted = useRef(true);

  useEffect(() => {
    isMounted.current = true;
    const loadComponent = async () => {
      try {
        const loadedComponent = await formContext.widgetRegistry.loadWidget(props.widget.type);
        if (isMounted.current) {
          setComponent(() => loadedComponent);
        }
      } catch {
        const code = errorCodes.widgetCouldNotBeLoaded;
        formContext.store.dispatch({
          type: 'SET_FORM_HEALTH',
          payload: {
            formHealth: {
              status: 'errored',
              message: `[${code}] Widget "${props.widget.type}" could not be loaded`,
              code,
            },
          },
        });
      }
    };

    loadComponent();
    return () => {
      isMounted.current = false;
    };
  }, [props.widget, formContext.widgetRegistry, formContext.store]);

  if (!Component) {
    return null;
  }

  return (
    <WidgetErrorBoundary widget={props.widget}>
      <Component widget={props.widget} />
    </WidgetErrorBoundary>
  );
}

export default WidgetRenderer;

// libs/vue/src/lib/WidgetRenderer.vue
<script setup lang="ts">
import { type NonFunctionWidget, errorCodes } from '@golemui/core';
import { onMounted, onUnmounted, ref, shallowRef, type Component } from 'vue';
import WidgetErrorBoundary from './WidgetErrorBoundary.vue';
import { useVueFormContext } from './provideFormContext';

// Repeater rows arrive from the store with their indexes already applied to `uid` and `path`,
// so there is no index handling here.
const props = defineProps<{
  widget: NonFunctionWidget<string>;
}>();

const formContext = useVueFormContext();
const LoadedComponent = shallowRef<Component | null>(null);
const isMounted = ref(true);

onMounted(async () => {
  try {
    const loaded = await formContext.widgetRegistry.loadWidget(props.widget.type);
    if (!isMounted.value) return;
    LoadedComponent.value = loaded;
  } catch {
    const code = errorCodes.widgetCouldNotBeLoaded;
    formContext.store.dispatch({
      type: 'SET_FORM_HEALTH',
      payload: {
        formHealth: {
          status: 'errored',
          message: `[${code}] Widget "${props.widget.type}" could not be loaded`,
          code,
        },
      },
    });
  }
});

onUnmounted(() => {
  isMounted.value = false;
});
</script>

<template>
  <WidgetErrorBoundary v-if="LoadedComponent" :widget="props.widget">
    <component :is="LoadedComponent" :widget="props.widget" />
  </WidgetErrorBoundary>
</template>
