// libs/gui/angular/src/lib/widget.loaders.ts
import { type Type } from '@angular/core';
import type { WidgetLoaders, WithWidget } from '@golemui/core';
import type { GolemWidget } from '@golemui/gui-shared/internals';

export const widgetLoaders: WidgetLoaders<Type<WithWidget>, GolemWidget> = {
  // ACTION WIDGETS
  button: async () => (await import('./components/button/button.component')).ButtonComponent,

  // INPUT WIDGETS
  repeater: async () =>
    (await import('./components/repeater/repeater.component')).RepeaterComponent,
  textinput: async () =>
    (await import('./components/textinput/textinput.component')).TextinputComponent,
  password: async () =>
    (await import('./components/password/password.component')).PasswordComponent,
  currency: async () =>
    (await import('./components/currency/currency.component')).CurrencyComponent,
  textarea: async () =>
    (await import('./components/textarea/textarea.component')).TextareaComponent,
  calendar: async () =>
    (await import('./components/calendar/calendar.component')).CalendarComponent,
  dateTimeCalendar: async () =>
    (await import('./components/date-time-calendar/date-time-calendar.component'))
      .DateTimeCalendarComponent,
  rangeCalendar: async () =>
    (await import('./components/range-calendar/range-calendar.component')).RangeCalendarComponent,
  rangeDateInput: async () =>
    (await import('./components/range-date/range-date.component')).RangeDateComponent,
  rangeTimeInput: async () =>
    (await import('./components/range-time/range-time.component')).RangeTimeComponent,
  rangeDateTimeInput: async () =>
    (await import('./components/range-date-time/range-date-time.component')).RangeDateTimeComponent,
  rangeDatePicker: async () =>
    (await import('./components/range-date-picker/range-date-picker.component'))
      .RangeDatePickerComponent,
  rangeTimePicker: async () =>
    (await import('./components/range-time-picker/range-time-picker.component'))
      .RangeTimePickerComponent,
  dateInput: async () => (await import('./components/date-input/date.component')).DateComponent,
  timeInput: async () => (await import('./components/time-input/time.component')).TimeComponent,
  timePicker: async () =>
    (await import('./components/time-picker/time-picker.component')).TimePickerComponent,
  dateTimeInput: async () =>
    (await import('./components/date-time-input/date-time.component')).DateTimeComponent,
  datePicker: async () =>
    (await import('./components/date-picker/date-picker.component')).DatePickerComponent,
  dateTimePicker: async () =>
    (await import('./components/date-time-picker/date-time-picker.component'))
      .DateTimePickerComponent,
  dropdown: async () =>
    (await import('./components/dropdown/dropdown.component')).DropdownComponent,
  toggle: async () => (await import('./components/toggle/toggle.component')).ToggleComponent,
  checkbox: async () =>
    (await import('./components/checkbox/checkbox.component')).CheckboxComponent,
  number: async () => (await import('./components/number/number.component')).NumberComponent,
  select: async () => (await import('./components/select/select.component')).SelectComponent,
  radiogroup: async () =>
    (await import('./components/radiogroup/radiogroup.component')).RadiogroupComponent,
  list: async () => (await import('./components/list/list.component')).ListComponent,
  markdown: async () =>
    (await import('./components/markdown/markdown.component')).MarkdownComponent,
  tags: async () => (await import('./components/tags/tags.component')).TagsComponent,

  // LAYOUT WIDGETS
  flex: async () => (await import('./components/flex/flex.component')).FlexComponent,
  grid: async () => (await import('./components/grid/grid.component')).GridComponent,
  tabs: async () => (await import('./components/tabs/tabs.component')).TabsComponent,
  accordion: async () =>
    (await import('./components/accordion/accordion.component')).AccordionComponent,

  // DISPLAY WIDGETS
  alert: async () => (await import('./components/alert/alert.component')).AlertComponent,
  markdownText: async () =>
    (await import('./components/markdown-text/markdown-text.component')).MarkdownTextComponent,
  renderer: async () =>
    (await import('./components/renderer/renderer.component')).RendererComponent,
};

// libs/gui/react/src/lib/widget.loaders.ts
import type { WidgetLoaders, WithWidget } from '@golemui/core';
import type { GolemWidget } from '@golemui/gui-shared/internals';

export const widgetLoaders: WidgetLoaders<React.ComponentType<WithWidget>, GolemWidget> = {
  // INTERACTIVE
  button: async () => (await import('./components/Button')).Button,

  // CONTROLS
  calendar: async () => (await import('./components/Calendar')).Calendar,
  dateTimeCalendar: async () => (await import('./components/DateTimeCalendar')).DateTimeCalendar,
  currency: async () => (await import('./components/Currency')).Currency,
  dateInput: async () => (await import('./components/DateInput')).DateInput,
  datePicker: async () => (await import('./components/DatePicker')).DatePicker,
  dateTimePicker: async () => (await import('./components/DateTimePicker')).DateTimePicker,
  dropdown: async () => (await import('./components/Dropdown')).Dropdown,
  list: async () => (await import('./components/List')).List,
  password: async () => (await import('./components/Password')).Password,
  textinput: async () => (await import('./components/TextInput')).TextInput,
  timeInput: async () => (await import('./components/TimeInput')).TimeInput,
  timePicker: async () => (await import('./components/TimePicker')).TimePicker,
  dateTimeInput: async () => (await import('./components/DateTimeInput')).DateTimeInput,
  textarea: async () => (await import('./components/TextArea')).TextArea,
  markdown: async () => (await import('./components/Markdown')).Markdown,
  checkbox: async () => (await import('./components/Checkbox')).Checkbox,
  toggle: async () => (await import('./components/Toggle')).Toggle,
  number: async () => (await import('./components/Number')).NumberInput,
  select: async () => (await import('./components/Select')).Select,
  radiogroup: async () => (await import('./components/RadioGroup')).RadioGroup,
  rangeCalendar: async () => (await import('./components/RangeCalendar')).RangeCalendar,
  rangeDateInput: async () => (await import('./components/RangeDateInput')).RangeDateInput,
  rangeTimeInput: async () => (await import('./components/RangeTimeInput')).RangeTimeInput,
  rangeDateTimeInput: async () =>
    (await import('./components/RangeDateTimeInput')).RangeDateTimeInput,
  rangeDatePicker: async () => (await import('./components/RangeDatePicker')).RangeDatePicker,
  rangeTimePicker: async () => (await import('./components/RangeTimePicker')).RangeTimePicker,
  tags: async () => (await import('./components/Tags')).Tags,

  // REPEATER
  repeater: async () => (await import('./components/Repeater')).Repeater,

  // LAYOUTS
  flex: async () => (await import('./components/Flex')).Flex,
  grid: async () => (await import('./components/Grid')).Grid,
  tabs: async () => (await import('./components/Tabs')).Tabs,
  accordion: async () => (await import('./components/Accordion')).Accordion,

  // DISPLAY
  alert: async () => (await import('./components/Alert')).Alert,
  markdownText: async () => (await import('./components/MarkdownText')).MarkdownText,
  renderer: async () => (await import('./components/Renderer')).Renderer,
};
