// libs/gui/react/src/lib/components/Renderer.tsx
import type * as Core from '@golemui/core';
import { useDisplayWdiget } from '@golemui/react';
import { type RendererProps } from '@golemui/gui-shared';
import { type ReactNode } from 'react';

export function Renderer(widgetInstance: Core.WithWidget) {
  const widget = widgetInstance.widget as Core.DisplayWidget;
  const { uid, templateData } = useDisplayWdiget<RendererProps<ReactNode>>(widget);
  const renderedElement = templateData?.render;
  return (
    <div className="gui-renderer gui-field" style={{ flex: templateData.size }}>
      <div className="gui-widget" id={uid}>
        {renderedElement}
      </div>
    </div>
  );
}

// libs/gui/angular/src/lib/components/renderer/renderer.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, OnDestroy, OnInit, Type } from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import { ComponentRendererProps } from '@golemui/gui-shared';

@Component({
  standalone: true,
  selector: 'gui-renderer-component',
  imports: [CommonModule],
  providers: [Angular.DisplayWidgetAdapter],
  templateUrl: './renderer.component.html',
  host: {
    class: 'gui-renderer gui-field',
    '[style.flex]': 'this.adapter.templateData().size',
  },
})
export class RendererComponent implements OnInit, OnDestroy, Core.WithWidget {
  widget!: Core.DisplayWidget;

  protected adapter: Angular.DisplayWidgetAdapter<ComponentRendererProps<Type<any>>> = inject(
    Angular.DisplayWidgetAdapter,
  );

  ngOnInit(): void {
    this.adapter.init(this.widget);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

@let templateData = adapter.templateData();

<div class="gui-widget" [id]="widget.uid">
  <ng-container
    *ngComponentOutlet="templateData.render.component; inputs: { api: templateData.render.api }"
  ></ng-container>
</div>
