// libs/react-vanilla/src/lib/field.loaders.ts
import * as Core from '@formforge/core';

export const vanillaFieldLoaders: Core.FieldLoaders<
  React.ComponentType<Core.WithField>
> = {
  // BUTTON
  button: async () => (await import('./components/Button')).Button,

  // CONTROLS
  // textinput: async () =>
  //   (await import('./textinput/textinput.component')).TextinputComponent,
  // checkbox: async () =>
  //   (await import('./checkbox/checkbox.component')).CheckboxComponent,

  // // LAYOUTS
  stack: async () => (await import('./components/Stack')).Stack,

  // // FIELDS
  // alert: async () => (await import('./alert/alert.component')).AlertComponent,
};

// libs/angular-vanilla/src/lib/field.loaders.ts
import { Type } from '@angular/core';
import * as Core from '@formforge/core';

export const vanillaFieldLoaders: Core.FieldLoaders<Type<Core.WithField>> = {
  // BUTTON
  button: async () =>
    (await import('./button/button.component')).ButtonComponent,

  // REPEATER
  repeater: async () =>
    (await import('./repeater/repeater.component')).RepeaterComponent,

  // CONTROLS
  textinput: async () =>
    (await import('./textinput/textinput.component')).TextinputComponent,
  checkbox: async () =>
    (await import('./checkbox/checkbox.component')).CheckboxComponent,

  // LAYOUTS
  stack: async () => (await import('./stack/stack.component')).StackComponent,
  tabs: async () => (await import('./tabs/tabs.component')).TabsComponent,

  // FIELDS
  alert: async () => (await import('./alert/alert.component')).AlertComponent,
};
