// libs/react/src/lib/FormComponent.tsx
import * as Core from '@golemui/core';
import { useEffect, useRef, useState } from 'react';
import WidgetErrorBoundary from './WidgetErrorBoundary';
import WidgetRenderer from './WidgetRenderer';
import { ReactFormContextProvider } from './ReactFormContextProvider';

type JsonStringified = string;
type JsonObject = Record<string, any>;

export interface FormComponentProps {
  formDef: JsonStringified | JsonObject;
  widgetLoaders: Core.WidgetLoaders<React.ComponentType<Core.WithWidget>>;
  itemRenderers: Record<string, Core.ItemRenderer>;
  localization?: Core.I18nTranslator;
  dependencies?: Record<string, unknown>;
  validators: Core.ValidatorFn<any>;
  middlewares?: Core.Middleware<Core.State, Core.Action>[];
  validateOn?: Core.ValidateOn;
  data?: Record<string, any>;
  formName?: string;
  locale?: string;
  direction?: 'ltr' | 'rtl';
  formEvent?: (event: Core.FormEvent) => void;
  formHealth?: (error: Core.FormHealth) => void;
}

export function FormComponent({
  formDef,
  widgetLoaders,
  itemRenderers,
  localization,
  locale,
  dependencies,
  middlewares,
  validators,
  validateOn,
  data,
  formName,
  direction: directionProp,
  formHealth,
  formEvent,
}: FormComponentProps) {
  const formContextRef = useRef<Core.FormContext<React.ComponentType<Core.WithWidget>>>(
    new Core.FormContext(),
  );
  const formNameRef = useRef(formName || Core.shortUUID());
  const [formLayoutField, setFormLayoutField] = useState<Core.LayoutWidget<string> | null>(null);
  const [direction, setDirection] = useState<'ltr' | 'rtl'>('ltr');

  // INITIALIZE FORM CONTEXT
  useEffect(() => {
    formContextRef.current.initialize(
      widgetLoaders,
      middlewares,
      validators,
      validateOn || 'eager',
      itemRenderers,
      localization,
      dependencies || {},
    );
  }, [
    widgetLoaders,
    middlewares,
    validators,
    validateOn,
    itemRenderers,
    localization,
    dependencies,
  ]);

  // FORM HEALTH
  useEffect(() => {
    const sub = Core.formHealth(formContextRef.current.store.state$).subscribe((health) =>
      formHealth?.(health),
    );
    return () => {
      sub.unsubscribe();
    };
  }, [formHealth]);

  // EVENTS
  useEffect(() => {
    const sub = formContextRef.current.events$.subscribe((event) => formEvent?.(event));
    return () => {
      sub.unsubscribe();
    };
  }, [formEvent]);

  // FORM ENTRY POINT
  useEffect(() => {
    const sub = formContextRef.current.store.state$.subscribe((state) => {
      setFormLayoutField(state.formDef.form);
      setDirection(Core.getDirectionFromLanguage(formContextRef.current.localization.lang));
    });
    return () => {
      sub.unsubscribe();
    };
  }, []);

  // INITIALIZE FORM
  useEffect(() => {
    formContextRef.current.store.dispatch({
      type: 'INITIALIZE',
      payload: {
        formName: formNameRef.current,
        formDef: formDef,
      },
    });
  }, [formDef]);

  // SET FORM DATA
  useEffect(() => {
    formContextRef.current.store.dispatch({
      type: 'SET_DATA',
      payload: { data: data || {} },
    });
  }, [data]);

  // I18n
  useEffect(() => {
    const sub = formContextRef.current.localization.subscribe((lang) => {
      setDirection(Core.getDirectionFromLanguage(lang));
      formContextRef.current.store.dispatch({
        type: 'SET_LANGUAGE',
        payload: {
          lang,
        },
      });
    });
    return () => {
      sub();
    };
  }, []);

  // LOCALE
  useEffect(() => {
    if (locale) {
      setDirection(Core.getDirectionFromLanguage(locale));
      formContextRef.current.store.dispatch({
        type: 'SET_LANGUAGE',
        payload: { lang: locale },
      });
    }
  }, [locale]);

  if (!formLayoutField) {
    return null;
  }

  return (
    <ReactFormContextProvider formContext={formContextRef.current}>
      <div className="gui-form">
        <form id={formNameRef.current} noValidate dir={directionProp ?? direction}>
          <WidgetErrorBoundary widget={formLayoutField}>
            <WidgetRenderer widget={formLayoutField} />
          </WidgetErrorBoundary>
        </form>
      </div>
    </ReactFormContextProvider>
  );
}

export default FormComponent;

// libs/angular/src/lib/components/form/form.component.ts
import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  effect,
  inject,
  input,
  OnDestroy,
  OnInit,
  output,
  signal,
  Type,
} from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import * as Core from '@golemui/core';
import { AngularFormContext } from '../../context/form.context';
import { WidgetDirective } from '../../directives/widget.directive';

type JsonStringified = string;
type JsonObject = Record<string, any>;

@Component({
  selector: 'gui-core-form',
  standalone: true,
  templateUrl: './form.component.html',
  imports: [CommonModule, WidgetDirective],
  providers: [AngularFormContext],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    class: 'gui-form',
  },
})
export class FormCoreComponent implements OnInit, OnDestroy {
  // INPUTS
  formDef = input.required<JsonStringified | JsonObject>();
  widgetLoaders = input.required<Core.WidgetLoaders<Type<Core.WithWidget>>>();
  validators = input.required<Core.ValidatorFn<any>>();
  middlewares = input<Core.Middleware<Core.State, Core.Action>[]>([]);
  data = input<Record<string, any>>({});
  formName = input(Core.shortUUID());
  validateOn = input<Core.ValidateOn>('eager');
  itemRenderers = input<Record<string, Core.ItemRenderer>>({});
  localization = input<Core.I18nTranslator>();
  locale = input<string>();
  dependencies = input<Record<string, unknown>>({});
  protected direction = signal<'ltr' | 'rtl'>('ltr');

  // OUTPUTS
  protected formHealth = output<Core.FormHealth>();
  protected formEvent = output<Core.FormEvent>();

  // INJECTS
  protected context: AngularFormContext<Type<Core.WithWidget>> = inject(AngularFormContext);

  // PRIVATE
  private destroyRef = inject(DestroyRef);
  private unsubscribeI18n: () => void = () => undefined;
  private _formDefInitialized = false;
  private _localeInitialized = false;

  constructor() {
    effect(() => {
      const formDef = this.formDef();
      if (!this._formDefInitialized) {
        this._formDefInitialized = true;
        return;
      }
      this.context.store.dispatch({
        type: 'INITIALIZE',
        payload: { formName: this.formName(), formDef },
      });
      this.context.store.dispatch({
        type: 'SET_DATA',
        payload: { data: this.data() },
      });
    });

    effect(() => {
      const lang = this.locale();
      if (!this._localeInitialized) {
        this._localeInitialized = true;
        return;
      }
      if (lang) {
        this.direction.set(Core.getDirectionFromLanguage(lang));
        this.context.store.dispatch({
          type: 'SET_LANGUAGE',
          payload: { lang },
        });
      }
    });
  }

  // LIFE CYCLE
  ngOnInit(): void {
    this.context.initialize(
      this.widgetLoaders(),
      this.middlewares(),
      this.validators(),
      this.validateOn(),
      this.itemRenderers(),
      this.localization(),
      this.dependencies() || {},
    );

    Core.formHealth(this.context.store.state$)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((health) => this.formHealth.emit(health));

    this.context.events$
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((event) => this.formEvent.emit(event));

    this.context.store.dispatch({
      type: 'INITIALIZE',
      payload: {
        formName: this.formName(),
        formDef: this.formDef(),
      },
    });

    this.context.store.dispatch({
      type: 'SET_DATA',
      payload: {
        data: this.data(),
      },
    });

    const initialLang = this.locale() ?? this.context.localization.lang;
    this.direction.set(Core.getDirectionFromLanguage(initialLang));

    if (this.locale()) {
      this.context.store.dispatch({
        type: 'SET_LANGUAGE',
        payload: { lang: this.locale()! },
      });
    }

    this.unsubscribeI18n = this.context.localization.subscribe((lang) => {
      this.direction.set(Core.getDirectionFromLanguage(lang));
      this.context.store.dispatch({
        type: 'SET_LANGUAGE',
        payload: {
          lang,
        },
      });
    });
  }

  ngOnDestroy(): void {
    this.unsubscribeI18n();
  }
}

@let formState = context.store.state$ | async;

<!-- Always render the form inside the boundary so a recovered health clears the error in place. -->
<ng-container *ngComponentOutlet="effectiveHealthBoundary(); inputs: { health: health() }" />

<form
  [id]="config().formName ?? _defaultFormName"
  novalidate
  [attr.dir]="direction()"
  [attr.autocomplete]="autocomplete()"
  (submit)="onFormSubmit($event)"
>
  @if (formState && formState.formDef && context.widgetRegistry.ready) {
    <ng-container guiWidget [widget]="formState.formDef.form" />
  } @else if (health().status !== 'errored') {
    <div>Loading form...</div>
  }
</form>
