// libs/react-vanilla/src/lib/components/DatePicker.tsx
import * as Core from '@golemui/core';
import { useControlField } from '@golemui/react';
import { DatePickerProps } from '@golemui/shared-vanilla';
import { useCallback, useEffect, useRef, useState } from 'react';
import '../styles.scss';
import { Errors } from './shared/Errors';

export function DatePicker(fieldInstance: Core.WithField) {
  const field = fieldInstance.field as Core.ControlField<string>;
  const {
    uid,
    errors,
    value,
    isTouched,
    templateData,
    onValueChanged,
    onBlur,
    injectValidationIssues,
  } = useControlField<string, DatePickerProps>(field);
  const [isCalendarOpen, setIsCalendarOpen] = useState(false);
  const dateControlRef = useRef<HTMLElement | null>(null);
  const calendarControlRef = useRef<HTMLElement | null>(null);

  const handleDateRef = useCallback(
    (node: HTMLElement | null) => {
      const target = node as any;
      const changeHandler = (e: CustomEvent) => {
        injectValidationIssues(null);
        onValueChanged(e.detail.value);
      };
      const errorHandler = (e: CustomEvent) => {
        injectValidationIssues([e.detail.message]);
      };
      const focusHandler = () => {
        setIsCalendarOpen(true);
      };

      dateControlRef.current = node;

      if (node) {
        target.addEventListener('change', changeHandler);
        target.addEventListener('focus', focusHandler);
        target.addEventListener('blur', onBlur);
        target.addEventListener('inputError', errorHandler);
      }

      return () => {
        target.removeEventListener('change', changeHandler);
        target.removeEventListener('focus', focusHandler);
        target.removeEventListener('blur', onBlur);
        target.removeEventListener('inputError', errorHandler);
      };
    },
    [onValueChanged, onBlur, injectValidationIssues],
  );
  const handleCalendarRef = useCallback(
    (node: HTMLElement | null) => {
      const target = node as any;
      const changeHandler = (e: CustomEvent) => {
        injectValidationIssues(null);
        onValueChanged(e.detail.value);
      };

      calendarControlRef.current = node;

      if (node) {
        target.addEventListener('change', changeHandler);
      }

      return () => {
        target.removeEventListener('change', changeHandler);
      };
    },
    [onValueChanged, injectValidationIssues],
  );

  useEffect(() => {
    const onDocumentClick = (event: MouseEvent) => {
      if (!isCalendarOpen) return;
      const path = event.composedPath();
      const clickedInsideDate = dateControlRef.current && path.includes(dateControlRef.current);
      const clickedInsideCalendar =
        calendarControlRef.current && path.includes(calendarControlRef.current);

      if (!clickedInsideDate && !clickedInsideCalendar) {
        setIsCalendarOpen(false);
      }
    };

    document.addEventListener('click', onDocumentClick);

    return () => {
      document.removeEventListener('click', onDocumentClick);
    };
  }, [isCalendarOpen]);

  const openCalendar = () => {
    if (!isCalendarOpen) setIsCalendarOpen(true);
  };

  const hint = templateData.hint;
  const icon = templateData.icon;
  const prevMonthIcon = templateData.prevMonthIcon;
  const nextMonthIcon = templateData.nextMonthIcon;
  const dayFormat = templateData.dayFormat;
  const weekdayFormat = templateData.weekdayFormat;
  const monthFormat = templateData.monthFormat;
  const showErrors = isTouched && errors && errors.length > 0;
  const isRequired = (templateData.validator as Core.Validator)?.required;
  const isDisabled = templateData.disabled as boolean;
  const isReadonly = templateData.readonly as boolean;

  return (
    <div className="gui-date-picker">
      <label className="gui-label" htmlFor={uid} data-cy={`${uid}_label`}>
        {templateData.label + (isRequired ? ' *' : '')}
        {hint && (
          <div className="gui-field-hint" id={`${uid}_hint`}>
            {hint}
          </div>
        )}
      </label>
      <div className="gui-field" onClick={openCalendar} aria-expanded={isCalendarOpen}>
        <gui-date-control
          ref={handleDateRef}
          uid={uid}
          hint={hint}
          touched={isTouched}
          errors={errors}
          hasError={showErrors}
          disabled={isDisabled}
          readonly={isReadonly}
          value={value}
          icon={icon}
        />

        {isCalendarOpen && (
          <gui-calendar-control
            ref={handleCalendarRef}
            uid={uid}
            hint={hint}
            touched={isTouched}
            errors={errors}
            hasError={showErrors}
            disabled={isDisabled}
            readonly={isReadonly}
            value={value}
            prevMonthIcon={prevMonthIcon}
            nextMonthIcon={nextMonthIcon}
            dayFormat={dayFormat}
            weekdayFormat={weekdayFormat}
            monthFormat={monthFormat}
          />
        )}
      </div>
      {showErrors && <Errors errors={errors} uid={uid} />}
    </div>
  );
}

// libs/angular-vanilla/src/lib/components/date-picker/date-picker.component.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  inject,
  OnDestroy,
  OnInit,
  signal,
  viewChild,
} from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import { DatePickerProps } from '@golemui/shared-vanilla';
import { ErrorsComponent } from '../../utils/templates/errors.component';
import { LabelComponent } from '../../utils/templates/label.component';

@Component({
  standalone: true,
  selector: 'gui-date-picker',
  imports: [CommonModule, ErrorsComponent, LabelComponent],
  providers: [Angular.ControlFieldAdapter],
  templateUrl: './date-picker.component.html',
  host: {
    class: 'gui-date-picker',
    '(document:click)': 'onDocumentClick($event)',
  },
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class DatePickerComponent implements OnInit, OnDestroy, Core.WithField {
  field!: Core.ControlField<string>;
  protected adapter: Angular.ControlFieldAdapter<string, DatePickerProps> = inject(
    Angular.ControlFieldAdapter,
  );
  currentDate = new Date();

  dateControl = viewChild<ElementRef>('dateControlRef');
  calendarControl = viewChild<ElementRef>('calendarControlRef');

  // TODO: Get localeId from i18n feature
  localeId = 'es';

  readonly isCalendarOpen = signal(false);

  onDocumentClick(event: MouseEvent) {
    const targetElement = event.target as HTMLElement;
    if (
      targetElement &&
      !this.dateControl()?.nativeElement.contains(targetElement) &&
      !this.calendarControl()?.nativeElement.contains(targetElement)
    ) {
      this.closeCalendar();
    }
  }

  ngOnInit(): void {
    this.adapter.init(this.field);
  }

  onChangeDate(event: Event) {
    this.adapter.injectValidationIssues(null);
    this.adapter.valueChanged((event as CustomEvent).detail.value);
  }

  onInputError(event: Event) {
    this.adapter.injectValidationIssues([(event as CustomEvent).detail.message]);
  }

  openCalendar() {
    this.isCalendarOpen.set(true);
  }

  closeCalendar() {
    this.isCalendarOpen.set(false);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

@let templateData = adapter.templateData();
@let showErrors = templateData.touched && templateData.errors && templateData.errors.length > 0;

<label gui-label [for]="field.uid" [uid]="field.uid" [templateData]="templateData"></label>

<div
  class="gui-field"
  [attr.aria-expanded]="isCalendarOpen()"
  (click)="openCalendar()"
>
  <gui-date-control
    #dateControlRef
    [uid]="field.uid"
    [hint]="templateData.hint"
    [touched]="templateData.touched"
    [errors]="templateData.errors"
    [hasError]="showErrors"
    [disabled]="templateData.disabled"
    [readonly]="templateData.readonly"
    [value]="templateData.value"
    [icon]="templateData.icon"
    (change)="onChangeDate($event)"
    (inputError)="onInputError($event)"
    (focus)="openCalendar()"
    (blur)="adapter.onBlur()"
  ></gui-date-control>

  @if (isCalendarOpen()) {
    <gui-calendar-control
      #calendarControlRef
      [uid]="field.uid"
      [hint]="templateData.hint"
      [value]="templateData.value"
      [touched]="templateData.touched"
      [errors]="templateData.errors"
      [hasError]="showErrors"
      [disabled]="templateData.disabled"
      [readonly]="templateData.readonly"
      [value]="templateData.value"
      [prevMonthIcon]="templateData.prevMonthIcon"
      [nextMonthIcon]="templateData.nextMonthIcon"
      [dayFormat]="templateData.dayFormat"
      [weekdayFormat]="templateData.weekdayFormat"
      [monthFormat]="templateData.monthFormat"
      (change)="onChangeDate($event)"
    ></gui-calendar-control>
  }
</div>

@if (showErrors) {
  <ul
    gui-errors
    [uid]="field.uid"
    [templateData]="templateData"
    [attr.data-cy]="field.uid + '_validator-errors'"
  ></ul>
}
