// libs/gui/vue/src/lib/components/Flex.vue
<script setup lang="ts">
import type { LayoutWidget, NonFunctionWidget, WithWidget } from '@golemui/core';
import { useLayoutWidget, WidgetRenderer } from '@golemui/vue';
import type { FlexProps } from '@golemui/gui-shared/internals';
import { computed } from 'vue';

const props = defineProps<WithWidget>();
const widget = props.widget as LayoutWidget;
const { uid, children, templateData } = useLayoutWidget<FlexProps>(widget);

const widgetClass = computed(() => {
  const direction = `gui-flex__widget--${templateData.value.direction ?? 'column'}`;
  const justify = `gui-flex__widget--justify-${(templateData.value.justify as string) ?? 'stretch'}`;
  const align = `gui-flex__widget--align-${(templateData.value.align as string) ?? 'start'}`;
  return `gui-flex__widget ${direction} ${justify} ${align}`;
});

const gapStyle = computed(() =>
  templateData.value.gap ? { gap: `${templateData.value.gap}px` } : {},
);
</script>

<template>
  <div class="gui-flex gui-field" :style="{ flex: templateData.size }">
    <div :class="widgetClass" :style="gapStyle" :id="uid">
      <WidgetRenderer
        v-for="child in children as NonFunctionWidget<string>[]"
        :key="child.uid"
        :widget="child"
      />
    </div>
  </div>
</template>

// libs/gui/angular/src/lib/components/flex/flex.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, type OnDestroy, type OnInit } from '@angular/core';
import { LayoutWidgetAdapter, WidgetDirective } from '@golemui/angular';
import type { LayoutWidget, WithWidget } from '@golemui/core';
import type { FlexProps } from '@golemui/gui-shared/internals';

@Component({
  standalone: true,
  selector: 'gui-flex-layout',
  imports: [CommonModule, WidgetDirective],
  providers: [LayoutWidgetAdapter],
  templateUrl: './flex.component.html',
  host: {
    class: 'gui-flex gui-field',
    '[style.flex]': 'this.adapter.templateData().size ?? 1',
  },
})
export class FlexComponent implements OnInit, OnDestroy, WithWidget {
  widget!: LayoutWidget;

  protected adapter: LayoutWidgetAdapter<FlexProps> = inject(LayoutWidgetAdapter);

  ngOnInit(): void {
    this.adapter.init(this.widget);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

@let templateData = adapter.templateData();

<div
  class="gui-flex__widget"
  [class.gui-flex__widget--row]="templateData.direction === 'row'"
  [class.gui-flex__widget--row-reverse]="templateData.direction === 'row-reverse'"
  [class.gui-flex__widget--column]="!templateData.direction || templateData.direction === 'column'"
  [class.gui-flex__widget--column-reverse]="templateData.direction === 'column-reverse'"
  [class.gui-flex__widget--justify-center]="templateData.justify === 'center'"
  [class.gui-flex__widget--justify-start]="templateData.justify === 'start'"
  [class.gui-flex__widget--justify-end]="templateData.justify === 'end'"
  [class.gui-flex__widget--justify-stretch]="
    !templateData.justify || templateData.justify === 'stretch'
  "
  [class.gui-flex__widget--align-center]="templateData.align === 'center'"
  [class.gui-flex__widget--align-start]="!templateData.align || templateData.align === 'start'"
  [class.gui-flex__widget--align-end]="templateData.align === 'end'"
  [class.gui-flex__widget--align-space-between]="templateData.align === 'space-between'"
  [class.gui-flex__widget--align-space-around]="templateData.align === 'space-around'"
  [class.gui-flex__widget--align-space-evenly]="templateData.align === 'space-evenly'"
  [style.gap.px]="templateData.gap"
  [id]="widget.uid"
>
  @for (child of templateData.children; track child.uid) {
    <ng-container guiWidget [widget]="child" />
  }
</div>
