// libs/react-vanilla/src/lib/components/TextArea.tsx
import * as Core from '@golemui/core';
import { useControlField } from '@golemui/react';
import { TextareaProps } from '@golemui/shared-vanilla';
import { useCallback, useLayoutEffect, useRef } from 'react';
import '../styles.scss';
import { Errors } from './shared/Errors';

function Counter({
  value,
  validator,
  counterMode,
}: {
  value?: string;
  validator: Core.Validator;
  counterMode: 'remaining' | 'current';
}) {
  const val = value?.length ?? 0;
  return (
    <div
      className={`gui-textarea--counter ${val > validator?.maxLength ? 'gui-textarea--counter__error' : ''}`}
    >
      <span>{counterMode === 'current' ? val : validator?.maxLength - val}</span>
      <span> / {validator?.maxLength}</span>
    </div>
  );
}

export function TextArea(fieldInstance: Core.WithField) {
  const field = fieldInstance.field as Core.ControlField<string>;
  const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useControlField<
    string,
    TextareaProps
  >(field);

  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLTextAreaElement>) => onValueChanged(e.target.value),
    [onValueChanged],
  );
  const hint = templateData.hint;
  const placeholder = templateData.placeholder;
  const icon = templateData.icon;
  const showErrors = isTouched && errors && errors.length > 0;
  const isRequired = (templateData.validator as Core.Validator)?.required;
  const isDisabled = templateData.disabled as boolean;
  const isReadonly = templateData.readonly as boolean;
  const counterMode = templateData.counterMode;

  useLayoutEffect(() => {
    const textarea = textareaRef.current;
    if (textarea && templateData.autoGrow) {
      textarea.style.height = 'auto';
      textarea.style.height = `${Math.max(templateData.minimumHeight ?? 120, textarea.scrollHeight)}px`;
    }
  }, [templateData]);

  return (
    <div className="gui-textarea">
      <label className="gui-label" htmlFor={uid} data-cy={`${uid}_label`}>
        {templateData.label + (isRequired ? ' *' : '')}
        {hint && (
          <div className="gui-field-hint" id={`${uid}_hint`}>
            {hint}
          </div>
        )}
      </label>
      <div className="gui-field">
        <textarea
          id={uid}
          ref={textareaRef}
          data-cy={`${uid}_textarea`}
          className={`${icon ? 'gui-textarea--icon' : ''}`}
          style={{
            height: `${templateData.minimumHeight ?? 120}px`,
            minHeight: `${templateData.minimumHeight ?? 120}px`,
            resize: templateData.autoGrow ? 'none' : 'vertical',
          }}
          required={isRequired}
          value={value ?? ''}
          disabled={isDisabled}
          readOnly={isReadonly}
          placeholder={placeholder ?? undefined}
          onInput={handleChange}
          onBlur={onBlur}
          aria-invalid={showErrors}
          aria-errormessage={showErrors ? `${uid}_errors` : undefined}
          aria-required={isRequired}
          aria-describedby={hint ? `${uid}_hint` : undefined}
        ></textarea>
        {icon && <span className={`${icon} gui-field-icon gui-field-icon--right`}></span>}
      </div>

      <div className="gui-textarea--validation">
        <div>{showErrors && <Errors errors={errors} uid={uid} />}</div>
        <div>
          {counterMode && (
            <Counter value={value} validator={templateData.validator} counterMode={counterMode} />
          )}
        </div>
      </div>
    </div>
  );
}

// libs/angular-vanilla/src/lib/components/textarea/textarea.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import { TextareaProps } from '@golemui/shared-vanilla';
import { LabelComponent } from '../../utils/templates/label.component';
import { ErrorsComponent } from '../../utils/templates/errors.component';
import { GuiAriaDirective } from '../../directives/aria.directive';

@Component({
  standalone: true,
  selector: 'gui-textarea',
  imports: [CommonModule, LabelComponent, ErrorsComponent, GuiAriaDirective],
  providers: [Angular.ControlFieldAdapter],
  templateUrl: './textarea.component.html',
  host: {
    class: 'gui-textarea',
  },
})
export class TextareaComponent implements OnInit, OnDestroy, Core.WithField {
  field!: Core.ControlField<string>;

  protected adapter: Angular.ControlFieldAdapter<string, TextareaProps> = inject(
    Angular.ControlFieldAdapter,
  );

  ngOnInit(): void {
    this.adapter.init(this.field);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }

  valueChanged(event: Event) {
    const target = event.target as HTMLTextAreaElement;

    if (this.adapter.templateData().autoGrow) {
      target.style.height = 'auto';
      target.style.height = `${Math.max(this.adapter.templateData().minimumHeight ?? 120, target.scrollHeight)}px`;
    }

    this.adapter.valueChanged(target.value);
  }
}

@let templateData = adapter.templateData();
@let showErrors = templateData.touched && templateData.errors && templateData.errors.length > 0;

<label gui-label [for]="field.uid" [uid]="field.uid" [templateData]="templateData"></label>

<div class="gui-field">
  <textarea
    guiAria
    [attr.data-cy]="field.uid + '_textarea'"
    [uid]="field.uid"
    [templateData]="templateData"
    [id]="field.uid"
    [class]="{
      'gui-textarea--icon': templateData.icon,
    }"
    [style.height.px]="templateData.minimumHeight ?? 120"
    [style.min-height.px]="templateData.minimumHeight ?? 120"
    [style.resize]="templateData.autoGrow ? 'none' : 'vertical'"
    [required]="templateData.validator?.required"
    [value]="templateData.value ?? ''"
    [disabled]="templateData.disabled"
    [readOnly]="templateData.readonly"
    [attr.placeholder]="templateData.placeholder"
    (input)="valueChanged($event)"
    (blur)="adapter.onBlur()"
  ></textarea>

  @if (templateData.icon) {
    <span class="gui-field-icon gui-field-icon--right" [class]="templateData.icon"></span>
  }
</div>

<div class="gui-textarea--validation">
  <div>
    @if (showErrors) {
      <ul
        gui-errors
        [uid]="field.uid"
        [templateData]="templateData"
        [attr.data-cy]="field.uid + '_validator-errors'"
      ></ul>
    }
  </div>

  @if (templateData.counterMode && templateData.validator?.maxLength) {
  <div
    class="gui-textarea--counter"
    [class.gui-textarea--counter__error]="
      (templateData.value?.length ?? 0) > templateData.validator?.maxLength
    "
  >
      @if (templateData.counterMode === 'current') {
        <span>{{ templateData.value?.length ?? 0 }}</span>
      } @else {
        <span>{{ templateData.validator.maxLength - (templateData.value?.length ?? 0) }}</span>
      }
      <span> / {{ templateData.validator.maxLength }}</span>
  </div>
  }
</div>
