// apps/nextjs-playground/src/components/custom-fields/heading/heading.component.tsx
import type { DisplayWidget, WithWidget } from '@golemui/core';
import { useDisplayWidget } from '@golemui/react';
import { createElement, type PropsWithChildren } from 'react';
import styles from './heading.component.module.scss';

type OwnWidgetProps = {
  text: string;
  level?: number;
};

export function HeadingComponent(fieldInstance: WithWidget) {
  const field = fieldInstance.widget as DisplayWidget;
  const { uid, templateData } = useDisplayWidget<OwnWidgetProps>(field);

  return (
    <div className="gui-widget" id={uid}>
      <DynamicHeading level={templateData.level || 1}>{templateData.text}</DynamicHeading>
    </div>
  );
}

function DynamicHeading({ level, children }: PropsWithChildren<{ level: number }>) {
  const HeadingTag = `h${level}`;

  return createElement(HeadingTag, { className: styles.heading }, children);
}

export default HeadingComponent;

// apps/analog-playground/src/app/custom-widgets/heading/heading.component.ts
import { Component, inject, type OnDestroy, type OnInit } from '@angular/core';
import { DisplayWidgetAdapter } from '@golemui/angular';
import type { DisplayWidget, WithWidget } from '@golemui/core';

type OwnWidgetProps = {
  text: string;
  level?: number;
};

@Component({
  selector: 'app-heading',
  providers: [DisplayWidgetAdapter],
  templateUrl: './heading.component.html',
  styleUrls: ['./heading.component.scss'],
})
export class HeadingComponent implements OnInit, OnDestroy, WithWidget {
  widget!: DisplayWidget;

  protected adapter: DisplayWidgetAdapter<OwnWidgetProps> = inject(DisplayWidgetAdapter);

  ngOnInit(): void {
    this.adapter.init(this.widget);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

@let templateData = adapter.templateData();

<div class="gui-widget">
  @switch (templateData.level) {
    @case (2) {
      <h2 class="heading">{{ templateData.text }}</h2>
    }
    @case (3) {
      <h3 class="heading">{{ templateData.text }}</h3>
    }
    @case (4) {
      <h4 class="heading">{{ templateData.text }}</h4>
    }
    @case (5) {
      <h5 class="heading">{{ templateData.text }}</h5>
    }
    @case (6) {
      <h6 class="heading">{{ templateData.text }}</h6>
    }
    @default {
      <h1 class="heading">{{ templateData.text }}</h1>
    }
  }
</div>
