// libs/react-vanilla/src/lib/components/shared/Errors.tsx
export function Errors({ errors, uid }: { errors: string[]; uid: string }) {
  return (
    <ul className="gui-validator" id={`${uid}_errors`} data-cy={`${uid}_validator-errors`}>
      {errors.map((error, index) => (
        <li
          className="gui-validator__error"
          role="alert"
          key={index}
          data-cy={`${uid}_validator-error`}
        >
          {error}
        </li>
      ))}
    </ul>
  );
}

// libs/gui/vue/src/lib/components/shared/Errors.vue
<script setup lang="ts">
defineProps<{
  errors: string[];
  uid: string;
}>();
</script>

<template>
  <ul class="gui-validator" :id="`${uid}_errors`" :data-cy="`${uid}_validator-errors`">
    <li
      v-for="(error, index) in errors"
      :key="index"
      class="gui-validator__error"
      role="alert"
      :data-cy="`${uid}_validator-error`"
    >
      {{ error }}
    </li>
  </ul>
</template>
