// libs/angular/src/lib/ssr.fixture.ts
import { Component, inject, type OnDestroy, type OnInit, type Type } from '@angular/core';
import type {
  FormInitConfig,
  InputWidget,
  LayoutWidget,
  StandardSchemaV1,
  ValidatorFn,
  WithWidget,
} from '@golemui/core';
import { InputWidgetAdapter } from './adapters/input-widget-adapter.service';
import { LayoutWidgetAdapter } from './adapters/layout-widget-adapter.service';
import { FormCoreComponent } from './components/form/form.component';
import { WidgetDirective } from './directives/widget.directive';

/**
 * Stub widgets and a form definition shared by the server render specs.
 *
 * The widgets use the real adapters and the real WidgetDirective, so a value that reaches
 * the markup was read from the store through the same path the shipped widgets use.
 */

@Component({
  standalone: true,
  selector: 'gui-stub-textinput',
  providers: [InputWidgetAdapter],
  template: `<input
    type="text"
    [id]="widget.uid"
    [name]="widget.path"
    [attr.data-label]="adapter.templateData().label"
    [value]="adapter.templateData().value ?? ''"
    readonly
  />`,
})
class StubTextInputComponent implements OnInit, OnDestroy, WithWidget {
  widget!: InputWidget<string>;
  protected adapter: InputWidgetAdapter<string, Record<string, any>> = inject(InputWidgetAdapter);

  ngOnInit(): void {
    this.adapter.init(this.widget);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

@Component({
  standalone: true,
  selector: 'gui-stub-flex',
  imports: [WidgetDirective],
  providers: [LayoutWidgetAdapter],
  template: `<div class="stub-flex" [id]="widget.uid">
    @for (child of adapter.templateData().children; track child.uid) {
      <ng-container guiWidget [widget]="child" />
    }
  </div>`,
})
class StubFlexComponent implements OnInit, OnDestroy, WithWidget {
  widget!: LayoutWidget;
  protected adapter: LayoutWidgetAdapter<Record<string, any>> = inject(LayoutWidgetAdapter);

  ngOnInit(): void {
    this.adapter.init(this.widget);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

export const stubWidgetLoaders = {
  textinput: async (): Promise<Type<WithWidget>> => StubTextInputComponent,
  flex: async (): Promise<Type<WithWidget>> => StubFlexComponent,
};

/** Accepts everything. The specs assert on markup, not on validation. */
export const noopValidators: ValidatorFn<any> = () =>
  ({
    '~standard': {
      version: 1,
      vendor: 'golemui-ssr-fixture',
      validate: (value: unknown) => ({ value }),
    },
  }) as StandardSchemaV1;

export const formDef = {
  form: {
    uid: 'root',
    kind: 'layout',
    type: 'flex',
    children: [
      { kind: 'input', type: 'textinput', path: 'firstName', label: 'First name' },
      { kind: 'input', type: 'textinput', path: 'lastName', label: 'Last name' },
    ],
  },
};

export const formData = { firstName: 'Ada', lastName: 'Lovelace' };

/** An explicit formName keeps the form id identical on the server and the client. */
export function buildConfig(): FormInitConfig<Type<WithWidget>> {
  return {
    formDef,
    formName: 'ssr-spec-form',
    widgetLoaders: stubWidgetLoaders,
    data: formData,
  };
}

/** The root component that the specs pass to `renderApplication` and `bootstrapApplication`. */
@Component({
  standalone: true,
  selector: 'gui-ssr-host',
  imports: [FormCoreComponent],
  template: `<gui-core-form [config]="config" [validators]="validators" />`,
})
export class SsrHostComponent {
  config = buildConfig();
  validators = noopValidators;
}

// libs/lit/src/lib/ssr.fixture.ts
import type {
  FormInitConfig,
  InputWidget,
  LayoutWidget,
  NonFunctionWidget,
  StandardSchemaV1,
  ValidatorFn,
  WithWidget,
} from '@golemui/core';
import { consume } from '@lit/context';
import { html, LitElement } from 'lit';
import { property } from 'lit/decorators.js';
import { type Subscription } from 'rxjs';
import { InputWidgetAdapter } from './adapters/input-widget.adapter';
import { LayoutWidgetAdapter } from './adapters/layout-widget.adapter';
import { formContext, type LitFormContext } from './context/form.context';
import { safeDefine } from './utils/define';
import type { Type } from './utils/type';
import './components/form/form.element';

/**
 * Stub widget elements and a form definition shared by the server render and the
 * resume specs. The stubs use the real adapters and the real form context, so a value
 * that appears in the markup was read from the store through the same code path the
 * gui widget set uses.
 */

class StubTextInputElement extends LitElement implements WithWidget {
  widget!: InputWidget<string>;

  @consume({ context: formContext })
  @property({ attribute: false })
  formContext!: LitFormContext<any>;

  adapter = new InputWidgetAdapter<string, { placeholder?: string }>();

  subscriptions: Subscription[] = [];

  override createRenderRoot() {
    return this;
  }

  override connectedCallback() {
    super.connectedCallback();
    this.adapter.context = this.formContext;
    this.adapter.init(this.widget);
    this.subscriptions.push(
      this.adapter.templateDataChanged$.subscribe(() => this.requestUpdate()),
    );
  }

  override render() {
    return html`<input
      type="text"
      id=${this.widget.uid}
      data-label=${this.adapter.templateData.label ?? ''}
      .value=${this.adapter.templateData.value ?? ''}
    />`;
  }

  override disconnectedCallback() {
    super.disconnectedCallback();
    this.adapter.destroy();
    for (const subscription of this.subscriptions) {
      subscription.unsubscribe();
    }
  }
}

class StubFlexElement extends LitElement implements WithWidget {
  widget!: LayoutWidget;

  @consume({ context: formContext })
  @property({ attribute: false })
  formContext!: LitFormContext<any>;

  adapter = new LayoutWidgetAdapter();

  subscriptions: Subscription[] = [];

  override createRenderRoot() {
    return this;
  }

  override connectedCallback() {
    super.connectedCallback();
    this.adapter.context = this.formContext;
    this.adapter.init(this.widget);
    this.subscriptions.push(
      this.adapter.templateDataChanged$.subscribe(() => this.requestUpdate()),
    );
  }

  override render() {
    const children = (this.adapter.templateData.children ?? []) as NonFunctionWidget<string>[];
    return html`<div class="stub-flex" id=${this.widget.uid}>
      ${children.map((child) => html`<gui-widget .widget=${child}></gui-widget>`)}
    </div>`;
  }

  override disconnectedCallback() {
    super.disconnectedCallback();
    this.adapter.destroy();
    for (const subscription of this.subscriptions) {
      subscription.unsubscribe();
    }
  }
}

safeDefine('gui-stub-input', StubTextInputElement);
safeDefine('gui-stub-flex', StubFlexElement);

export const stubWidgetLoaders = {
  textinput: async (): Promise<Type<WithWidget>> => StubTextInputElement as Type<WithWidget>,
  flex: async (): Promise<Type<WithWidget>> => StubFlexElement as Type<WithWidget>,
};

/** Accepts everything. The specs assert on markup, not on validation. */
export const noopValidators: ValidatorFn<any> = () =>
  ({
    '~standard': {
      version: 1,
      vendor: 'golemui-ssr-fixture',
      validate: (value: unknown) => ({ value }),
    },
  }) as StandardSchemaV1;

export const formDef = {
  form: {
    uid: 'root',
    kind: 'layout',
    type: 'flex',
    children: [
      { kind: 'input', type: 'textinput', path: 'firstName', label: 'First name' },
      { kind: 'input', type: 'textinput', path: 'lastName', label: 'Last name' },
    ],
  },
};

export const formData = { firstName: 'Ada', lastName: 'Lovelace' };

export function buildConfig(): FormInitConfig<Type<WithWidget>> {
  return {
    formName: 'fixture-form',
    formDef,
    widgetLoaders: stubWidgetLoaders as any,
    data: formData,
  };
}

/**
 * The exact output of renderGuiFormHtml for buildConfig() plus noopValidators.
 * The server render spec asserts equality with this string byte for byte, and the
 * resume spec loads it into the DOM, so the two specs always test the same markup.
 */
export const canonicalServerMarkup = `<gui-core-form
      
      
      
     class="gui-form" defer-hydration>
  
  
      <form
        id="fixture-form"
        novalidate
        dir="ltr"
        
        
      >
         <gui-widget  style="display:contents" defer-hydration><gui-stub-flex   id="host-root" defer-hydration><div class="stub-flex" id="root">
      <gui-widget  style="display:contents" defer-hydration><gui-stub-input   id="host-firstName-textinput" defer-hydration><input
      type="text"
      id="firstName-textinput"
      data-label="First name"
      value="Ada"
    /></gui-stub-input></gui-widget><gui-widget  style="display:contents" defer-hydration><gui-stub-input   id="host-lastName-textinput" defer-hydration><input
      type="text"
      id="lastName-textinput"
      data-label="Last name"
      value="Lovelace"
    /></gui-stub-input></gui-widget>
    </div></gui-stub-flex></gui-widget>
      </form>
    
</gui-core-form>`;
