// libs/gui/react/src/lib/components/Markdown.tsx
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/react';
import { type MarkdownProps } from '@golemui/gui-shared';
import { useCallback } from 'react';
import { GuiMarkdownReact } from '../web-components';
import '../styles.scss';


export function Markdown(widgetInstance: WithWidget) {
  const widget = widgetInstance.widget as InputWidget<string>;
  const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useInputWidget<
    string,
    MarkdownProps
  >(widget);

  const handleChange = useCallback(
    (e: Event) => onValueChanged((e as CustomEvent).detail.value),
    [onValueChanged],
  );

  const label = templateData.label as string;
  const hint = templateData.hint;
  const placeholder = templateData.placeholder;
  const autocomplete = templateData.autocomplete;
  const maxLength = (templateData.validator as Validator)?.maxLength;
  const counterMode = templateData.counterMode;
  const autoGrow = templateData.autoGrow;
  const minimumHeight = templateData.minimumHeight;
  const tools = templateData.tools;
  const defaultOpenPreview = templateData.defaultOpenPreview;
  const headingTitle = templateData.headingTitle;
  const boldTitle = templateData.boldTitle;
  const italicTitle = templateData.italicTitle;
  const strikethroughTitle = templateData.strikethroughTitle;
  const quoteTitle = templateData.quoteTitle;
  const linkTitle = templateData.linkTitle;
  const orderedListTitle = templateData.orderedListTitle;
  const unorderedListTitle = templateData.unorderedListTitle;
  const splitViewTitle = templateData.splitViewTitle;
  const isDisabled = templateData.disabled as boolean;
  const isReadonly = templateData.readonly as boolean;
  const isRequired = (templateData.validator as Validator)?.required;

  return (
    <div className="gui-markdown gui-field" style={{ flex: templateData.size }}>
      <GuiMarkdownReact
        uid={uid}
        label={label}
        errors={errors}
        touched={isTouched}
        required={isRequired}
        disabled={isDisabled}
        readOnly={isReadonly}
        value={value}
        hint={hint}
        placeholder={placeholder}
        autocomplete={autocomplete ?? undefined}
        counterMode={counterMode}
        minimumHeight={minimumHeight}
        autoGrow={autoGrow}
        maxLength={maxLength}
        tools={tools}
        defaultOpenPreview={defaultOpenPreview}
        headingTitle={headingTitle}
        boldTitle={boldTitle}
        italicTitle={italicTitle}
        strikethroughTitle={strikethroughTitle}
        quoteTitle={quoteTitle}
        linkTitle={linkTitle}
        orderedListTitle={orderedListTitle}
        unorderedListTitle={unorderedListTitle}
        splitViewTitle={splitViewTitle}
        dependencies={templateData.deps}
        onInput={handleChange}
        onBlur={onBlur}
      ></GuiMarkdownReact>
    </div>
  );
}

// libs/gui/angular/src/lib/components/markdown/markdown.component.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  inject,
  OnDestroy,
  OnInit,
} from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import { MarkdownProps } from '@golemui/gui-shared';

@Component({
  standalone: true,
  selector: 'gui-markdown-control',
  imports: [CommonModule],
  providers: [Angular.InputWidgetAdapter],
  templateUrl: './markdown.component.html',
  host: {
    class: 'gui-markdown gui-field',
  },
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class MarkdownComponent implements OnInit, OnDestroy, Core.WithWidget {
  widget!: Core.InputWidget<string>;

  protected adapter: Angular.InputWidgetAdapter<string, MarkdownProps> = inject(
    Angular.InputWidgetAdapter,
  );

  ngOnInit(): void {
    this.adapter.init(this.widget);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }

  valueChanged(event: Event) {
    const value = (event as CustomEvent).detail.value;
    this.adapter.valueChanged(value);
  }
}

@let templateData = adapter.templateData();

<gui-markdown
  class="gui-field"
  [uid]="widget.uid"
  [label]="templateData.label"
  [errors]="templateData.errors"
  [touched]="templateData.touched"
  [required]="templateData.validator?.required"
  [disabled]="templateData.disabled"
  [readOnly]="templateData.readonly"
  [value]="templateData.value"
  [hint]="templateData.hint"
  [placeholder]="templateData.placeholder"
  [icon]="templateData.icon"
  [counterMode]="templateData.counterMode"
  [minimumHeight]="templateData.minimumHeight"
  [autoGrow]="templateData.autoGrow"
  [headingTitle]="templateData.headingTitle"
  [boldTitle]="templateData.boldTitle"
  [italicTitle]="templateData.italicTitle"
  [strikethroughTitle]="templateData.strikethroughTitle"
  [quoteTitle]="templateData.quoteTitle"
  [linkTitle]="templateData.linkTitle"
  [orderedListTitle]="templateData.orderedListTitle"
  [unorderedListTitle]="templateData.unorderedListTitle"
  [splitViewTitle]="templateData.splitViewTitle"
  [tools]="templateData.tools"
  [defaultOpenPreview]="templateData.defaultOpenPreview"
  [maxLength]="templateData.validator?.maxLength"
  [dependencies]="templateData.deps"
  (input)="valueChanged($event)"
  (blur)="adapter.onBlur()"
></gui-markdown>
