// libs/react-vanilla/src/lib/components/Accordion.tsx
import * as Core from '@golemui/core';
import { FieldRenderer, useLayoutField } from '@golemui/react';
import { AccordionProps } from '@golemui/shared-vanilla';
import { useCallback, useState } from 'react';

export function Accordion(fieldInstance: Core.WithField) {
  const field = fieldInstance.field as Core.LayoutField;
  const { uid, children, props } = useLayoutField<AccordionProps>(field);
  const [activeSections, setActiveSections] = useState(props.defaultOpen ?? {});

  const onClickButton = useCallback(
    (uid: string) => {
      setActiveSections((state) => {
        const newState = { ...state };

        if (props.singleOpen) {
          Object.keys(newState)
            .filter((sectionUid) => sectionUid !== uid)
            .forEach((sectionUid) => {
              newState[sectionUid] = sectionUid === uid ? !newState[sectionUid] : false;
            });
        }

        newState[uid] = !newState[uid];

        return newState;
      });
    },
    [props.singleOpen],
  );

  const renderContent = useCallback(
    (uid: string) => {
      const child = children.find((section) => section.uid === uid) as Core.FormField<string>;
      const isActiveSection = activeSections[uid];

      return isActiveSection && child ? (
        <section className="gui-field" role="region">
          <FieldRenderer field={child} />
        </section>
      ) : null;
    },
    [children, activeSections],
  );

  const renderAccordion = useCallback(() => {
    return props.sections.map((section, index) => (
      <div className="gui-accordion__section" key={`${'accordion-section-' + section.uid}`}>
        <button
          type="button"
          tabIndex={index}
          aria-expanded={activeSections[section.uid]}
          className={activeSections[section.uid] ? 'active' : ''}
          onClick={() => onClickButton(section.uid)}
        >
          {section.label}
          <span className="gui-accordion__icon"></span>
        </button>

        {renderContent(section.uid)}
      </div>
    ));
  }, [props, activeSections, onClickButton, renderContent]);

  return (
    <div className="gui-accordion">
      <div className="gui-field" id={uid}>
        {renderAccordion()}
      </div>
    </div>
  );
}

// libs/angular-vanilla/src/lib/accordion/accordion.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import { AccordionProps } from '@golemui/shared-vanilla';

@Component({
  standalone: true,
  selector: 'gui-accordion',
  imports: [CommonModule, Angular.FieldDirective],
  providers: [Angular.LayoutAdapter],
  templateUrl: './accordion.component.html',
  host: {
    class: 'gui-accordion',
  },
})
export class AccordionComponent implements OnInit, OnDestroy, Core.WithField {
  field!: Core.LayoutField;
  activeSections: { [key: string]: boolean } = {};

  protected adapter: Angular.LayoutAdapter<AccordionProps> = inject(Angular.LayoutAdapter);

  ngOnInit(): void {
    const props: AccordionProps = this.field.props as AccordionProps;
    this.adapter.init(this.field);
    this.activeSections = props.defaultOpen ?? {};
  }

  onClickButton(uid: string) {
    const props: AccordionProps = this.field.props as AccordionProps;
    if (props.singleOpen) {
      Object.keys(this.activeSections)
        .filter((sectionUid) => sectionUid !== uid)
        .forEach((key) => {
          this.activeSections[key] = false;
        });
    }

    this.activeSections[uid] = !this.activeSections[uid];
  }

  getChild(uid: string) {
    return this.field.children.find((section) => section.uid === uid) as Core.FormField<string>;
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

@let templateData = adapter.templateData();

<div class="gui-field" [id]="field.uid">
  @for (section of templateData.sections; track section.uid) {
    <div class="gui-accordion__section">
      <button
        type="button"
        [tabindex]="$index"
        [attr.aria-expanded]="activeSections[section.uid]"
        [class.active]="activeSections[section.uid]"
        (click)="onClickButton(section.uid)"
      >
        {{ section.label }}<span class="gui-accordion__icon"></span>
      </button>

      @if (activeSections[section.uid]) {
        <section class="gui-field" role="region">
          <ng-container guiField [field]="getChild(section.uid)" />
        </section>
      }
    </div>
  }
</div>
