// libs/gui/vue/src/lib/components/shared/Errors.vue
<script setup lang="ts">
defineProps<{
  errors: string[];
  uid: string;
}>();
</script>

<template>
  <ul class="gui-validator" :id="`${uid}_errors`" :data-cy="`${uid}_validator-errors`">
    <li
      v-for="(error, index) in errors"
      :key="index"
      class="gui-validator__error"
      role="alert"
      :data-cy="`${uid}_validator-error`"
    >
      {{ error }}
    </li>
  </ul>
</template>

// libs/gui/angular/src/lib/utils/templates/errors.component.ts
import { Component, input } from '@angular/core';
import { CommonModule } from '@angular/common';
import type { ControlTemplateData } from '@golemui/core'

@Component({
  standalone: true,
  selector: '[gui-errors]',
  imports: [CommonModule],
  template: `@for (error of templateData().errors; track $index) {
    <li class="gui-validator__error" role="alert" [attr.data-cy]="uid() + '_validator-error'">
      {{ error }}
    </li>
  }`,
  host: {
    '[attr.id]': 'uid() + "_errors"',
    class: 'gui-validator',
  },
})
export class ErrorsComponent<T, ExtraProps extends { hint?: string }> {
  uid = input.required<string>();
  templateData = input.required<ControlTemplateData<T> & ExtraProps>();
}
