// apps/nextjs-playground/src/components/custom-fields/heading/heading.component.tsx
import type { DisplayWidget, WithWidget } from '@golemui/core';
import { useDisplayWidget } from '@golemui/react';
import { createElement, type PropsWithChildren } from 'react';
import styles from './heading.component.module.scss';

type OwnWidgetProps = {
  text: string;
  level?: number;
};

export function HeadingComponent(fieldInstance: WithWidget) {
  const field = fieldInstance.widget as DisplayWidget;
  const { uid, templateData } = useDisplayWidget<OwnWidgetProps>(field);

  return (
    <div className="gui-widget" id={uid}>
      <DynamicHeading level={templateData.level || 1}>{templateData.text}</DynamicHeading>
    </div>
  );
}

function DynamicHeading({ level, children }: PropsWithChildren<{ level: number }>) {
  const HeadingTag = `h${level}`;

  return createElement(HeadingTag, { className: styles.heading }, children);
}

export default HeadingComponent;

// apps/angular-playground/src/app/custom-widgets/heading/heading.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';

type OwnWidgetProps = {
  text: string;
  level?: number;
};

@Component({
  standalone: true,
  selector: 'app-heading',
  imports: [CommonModule, Angular.WidgetDirective],
  providers: [Angular.DisplayWidgetAdapter],
  templateUrl: './heading.component.html',
  styleUrls: ['./heading.component.scss'],
})
export class HeadingComponent implements OnInit, OnDestroy, Core.WithWidget {
  widget!: Core.DisplayWidget;

  protected adapter: Angular.DisplayWidgetAdapter<OwnWidgetProps> = inject(
    Angular.DisplayWidgetAdapter,
  );

  ngOnInit(): void {
    this.adapter.init(this.widget);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

@let templateData = adapter.templateData();

<div class="gui-field">
  <ng-container [ngSwitch]="templateData.level">
    <h1 *ngSwitchCase="1" class="heading">{{ templateData.text }}</h1>
    <h2 *ngSwitchCase="2" class="heading">{{ templateData.text }}</h2>
    <h3 *ngSwitchCase="3" class="heading">{{ templateData.text }}</h3>
    <h4 *ngSwitchCase="4" class="heading">{{ templateData.text }}</h4>
    <h5 *ngSwitchCase="5" class="heading">{{ templateData.text }}</h5>
    <h6 *ngSwitchCase="6" class="heading">{{ templateData.text }}</h6>
    <h1 *ngSwitchDefault class="heading">{{ templateData.text }}</h1>
  </ng-container>
</div>
