// libs/gui/vue/src/lib/components/MultiList.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget, useVueFormContext } from '@golemui/vue';
import type { ListItem, MultiListProps, OptionValue } from '@golemui/gui-shared/internals';
import { computed, onUnmounted, ref, watch, type Component } from 'vue';
import DefaultMultiListItemRenderer from './item-renderers/DefaultMultiListItemRenderer.vue';
import '@golemui/gui-components/label';
import '@golemui/gui-components/multi-list';
import '@golemui/gui-components/pills';
import '@golemui/gui-components/errors';

interface GuiMultiListElement extends HTMLElement {
  focusItemAtIndex(index: number): void;
  scrollToIndex(index: number): void;
}

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<OptionValue[]>;
const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useInputWidget<
  OptionValue[],
  MultiListProps<unknown>
>(widget);

const rangeStart = ref(0);
const rangeEnd = ref(10);
const listItems = ref<ListItem<any>[]>([]);
const focusedIndex = ref<number>(-1);
const listRef = ref<GuiMultiListElement | null>(null);

const currentValues = computed(() => (Array.isArray(value.value) ? value.value : []));

const visibleItems = computed(() => {
  const items = listItems.value.length > 0 ? listItems.value : templateData.value.items || [];
  return items.slice(rangeStart.value, rangeEnd.value);
});

const pillItems = computed(() => {
  const labelField = (templateData.value.labelField as string) ?? 'label';
  return currentValues.value.map((val) => {
    const item = listItems.value.find((i) => i.value === val);
    const isObject = item != null && item.template !== null && typeof item.template === 'object';
    const label =
      item == null
        ? String(val)
        : isObject
          ? String((item.template as any)[labelField])
          : String(item.template);
    return { key: String(val), label };
  });
});

const required = computed(() => (templateData.value.validator as Validator)?.required);
const isDisabled = computed(() => templateData.value.disabled as boolean);
const isReadOnly = computed(() => templateData.value.readonly as boolean);
const showErrors = computed(() => isTouched.value && errors.value && errors.value.length > 0);

const toggleValue = (val: OptionValue) => {
  if (templateData.value.disabled || templateData.value.readonly) return;

  const current = currentValues.value;
  if (current.includes(val)) {
    onValueChanged(current.filter((v) => v !== val));
    return;
  }
  if (templateData.value.limit !== undefined && current.length >= templateData.value.limit) return;
  onValueChanged([...current, val]);
};

const handleRangeChange = (e: Event) => {
  const { startIndex, endIndex } = (e as CustomEvent).detail;
  rangeStart.value = startIndex;
  rangeEnd.value = endIndex;
};
const handleUpdateItems = (e: Event) => {
  const items = (e as CustomEvent).detail;
  listItems.value = items ? [...items] : [];
};
const handleFocusChange = (e: Event) => {
  focusedIndex.value = (e as CustomEvent).detail.index;
};
const handleChange = (e: Event) => {
  toggleValue((e as CustomEvent).detail.value);
};

let currentList: GuiMultiListElement | null = null;
watch(listRef, (el) => {
  if (currentList) {
    currentList.removeEventListener('change', handleChange);
    currentList.removeEventListener('gui-update-items', handleUpdateItems);
    currentList.removeEventListener('gui-range-change', handleRangeChange);
    currentList.removeEventListener('gui-focus-change', handleFocusChange);
  }
  currentList = el;
  if (el) {
    el.addEventListener('change', handleChange);
    el.addEventListener('gui-update-items', handleUpdateItems);
    el.addEventListener('gui-range-change', handleRangeChange);
    el.addEventListener('gui-focus-change', handleFocusChange);
  }
});

onUnmounted(() => {
  currentList?.removeEventListener('change', handleChange);
  currentList?.removeEventListener('gui-update-items', handleUpdateItems);
  currentList?.removeEventListener('gui-range-change', handleRangeChange);
  currentList?.removeEventListener('gui-focus-change', handleFocusChange);
});

const handleBlur = (e: FocusEvent) => {
  if (listRef.value && e.relatedTarget && listRef.value.contains(e.relatedTarget as Node)) return;
  onBlur();
};

const handleClickItem = (item: ListItem<any>, index: number) => {
  if (templateData.value.disabled || item.disabled) return;
  toggleValue(item.value);
  focusedIndex.value = index;
  listRef.value?.focusItemAtIndex(index);
};

const handlePillRemove = (e: Event) => {
  const key = (e as CustomEvent).detail?.key;
  const val = currentValues.value.find((v) => String(v) === key);
  if (val === undefined) return;
  toggleValue(val);
};

const handlePillClick = (e: Event) => {
  const key = (e as CustomEvent).detail?.key;
  const index = listItems.value.findIndex((i) => String(i.value) === key);
  if (index < 0 || !listRef.value) return;
  listRef.value.focusItemAtIndex(index);
  listRef.value.scrollToIndex(index);
  focusedIndex.value = index;
};

const formContext = useVueFormContext();
const ItemRenderer = computed<Component>(() => {
  const renderers = formContext.itemRenderers as Record<string, Component>;
  return (
    renderers[templateData.value.itemRenderer as string] ||
    (DefaultMultiListItemRenderer as Component)
  );
});
</script>

<template>
  <div class="gui-multi-list-widget gui-field" :style="{ flex: templateData.size }">
    <gui-label
      :uid="uid"
      :label="templateData.label"
      :hint="templateData.hint"
      :errors="errors"
      :touched="isTouched"
      :required="required"
      :native="false"
    ></gui-label>

    <div class="gui-widget">
      <gui-pills
        v-if="pillItems.length > 0"
        class="gui-multi-list__pills"
        :uid="uid"
        :toolbarAriaLabel="'Selected options'"
        :items="pillItems"
        :removable="true"
        :clickable="true"
        :bubble="false"
        :disabled="isDisabled"
        :readOnly="isReadOnly"
        :removeAriaLabel="templateData.removeAriaLabel ?? 'Remove option'"
        :removeIcon="templateData.removeIcon"
        @pillremove="handlePillRemove"
        @pillclick="handlePillClick"
      ></gui-pills>

      <gui-multi-list
        ref="listRef"
        :id="uid"
        :uid="uid"
        :values="currentValues"
        :valueField="templateData.valueField"
        :items="templateData.items"
        :itemHeight="templateData.itemHeight"
        :height="templateData.height"
        :required="required"
        :touched="isTouched"
        :disabled="isDisabled"
        :readOnly="isReadOnly"
        @blur="handleBlur"
      >
        <div
          v-for="(item, idx) in visibleItems"
          :key="rangeStart + idx"
          role="option"
          tabindex="-1"
          :id="`${uid}-item-${rangeStart + idx}`"
          class="gui-list__item-wrapper"
          :style="{ height: `${templateData.itemHeight || 40}px` }"
          :aria-selected="currentValues.includes(item.value)"
          :aria-disabled="isDisabled || item.disabled ? 'true' : 'false'"
          @click="handleClickItem(item, rangeStart + idx)"
        >
          <component
            :is="ItemRenderer"
            :template="
              (() => {
                const labelField = templateData.labelField ?? 'label';
                const isObject = item.template !== null && typeof item.template === 'object';
                return isObject && labelField && !templateData.itemRenderer
                  ? (item.template as any)[labelField]
                  : item.template;
              })()
            "
            :value="item.value"
            :index="idx"
            :selected="currentValues.includes(item.value)"
            :disabled="isDisabled || !!item.disabled"
            :focused="focusedIndex === rangeStart + idx"
          />
        </div>
      </gui-multi-list>
    </div>

    <gui-errors v-if="showErrors" :uid="uid" :errors="errors" :touched="isTouched"></gui-errors>
  </div>
</template>

// libs/gui/angular/src/lib/components/multi-list/multi-list.component.ts
import { CommonModule, NgComponentOutlet } from '@angular/common';
import {
  Component,
  computed,
  CUSTOM_ELEMENTS_SCHEMA,
  type ElementRef,
  inject,
  type OnDestroy,
  type OnInit,
  signal,
  viewChild,
} from '@angular/core';
import { type AngularItemRenderer, InputWidgetAdapter } from '@golemui/angular';
import type { InputWidget, WithWidget } from '@golemui/core';
import type { ListItem, MultiListProps, OptionValue } from '@golemui/gui-shared/internals';
import { DefaultMultiListItemRenderer } from './default-multi-list.item-renderer';
import '@golemui/gui-components/label';
import '@golemui/gui-components/multi-list';
import '@golemui/gui-components/pills';
import '@golemui/gui-components/errors';

@Component({
  standalone: true,
  selector: 'gui-multi-list-control',
  imports: [CommonModule, NgComponentOutlet],
  providers: [InputWidgetAdapter],
  templateUrl: './multi-list.component.html',
  host: {
    class: 'gui-multi-list-widget gui-field',
    '[style.flex]': 'this.adapter.templateData().size',
  },
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class MultiListComponent implements OnInit, OnDestroy, WithWidget {
  widget!: InputWidget<OptionValue[]>;

  protected adapter: InputWidgetAdapter<OptionValue[], MultiListProps<unknown>> =
    inject(InputWidgetAdapter);

  protected defaultListItemRenderer: AngularItemRenderer<string> = DefaultMultiListItemRenderer;

  protected listElementRef = viewChild.required<ElementRef>('listRef');

  protected currentRange = signal({ start: 0, end: 10 });
  protected listItems = signal<ListItem<any>[]>([]);
  protected focusedIndex = signal<number>(-1);

  protected visibleItems = computed(() => {
    const items = this.listItems() || [];
    const { start, end } = this.currentRange();

    return items.slice(start, end);
  });

  protected currentValues = computed(() => {
    const value = this.adapter.templateData().value;
    return Array.isArray(value) ? value : [];
  });

  protected pillItems = computed(() => {
    const labelField = (this.adapter.templateData().labelField as string) ?? 'label';
    const items = this.listItems();
    return this.currentValues().map((value) => {
      const item = items.find((i) => i.value === value);
      const isObject = item != null && item.template !== null && typeof item.template === 'object';
      const label =
        item == null
          ? String(value)
          : isObject
            ? String((item.template as any)[labelField])
            : String(item.template);
      return { key: String(value), label };
    });
  });

  ngOnInit(): void {
    this.adapter.init(this.widget);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }

  protected toggleValue(value: OptionValue) {
    const templateData = this.adapter.templateData();
    if (templateData.disabled || templateData.readonly) return;

    const current = this.currentValues();
    if (current.includes(value)) {
      this.adapter.valueChanged(current.filter((v) => v !== value));
      return;
    }
    if (templateData.limit !== undefined && current.length >= templateData.limit) return;
    this.adapter.valueChanged([...current, value]);
  }

  protected onClickItem(item: any, index: number, listRef: any) {
    if (this.adapter.templateData().disabled || item.disabled) return;

    this.toggleValue(item.value);
    this.focusedIndex.set(index);
    listRef.focusItemAtIndex(index);
  }

  protected valueChanged(event: Event) {
    const value = (event as CustomEvent).detail.value;
    this.toggleValue(value);
  }

  protected onPillRemove(event: Event) {
    const key = (event as CustomEvent).detail?.key;
    const value = this.currentValues().find((v) => String(v) === key);
    if (value === undefined) return;
    this.toggleValue(value);
  }

  protected onPillClick(event: Event) {
    const key = (event as CustomEvent).detail?.key;
    const index = this.listItems().findIndex((i) => String(i.value) === key);
    if (index < 0) return;
    const listElement = this.listElementRef()?.nativeElement;
    if (!listElement) return;
    listElement.focusItemAtIndex(index);
    listElement.scrollToIndex(index);
    this.focusedIndex.set(index);
  }

  protected onFocusChange(event: Event) {
    const index = (event as CustomEvent).detail.index;
    this.focusedIndex.set(index);
  }

  protected onUpdateItems(event: Event) {
    const items = (event as CustomEvent).detail;
    this.listItems.set(items ? [...items] : []);
  }

  protected onRangeChange(event: Event) {
    const { startIndex, endIndex } = (event as CustomEvent).detail;
    this.currentRange.set({ start: startIndex, end: endIndex });
  }
}

@let templateData = adapter.templateData();
@let itemRenderer = adapter.getItemRenderer(templateData.itemRenderer, defaultListItemRenderer);
@let showErrors = templateData.touched && templateData.errors && templateData.errors.length > 0;

<gui-label
  [targetElement]="listElementRef().nativeElement"
  [uid]="widget.uid"
  [label]="templateData.label"
  [hint]="templateData.hint"
  [errors]="templateData.errors"
  [touched]="templateData.touched"
  [required]="templateData.validator?.required"
  [native]="false"
></gui-label>

<div class="gui-widget">
  @if (pillItems().length > 0) {
    <gui-pills
      class="gui-multi-list__pills"
      [uid]="widget.uid"
      [toolbarAriaLabel]="'Selected options'"
      [items]="pillItems()"
      [removable]="true"
      [clickable]="true"
      [bubble]="false"
      [disabled]="templateData.disabled"
      [readOnly]="templateData.readonly"
      [removeAriaLabel]="templateData.removeAriaLabel ?? 'Remove option'"
      [removeIcon]="templateData.removeIcon"
      (pillremove)="onPillRemove($event)"
      (pillclick)="onPillClick($event)"
    ></gui-pills>
  }

  <gui-multi-list
    #listRef
    [uid]="widget.uid"
    [errors]="templateData.errors"
    [touched]="templateData.touched"
    [required]="templateData.validator?.required"
    [disabled]="templateData.disabled"
    [readonly]="templateData.readonly"
    [values]="currentValues()"
    [valueField]="templateData.valueField"
    [items]="templateData.items"
    [itemHeight]="templateData.itemHeight"
    [height]="templateData.height"
    [label]="templateData.label"
    [hint]="templateData.hint"
    (blur)="adapter.onBlur()"
    (change)="valueChanged($event)"
    (gui-update-items)="onUpdateItems($event)"
    (gui-range-change)="onRangeChange($event)"
    (gui-focus-change)="onFocusChange($event)"
  >
    @for (item of visibleItems(); track $index) {
      @let absoluteIndex = currentRange().start + $index;
      @let labelField = templateData.labelField ?? 'label';
      @let isObject = item.template !== null && typeof item.template === 'object';
      @let template =
        isObject && labelField && !templateData.itemRenderer
          ? item.template[labelField]
          : item.template;

      <!-- eslint-disable-next-line @angular-eslint/template/click-events-have-key-events -->
      <div
        role="option"
        tabindex="-1"
        class="gui-list__item-wrapper"
        [id]="widget.uid + '-item-' + absoluteIndex"
        [style.height.px]="templateData.itemHeight || 40"
        [attr.aria-selected]="currentValues().includes(item.value)"
        [attr.aria-disabled]="templateData.disabled || !!item.disabled"
        (click)="onClickItem(item, absoluteIndex, listRef)"
      >
        <ng-container
          *ngComponentOutlet="
            itemRenderer;
            inputs: {
              template: template,
              value: item.value,
              disabled: templateData.disabled || !!item.disabled,
              selected: currentValues().includes(item.value),
              focused: focusedIndex() === absoluteIndex,
              index: $index,
            }
          "
        >
        </ng-container>
      </div>
    }
  </gui-multi-list>
</div>

@if (showErrors) {
  <gui-errors
    [uid]="widget.uid"
    [errors]="templateData.errors"
    [touched]="templateData.touched"
  ></gui-errors>
}
