// libs/react-vanilla/src/lib/components/RangeCalendar.tsx
import * as Core from '@golemui/core';
import { useInputWidget } from '@golemui/react';
import { DateRange, RangeCalendarProps } from '@golemui/shared-vanilla';
import { useCallback } from 'react';
import '../styles.scss';

export function RangeCalendar(widgetInstance: Core.WithWidget) {
  const widget = widgetInstance.widget as Core.InputWidget<DateRange[]>;
  const { uid, errors, value, isTouched, templateData, onBlur, onValueChanged } = useInputWidget<
    DateRange[],
    RangeCalendarProps
  >(widget);

  const handleRef = useCallback(
    (node: HTMLElement | null) => {
      const target = node as any;
      const changeHandler = (e: CustomEvent) => onValueChanged(e.detail.value);
      const blurHandler = (e: CustomEvent) => {
        onBlur();
      };
      if (node) {
        target.addEventListener('blur', blurHandler);
        target.addEventListener('change', changeHandler);
      }

      return () => {
        target.removeEventListener('blur', blurHandler);
        target.removeEventListener('change', changeHandler);
      };
    },
    [onValueChanged, onBlur],
  );

  const label = templateData.label as string;
  const hint = templateData.hint;
  const prevMonthIcon = templateData.prevMonthIcon;
  const nextMonthIcon = templateData.nextMonthIcon;
  const prevMonthAriaLabel = templateData.prevMonthAriaLabel;
  const nextMonthAriaLabel = templateData.nextMonthAriaLabel;
  const dayFormat = templateData.dayFormat;
  const weekdayFormat = templateData.weekdayFormat;
  const monthFormat = templateData.monthFormat;
  const minDate = templateData.minDate;
  const maxDate = templateData.maxDate;
  const disabledRanges = templateData.disabledRanges;
  const numberOfMonths = templateData.numberOfMonths;
  const lang = templateData.lang;
  const isDisabled = templateData.disabled as boolean;
  const isReadonly = templateData.readonly as boolean;
  const isRequired = (templateData.validator as Core.Validator)?.required;

  return (
    <div className="gui-range-calendar">
      <gui-range-calendar
        ref={handleRef}
        uid={uid}
        label={label}
        hint={hint}
        errors={errors}
        touched={isTouched}
        required={isRequired}
        disabled={isDisabled}
        readOnly={isReadonly}
        value={value}
        prevMonthIcon={prevMonthIcon}
        nextMonthIcon={nextMonthIcon}
        prevMonthAriaLabel={prevMonthAriaLabel}
        nextMonthAriaLabel={nextMonthAriaLabel}
        dayFormat={dayFormat}
        weekdayFormat={weekdayFormat}
        monthFormat={monthFormat}
        minDate={minDate}
        maxDate={maxDate}
        disabledRanges={disabledRanges}
        numberOfMonths={numberOfMonths}
        localeId={lang}
      />
    </div>
  );
}

// libs/angular-vanilla/src/lib/components/range-calendar/range-calendar.component.ts
import { CommonModule } from '@angular/common';
import { Component, CUSTOM_ELEMENTS_SCHEMA, inject, OnDestroy, OnInit } from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import { RangeCalendarProps } from '@golemui/shared-vanilla';

@Component({
  standalone: true,
  selector: 'gui-range-calendar-control',
  imports: [CommonModule],
  providers: [Angular.ControlFieldAdapter],
  templateUrl: './range-calendar.component.html',
  host: {
    class: 'gui-range-calendar',
    '[style.flex]': 'this.adapter.templateData().size',
  },
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class RangeCalendarComponent implements OnInit, OnDestroy, Core.WithWidget {
  widget!: Core.InputWidget<string>;
  protected adapter: Angular.ControlFieldAdapter<string, RangeCalendarProps> = inject(
    Angular.ControlFieldAdapter,
  );
  currentDate = new Date();

  ngOnInit(): void {
    this.adapter.init(this.widget);
  }

  onChangeDate(event: Event) {
    this.adapter.valueChanged((event as CustomEvent).detail.value);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

@let templateData = adapter.templateData();

<gui-range-calendar
  [uid]="widget.uid"
  [label]="templateData.label"
  [hint]="templateData.hint"
  [value]="templateData.value"
  [errors]="templateData.errors"
  [touched]="templateData.touched"
  [required]="templateData.validator?.required"
  [disabled]="templateData.disabled"
  [readonly]="templateData.readonly"
  [value]="templateData.value"
  [prevMonthIcon]="templateData.prevMonthIcon"
  [nextMonthIcon]="templateData.nextMonthIcon"
  [prevMonthAriaLabel]="templateData.prevMonthAriaLabel"
  [nextMonthAriaLabel]="templateData.nextMonthAriaLabel"
  [dayFormat]="templateData.dayFormat"
  [weekdayFormat]="templateData.weekdayFormat"
  [monthFormat]="templateData.monthFormat"
  [minDate]="templateData.minDate"
  [maxDate]="templateData.maxDate"
  [disabledRanges]="templateData.disabledRanges"
  [numberOfMonths]="templateData.numberOfMonths"
  [localeId]="templateData.lang"
  (blur)="adapter.onBlur()"
  (change)="onChangeDate($event)"
></gui-range-calendar>
