// libs/react-vanilla/src/lib/components/Accordion.tsx
import * as Core from '@golemui/core';
import { useLayoutWidget, WidgetRenderer } from '@golemui/react';
import { AccordionProps } from '@golemui/shared-vanilla';
import { useCallback, useEffect, useState } from 'react';

const empty = {};

export function Accordion(widgetInstance: Core.WithWidget) {
  const widget = widgetInstance.widget as Core.LayoutWidget;
  const { uid, children, templateData, onChange } = useLayoutWidget<AccordionProps>(widget);
  const [activeSections, setActiveSections] =
    useState<NonNullable<AccordionProps['defaultOpen']>>(empty);

  useEffect(() => {
    if (activeSections === empty && templateData.defaultOpen) {
      setActiveSections(templateData.defaultOpen || {});
    }
  }, [activeSections, templateData]);

  const onClickButton = useCallback(
    (uid: string) => {
      const newState: typeof activeSections = { ...activeSections };

      if (templateData.singleOpen) {
        Object.keys(newState)
          .filter((sectionUid) => sectionUid !== uid)
          .forEach((sectionUid) => {
            newState[sectionUid] = sectionUid === uid ? !newState[sectionUid] : false;
          });
      }

      newState[uid] = !newState[uid];

      setActiveSections(newState);
      onChange(newState);
    },
    [activeSections, templateData.singleOpen, onChange],
  );

  const renderContent = useCallback(
    (uid: string) => {
      const child = children.find(
        (section) => section.uid === uid,
      ) as Core.NonFunctionWidget<string>;
      const isActiveSection = activeSections[uid];
      return (isActiveSection || templateData.renderMode !== 'activeOnly') && child ? (
        <section
          className="gui-field"
          role="region"
          id={`accordion_section_${uid}`}
          hidden={!isActiveSection && templateData.renderMode !== 'activeOnly'}
          aria-labelledby={`accordion_button_${uid}`}
        >
          <WidgetRenderer widget={child} />
        </section>
      ) : null;
    },
    [children, activeSections, templateData.renderMode],
  );

  const renderAccordion = useCallback(() => {
    const sections = templateData.sections || [];
    return sections.map((section, index) => (
      <div className="gui-accordion__section" key={`${'accordion_section_' + section.uid}`}>
        <button
          type="button"
          id={`accordion_button_${section.uid}`}
          aria-controls={`accordion_section_${section.uid}`}
          aria-expanded={activeSections[section.uid] ? 'true' : 'false'}
          className={activeSections[section.uid] ? 'active' : ''}
          onClick={() => onClickButton(section.uid)}
        >
          {section.label}
          <span className="gui-accordion__icon"></span>
        </button>

        {renderContent(section.uid)}
      </div>
    ));
  }, [templateData.sections, activeSections, renderContent, onClickButton]);

  return (
    <div className="gui-accordion" style={{ flex: templateData.size }}>
      <div className="gui-field" id={uid}>
        {renderAccordion()}
      </div>
    </div>
  );
}

// libs/angular-vanilla/src/lib/components/accordion/accordion.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import { AccordionEventDetail, AccordionProps } from '@golemui/shared-vanilla';

@Component({
  standalone: true,
  selector: 'gui-accordion-layout',
  imports: [CommonModule, Angular.WidgetDirective],
  providers: [Angular.LayoutWidgetAdapter],
  templateUrl: './accordion.component.html',
  host: {
    class: 'gui-accordion',
    '[style.flex]': 'this.adapter.templateData().size',
  },
})
export class AccordionComponent implements OnInit, OnDestroy, Core.WithWidget {
  widget!: Core.LayoutWidget;
  activeSections: { [key: string]: boolean } = {};

  protected adapter: Angular.LayoutWidgetAdapter<AccordionProps> = inject(
    Angular.LayoutWidgetAdapter,
  );

  ngOnInit(): void {
    const props: AccordionProps = this.widget.props as AccordionProps;
    this.adapter.init(this.widget);
    this.activeSections = props.defaultOpen ?? {};
  }

  onClickButton(uid: string) {
    const props: AccordionProps = this.widget.props as AccordionProps;
    if (props.singleOpen) {
      Object.keys(this.activeSections)
        .filter((sectionUid) => sectionUid !== uid)
        .forEach((key) => {
          this.activeSections[key] = false;
        });
    }

    this.activeSections[uid] = !this.activeSections[uid];

    this.adapter.change<AccordionEventDetail>(this.activeSections);
  }

  getChild(uid: string) {
    return this.widget.children.find(
      (section) => section.uid === uid,
    ) as Core.NonFunctionWidget<string>;
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

@let templateData = adapter.templateData();

<div class="gui-field" [id]="widget.uid">
  @for (section of templateData.sections; track section.uid) {
    <div class="gui-accordion__section">
      <button
        type="button"
        [id]="'accordion_button_' + section.uid"
        [attr.aria-controls]="'accordion_section_' + section.uid"
        [attr.aria-expanded]="activeSections[section.uid] ? 'true' : 'false'"
        [class.active]="activeSections[section.uid]"
        (click)="onClickButton(section.uid)"
      >
        {{ section.label }}<span class="gui-accordion__icon"></span>
      </button>

      @if (activeSections[section.uid] || templateData.renderMode !== 'activeOnly') {
        <section
          class="gui-field"
          role="region"
          [hidden]="!activeSections[section.uid] && templateData.renderMode !== 'activeOnly'"
          [id]="'accordion_section_' + section.uid"
          [attr.aria-labelledby]="'accordion_button_' + section.uid"
        >
          <ng-container guiWidget [widget]="getChild(section.uid)" />
        </section>
      }
    </div>
  }
</div>
