// apps/lit-playground/src/app/item-renderers/country.item-renderer.ts
import { html, TemplateResult } from 'lit';
import { classMap } from 'lit/directives/class-map.js';
import { ItemRenderContext } from '@golemui/core';

type CountryItem = {
  id: string;
  label: string;
  flag: string;
};

export const countryItemRenderer = (ctx: ItemRenderContext<CountryItem>): TemplateResult => {
  const classes = {
    'product-renderer': true,
    disabled: !!ctx.disabled,
    selected: !!ctx.selected,
    focused: !!ctx.focused,
    odd: ctx.index % 2 !== 0,
  };

  return html`
    <div class=${classMap(classes)}>
      <span>${ctx.template.label}</span>
      <span>${ctx.template.flag}</span>
    </div>
  `;
};

// apps/nextjs-playground/src/components/item-renderers/CountryItemRenderer.tsx
import React from 'react';
import { type ListItemRendererProps } from '@golemui/gui-react';
import './country-item-renderer.scss';
import { cn } from '@golemui/react';

type CountryItem = {
  id: string;
  label: string;
  flag: string;
};

export function CountryItemRenderer({
  template,
  index,
  selected,
  disabled,
  focused,
}: ListItemRendererProps<CountryItem>) {
  const classes = {
    'country-renderer': true,
    disabled: disabled,
    selected: selected,
    focused: focused,
    odd: index % 2 === 0,
  };

  return (
    <div className={cn(classes)}>
      <span>{template?.label}</span>
      <span>{template?.flag}</span>
    </div>
  );
}
