// libs/gui/vue/src/lib/components/MarkdownText.vue
<script setup lang="ts">
import type { DisplayWidget, WithWidget } from '@golemui/core';
import { useDisplayWidget } from '@golemui/vue';
import type { MarkdownTextProps } from '@golemui/gui-shared/internals';
import '@golemui/gui-components/markdown-text';

const props = defineProps<WithWidget>();
const widget = props.widget as DisplayWidget;
const { uid, templateData } = useDisplayWidget<MarkdownTextProps>(widget);
</script>

<template>
  <div class="gui-markdown-text gui-field" :style="{ flex: templateData.size }">
    <div class="gui-widget" :id="uid">
      <gui-markdown-text :md="templateData.md" :dependencies="templateData.deps" />
    </div>
  </div>
</template>

// libs/gui/angular/src/lib/components/markdown-text/markdown-text.component.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  inject,
  type OnDestroy,
  type OnInit,
} from '@angular/core';
import { DisplayWidgetAdapter } from '@golemui/angular';
import type { DisplayWidget, WithWidget } from '@golemui/core';
import type { MarkdownTextProps } from '@golemui/gui-shared/internals';
import '@golemui/gui-components/markdown-text';

@Component({
  standalone: true,
  selector: 'gui-markdown-text-display',
  imports: [CommonModule],
  providers: [DisplayWidgetAdapter],
  templateUrl: './markdown-text.component.html',
  host: {
    class: 'gui-markdown-text gui-field',
    '[style.flex]': 'this.adapter.templateData().size',
  },
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class MarkdownTextComponent implements OnInit, OnDestroy, WithWidget {
  widget!: DisplayWidget;

  protected adapter: DisplayWidgetAdapter<MarkdownTextProps> = inject(DisplayWidgetAdapter);

  ngOnInit(): void {
    this.adapter.init(this.widget);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

@let templateData = adapter.templateData();

<div class="gui-widget" [id]="widget.uid">
  <gui-markdown-text
    [attr.defer-hydration]="deferHydration"
    [md]="templateData.md"
    [dependencies]="templateData.deps"
  ></gui-markdown-text>
</div>
