// libs/angular-vanilla/src/lib/widget.loaders.ts
import { Type } from '@angular/core';
import * as Core from '@golemui/core';
import { VanillaWidget } from '@golemui/shared-vanilla';

export const vanillaWidgetLoaders: Core.WidgetLoaders<Type<Core.WithWidget>, VanillaWidget> = {
  // ACTION WIDGETS
  button: async () => (await import('./components/button/button.component')).ButtonComponent,

  // INPUT WIDGETS
  repeater: async () =>
    (await import('./components/repeater/repeater.component')).RepeaterComponent,
  textinput: async () =>
    (await import('./components/textinput/textinput.component')).TextinputComponent,
  password: async () =>
    (await import('./components/password/password.component')).PasswordComponent,
  currency: async () =>
    (await import('./components/currency/currency.component')).CurrencyComponent,
  textarea: async () =>
    (await import('./components/textarea/textarea.component')).TextareaComponent,
  calendar: async () =>
    (await import('./components/calendar/calendar.component')).CalendarComponent,
  rangeCalendar: async () =>
    (await import('./components/range-calendar/range-calendar.component')).RangeCalendarComponent,
  dateInput: async () => (await import('./components/date-input/date.component')).DateComponent,
  datePicker: async () =>
    (await import('./components/date-picker/date-picker.component')).DatePickerComponent,
  dropdown: async () =>
    (await import('./components/dropdown/dropdown.component')).DropdownComponent,
  toggle: async () => (await import('./components/toggle/toggle.component')).ToggleComponent,
  checkbox: async () =>
    (await import('./components/checkbox/checkbox.component')).CheckboxComponent,
  number: async () => (await import('./components/number/number.component')).NumberComponent,
  select: async () => (await import('./components/select/select.component')).SelectComponent,
  radiogroup: async () =>
    (await import('./components/radiogroup/radiogroup.component')).RadiogroupComponent,
  list: async () => (await import('./components/list/list.component')).ListComponent,

  // LAYOUT WIDGETS
  flex: async () => (await import('./components/flex/flex.component')).FlexComponent,
  tabs: async () => (await import('./components/tabs/tabs.component')).TabsComponent,
  accordion: async () =>
    (await import('./components/accordion/accordion.component')).AccordionComponent,

  // DISPLAY WIDGETS
  alert: async () => (await import('./components/alert/alert.component')).AlertComponent,
  renderer: async () =>
    (await import('./components/renderer/renderer.component')).RendererComponent,
};

// libs/react-vanilla/src/lib/widget.loaders.ts
import * as Core from '@golemui/core';
import { VanillaWidget } from '@golemui/shared-vanilla';

export const vanillaWidgetLoaders: Core.WidgetLoaders<
  React.ComponentType<Core.WithWidget>,
  VanillaWidget
> = {
  // INTERACTIVE
  button: async () => (await import('./components/Button')).Button,

  // CONTROLS
  calendar: async () => (await import('./components/Calendar')).Calendar,
  currency: async () => (await import('./components/Currency')).Currency,
  dateInput: async () => (await import('./components/DateInput')).DateInput,
  datePicker: async () => (await import('./components/DatePicker')).DatePicker,
  dropdown: async () => (await import('./components/Dropdown')).Dropdown,
  list: async () => (await import('./components/List')).List,
  password: async () => (await import('./components/Password')).Password,
  textinput: async () => (await import('./components/TextInput')).TextInput,
  textarea: async () => (await import('./components/TextArea')).TextArea,
  checkbox: async () => (await import('./components/Checkbox')).Checkbox,
  toggle: async () => (await import('./components/Toggle')).Toggle,
  number: async () => (await import('./components/Number')).NumberInput,
  select: async () => (await import('./components/Select')).Select,
  radiogroup: async () => (await import('./components/RadioGroup')).RadioGroup,
  rangeCalendar: async () => (await import('./components/RangeCalendar')).RangeCalendar,

  // REPEATER
  repeater: async () => (await import('./components/Repeater')).Repeater,

  // LAYOUTS
  flex: async () => (await import('./components/Flex')).Flex,
  tabs: async () => (await import('./components/Tabs')).Tabs,
  accordion: async () => (await import('./components/Accordion')).Accordion,

  // DISPLAY
  alert: async () => (await import('./components/Alert')).Alert,
  renderer: async () => (await import('./components/Renderer')).Renderer,
};
