// apps/lit-playground/src/app/item-renderers/complex-list.item-renderer.ts
import { html, TemplateResult } from 'lit';
import { classMap } from 'lit/directives/class-map.js';
import { ItemRenderContext } from '@golemui/core';

type ComplexItem = {
  title: string;
  description: string;
};

export const complexListItemRenderer = (ctx: ItemRenderContext<ComplexItem>): TemplateResult => {
  const classes = {
    'my-custom-class': true,
    disabled: !!ctx.disabled,
    selected: !!ctx.selected,
    focused: !!ctx.focused,
    odd: ctx.index % 2 !== 0,
  };

  return html`
    <div
      role="option"
      class=${classMap(classes)}
      aria-selected=${ctx.selected ? 'true' : 'false'}
      aria-disabled=${ctx.disabled ? 'true' : 'false'}
    >
      <h2>${ctx.template.title}</h2>
      <p>${ctx.template.description}</p>
    </div>
  `;
};

// apps/react-playground/src/app/item-renderers/ComplexListItemRenderer.tsx
import React from 'react';
import { ListItemRendererProps } from '@golemui/react-vanilla';
import './complex-list-item-renderer.scss';
import { cn } from '@golemui/react';

type ComplexItem = {
  title: string;
  description: string;
};

export function ComplexListItemRenderer({
  template,
  index,
  selected,
  disabled,
  focused,
}: ListItemRendererProps<ComplexItem>) {
  const classes = {
    'my-custom-class': true,
    disabled: disabled,
    selected: selected,
    focused: focused,
    odd: index % 2 === 0,
  };

  return (
    <div role="option" className={cn(classes)} aria-selected={selected} aria-disabled={disabled}>
      <h2>{template?.title}</h2>
      <p>{template?.description}</p>
    </div>
  );
}
