// libs/gui/angular/src/lib/components/accordion/accordion.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, type OnDestroy, type OnInit } from '@angular/core';
import { LayoutWidgetAdapter, WidgetDirective } from '@golemui/angular'
import type { LayoutWidget, NonFunctionWidget, WithWidget } from '@golemui/core'
import { type AccordionEventDetail } from '@golemui/gui-components';
import { type AccordionProps } from '@golemui/gui-shared';

@Component({
  standalone: true,
  selector: 'gui-accordion-layout',
  imports: [CommonModule, WidgetDirective],
  providers: [LayoutWidgetAdapter],
  templateUrl: './accordion.component.html',
  host: {
    class: 'gui-accordion gui-field',
    '[style.flex]': 'this.adapter.templateData().size',
  },
})
export class AccordionComponent implements OnInit, OnDestroy, WithWidget {
  widget!: LayoutWidget;
  activeSections: { [key: string]: boolean } = {};

  protected adapter: LayoutWidgetAdapter<AccordionProps> = inject(
    LayoutWidgetAdapter,
  );

  ngOnInit(): void {
    const props: AccordionProps = this.widget.props as AccordionProps;
    this.adapter.init(this.widget);
    this.activeSections = props.defaultOpen ?? {};
  }

  onClickButton(uid: string) {
    const props: AccordionProps = this.widget.props as AccordionProps;
    if (props.singleOpen) {
      Object.keys(this.activeSections)
        .filter((sectionUid) => sectionUid !== uid)
        .forEach((key) => {
          this.activeSections[key] = false;
        });
    }

    this.activeSections[uid] = !this.activeSections[uid];

    this.adapter.change<AccordionEventDetail>(this.activeSections);
  }

  getChild(uid: string) {
    return this.widget.children.find(
      (section) => section.uid === uid,
    ) as NonFunctionWidget<string>;
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

@let templateData = adapter.templateData();

<div class="gui-widget" [id]="widget.uid">
  @for (section of templateData.sections; track section.uid) {
    <div class="gui-accordion__section">
      <button
        type="button"
        tabindex="0"
        [id]="'accordion_button_' + section.uid"
        [attr.aria-controls]="'accordion_section_' + section.uid"
        [attr.aria-expanded]="activeSections[section.uid] ? 'true' : 'false'"
        [class.active]="activeSections[section.uid]"
        (click)="onClickButton(section.uid)"
      >
        {{ section.label
        }}<span class="gui-accordion__arrow"
          ><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 256 256">
            <path
              d="M213.66,101.66l-80,80a8,8,0,0,1-11.32,0l-80-80A8,8,0,0,1,53.66,90.34L128,164.69l74.34-74.35a8,8,0,0,1,11.32,11.32Z"
            ></path></svg
        ></span>
      </button>

      @let child = getChild(section.uid);
      @if (child && (activeSections[section.uid] || templateData.renderMode !== 'activeOnly')) {
        <section
          class="gui-widget"
          role="region"
          [hidden]="!activeSections[section.uid] && templateData.renderMode !== 'activeOnly'"
          [id]="'accordion_section_' + section.uid"
          [attr.aria-labelledby]="'accordion_button_' + section.uid"
        >
          <ng-container guiWidget [widget]="child" />
        </section>
      }
    </div>
  }
</div>

// libs/gui/react/src/lib/components/Accordion.tsx
import type { LayoutWidget, NonFunctionWidget, WithWidget } from '@golemui/core';
import { useLayoutWidget, WidgetRenderer } from '@golemui/react';
import { type AccordionProps } from '@golemui/gui-shared';
import { useCallback, useEffect, useState } from 'react';

const empty = {};

export function Accordion(widgetInstance: WithWidget) {
  const widget = widgetInstance.widget as LayoutWidget;
  const { uid, children, templateData, onChange } = useLayoutWidget<AccordionProps>(widget);
  const [activeSections, setActiveSections] =
    useState<NonNullable<AccordionProps['defaultOpen']>>(empty);

  useEffect(() => {
    if (activeSections === empty && templateData.defaultOpen) {
      setActiveSections(templateData.defaultOpen || {});
    }
  }, [activeSections, templateData]);

  const onClickButton = useCallback(
    (uid: string) => {
      const newState: typeof activeSections = { ...activeSections };

      if (templateData.singleOpen) {
        Object.keys(newState)
          .filter((sectionUid) => sectionUid !== uid)
          .forEach((sectionUid) => {
            newState[sectionUid] = sectionUid === uid ? !newState[sectionUid] : false;
          });
      }

      newState[uid] = !newState[uid];

      setActiveSections(newState);
      onChange(newState);
    },
    [activeSections, templateData.singleOpen, onChange],
  );

  const renderContent = useCallback(
    (uid: string) => {
      const child = children.find((section) => section.uid === uid) as NonFunctionWidget<string>;
      const isActiveSection = activeSections[uid];
      return (isActiveSection || templateData.renderMode !== 'activeOnly') && child ? (
        <section
          className="gui-widget"
          role="region"
          id={`accordion_section_${uid}`}
          hidden={!isActiveSection && templateData.renderMode !== 'activeOnly'}
          aria-labelledby={`accordion_button_${uid}`}
        >
          <WidgetRenderer widget={child} />
        </section>
      ) : null;
    },
    [children, activeSections, templateData.renderMode],
  );

  const renderAccordion = useCallback(() => {
    const sections = templateData.sections || [];
    return sections.map((section, index) => (
      <div className="gui-accordion__section" key={`${'accordion_section_' + section.uid}`}>
        <button
          type="button"
          tabIndex={0}
          id={`accordion_button_${section.uid}`}
          aria-controls={`accordion_section_${section.uid}`}
          aria-expanded={activeSections[section.uid] ? 'true' : 'false'}
          className={activeSections[section.uid] ? 'active' : ''}
          onClick={() => onClickButton(section.uid)}
        >
          {section.label as string}
          <span className="gui-accordion__arrow">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 256 256">
              <path d="M213.66,101.66l-80,80a8,8,0,0,1-11.32,0l-80-80A8,8,0,0,1,53.66,90.34L128,164.69l74.34-74.35a8,8,0,0,1,11.32,11.32Z"></path>
            </svg>
          </span>
        </button>

        {renderContent(section.uid)}
      </div>
    ));
  }, [templateData.sections, activeSections, renderContent, onClickButton]);

  return (
    <div className="gui-accordion gui-field" style={{ flex: templateData.size }}>
      <div className="gui-widget" id={uid}>
        {renderAccordion()}
      </div>
    </div>
  );
}
