// libs/gui/angular/src/lib/components/date-time-calendar/date-time-calendar.component.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  inject,
  type OnDestroy,
  type OnInit,
} from '@angular/core';
import { InputWidgetAdapter } from '@golemui/angular';
import type { InputWidget, WithWidget } from '@golemui/core';
import type { DateTimeCalendarProps } from '@golemui/gui-shared/internals';
import '@golemui/gui-components/date-time-calendar';

@Component({
  standalone: true,
  selector: 'gui-date-time-calendar-control',
  imports: [CommonModule],
  providers: [InputWidgetAdapter],
  templateUrl: './date-time-calendar.component.html',
  host: {
    class: 'gui-date-time-calendar gui-field',
    '[style.flex]': 'this.adapter.templateData().size',
  },
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class DateTimeCalendarComponent implements OnInit, OnDestroy, WithWidget {
  widget!: InputWidget<string>;
  protected adapter: InputWidgetAdapter<string, DateTimeCalendarProps> =
    inject(InputWidgetAdapter);

  ngOnInit(): void {
    this.adapter.init(this.widget);
  }

  protected onChangeValue(event: Event) {
    this.adapter.injectValidationIssues(null);
    this.adapter.valueChanged((event as CustomEvent).detail.value);
  }

  protected onInputError(event: Event) {
    this.adapter.injectValidationIssues([(event as CustomEvent).detail.message]);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

@let templateData = adapter.templateData();

<gui-date-time-calendar
  [uid]="widget.uid"
  [label]="templateData.label"
  [hint]="templateData.hint"
  [errors]="templateData.errors"
  [touched]="templateData.touched"
  [required]="templateData.validator?.required"
  [disabled]="templateData.disabled"
  [readonly]="templateData.readonly"
  [value]="templateData.value"
  [prevMonthIcon]="templateData.prevMonthIcon"
  [nextMonthIcon]="templateData.nextMonthIcon"
  [prevMonthAriaLabel]="templateData.prevMonthAriaLabel"
  [nextMonthAriaLabel]="templateData.nextMonthAriaLabel"
  [dayFormat]="templateData.dayFormat"
  [weekdayFormat]="templateData.weekdayFormat"
  [monthFormat]="templateData.monthFormat"
  [minDate]="templateData.minDate"
  [maxDate]="templateData.maxDate"
  [disabledRanges]="templateData.disabledRanges"
  [numberOfMonths]="templateData.numberOfMonths"
  [localeId]="templateData.lang"
  [hourFormat]="templateData.hourFormat"
  [minuteStep]="templateData.minuteStep"
  [minTime]="templateData.minTime"
  [maxTime]="templateData.maxTime"
  [disabledTimeRanges]="templateData.disabledTimeRanges"
  [allowCustomTime]="templateData.allowCustomTime"
  [minTimeMessage]="templateData.minTimeMessage"
  [maxTimeMessage]="templateData.maxTimeMessage"
  [disabledTimeRangeMessage]="templateData.disabledTimeRangeMessage"
  [noAvailableTimesMessage]="templateData.noAvailableTimesMessage"
  (change)="onChangeValue($event)"
  (inputError)="onInputError($event)"
  (blur)="adapter.onBlur()"
></gui-date-time-calendar>

// libs/gui/react/src/lib/components/DateTimeCalendar.tsx
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/react';
import type { DateTimeCalendarProps } from '@golemui/gui-shared/internals';
import { useCallback } from 'react';
import { GuiDateTimeCalendarReact } from '../web-components';
import '../styles.scss';

export function DateTimeCalendar(widgetInstance: WithWidget) {
  const widget = widgetInstance.widget as InputWidget<string>;
  const {
    uid,
    errors,
    value,
    isTouched,
    templateData,
    onBlur,
    onValueChanged,
    injectValidationIssues,
  } = useInputWidget<string, DateTimeCalendarProps>(widget);

  const handleChange = useCallback(
    (e: Event) => {
      injectValidationIssues(null);
      onValueChanged((e as CustomEvent).detail.value);
    },
    [injectValidationIssues, onValueChanged],
  );

  const handleInputError = useCallback(
    (e: Event) => {
      injectValidationIssues([(e as CustomEvent).detail.message]);
    },
    [injectValidationIssues],
  );

  const isRequired = (templateData.validator as Validator)?.required;

  return (
    <div className="gui-date-time-calendar gui-field" style={{ flex: templateData.size }}>
      <GuiDateTimeCalendarReact
        uid={uid}
        label={templateData.label as string}
        hint={templateData.hint}
        errors={errors}
        touched={isTouched}
        required={isRequired}
        disabled={templateData.disabled as boolean}
        readOnly={templateData.readonly as boolean}
        value={value}
        prevMonthIcon={templateData.prevMonthIcon}
        nextMonthIcon={templateData.nextMonthIcon}
        prevMonthAriaLabel={templateData.prevMonthAriaLabel}
        nextMonthAriaLabel={templateData.nextMonthAriaLabel}
        dayFormat={templateData.dayFormat}
        weekdayFormat={templateData.weekdayFormat}
        monthFormat={templateData.monthFormat}
        minDate={templateData.minDate}
        maxDate={templateData.maxDate}
        disabledRanges={templateData.disabledRanges}
        numberOfMonths={templateData.numberOfMonths}
        localeId={templateData.lang}
        hourFormat={templateData.hourFormat}
        minuteStep={templateData.minuteStep}
        minTime={templateData.minTime}
        maxTime={templateData.maxTime}
        disabledTimeRanges={templateData.disabledTimeRanges}
        allowCustomTime={templateData.allowCustomTime}
        minTimeMessage={templateData.minTimeMessage as string}
        maxTimeMessage={templateData.maxTimeMessage as string}
        disabledTimeRangeMessage={templateData.disabledTimeRangeMessage as string}
        noAvailableTimesMessage={templateData.noAvailableTimesMessage as string}
        onChange={handleChange}
        onBlur={onBlur}
        onInputError={handleInputError}
      />
    </div>
  );
}
