// libs/gui/vue/src/lib/components/Form.vue
<script setup lang="ts">
import type {
  FormEvent,
  FormHealth,
  FormInitConfig,
  WidgetLoaders,
  WithWidget,
} from '@golemui/core';
import { resolveFormInput } from '@golemui/gui-shared/internals';
import { initValidators } from '@golemui/gui-validators';
import { FormComponent, type FormComponentHandle, type VueItemRenderer } from '@golemui/vue';
import { computed, ref, type Component } from 'vue';
import { widgetLoaders as golemWidgetLoaders } from '../widget.loaders';
import type { GuiFormEmits, GuiFormHandle, GuiFormProps } from './Form.types';

const props = defineProps<GuiFormProps>();
const emit = defineEmits<GuiFormEmits>();

const formRef = ref<FormComponentHandle | null>(null);

const resolved = computed(() =>
  resolveFormInput(props.config.formDef, props.config.formSelectors, props.config.formConfig),
);

const coreConfig = computed<FormInitConfig<Component<WithWidget>>>(() => {
  const r = resolved.value;
  return {
    formDef: r.formDef as string | Record<string, any>,
    widgetLoaders: {
      ...golemWidgetLoaders,
      ...(r.widgetLoaders as WidgetLoaders<Component<WithWidget>>),
      ...((props.config.customWidgetLoaders ?? {}) as WidgetLoaders<Component<WithWidget>>),
    },
    dependencies: { ...(r.dependencies ?? {}), ...(props.config.dependencies ?? {}) },
    validateOn: props.config.validateOn ?? r.validateOn ?? 'eager',
    itemRenderers: {
      ...((r.itemRenderers ?? {}) as Record<string, VueItemRenderer<any>>),
      ...((props.config.itemRenderers ?? {}) as Record<string, VueItemRenderer<any>>),
    },
    localization: props.config.localization,
    middlewares: props.config.middlewares ?? [],
    data: props.config.data,
    meta: props.config.meta,
    formName: props.config.formName,
  };
});

const allValidators = computed(() => initValidators({ ...(props.config.customValidators ?? {}) }));

const onInnerFormEvent = (event: FormEvent) => {
  resolved.value.formEvent?.(event);
  emit('form-event', event);
};

const onInnerFormHealth = (health: FormHealth) => emit('form-health', health);

defineExpose<GuiFormHandle>({
  setData: (data) => formRef.value?.setData(data),
  setMeta: (meta) => formRef.value?.setMeta(meta),
});
</script>

<template>
  <FormComponent
    ref="formRef"
    :config="coreConfig"
    :validators="allValidators"
    :autocomplete="autocomplete"
    @form-event="onInnerFormEvent"
    @form-health="onInnerFormHealth"
  />
</template>

// libs/gui/react/src/lib/components/Form.tsx
import type { FormEvent, FormHealth, WidgetLoaders, WithWidget } from '@golemui/core';
import { type FormInitConfig } from '@golemui/core';
import { type GuiFormInitConfig } from '@golemui/gui-shared';
import { resolveFormInput } from '@golemui/gui-shared/internals';
import { initValidators } from '@golemui/gui-validators';
import { FormComponent, type FormComponentHandle, type ReactItemRenderer } from '@golemui/react';
import { type ComponentType, type Ref, useMemo } from 'react';
import { widgetLoaders as golemWidgetLoaders } from '../widget.loaders';

export interface ReactFormComponentProps {
  config: GuiFormInitConfig;
  autocomplete?: string;
  formEvent?: (event: FormEvent) => void;
  formHealth?: (formHealth: FormHealth) => void;
  ref?: Ref<FormComponentHandle>;
}

export function GuiForm({
  config,
  formHealth = undefined,
  formEvent = undefined,
  autocomplete,
  ref,
}: ReactFormComponentProps) {
  const resolved = useMemo(
    () => resolveFormInput(config.formDef, config.formSelectors, config.formConfig),
    [config],
  );

  const coreConfig: FormInitConfig<ComponentType<WithWidget>> = {
    formDef: resolved.formDef as string | Record<string, any>,
    widgetLoaders: {
      ...golemWidgetLoaders,
      ...(resolved.widgetLoaders as WidgetLoaders<ComponentType<WithWidget>>),
      ...((config.customWidgetLoaders ?? {}) as WidgetLoaders<ComponentType<WithWidget>>),
    },
    dependencies: { ...(resolved.dependencies ?? {}), ...(config.dependencies ?? {}) },
    validateOn: config.validateOn ?? resolved.validateOn ?? 'eager',
    itemRenderers: {
      ...((resolved.itemRenderers ?? {}) as Record<string, ReactItemRenderer<any>>),
      ...((config.itemRenderers ?? {}) as Record<string, ReactItemRenderer<any>>),
    },
    localization: config.localization,
    middlewares: config.middlewares ?? [],
    data: config.data,
    meta: config.meta,
    formName: config.formName,
  };

  const allValidators = initValidators({ ...(config.customValidators ?? {}) });

  // Chain DX-registered event handlers with the user-supplied callback so both fire.
  const mergedFormEvent =
    resolved.formEvent && formEvent
      ? (event: FormEvent) => {
          resolved.formEvent?.(event);
          formEvent(event);
        }
      : (formEvent ?? resolved.formEvent);

  return (
    <FormComponent
      ref={ref}
      config={coreConfig}
      validators={allValidators}
      autocomplete={autocomplete}
      formHealth={formHealth}
      formEvent={mergedFormEvent}
    />
  );
}
