// libs/gui/vue/src/lib/components/Markdown.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/vue';
import type { MarkdownProps } from '@golemui/gui-shared';
import { computed } from 'vue';
import '@golemui/gui-components/markdown';

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<string>;
const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useInputWidget<
  string,
  MarkdownProps
>(widget);

const handleInput = (e: Event) => onValueChanged((e as CustomEvent).detail.value);
const required = computed(() => (templateData.value.validator as Validator)?.required);
const maxLength = computed(() => (templateData.value.validator as Validator)?.maxLength);
// Mirror Lit element's internal `?? 'remaining'` / `?? 120` fallbacks so an
// empty string from Vue→Lit attribute coercion can't slip past the `??` operator.
const counterMode = computed(() => templateData.value.counterMode || 'remaining');
const minimumHeight = computed(() => templateData.value.minimumHeight ?? 120);
</script>

<template>
  <div class="gui-markdown gui-field" :style="{ flex: templateData.size }">
    <gui-markdown
      :uid="uid"
      :label="templateData.label"
      :errors="errors"
      :touched="isTouched"
      :required="required"
      :disabled="templateData.disabled"
      :readOnly="templateData.readonly"
      :value="value"
      :hint="templateData.hint"
      :placeholder="templateData.placeholder"
      :autocomplete="templateData.autocomplete ?? undefined"
      :counterMode.prop="counterMode"
      :minimumHeight.prop="minimumHeight"
      :autoGrow="templateData.autoGrow"
      :maxLength="maxLength"
      :tools="templateData.tools"
      :defaultOpenPreview="templateData.defaultOpenPreview"
      :headingTitle="templateData.headingTitle"
      :boldTitle="templateData.boldTitle"
      :italicTitle="templateData.italicTitle"
      :strikethroughTitle="templateData.strikethroughTitle"
      :quoteTitle="templateData.quoteTitle"
      :linkTitle="templateData.linkTitle"
      :orderedListTitle="templateData.orderedListTitle"
      :unorderedListTitle="templateData.unorderedListTitle"
      :splitViewTitle="templateData.splitViewTitle"
      :dependencies="templateData.deps"
      @input="handleInput"
      @blur="onBlur"
    ></gui-markdown>
  </div>
</template>

// libs/gui/react/src/lib/components/Markdown.tsx
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/react';
import { type MarkdownProps } from '@golemui/gui-shared';
import { useCallback } from 'react';
import { GuiMarkdownReact } from '../web-components';
import '../styles.scss';


export function Markdown(widgetInstance: WithWidget) {
  const widget = widgetInstance.widget as InputWidget<string>;
  const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useInputWidget<
    string,
    MarkdownProps
  >(widget);

  const handleChange = useCallback(
    (e: Event) => onValueChanged((e as CustomEvent).detail.value),
    [onValueChanged],
  );

  const label = templateData.label as string;
  const hint = templateData.hint;
  const placeholder = templateData.placeholder;
  const autocomplete = templateData.autocomplete;
  const maxLength = (templateData.validator as Validator)?.maxLength;
  const counterMode = templateData.counterMode;
  const autoGrow = templateData.autoGrow;
  const minimumHeight = templateData.minimumHeight;
  const tools = templateData.tools;
  const defaultOpenPreview = templateData.defaultOpenPreview;
  const headingTitle = templateData.headingTitle;
  const boldTitle = templateData.boldTitle;
  const italicTitle = templateData.italicTitle;
  const strikethroughTitle = templateData.strikethroughTitle;
  const quoteTitle = templateData.quoteTitle;
  const linkTitle = templateData.linkTitle;
  const orderedListTitle = templateData.orderedListTitle;
  const unorderedListTitle = templateData.unorderedListTitle;
  const splitViewTitle = templateData.splitViewTitle;
  const isDisabled = templateData.disabled as boolean;
  const isReadonly = templateData.readonly as boolean;
  const isRequired = (templateData.validator as Validator)?.required;

  return (
    <div className="gui-markdown gui-field" style={{ flex: templateData.size }}>
      <GuiMarkdownReact
        uid={uid}
        label={label}
        errors={errors}
        touched={isTouched}
        required={isRequired}
        disabled={isDisabled}
        readOnly={isReadonly}
        value={value}
        hint={hint}
        placeholder={placeholder}
        autocomplete={autocomplete ?? undefined}
        counterMode={counterMode}
        minimumHeight={minimumHeight}
        autoGrow={autoGrow}
        maxLength={maxLength}
        tools={tools}
        defaultOpenPreview={defaultOpenPreview}
        headingTitle={headingTitle}
        boldTitle={boldTitle}
        italicTitle={italicTitle}
        strikethroughTitle={strikethroughTitle}
        quoteTitle={quoteTitle}
        linkTitle={linkTitle}
        orderedListTitle={orderedListTitle}
        unorderedListTitle={unorderedListTitle}
        splitViewTitle={splitViewTitle}
        dependencies={templateData.deps}
        onInput={handleChange}
        onBlur={onBlur}
      ></GuiMarkdownReact>
    </div>
  );
}
