// libs/gui/vue/src/lib/components/RangeTimePicker.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/vue';
import type { TimeRange, RangeTimePickerProps } from '@golemui/gui-shared/internals';
import { computed, onUnmounted, ref, watch } from 'vue';
import '@golemui/gui-components/range-time-picker';

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<TimeRange[]>;
const {
  uid,
  errors,
  value,
  isTouched,
  templateData,
  onValueChanged,
  onBlur,
  injectValidationIssues,
} = useInputWidget<TimeRange[], RangeTimePickerProps>(widget);

const required = computed(() => (templateData.value.validator as Validator)?.required);

const pickerRef = ref<HTMLElement | null>(null);
const changeHandler = (e: Event) => {
  injectValidationIssues(null);
  onValueChanged((e as CustomEvent).detail.value);
};
const errorHandler = (e: Event) => {
  injectValidationIssues([(e as CustomEvent).detail.message]);
};

let currentEl: HTMLElement | null = null;
watch(pickerRef, (el) => {
  if (currentEl) {
    currentEl.removeEventListener('gui-input', changeHandler);
    currentEl.removeEventListener('gui-input-error', errorHandler);
    currentEl.removeEventListener('gui-blur', onBlur);
  }
  currentEl = el;
  if (el) {
    el.addEventListener('gui-input', changeHandler);
    el.addEventListener('gui-input-error', errorHandler);
    el.addEventListener('gui-blur', onBlur);
  }
});

onUnmounted(() => {
  currentEl?.removeEventListener('gui-input', changeHandler);
  currentEl?.removeEventListener('gui-input-error', errorHandler);
  currentEl?.removeEventListener('gui-blur', onBlur);
});
</script>

<template>
  <div class="gui-range-time-picker gui-field" :style="{ flex: templateData.size }">
    <gui-range-time-picker
      ref="pickerRef"
      :uid="uid"
      :label="templateData.label"
      :hint="templateData.hint"
      :errors="errors"
      :touched="isTouched"
      :required="required"
      :disabled="templateData.disabled"
      :readOnly="templateData.readonly"
      :value.prop="value"
      :icon="templateData.icon"
      :localeId="templateData.lang"
      :toggleAriaLabel="templateData.toggleAriaLabel"
      :hourAriaLabel="templateData.hourAriaLabel"
      :minuteAriaLabel="templateData.minuteAriaLabel"
      :dayPeriodAriaLabel="templateData.dayPeriodAriaLabel"
      :separator="templateData.separator"
      :removePillAriaLabel="templateData.removePillAriaLabel"
      :startTimeAriaLabel="templateData.startTimeAriaLabel"
      :endTimeAriaLabel="templateData.endTimeAriaLabel"
      :startTimeLabel="templateData.startTimeLabel"
      :endTimeLabel="templateData.endTimeLabel"
      :hourFormat="templateData.hourFormat"
      :minuteStep="templateData.minuteStep"
      :minTime="templateData.minTime"
      :maxTime="templateData.maxTime"
      :disabledRanges.prop="templateData.disabledRanges"
      :allowCustomTime="templateData.allowCustomTime"
      :height="templateData.height"
      :itemHeight="templateData.itemHeight"
      :minTimeMessage="templateData.minTimeMessage"
      :maxTimeMessage="templateData.maxTimeMessage"
      :rangeOrderMessage="templateData.rangeOrderMessage"
      :disabledRangeMessage="templateData.disabledRangeMessage"
      :noAvailableTimesMessage="templateData.noAvailableTimesMessage"
      :incompleteMessage="templateData.incompleteMessage"
      :allowEdit="templateData.allowEdit"
      :editLabel="templateData.editLabel"
      :editAriaLabel="templateData.editAriaLabel"
      :confirmEditLabel="templateData.confirmEditLabel"
      :cancelEditLabel="templateData.cancelEditLabel"
      :editStartedMessage="templateData.editStartedMessage"
      :editCommittedMessage="templateData.editCommittedMessage"
      :editCancelledMessage="templateData.editCancelledMessage"
    />
  </div>
</template>

// libs/gui/react/src/lib/components/RangeTimePicker.tsx
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/react';
import type { TimeRange, RangeTimePickerProps } from '@golemui/gui-shared/internals';
import { useCallback } from 'react';
import '../styles.scss';
import { GuiRangeTimePickerReact } from '../web-components';

export function RangeTimePicker(widgetInstance: WithWidget) {
  const widget = widgetInstance.widget as InputWidget<TimeRange[]>;
  const {
    uid,
    errors,
    value,
    isTouched,
    templateData,
    onValueChanged,
    onBlur,
    injectValidationIssues,
  } = useInputWidget<TimeRange[], RangeTimePickerProps>(widget);

  const handleChange = useCallback(
    (e: Event) => {
      injectValidationIssues(null);
      onValueChanged((e as CustomEvent).detail.value);
    },
    [injectValidationIssues, onValueChanged],
  );

  const handleInputError = useCallback(
    (e: Event) => {
      injectValidationIssues([(e as CustomEvent).detail.message]);
    },
    [injectValidationIssues],
  );

  const isRequired = (templateData.validator as Validator)?.required;

  return (
    <div className="gui-range-time-picker gui-field" style={{ flex: templateData.size }}>
      <GuiRangeTimePickerReact
        uid={uid}
        label={templateData.label as string}
        hint={templateData.hint}
        errors={errors}
        touched={isTouched}
        required={isRequired}
        disabled={templateData.disabled as boolean}
        readOnly={templateData.readonly as boolean}
        value={value}
        icon={templateData.icon}
        localeId={templateData.lang}
        toggleAriaLabel={templateData.toggleAriaLabel}
        hourAriaLabel={templateData.hourAriaLabel}
        minuteAriaLabel={templateData.minuteAriaLabel}
        dayPeriodAriaLabel={templateData.dayPeriodAriaLabel}
        separator={templateData.separator}
        removePillAriaLabel={templateData.removePillAriaLabel}
        startTimeAriaLabel={templateData.startTimeAriaLabel}
        endTimeAriaLabel={templateData.endTimeAriaLabel}
        startTimeLabel={templateData.startTimeLabel as string}
        endTimeLabel={templateData.endTimeLabel as string}
        hourFormat={templateData.hourFormat}
        minuteStep={templateData.minuteStep}
        minTime={templateData.minTime}
        maxTime={templateData.maxTime}
        disabledRanges={templateData.disabledRanges}
        allowCustomTime={templateData.allowCustomTime}
        height={templateData.height}
        itemHeight={templateData.itemHeight}
        minTimeMessage={templateData.minTimeMessage as string}
        maxTimeMessage={templateData.maxTimeMessage as string}
        rangeOrderMessage={templateData.rangeOrderMessage as string}
        disabledRangeMessage={templateData.disabledRangeMessage as string}
        noAvailableTimesMessage={templateData.noAvailableTimesMessage as string}
        incompleteMessage={templateData.incompleteMessage as string}
        allowEdit={templateData.allowEdit}
        editLabel={templateData.editLabel as string}
        editAriaLabel={templateData.editAriaLabel as string}
        confirmEditLabel={templateData.confirmEditLabel as string}
        cancelEditLabel={templateData.cancelEditLabel as string}
        editStartedMessage={templateData.editStartedMessage as string}
        editCommittedMessage={templateData.editCommittedMessage as string}
        editCancelledMessage={templateData.editCancelledMessage as string}
        onChange={handleChange}
        onBlur={onBlur}
        onInputError={handleInputError}
      />
    </div>
  );
}
