// libs/gui/vue/src/lib/components/RangeTimeInput.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/vue';
import type { TimeRange, RangeTimeInputProps } from '@golemui/gui-shared/internals';
import { computed, onUnmounted, ref, watch } from 'vue';
import '@golemui/gui-components/range-time-input';

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<TimeRange[]>;
const {
  uid,
  errors,
  value,
  isTouched,
  templateData,
  onValueChanged,
  onBlur,
  injectValidationIssues,
} = useInputWidget<TimeRange[], RangeTimeInputProps>(widget);

const required = computed(() => (templateData.value.validator as Validator)?.required);

const elRef = ref<HTMLElement | null>(null);
const changeHandler = (e: Event) => {
  injectValidationIssues(null);
  onValueChanged((e as CustomEvent).detail.value);
};
const blurHandler = () => onBlur();
const errorHandler = (e: Event) => {
  injectValidationIssues([(e as CustomEvent).detail.message]);
};

let currentEl: HTMLElement | null = null;
watch(elRef, (el) => {
  if (currentEl) {
    currentEl.removeEventListener('blur', blurHandler);
    currentEl.removeEventListener('change', changeHandler);
    currentEl.removeEventListener('inputError', errorHandler);
  }
  currentEl = el;
  if (el) {
    el.addEventListener('blur', blurHandler);
    el.addEventListener('change', changeHandler);
    el.addEventListener('inputError', errorHandler);
  }
});

onUnmounted(() => {
  currentEl?.removeEventListener('blur', blurHandler);
  currentEl?.removeEventListener('change', changeHandler);
  currentEl?.removeEventListener('inputError', errorHandler);
});
</script>

<template>
  <div class="gui-range-time-input gui-field" :style="{ flex: templateData.size }">
    <gui-range-time
      ref="elRef"
      :uid="uid"
      :label="templateData.label"
      :hint="templateData.hint"
      :errors="errors"
      :touched="isTouched"
      :required="required"
      :disabled="templateData.disabled"
      :readOnly="templateData.readonly"
      :value="value"
      :icon="templateData.icon"
      :localeId="templateData.lang"
      :hourAriaLabel="templateData.hourAriaLabel"
      :minuteAriaLabel="templateData.minuteAriaLabel"
      :dayPeriodAriaLabel="templateData.dayPeriodAriaLabel"
      :separator="templateData.separator"
      :removePillAriaLabel="templateData.removePillAriaLabel"
      :startTimeAriaLabel="templateData.startTimeAriaLabel"
      :endTimeAriaLabel="templateData.endTimeAriaLabel"
      :hourFormat="templateData.hourFormat"
      :minuteStep="templateData.minuteStep"
      :minTime="templateData.minTime"
      :maxTime="templateData.maxTime"
      :minTimeMessage="templateData.minTimeMessage"
      :maxTimeMessage="templateData.maxTimeMessage"
      :rangeOrderMessage="templateData.rangeOrderMessage"
      :incompleteMessage="templateData.incompleteMessage"
      :allowEdit="templateData.allowEdit"
      :editLabel="templateData.editLabel"
      :editAriaLabel="templateData.editAriaLabel"
      :confirmEditLabel="templateData.confirmEditLabel"
      :cancelEditLabel="templateData.cancelEditLabel"
      :editStartedMessage="templateData.editStartedMessage"
      :editCommittedMessage="templateData.editCommittedMessage"
      :editCancelledMessage="templateData.editCancelledMessage"
    />
  </div>
</template>

// libs/gui/react/src/lib/components/RangeTimeInput.tsx
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/react';
import type { TimeRange, RangeTimeInputProps } from '@golemui/gui-shared/internals';
import { useCallback } from 'react';
import { GuiRangeTimeReact } from '../web-components';
import '../styles.scss';

export function RangeTimeInput(widgetInstance: WithWidget) {
  const widget = widgetInstance.widget as InputWidget<TimeRange[]>;
  const {
    uid,
    errors,
    value,
    isTouched,
    templateData,
    onBlur,
    onValueChanged,
    injectValidationIssues,
  } = useInputWidget<TimeRange[], RangeTimeInputProps>(widget);

  const handleRef = useCallback(
    (node: HTMLElement | null) => {
      const target = node as any;
      const changeHandler = (e: CustomEvent) => {
        injectValidationIssues(null);
        onValueChanged(e.detail.value);
      };
      const blurHandler = () => {
        onBlur();
      };
      const errorHandler = (e: CustomEvent) => {
        injectValidationIssues([e.detail.message]);
      };

      if (node) {
        target.addEventListener('blur', blurHandler);
        target.addEventListener('change', changeHandler);
        target.addEventListener('inputError', errorHandler);
      }

      return () => {
        target.removeEventListener('blur', blurHandler);
        target.removeEventListener('change', changeHandler);
        target.removeEventListener('inputError', errorHandler);
      };
    },
    [onValueChanged, onBlur, injectValidationIssues],
  );

  const label = templateData.label as string;
  const hint = templateData.hint;
  const icon = templateData.icon;
  const lang = templateData.lang;
  const separator = templateData.separator;
  const removePillAriaLabel = templateData.removePillAriaLabel;
  const startTimeAriaLabel = templateData.startTimeAriaLabel;
  const endTimeAriaLabel = templateData.endTimeAriaLabel;
  const isDisabled = templateData.disabled as boolean;
  const isReadonly = templateData.readonly as boolean;
  const isRequired = (templateData.validator as Validator)?.required;

  return (
    <div className="gui-range-time-input gui-field" style={{ flex: templateData.size }}>
      <GuiRangeTimeReact
        ref={handleRef}
        uid={uid}
        label={label}
        hint={hint}
        errors={errors}
        touched={isTouched}
        required={isRequired}
        disabled={isDisabled}
        readOnly={isReadonly}
        value={value}
        icon={icon}
        localeId={lang}
        hourAriaLabel={templateData.hourAriaLabel}
        minuteAriaLabel={templateData.minuteAriaLabel}
        dayPeriodAriaLabel={templateData.dayPeriodAriaLabel}
        separator={separator}
        removePillAriaLabel={removePillAriaLabel}
        startTimeAriaLabel={startTimeAriaLabel}
        endTimeAriaLabel={endTimeAriaLabel}
        hourFormat={templateData.hourFormat}
        minuteStep={templateData.minuteStep}
        minTime={templateData.minTime}
        maxTime={templateData.maxTime}
        minTimeMessage={templateData.minTimeMessage as string}
        maxTimeMessage={templateData.maxTimeMessage as string}
        rangeOrderMessage={templateData.rangeOrderMessage as string}
        incompleteMessage={templateData.incompleteMessage as string}
        allowEdit={templateData.allowEdit}
        editLabel={templateData.editLabel as string}
        editAriaLabel={templateData.editAriaLabel as string}
        confirmEditLabel={templateData.confirmEditLabel as string}
        cancelEditLabel={templateData.cancelEditLabel as string}
        editStartedMessage={templateData.editStartedMessage as string}
        editCommittedMessage={templateData.editCommittedMessage as string}
        editCancelledMessage={templateData.editCancelledMessage as string}
      />
    </div>
  );
}
