// libs/gui/angular/src/lib/components/range-calendar/range-calendar.component.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  inject,
  type OnDestroy,
  type OnInit,
} from '@angular/core';
import { InputWidgetAdapter } from '@golemui/angular';
import type { InputWidget, WithWidget } from '@golemui/core';
import type { RangeCalendarProps } from '@golemui/gui-shared/internals';
import '@golemui/gui-components/range-calendar';
import { deferHydrationAttr } from '../../utils/defer-hydration';

@Component({
  standalone: true,
  selector: 'gui-range-calendar-control',
  imports: [CommonModule],
  providers: [InputWidgetAdapter],
  templateUrl: './range-calendar.component.html',
  host: {
    class: 'gui-range-calendar gui-field',
    '[style.flex]': 'this.adapter.templateData().size',
  },
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class RangeCalendarComponent implements OnInit, OnDestroy, WithWidget {
  widget!: InputWidget<string>;
  protected adapter: InputWidgetAdapter<string, RangeCalendarProps> = inject(InputWidgetAdapter);
  protected readonly deferHydration = deferHydrationAttr();

  ngOnInit(): void {
    this.adapter.init(this.widget);
  }

  onChangeDate(event: Event) {
    this.adapter.injectValidationIssues(null);
    this.adapter.valueChanged((event as CustomEvent).detail.value);
  }

  onInputError(event: Event) {
    this.adapter.injectValidationIssues([(event as CustomEvent).detail.message]);
    this.adapter.onBlur();
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

@let templateData = adapter.templateData();

<gui-range-calendar
  [attr.defer-hydration]="deferHydration"
  [uid]="widget.uid"
  [label]="templateData.label"
  [hint]="templateData.hint"
  [value]="templateData.value"
  [errors]="templateData.errors"
  [touched]="templateData.touched"
  [required]="templateData.validator?.required"
  [disabled]="templateData.disabled"
  [readonly]="templateData.readonly"
  [value]="templateData.value"
  [prevMonthIcon]="templateData.prevMonthIcon"
  [nextMonthIcon]="templateData.nextMonthIcon"
  [prevMonthAriaLabel]="templateData.prevMonthAriaLabel"
  [nextMonthAriaLabel]="templateData.nextMonthAriaLabel"
  [selectYearAriaLabel]="templateData.selectYearAriaLabel"
  [yearGridAriaLabel]="templateData.yearGridAriaLabel"
  [dayFormat]="templateData.dayFormat"
  [weekdayFormat]="templateData.weekdayFormat"
  [monthFormat]="templateData.monthFormat"
  [minDate]="templateData.minDate"
  [maxDate]="templateData.maxDate"
  [disabledRanges]="templateData.disabledRanges"
  [disabledDateRangeMessage]="templateData.disabledDateRangeMessage"
  [numberOfMonths]="templateData.numberOfMonths"
  [hidePills]="false"
  [removePillAriaLabel]="templateData.removePillAriaLabel"
  [localeId]="templateData.lang"
  [allowEdit]="templateData.allowEdit"
  [editLabel]="templateData.editLabel"
  [editAriaLabel]="templateData.editAriaLabel"
  [confirmEditLabel]="templateData.confirmEditLabel"
  [cancelEditLabel]="templateData.cancelEditLabel"
  [editStartedMessage]="templateData.editStartedMessage"
  [editCommittedMessage]="templateData.editCommittedMessage"
  [editCancelledMessage]="templateData.editCancelledMessage"
  (blur)="adapter.onBlur()"
  (change)="onChangeDate($event)"
  (inputError)="onInputError($event)"
></gui-range-calendar>

// libs/gui/react/src/lib/components/RangeCalendar.tsx
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/react';
import type { DateRange, RangeCalendarProps } from '@golemui/gui-shared/internals';
import { useCallback } from 'react';
import { GuiRangeCalendarReact } from '../web-components';
import '../styles.scss';

export function RangeCalendar(widgetInstance: WithWidget) {
  const widget = widgetInstance.widget as InputWidget<DateRange[]>;
  const {
    uid,
    errors,
    value,
    isTouched,
    templateData,
    onBlur,
    onValueChanged,
    injectValidationIssues,
  } = useInputWidget<DateRange[], RangeCalendarProps>(widget);

  const handleRef = useCallback(
    (node: HTMLElement | null) => {
      const target = node as any;
      const changeHandler = (e: CustomEvent) => {
        injectValidationIssues(null);
        onValueChanged(e.detail.value);
      };
      const blurHandler = () => {
        onBlur();
      };
      const errorHandler = (e: CustomEvent) => {
        injectValidationIssues([e.detail.message]);
        onBlur();
      };
      if (node) {
        target.addEventListener('gui-blur', blurHandler);
        target.addEventListener('gui-input', changeHandler);
        target.addEventListener('gui-input-error', errorHandler);
      }

      return () => {
        target.removeEventListener('gui-blur', blurHandler);
        target.removeEventListener('gui-input', changeHandler);
        target.removeEventListener('gui-input-error', errorHandler);
      };
    },
    [onValueChanged, onBlur, injectValidationIssues],
  );

  const label = templateData.label as string;
  const hint = templateData.hint;
  const prevMonthIcon = templateData.prevMonthIcon;
  const nextMonthIcon = templateData.nextMonthIcon;
  const prevMonthAriaLabel = templateData.prevMonthAriaLabel;
  const nextMonthAriaLabel = templateData.nextMonthAriaLabel;
  const selectYearAriaLabel = templateData.selectYearAriaLabel;
  const yearGridAriaLabel = templateData.yearGridAriaLabel;
  const dayFormat = templateData.dayFormat;
  const weekdayFormat = templateData.weekdayFormat;
  const monthFormat = templateData.monthFormat;
  const minDate = templateData.minDate;
  const maxDate = templateData.maxDate;
  const disabledRanges = templateData.disabledRanges;
  const numberOfMonths = templateData.numberOfMonths;
  const removePillAriaLabel = templateData.removePillAriaLabel;
  const lang = templateData.lang;
  const isDisabled = templateData.disabled as boolean;
  const isReadonly = templateData.readonly as boolean;
  const isRequired = (templateData.validator as Validator)?.required;

  return (
    <div className="gui-range-calendar gui-field" style={{ flex: templateData.size }}>
      <GuiRangeCalendarReact
        ref={handleRef}
        uid={uid}
        label={label}
        hint={hint}
        errors={errors}
        touched={isTouched}
        required={isRequired}
        disabled={isDisabled}
        readOnly={isReadonly}
        value={value}
        prevMonthIcon={prevMonthIcon}
        nextMonthIcon={nextMonthIcon}
        prevMonthAriaLabel={prevMonthAriaLabel}
        nextMonthAriaLabel={nextMonthAriaLabel}
        selectYearAriaLabel={selectYearAriaLabel}
        yearGridAriaLabel={yearGridAriaLabel}
        dayFormat={dayFormat}
        weekdayFormat={weekdayFormat}
        monthFormat={monthFormat}
        minDate={minDate}
        maxDate={maxDate}
        disabledRanges={disabledRanges}
        disabledDateRangeMessage={templateData.disabledDateRangeMessage as string}
        numberOfMonths={numberOfMonths}
        hidePills={false}
        removePillAriaLabel={removePillAriaLabel}
        localeId={lang}
        allowEdit={templateData.allowEdit}
        editLabel={templateData.editLabel as string}
        editAriaLabel={templateData.editAriaLabel as string}
        confirmEditLabel={templateData.confirmEditLabel as string}
        cancelEditLabel={templateData.cancelEditLabel as string}
        editStartedMessage={templateData.editStartedMessage as string}
        editCommittedMessage={templateData.editCommittedMessage as string}
        editCancelledMessage={templateData.editCancelledMessage as string}
      />
    </div>
  );
}
