// libs/gui/angular/src/lib/components/repeater/repeater.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import { RepeaterProps } from '@golemui/gui-shared';

@Component({
  standalone: true,
  selector: 'gui-repeater-control',
  imports: [CommonModule, Angular.RepeaterWidgetDirective],
  providers: [Angular.InputWidgetAdapter, Angular.RepeaterWidgetDirective],
  templateUrl: './repeater.component.html',
  host: {
    class: 'gui-repeater gui-field',
    '[style.flex]': 'this.adapter.templateData().size',
  },
})
export class RepeaterComponent implements OnInit, OnDestroy, Core.WithWidget {
  widget!: Core.InputWidget<Record<string, unknown>[]>;
  protected adapter: Angular.InputWidgetAdapter<
    Record<string, unknown>[],
    RepeaterProps<Core.NonFunctionWidget>
  > = inject(Angular.InputWidgetAdapter);

  isFocused = false;

  ngOnInit(): void {
    this.adapter.init(this.widget);
  }

  addItem() {
    const newValue = [...(this.adapter.templateData().value ?? []), {}];
    this.adapter.valueChanged(newValue);
  }

  removeItem(index: number) {
    const items = (this.adapter.templateData().value ?? []).filter((_, i) => index !== i);
    // Make sure we don't keep object references
    if ('structuredClone' in window) {
      this.adapter.valueChanged(structuredClone(items));
    } else {
      this.adapter.valueChanged(JSON.parse(JSON.stringify(items)));
    }
  }

  onFocusIn(event: FocusEvent) {
    event.stopPropagation();
    this.isFocused = true;
  }

  onFocusOut(event: FocusEvent) {
    event.stopPropagation();
    this.isFocused = false;
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

@let templateData = adapter.templateData();
@let showErrors = templateData.touched && templateData.errors && templateData.errors.length > 0;

<div
  #repeaterRef
  [id]="widget.uid"
  class="gui-repeater__main-card gui-repeater__card"
  [class.gui-repeater__card--focused]="isFocused"
  (focusin)="onFocusIn($event)"
  (focusout)="onFocusOut($event)"
>
  <gui-label
    [targetElement]="[repeaterRef]"
    [uid]="widget.uid"
    [label]="templateData.label"
    [errors]="templateData.errors"
    [touched]="templateData.touched"
    [required]="templateData.validator?.required"
    [native]="false"
  ></gui-label>
  @if (templateData.template && templateData.value) {
    @for (item of templateData.value; track item) {
      <div class="gui-repeater__card">
        <div class="gui-repeater__card-header">
          @if (templateData.title) {
            <span class="gui-repeater__card-title">{{ templateData.title }} {{ $index + 1 }}</span>
          }
          <button
            type="button"
            class="gui-button gui-button--sm gui-repeater__remove-btn"
            (click)="removeItem($index)"
          >
            @if (templateData.removeButtonIcon) {
              <span
                class="gui-widget-icon gui-button-icon {{ templateData.removeButtonIcon }}"
                [attr.data-icon]="templateData.removeButtonIcon"
              ></span>
            }
            {{ templateData.removeLabel ?? 'Remove' }}
          </button>
        </div>
        <ng-container guiRepeaterWidget [repeaterIndex]="$index" [widget]="templateData.template" />
      </div>
    }
  }
  <button
    type="button"
    class="gui-button gui-repeater__add-btn"
    (click)="addItem()"
    [disabled]="
      templateData.limit ? templateData.limit === (templateData.value?.length ?? 0) : false
    "
  >
    @if (templateData.addButtonIcon) {
      <span
        class="gui-widget-icon gui-button-icon {{ templateData.addButtonIcon }}"
        [attr.data-icon]="templateData.addButtonIcon"
      ></span>
    }
    {{ templateData.addLabel ?? 'Add' }}
  </button>
</div>

@if (showErrors) {
  <gui-errors
    [uid]="widget.uid"
    [errors]="templateData.errors"
    [touched]="templateData.touched"
  ></gui-errors>
}

// libs/gui/react/src/lib/components/Repeater.tsx
import * as Core from '@golemui/core';
import {
  RepeaterIndexesContext,
  useInputWidget,
  useRepeaterIndexes,
  WidgetRenderer,
} from '@golemui/react';
import { RepeaterProps, getItemKey } from '@golemui/gui-shared';
import React, { useCallback, useRef, useState } from 'react';
import '../styles.scss';

/**
 * Monotonically increasing counter for generating unique repeater item IDs.
 */
let nextRepeaterItemId = 0;
const idIncrementer = () => nextRepeaterItemId++;

export function Repeater(widgetInstance: Core.WithWidget) {
  const widget = widgetInstance.widget as Core.InputWidget<Record<string, unknown>[]>;
  const { uid, value, onValueChanged, templateData, errors, isTouched, onBlur } = useInputWidget<
    Record<string, unknown>[],
    RepeaterProps<any>
  >(widget);

  const repeaterRef = useRef<HTMLDivElement>(null);

  const addItem = useCallback(
    (value: Record<string, unknown>[]) => {
      const newValue = [...(value ?? []), {}];
      onValueChanged(newValue);
    },
    [onValueChanged],
  );

  const removeItem = useCallback(
    (value: Record<string, unknown>[], index: number) => {
      const items = (value ?? []).filter((_, i) => index !== i);
      // Make sure we don't keep object references
      if ('structuredClone' in window) {
        onValueChanged(structuredClone(items));
      } else {
        onValueChanged(JSON.parse(JSON.stringify(items)));
      }
    },
    [onValueChanged],
  );

  const [isFocused, setIsFocused] = useState(false);

  const onFocusIn = useCallback((event: React.FocusEvent) => {
    event.stopPropagation();
    setIsFocused(true);
  }, []);

  const onFocusOut = useCallback((event: React.FocusEvent) => {
    event.stopPropagation();
    onBlur();
    setIsFocused(false);
  }, []);

  const repeaterIndexesFromContext = useRepeaterIndexes();

  const renderWidgets = useCallback(() => {
    return value?.map((item, index) => {
      const itemKey = getItemKey(item, idIncrementer);
      return (
        <RepeaterIndexesContext.Provider
          value={[...repeaterIndexesFromContext, index]}
          key={`${uid}-${itemKey}`}
        >
          <div className="gui-repeater__card">
            <div className="gui-repeater__card-header">
              {templateData.title && (
                <span className="gui-repeater__card-title">{`${templateData.title} ${index + 1}`}</span>
              )}
              <button
                type="button"
                className="gui-button gui-button--sm gui-repeater__remove-btn"
                onClick={() => removeItem(value, index)}
              >
                {templateData.removeButtonIcon && (
                  <span className={`gui-widget-icon gui-button-icon ${templateData.removeButtonIcon}`} data-icon={templateData.removeButtonIcon}></span>
                )}
                {templateData.removeLabel ?? 'Remove'}
              </button>
            </div>
            <WidgetRenderer
              key={`${uid}-${itemKey}`}
              widget={templateData.template}
              repeaterIndex={index}
            />
          </div>
        </RepeaterIndexesContext.Provider>
      );
    });
  }, [templateData, value, uid, removeItem, repeaterIndexesFromContext]);

  const isRequired = (templateData.validator as Core.Validator)?.required;

  return (
    <div className="gui-repeater gui-field" style={{ flex: templateData.size }}>
      <div
        ref={repeaterRef}
        id={uid}
        className={`gui-repeater__main-card gui-repeater__card${isFocused ? ' gui-repeater__card--focused' : ''}`}
        onFocus={onFocusIn}
        onBlur={onFocusOut}
      >
        <gui-label
          targetElement={repeaterRef.current || undefined}
          uid={uid}
          label={templateData.label as string}
          errors={errors}
          touched={isTouched}
          required={isRequired}
          native={false}
        ></gui-label>

        {renderWidgets()}
        <button
          type="button"
          className="gui-button gui-repeater__add-btn"
          onClick={() => addItem(value || [])}
          disabled={templateData.limit ? templateData.limit === (value?.length ?? 0) : false}
        >
          {templateData.addButtonIcon && (
            <span className={`gui-widget-icon gui-button-icon ${templateData.addButtonIcon}`} data-icon={templateData.addButtonIcon}></span>
          )}
          {templateData.addLabel ?? 'Add'}
        </button>
      </div>
      <gui-errors uid={uid} errors={errors} touched={isTouched}></gui-errors>
    </div>
  );
}
