// libs/gui/vue/src/lib/components/Tabs.vue
<script setup lang="ts">
import type { LayoutWidget, NonFunctionWidget, WithWidget } from '@golemui/core';
import { useLayoutWidget, WidgetRenderer } from '@golemui/vue';
import { createIntersectionObserver } from '@golemui/gui-components/internals';
import { repeaterIndexSuffix, type TabsProps } from '@golemui/gui-shared/internals';
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';

const props = defineProps<WithWidget>();
const widget = props.widget as LayoutWidget;
const { uid, children, templateData, onChange } = useLayoutWidget<TabsProps>(widget);

const containerRef = ref<HTMLDivElement | null>(null);
const tabRefs = ref<HTMLButtonElement[]>([]);
const startSentinelRef = ref<HTMLLIElement | null>(null);
const endSentinelRef = ref<HTMLLIElement | null>(null);
const isStartVisible = ref(false);
const isEndVisible = ref(false);
const activeTab = ref<string | undefined>(templateData.value.defaultOpen);
// Tab uids come from the props without row indexes, the panel children come from the store with
// them, so the comparison adds this layout's own suffix.
const rowIndexSuffix = repeaterIndexSuffix(widget.uid);
const activeChildUid = computed(() => `${activeTab.value ?? ''}${rowIndexSuffix}`);

let startObserver: { disconnect(): void } | null = null;
let endObserver: { disconnect(): void } | null = null;

onMounted(() => {
  if (startSentinelRef.value) {
    startObserver = createIntersectionObserver(startSentinelRef.value, (intersecting) => {
      isStartVisible.value = intersecting;
    });
  }
  if (endSentinelRef.value) {
    endObserver = createIntersectionObserver(endSentinelRef.value, (intersecting) => {
      isEndVisible.value = intersecting;
    });
  }
});

onUnmounted(() => {
  startObserver?.disconnect();
  endObserver?.disconnect();
});

watch(
  () => templateData.value.tabs,
  (tabs) => {
    if (activeTab.value === undefined && tabs?.length > 0) {
      activeTab.value = tabs[0].uid;
    }
  },
  { immediate: true },
);

watch(
  () => templateData.value.defaultOpen,
  (val) => {
    if (val) activeTab.value = val;
  },
);

watch(activeTab, (next) => {
  const tabs = templateData.value.tabs || [];
  const idx = tabs.findIndex((tab) => tab.uid === next);
  if (idx > -1) {
    tabRefs.value[idx]?.scrollIntoView({ block: 'nearest', inline: 'nearest' });
  }
});

const handleTabChange = (newUid: string) => {
  activeTab.value = newUid;
  onChange(newUid);
};

const onKeyDown = (event: KeyboardEvent) => {
  const tabs = templateData.value.tabs;
  const currentIndex = tabs.findIndex((tab) => tab.uid === activeTab.value);
  const isRTL = containerRef.value
    ? window.getComputedStyle(containerRef.value).direction === 'rtl'
    : false;
  let nextIndex: number | null = null;
  switch (event.key) {
    case 'ArrowLeft':
      nextIndex = currentIndex + (isRTL ? 1 : -1);
      break;
    case 'ArrowRight':
      nextIndex = currentIndex + (isRTL ? -1 : 1);
      break;
    case 'Home':
      nextIndex = 0;
      break;
    case 'End':
      nextIndex = tabs.length - 1;
      break;
    default:
      return;
  }
  if (nextIndex !== null && nextIndex >= 0 && nextIndex < tabs.length) {
    handleTabChange(tabs[nextIndex].uid);
    tabRefs.value[nextIndex]?.focus();
  }
};

const setTabRef = (idx: number) => (el: any) => {
  if (el) tabRefs.value[idx] = el as HTMLButtonElement;
};

const visibleSections = computed(() => {
  const renderMode = templateData.value.renderMode;
  return (children.value as NonFunctionWidget<string>[]).filter(
    (section) => section.uid === activeChildUid.value || renderMode !== 'activeOnly',
  );
});
</script>

<template>
  <div ref="containerRef" class="gui-tabs gui-field" :style="{ flex: templateData.size }">
    <nav
      :id="uid"
      :class="{
        'gui-widget': true,
        'gui-widget--horizontal': true,
        'gui-tabs--start-shadow': !isStartVisible,
        'gui-tabs--end-shadow': !isEndVisible,
      }"
    >
      <ul role="tablist">
        <li
          ref="startSentinelRef"
          role="presentation"
          class="gui-sentinel gui-sentinel__start"
        ></li>
        <li
          v-for="(tab, index) in templateData.tabs"
          :key="`tab_${widget.uid}_${tab.uid}`"
          role="presentation"
        >
          <button
            :ref="setTabRef(index)"
            type="button"
            role="tab"
            :tabindex="tab.uid === activeTab ? 0 : -1"
            :data-cy="`tab_${widget.uid}_${index}`"
            :id="`tab_${widget.uid}_${index}`"
            :aria-controls="`tabpanel_${widget.uid}_${index}`"
            :aria-selected="tab.uid === activeTab ? 'true' : 'false'"
            :class="tab.uid === activeTab ? 'active' : ''"
            @click="handleTabChange(tab.uid)"
            @keydown="onKeyDown"
            @focus="
              (e) =>
                (e.target as HTMLElement).scrollIntoView({ block: 'nearest', inline: 'nearest' })
            "
          >
            {{ tab.label }}
          </button>
        </li>
        <li ref="endSentinelRef" role="presentation" class="gui-sentinel gui-sentinel__end"></li>
      </ul>
    </nav>
    <section
      v-for="(section, idx) in visibleSections"
      :key="`tabpanel_${widget.uid}_${section.uid}`"
      role="tabpanel"
      tabindex="0"
      :data-cy="`tabpanel_${widget.uid}_${idx}`"
      :id="`tabpanel_${widget.uid}_${idx}`"
      :hidden="section.uid !== activeChildUid && templateData.renderMode !== 'activeOnly'"
      :aria-labelledby="`tab_${widget.uid}_${idx}`"
    >
      <WidgetRenderer :widget="section" />
    </section>
  </div>
</template>

// libs/gui/react/src/lib/components/Tabs.tsx
import type { LayoutWidget, NonFunctionWidget, WithWidget } from '@golemui/core';
import { cn, useLayoutWidget, WidgetRenderer } from '@golemui/react';
import { createIntersectionObserver } from '@golemui/gui-components/internals';
import { repeaterIndexSuffix, type TabsProps } from '@golemui/gui-shared/internals';
import React, { useCallback, useEffect, useRef, useState } from 'react';

export function Tabs(widgetInstance: WithWidget) {
  const containerRef = useRef<HTMLDivElement>(null);
  const widget = widgetInstance.widget as LayoutWidget;
  const { uid, children, templateData, onChange } = useLayoutWidget<TabsProps>(widget);
  const tabRefs = useRef<HTMLButtonElement[]>([]);
  const startSentinelRef = useRef<HTMLLIElement>(null);
  const endSentinelRef = useRef<HTMLLIElement>(null);
  const [isStartVisible, setIsStartVisible] = useState(false);
  const [isEndVisible, setIsEndVisible] = useState(false);
  const [activeTab, setActiveTab] = useState(templateData.defaultOpen);
  // Tab uids come from the props without row indexes, the panel children come from the store with
  // them, so the comparison adds this layout's own suffix.
  const rowIndexSuffix = repeaterIndexSuffix(widget.uid);
  const activeChildUid = `${activeTab ?? ''}${rowIndexSuffix}`;

  useEffect(() => {
    const startSentinel = startSentinelRef.current;
    const endSentinel = endSentinelRef.current;

    const startObserver = createIntersectionObserver(startSentinel!, (isIntersecting) =>
      setIsStartVisible(isIntersecting),
    );
    const endObserver = createIntersectionObserver(endSentinel!, (isIntersecting) =>
      setIsEndVisible(isIntersecting),
    );

    return () => {
      startObserver.disconnect();
      endObserver.disconnect();
    };
  }, []);

  useEffect(() => {
    if (activeTab === undefined && templateData.tabs?.length > 0) {
      setActiveTab(templateData.tabs[0].uid);
    }
  }, [templateData.tabs, activeTab]);

  useEffect(() => {
    if (templateData.defaultOpen) {
      setActiveTab(templateData.defaultOpen);
    }
  }, [templateData.defaultOpen]);

  useEffect(() => {
    const tabs = templateData.tabs || [];
    const currentIndex = tabs.findIndex((tab) => tab.uid === activeTab);
    if (currentIndex > -1) {
      tabRefs.current[currentIndex].scrollIntoView({ block: 'nearest', inline: 'nearest' });
    }
  }, [activeTab, templateData.tabs]);

  const handleTabChange = useCallback(
    (uid: string) => {
      setActiveTab(uid);
      onChange(uid);
    },
    [onChange],
  );

  const onKeyDown = useCallback(
    (event: React.KeyboardEvent) => {
      const currentIndex = templateData.tabs.findIndex((tab) => tab.uid === activeTab);
      const tabButtons = tabRefs.current;
      const isRTL = containerRef.current
        ? window.getComputedStyle(containerRef.current).direction === 'rtl'
        : false;

      switch (event.key) {
        case 'ArrowLeft': {
          const nextIndex = currentIndex + (isRTL ? 1 : -1);

          if (nextIndex >= 0 && nextIndex < templateData.tabs.length) {
            handleTabChange(templateData.tabs[nextIndex].uid);
            tabButtons[nextIndex]?.focus();
          }
          break;
        }
        case 'ArrowRight': {
          const nextIndex = currentIndex + (isRTL ? -1 : 1);

          if (nextIndex >= 0 && nextIndex < templateData.tabs.length) {
            handleTabChange(templateData.tabs[nextIndex].uid);
            tabButtons[nextIndex]?.focus();
          }
          break;
        }
        case 'Home':
          handleTabChange(templateData.tabs[0].uid);
          tabButtons[0]?.focus();
          break;
        case 'End':
          handleTabChange(templateData.tabs[templateData.tabs.length - 1].uid);
          tabButtons[templateData.tabs.length - 1]?.focus();
          break;
        default:
          return;
      }
    },
    [activeTab, templateData.tabs, handleTabChange],
  );

  const renderTabs = useCallback(() => {
    const tabs = templateData.tabs || [];
    return tabs.map((tab, index) => {
      return (
        <li role="presentation" key={`tab_${widget.uid}_${tab.uid}`}>
          <button
            ref={(el) => {
              tabRefs.current[index] = el!;
            }}
            type="button"
            role="tab"
            tabIndex={tab.uid === activeTab ? 0 : -1}
            data-cy={`tab_${widget.uid}_${index}`}
            id={`tab_${widget.uid}_${index}`}
            aria-controls={`tabpanel_${widget.uid}_${index}`}
            aria-selected={tab.uid === activeTab ? 'true' : 'false'}
            className={`${tab.uid === activeTab ? 'active' : ''}`}
            onClick={() => handleTabChange(tab.uid)}
            onKeyDown={(event: React.KeyboardEvent) => onKeyDown(event)}
            onFocus={(event: React.FocusEvent) => {
              event.target.scrollIntoView({ block: 'nearest', inline: 'nearest' });
            }}
          >
            {tab.label}
          </button>
        </li>
      );
    });
  }, [templateData, activeTab, widget, tabRefs, handleTabChange, onKeyDown]);

  const renderWidgets = useCallback(() => {
    const activeSectionIndex = children.findIndex((section: any) => section.uid === activeChildUid);

    return children
      .filter((widget) => widget.uid === activeChildUid || templateData.renderMode !== 'activeOnly')
      .map((section) => (
        <section
          key={`tabpanel_${widget.uid}_${section.uid}`}
          role="tabpanel"
          tabIndex={0}
          data-cy={`tabpanel_${widget.uid}_${activeSectionIndex}`}
          id={`tabpanel_${widget.uid}_${activeSectionIndex}`}
          hidden={section.uid !== activeChildUid && templateData.renderMode !== 'activeOnly'}
          aria-labelledby={`tab_${widget.uid}_${activeSectionIndex}`}
        >
          <WidgetRenderer key={section.uid} widget={section as NonFunctionWidget<string>} />
        </section>
      ));
  }, [children, activeChildUid, widget]);

  return (
    <div className="gui-tabs gui-field" style={{ flex: templateData.size }}>
      <nav
        className={cn({
          'gui-widget': true,
          'gui-widget--horizontal': true,
          'gui-tabs--start-shadow': !isStartVisible,
          'gui-tabs--end-shadow': !isEndVisible,
        })}
        id={uid}
      >
        <ul role="tablist">
          <li
            role="presentation"
            ref={startSentinelRef}
            className="gui-sentinel gui-sentinel__start"
          ></li>
          {renderTabs()}
          <li
            role="presentation"
            ref={endSentinelRef}
            className="gui-sentinel gui-sentinel__end"
          ></li>
        </ul>
      </nav>
      {renderWidgets()}
    </div>
  );
}
