// libs/gui/vue/src/lib/components/TimeInput.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/vue';
import type { TimeInputProps } from '@golemui/gui-shared/internals';
import { computed, onUnmounted, ref, watch } from 'vue';
import '@golemui/gui-components/time-input';

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<string>;
const {
  uid,
  errors,
  value,
  isTouched,
  templateData,
  onValueChanged,
  onBlur,
  injectValidationIssues,
} = useInputWidget<string, TimeInputProps>(widget);

const required = computed(() => (templateData.value.validator as Validator)?.required);

const timeRef = ref<HTMLElement | null>(null);
const changeHandler = (e: Event) => {
  injectValidationIssues(null);
  onValueChanged((e as CustomEvent).detail.value);
};
const errorHandler = (e: Event) => {
  injectValidationIssues([(e as CustomEvent).detail.message]);
};

let currentEl: HTMLElement | null = null;
watch(timeRef, (el) => {
  if (currentEl) {
    currentEl.removeEventListener('gui-input', changeHandler);
    currentEl.removeEventListener('gui-blur', onBlur);
    currentEl.removeEventListener('gui-input-error', errorHandler);
  }
  currentEl = el;
  if (el) {
    el.addEventListener('gui-input', changeHandler);
    el.addEventListener('gui-blur', onBlur);
    el.addEventListener('gui-input-error', errorHandler);
  }
});

onUnmounted(() => {
  currentEl?.removeEventListener('gui-input', changeHandler);
  currentEl?.removeEventListener('gui-blur', onBlur);
  currentEl?.removeEventListener('gui-input-error', errorHandler);
});
</script>

<template>
  <div class="gui-time gui-field" :style="{ flex: templateData.size }">
    <gui-time
      ref="timeRef"
      :uid="uid"
      :label="templateData.label"
      :hint="templateData.hint"
      :errors="errors"
      :touched="isTouched"
      :required="required"
      :disabled="templateData.disabled"
      :readOnly="templateData.readonly"
      :value="value"
      :icon="templateData.icon"
      :localeId="templateData.lang"
      :hourAriaLabel="templateData.hourAriaLabel"
      :minuteAriaLabel="templateData.minuteAriaLabel"
      :dayPeriodAriaLabel="templateData.dayPeriodAriaLabel"
      :hourFormat="templateData.hourFormat"
      :minuteStep="templateData.minuteStep ?? 1"
      :minTime="templateData.minTime"
      :maxTime="templateData.maxTime"
      :minTimeMessage="templateData.minTimeMessage"
      :maxTimeMessage="templateData.maxTimeMessage"
      :incompleteMessage="templateData.incompleteMessage"
    />
  </div>
</template>

// libs/gui/react/src/lib/components/TimeInput.tsx
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/react';
import type { TimeInputProps } from '@golemui/gui-shared/internals';
import { useCallback } from 'react';
import { GuiTimeReact } from '../web-components';
import '../styles.scss';

export function TimeInput(widgetInstance: WithWidget) {
  const widget = widgetInstance.widget as InputWidget<string>;
  const {
    uid,
    errors,
    value,
    isTouched,
    templateData,
    onValueChanged,
    onBlur,
    injectValidationIssues,
  } = useInputWidget<string, TimeInputProps>(widget);

  const handleRef = useCallback(
    (node: HTMLElement | null) => {
      const target = node as any;
      const changeHandler = (e: CustomEvent) => {
        injectValidationIssues(null);
        onValueChanged(e.detail.value);
      };

      const errorHandler = (e: CustomEvent) => {
        injectValidationIssues([e.detail.message]);
      };

      if (node) {
        target.addEventListener('gui-input', changeHandler);
        target.addEventListener('gui-blur', onBlur);
        target.addEventListener('gui-input-error', errorHandler);
      }

      return () => {
        target.removeEventListener('gui-input', changeHandler);
        target.removeEventListener('gui-blur', onBlur);
        target.removeEventListener('gui-input-error', errorHandler);
      };
    },
    [onValueChanged, onBlur, injectValidationIssues],
  );

  const label = templateData.label as string;
  const hint = templateData.hint;
  const icon = templateData.icon;
  const isDisabled = templateData.disabled as boolean;
  const isReadonly = templateData.readonly as boolean;
  const isRequired = (templateData.validator as Validator)?.required;
  const lang = templateData.lang;
  const hourFormat = templateData.hourFormat;
  const minuteStep = templateData.minuteStep;

  return (
    <div className="gui-time gui-field" style={{ flex: templateData.size }}>
      <GuiTimeReact
        ref={handleRef}
        uid={uid}
        label={label}
        hint={hint}
        errors={errors}
        touched={isTouched}
        required={isRequired}
        disabled={isDisabled}
        readOnly={isReadonly}
        value={value}
        icon={icon}
        localeId={lang}
        hourAriaLabel={templateData.hourAriaLabel}
        minuteAriaLabel={templateData.minuteAriaLabel}
        dayPeriodAriaLabel={templateData.dayPeriodAriaLabel}
        hourFormat={hourFormat}
        minuteStep={minuteStep}
        minTime={templateData.minTime}
        maxTime={templateData.maxTime}
        minTimeMessage={templateData.minTimeMessage as string}
        maxTimeMessage={templateData.maxTimeMessage as string}
        incompleteMessage={templateData.incompleteMessage as string}
      />
    </div>
  );
}
