// libs/gui/vue/src/lib/components/Toggle.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/vue';
import type { ToggleProps } from '@golemui/gui-shared';
import { computed } from 'vue';
import '@golemui/gui-components/toggle';

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<boolean>;
const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useInputWidget<
  boolean,
  ToggleProps
>(widget);

const handleChange = (e: Event) => onValueChanged((e as CustomEvent).detail.value);
const required = computed(() => (templateData.value.validator as Validator)?.required);
// Mirror Lit class-field default to avoid Vue coercing undefined → '' on the enum prop.
const togglePosition = computed(() => templateData.value.togglePosition || 'left');
</script>

<template>
  <div class="gui-toggle gui-field" :style="{ flex: templateData.size }">
    <gui-toggle
      :uid="uid"
      :label="templateData.label"
      :errors="errors"
      :touched="isTouched"
      :required="required"
      :disabled="templateData.disabled"
      :readOnly="templateData.readonly"
      :value="value"
      :hint="templateData.hint"
      :togglePosition.prop="togglePosition"
      @change="handleChange"
      @blur="onBlur"
    ></gui-toggle>
  </div>
</template>

// libs/gui/react/src/lib/components/Toggle.tsx
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/react';
import { type ToggleProps } from '@golemui/gui-shared';
import { useCallback } from 'react';
import { GuiToggleReact } from '../web-components';
import '../styles.scss';


export function Toggle(widgetInstance: WithWidget) {
  const widget = widgetInstance.widget as InputWidget<boolean>;
  const { uid, errors, value, onValueChanged, onBlur, templateData, isTouched } = useInputWidget<
    boolean,
    ToggleProps
  >(widget);

  const handleChange = useCallback(
    (e: Event) => onValueChanged((e as CustomEvent).detail.value),
    [onValueChanged],
  );

  const label = templateData.label as string;
  const hint = templateData.hint;
  const togglePosition = templateData.togglePosition;
  const isDisabled = templateData.disabled as boolean;
  const isReadonly = templateData.readonly as boolean;
  const isRequired = (templateData.validator as Validator)?.required;

  return (
    <div className={`gui-toggle gui-field`} style={{ flex: templateData.size }}>
      <GuiToggleReact
        uid={uid}
        label={label}
        errors={errors}
        touched={isTouched}
        required={isRequired}
        disabled={isDisabled}
        readOnly={isReadonly}
        value={value}
        hint={hint}
        togglePosition={togglePosition}
        onChange={handleChange}
        onBlur={onBlur}
      />
    </div>
  );
}
