// libs/gui/react/src/lib/components/Button.tsx
import type { ActionWidget, WithWidget } from '@golemui/core';
import { useActionWidget } from '@golemui/react';
import { GuiButtonReact } from '../web-components';
import '../styles.scss';
import type { ButtonProps } from '@golemui/gui-shared/internals';

export function Button(widgetInstance: WithWidget) {
  const widget = widgetInstance.widget as ActionWidget;
  const { uid, templateData, onClick } = useActionWidget<ButtonProps>(widget);
  const invalid = templateData.invalid === true && templateData.actionType === 'submit';

  return (
    <div
      className={invalid ? 'gui-button gui-field gui-button--invalid' : 'gui-button gui-field'}
      style={{ flex: templateData.size }}
    >
      <GuiButtonReact
        uid={uid}
        type={templateData.actionType ?? 'button'}
        label={templateData.label as string}
        disabled={templateData.disabled as boolean}
        variant={templateData.variant}
        icon={templateData.icon}
        iconPosition={templateData.iconPosition}
        onClick={onClick}
      />
    </div>
  );
}

// libs/gui/angular/src/lib/components/button/button.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  inject,
  type OnDestroy,
  type OnInit,
} from '@angular/core';
import { ActionWidgetAdapter } from '@golemui/angular';
import type { ActionWidget, WithWidget } from '@golemui/core';
import type { ButtonProps } from '@golemui/gui-shared/internals';
import '@golemui/gui-components/button';
import { deferHydrationAttr } from '../../utils/defer-hydration';

@Component({
  standalone: true,
  selector: 'gui-button-interactive',
  providers: [ActionWidgetAdapter],
  templateUrl: './button.component.html',
  host: {
    class: 'gui-button gui-field',
    '[style.flex]': 'this.adapter.templateData().size',
  },
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class ButtonComponent implements OnInit, OnDestroy, WithWidget {
  widget!: ActionWidget;
  protected adapter: ActionWidgetAdapter<ButtonProps> = inject(ActionWidgetAdapter);
  protected readonly deferHydration = deferHydrationAttr();

  ngOnInit(): void {
    this.adapter.init(this.widget);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }

  onClick() {
    this.adapter.click();
  }
}

@let templateData = adapter.templateData();

<gui-button
  [attr.defer-hydration]="deferHydration"
  [uid]="widget.uid"
  [actionType]="templateData.actionType ?? 'button'"
  [label]="templateData.label"
  [disabled]="templateData.disabled"
  [invalid]="templateData.invalid"
  [variant]="templateData.variant"
  [icon]="templateData.icon"
  [iconPosition]="templateData.iconPosition"
  (click)="onClick()"
></gui-button>
