// libs/gui/lit/src/lib/components/default-list-item-renderer.ts
import { html } from 'lit';
import { classMap } from 'lit/directives/class-map.js';
import { type ItemRenderContext } from '@golemui/core';

export const defaultListItemRenderer = (ctx: ItemRenderContext<any>) => {
  const classes = {
    'gui-list__item': true,
    'gui-list__item-selected': !!ctx.selected,
    'gui-list__item-focused': !!ctx.focused,
    'gui-list__item-disabled': !!ctx.disabled,
  };

  return html`
    <div
      role="option"
      class=${classMap(classes)}
      aria-selected=${ctx.selected ? 'true' : 'false'}
      aria-disabled=${ctx.disabled ? 'true' : 'false'}
    >
      ${ctx.template}
    </div>
  `;
};

// libs/gui/react/src/lib/components/item-renderers/DefaultListItemRenderer.tsx
import React from 'react';
import { ListItemRendererProps } from './props';
import { OptionValue } from '@golemui/gui-components';

export function DefaultListItemRenderer({
  template,
  selected,
  disabled,
  focused,
}: ListItemRendererProps<OptionValue>) {
  const classes = [
    'gui-list__item',
    disabled ? 'gui-list__item-disabled' : '',
    selected ? 'gui-list__item-selected' : '',
    focused ? 'gui-list__item-focused' : '',
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <div role="option" className={classes} aria-selected={selected}>
      {template}
    </div>
  );
}
