// libs/gui/vue/src/lib/components/item-renderers/DefaultListItemRenderer.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { OptionValue } from '@golemui/gui-shared/internals';
import type { ListItemRendererProps } from './props';

const props = defineProps<ListItemRendererProps<OptionValue>>();

const classes = computed(() =>
  [
    'gui-list__item',
    props.disabled ? 'gui-list__item-disabled' : '',
    props.selected ? 'gui-list__item-selected' : '',
    props.focused ? 'gui-list__item-focused' : '',
  ]
    .filter(Boolean)
    .join(' '),
);
</script>

<template>
  <div role="option" :class="classes" :aria-selected="selected">
    {{ template }}
  </div>
</template>

// libs/gui/react/src/lib/components/item-renderers/DefaultListItemRenderer.tsx
import React from 'react';
import { type ListItemRendererProps } from './props';
import type { OptionValue } from '@golemui/gui-shared/internals';

export function DefaultListItemRenderer({
  template,
  selected,
  disabled,
  focused,
}: ListItemRendererProps<OptionValue>) {
  const classes = [
    'gui-list__item',
    disabled ? 'gui-list__item-disabled' : '',
    selected ? 'gui-list__item-selected' : '',
    focused ? 'gui-list__item-focused' : '',
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <div role="option" className={classes} aria-selected={selected}>
      {template}
    </div>
  );
}
