// libs/angular/src/lib/components/item-renderers/item-renderer.ts
import { type Type } from '@angular/core';
import type { ItemRenderContext, ItemRenderItemData } from '@golemui/core'

/**
 * The Angular-specific Core.ItemRenderer type.
 * @template T The type of the data item.
 */
export type AngularItemRenderer<T extends ItemRenderItemData> = Type<
  ItemRenderContext<T>
>;

// libs/lit/src/lib/components/item-renderers/item-renderer.ts
import type { ItemRenderContext, ItemRenderItemData } from '@golemui/core';
import { type TemplateResult } from 'lit';

/**
 * The Lit-specific Core.ItemRenderer type.
 * @template T The type of the data item.
 */
export type LitItemRenderer<T extends ItemRenderItemData> = (
  ctx: ItemRenderContext<T>,
) => TemplateResult;
