// libs/react-vanilla/src/lib/components/Button.tsx
import * as Core from '@golemui/core';
import { useInteractiveField } from '@golemui/react';
import '../styles.scss';

export function Button(fieldInstance: Core.WithField) {
  const field = fieldInstance.field as Core.InteractiveField;
  const { uid, templateData, onClick } = useInteractiveField(field);
  const isDisabled = templateData.disabled as boolean;

  return (
    <div className="gui-button">
      <div className="gui-field">
        <button
          type="button"
          id={uid}
          data-cy={`${uid}_button`}
          onClick={onClick}
          disabled={isDisabled}
        >
          {templateData.label as string}
        </button>
      </div>
    </div>
  );
}

// libs/angular-vanilla/src/lib/button/button.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';

@Component({
  standalone: true,
  selector: 'gui-button',
  imports: [CommonModule],
  providers: [Angular.InteractiveFieldAdapter],
  templateUrl: './button.component.html',
  styleUrl: '../styles.scss',
  host: {
    class: 'gui-button',
  },
})
export class ButtonComponent implements OnInit, OnDestroy, Core.WithField {
  field!: Core.InteractiveField;
  protected adapter: Angular.InteractiveFieldAdapter = inject(Angular.InteractiveFieldAdapter);

  ngOnInit(): void {
    this.adapter.init(this.field);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }

  onClick() {
    this.adapter.click();
  }
}

<div class="field">
  <button
    type="button"
    [id]="field.uid"
    (click)="onClick()"
    [disabled]="adapter.templateData.disabled"
  >
    {{ adapter.templateData.label }}
  </button>
  {{ adapter.templateData.disabled }}
</div>
