// apps/react-playground/src/app/item-renderers/AirportItemRenderer.tsx
import React from 'react';
import { ListItemRendererProps } from '@golemui/react-vanilla';
import './airport-item-renderer.scss';
import { cn } from '@golemui/react';
import { AirportItem } from '@golemui/apps-shared';

export function AirportItemRenderer({
  template,
  index,
  selected,
  disabled,
  focused,
}: ListItemRendererProps<AirportItem>) {
  const classes = {
    airport: true,
    disabled: disabled,
    selected: selected,
    focused: focused,
    odd: index % 2 === 0,
  };

  return (
    <div role="option" className={cn(classes)} aria-selected={selected} aria-disabled={disabled}>
      <div>
        <p>{template?.name}</p>
      </div>
      <div>
        <h2>{template?.iata}</h2>
      </div>
    </div>
  );
}

// apps/lit-playground/src/app/item-renderers/airport.item-renderer.ts
import { html, TemplateResult } from 'lit';
import { classMap } from 'lit/directives/class-map.js';
import { ItemRenderContext } from '@golemui/core';
import { AirportItem } from '@golemui/apps-shared';

export const airportItemRenderer = (ctx: ItemRenderContext<AirportItem>): TemplateResult => {
  const classes = {
    'airport-renderer': true,
    disabled: !!ctx.disabled,
    selected: !!ctx.selected,
    focused: !!ctx.focused,
    odd: ctx.index % 2 !== 0,
  };

  return html`
    <div
      role="option"
      class=${classMap(classes)}
      aria-selected=${ctx.selected ? 'true' : 'false'}
      aria-disabled=${ctx.disabled ? 'true' : 'false'}
    >
      <div>
        <p>${ctx.template.name}</p>
      </div>
      <div>
        <h2>${ctx.template.iata}</h2>
      </div>
    </div>
  `;
};
