// apps/nextjs-playground/src/components/item-renderers/ComplexListItemRenderer.tsx
import React from 'react';
import { type ListItemRendererProps } from '@golemui/gui-react';
import './complex-list-item-renderer.scss';
import { cn } from '@golemui/react';

type ComplexItem = {
  title: string;
  description: string;
};

export function ComplexListItemRenderer({
  template,
  index,
  selected,
  disabled,
  focused,
}: ListItemRendererProps<ComplexItem>) {
  const classes = {
    'my-custom-class': true,
    disabled: disabled,
    selected: selected,
    focused: focused,
    odd: index % 2 === 0,
  };

  return (
    <div className={cn(classes)}>
      <h2>{template?.title}</h2>
      <p>{template?.description}</p>
    </div>
  );
}

// apps/lit-playground/src/app/item-renderers/complex-list.item-renderer.ts
import { html, TemplateResult } from 'lit';
import { classMap } from 'lit/directives/class-map.js';
import { ItemRenderContext } from '@golemui/core';

type ComplexItem = {
  title: string;
  description: string;
};

export const complexListItemRenderer = (ctx: ItemRenderContext<ComplexItem>): TemplateResult => {
  const classes = {
    'my-custom-class': true,
    disabled: !!ctx.disabled,
    selected: !!ctx.selected,
    focused: !!ctx.focused,
    odd: ctx.index % 2 !== 0,
  };

  return html`
    <div class=${classMap(classes)}>
      <h2>${ctx.template.title}</h2>
      <p>${ctx.template.description}</p>
    </div>
  `;
};
