// apps/react-playground/src/app/item-renderers/ProductItemRenderer.tsx
import React from 'react';
import { ListItemRendererProps } from '@golemui/react-vanilla';
import './product-item-renderer.scss';
import { cn } from '@golemui/react';

type ProductItem = {
  product: string;
  description: string;
  price: string;
};

export function ProductItemRenderer({
  template,
  index,
  selected,
  disabled,
  focused,
}: ListItemRendererProps<ProductItem>) {
  const classes = {
    product: true,
    disabled: disabled,
    selected: selected,
    focused: focused,
    odd: index % 2 === 0,
  };

  return (
    <div role="option" className={cn(classes)} aria-selected={selected} aria-disabled={disabled}>
      <div>
        <h2>{template?.product}</h2>
        <p>{template?.description}</p>
      </div>
      <div>
        <p>{template?.price}</p>
      </div>
    </div>
  );
}

// apps/lit-playground/src/app/item-renderers/product.item-renderer.ts
import { html, TemplateResult } from 'lit';
import { classMap } from 'lit/directives/class-map.js';
import { ItemRenderContext } from '@golemui/core';

type ProductItem = {
  product: string;
  description: string;
  price: number;
};

export const productItemRenderer = (ctx: ItemRenderContext<ProductItem>): TemplateResult => {
  const classes = {
    'product-renderer': true,
    disabled: !!ctx.disabled,
    selected: !!ctx.selected,
    focused: !!ctx.focused,
    odd: ctx.index % 2 !== 0,
  };

  return html`
    <div
      role="option"
      class=${classMap(classes)}
      aria-selected=${ctx.selected ? 'true' : 'false'}
      aria-disabled=${ctx.disabled ? 'true' : 'false'}
    >
      <div>
        <h2>${ctx.template.product}</h2>
        <p>${ctx.template.description}</p>
      </div>
      <div>
        <p>${ctx.template.price}</p>
      </div>
    </div>
  `;
};
