// libs/react-vanilla/src/lib/components/Checkbox.tsx
import * as Core from '@golemui/core';
import { useControlField } from '@golemui/react';
import { CheckboxProps } from '@golemui/shared-vanilla';
import { useCallback } from 'react';
import '../styles.scss';
import { Errors } from './shared/Errors';

export function Checkbox(fieldInstance: Core.WithField) {
  const field = fieldInstance.field as Core.ControlField<boolean>;
  const {
    uid,
    validator,
    errors,
    value,
    isDisabled,
    isReadonly,
    label,
    onValueChanged,
    onBlur,
    props,
  } = useControlField<boolean, CheckboxProps>(field);

  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => !isReadonly && onValueChanged(e.target.checked),
    [onValueChanged, isReadonly],
  );

  const checkboxPosition = props.checkboxPosition;

  return (
    <div className={`gui-checkbox ${checkboxPosition === 'left' ? 'gui-checkbox--left' : ''}`}>
      <label htmlFor={uid}>{label + (validator?.required ? ' *' : '')}</label>

      <div className="gui-field gui-field--horizontal">
        <input
          type="checkbox"
          id={uid}
          checked={value ?? false}
          disabled={isDisabled}
          aria-checked={value ?? false}
          aria-readonly={isReadonly}
          onChange={handleChange}
          onBlur={onBlur}
        />
      </div>
      <Errors errors={errors} />
    </div>
  );
}

// libs/angular-vanilla/src/lib/components/checkbox/checkbox.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import { CheckboxProps } from '@golemui/shared-vanilla';
import { LabelComponent } from '../../utils/templates/label.component';
import { ErrorsComponent } from '../../utils/templates/errors.component';
import { GuiAriaDirective } from '../../directives/aria.directive';

@Component({
  standalone: true,
  selector: 'gui-checkbox',
  imports: [CommonModule, LabelComponent, ErrorsComponent, GuiAriaDirective],
  providers: [Angular.ControlFieldAdapter],
  templateUrl: './checkbox.component.html',
  host: {
    class: 'gui-checkbox',
    '[class.gui-checkbox--left]': 'adapter.templateData().checkboxPosition === "left"',
  },
})
export class CheckboxComponent implements OnInit, OnDestroy, Core.WithField {
  field!: Core.ControlField<string>;
  protected adapter: Angular.ControlFieldAdapter<string, CheckboxProps> = inject(
    Angular.ControlFieldAdapter,
  );

  ngOnInit(): void {
    this.adapter.init(this.field);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }

  valueChanged(event: Event) {
    const target = event.target as HTMLInputElement;
    this.adapter.valueChanged(target.checked);
  }
}

@let templateData = adapter.templateData();
@let showErrors = templateData.touched && templateData.errors && templateData.errors.length > 0;

<label gui-label [for]="field.uid" [uid]="field.uid" [templateData]="templateData">
  @if (showErrors) {
    <ul gui-errors [uid]="field.uid" [templateData]="templateData"></ul>
  }
</label>

<div class="gui-field gui-field--horizontal">
  <input
    type="checkbox"
    guiAria
    [uid]="field.uid"
    [templateData]="templateData"
    [id]="field.uid"
    [required]="templateData.validator?.required"
    [value]="templateData.value ?? false"
    [checked]="templateData.value ? true : undefined"
    [disabled]="templateData.disabled"
    [readonly]="templateData.readonly"
    (click)="!templateData.readonly && valueChanged($event)"
    (blur)="adapter.onBlur()"
  />
</div>
