// libs/react-vanilla/src/lib/components/List.tsx
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import * as Core from '@golemui/core';
import { useInputWidget, useItemRenderer } from '@golemui/react';
import { ListItem, ListProps, OptionValue } from '@golemui/shared-vanilla';
import { DefaultListItemRenderer } from './item-renderers/DefaultListItemRenderer';
import { ListItemRendererProps } from './item-renderers/props';

interface GuiListElement extends HTMLElement {
  focusItemAtIndex(index: number): void;
}

export function List(widgetInstance: Core.WithWidget) {
  const widget = widgetInstance.widget as Core.InputWidget<OptionValue>;

  const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useInputWidget<
    OptionValue,
    ListProps<unknown>
  >(widget);

  // React catches bubbling blur events meanwhile Lit and Angular don't, we prevent double blur events here
  const handleBlur = useCallback(
    (e: React.FocusEvent) => {
      if (listRef.current && e.relatedTarget && listRef.current.contains(e.relatedTarget as Node)) {
        return;
      }

      onBlur();
    },
    [onBlur],
  );

  const [range, setRange] = useState({ start: 0, end: 10 });
  const [listItems, setListItems] = useState<ListItem<any>[]>([]);
  const [focusedIndex, setFocusedIndex] = useState<number>(-1);

  const listRef = useRef<GuiListElement>(null);

  const visibleItems = useMemo(() => {
    const items = listItems.length > 0 ? listItems : templateData.items || [];
    return items.slice(range.start, range.end);
  }, [listItems, templateData.items, range]);

  useEffect(() => {
    const element = listRef.current;
    if (!element) return;

    const handleRangeChange = (e: Event) => {
      const { startIndex, endIndex } = (e as CustomEvent).detail;
      setRange({ start: startIndex, end: endIndex });
    };

    const handleUpdateItems = (e: Event) => {
      const items = (e as CustomEvent).detail;
      setListItems(items ? [...items] : []);
    };

    const handleFocusChange = (e: Event) => {
      const index = (e as CustomEvent).detail.index;
      setFocusedIndex(index);
    };

    const handleChange = (e: Event) => {
      const val = (e as CustomEvent).detail.value;
      onValueChanged(val);
    };

    // Binding
    element.addEventListener('change', handleChange);
    element.addEventListener('gui-update-items', handleUpdateItems);
    element.addEventListener('gui-range-change', handleRangeChange);
    element.addEventListener('gui-focus-change', handleFocusChange);

    return () => {
      // Cleanup
      element.removeEventListener('change', handleChange);
      element.removeEventListener('gui-update-items', handleUpdateItems);
      element.removeEventListener('gui-range-change', handleRangeChange);
      element.removeEventListener('gui-focus-change', handleFocusChange);
    };
  }, [onValueChanged]);

  const handleClickItem = useCallback(
    (item: ListItem<any>, index: number) => {
      if (templateData.disabled) return;

      onValueChanged(item.value);
      setFocusedIndex(index);

      if (listRef.current) {
        listRef.current.focusItemAtIndex(index);
      }
    },
    [onValueChanged],
  );

  const ItemRenderer = (useItemRenderer(templateData.itemRenderer as string) ||
    DefaultListItemRenderer) as React.ComponentType<ListItemRendererProps<any>>;
  const label = templateData.label as string;
  const isRequired = (templateData.validator as Core.Validator)?.required;
  const isDisabled = templateData.disabled as boolean;
  const isReadOnly = templateData.readonly as boolean;

  return (
    <div className="gui-list" style={{ flex: templateData.size }}>
      <gui-label
        targetElement={listRef.current || undefined}
        uid={uid}
        label={label}
        hint={templateData.hint}
        errors={errors}
        touched={isTouched}
        required={isRequired}
      ></gui-label>

      <div className="gui-field">
        <gui-list
          ref={listRef}
          id={uid}
          uid={uid}
          value={value ?? ''}
          valueField={templateData.valueField}
          items={templateData.items}
          itemHeight={templateData.itemHeight}
          height={templateData.height}
          required={isRequired}
          touched={isTouched}
          disabled={isDisabled}
          readOnly={isReadOnly}
          onBlur={handleBlur}
        >
          {visibleItems.map((item, index) => {
            const absoluteIndex = range.start + index;
            const isSelected = value === item.value;
            const isFocused = focusedIndex === absoluteIndex;

            return (
              <div
                key={absoluteIndex}
                role="option"
                tabIndex={-1}
                id={`${uid}-item-${absoluteIndex}`}
                className="gui-list__item-wrapper"
                style={{ height: `${templateData.itemHeight || 40}px` }}
                aria-selected={isSelected}
                aria-disabled={isDisabled ? 'true' : 'false'}
                onClick={() => handleClickItem(item, absoluteIndex)}
              >
                <ItemRenderer
                  template={item.template}
                  value={item.value}
                  index={index}
                  selected={isSelected}
                  disabled={isDisabled}
                  focused={isFocused}
                />
              </div>
            );
          })}
        </gui-list>
      </div>

      <gui-errors errors={errors} touched={isTouched}></gui-errors>
    </div>
  );
}

// libs/angular-vanilla/src/lib/components/list/list.component.ts
import { CommonModule, NgComponentOutlet } from '@angular/common';
import {
  Component,
  computed,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  inject,
  OnDestroy,
  OnInit,
  signal,
  viewChild,
} from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import { ListItem, ListProps, OptionValue } from '@golemui/shared-vanilla';
import { DefaultListItemRenderer } from './default-list.item-renderer';

@Component({
  standalone: true,
  selector: 'gui-list-control',
  imports: [CommonModule, NgComponentOutlet],
  providers: [Angular.InputWidgetAdapter],
  templateUrl: './list.component.html',
  host: {
    class: 'gui-list',
    '[style.flex]': 'this.adapter.templateData().size',
  },
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class ListComponent implements OnInit, OnDestroy, Core.WithWidget {
  widget!: Core.InputWidget<string>;

  protected adapter: Angular.InputWidgetAdapter<OptionValue, ListProps<unknown>> = inject(
    Angular.InputWidgetAdapter,
  );

  protected defaultListItemRenderer: Angular.AngularItemRenderer<string> = DefaultListItemRenderer;

  protected listElementRef = viewChild.required<ElementRef>('listRef');

  protected currentRange = signal({ start: 0, end: 10 });
  protected listItems = signal<ListItem<any>[]>([]);
  protected focusedIndex = signal<number>(-1);

  protected visibleItems = computed(() => {
    const items = this.listItems() || [];
    const { start, end } = this.currentRange();

    return items.slice(start, end);
  });

  ngOnInit(): void {
    this.adapter.init(this.widget);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }

  protected onClickItem(item: any, index: number, listRef: any) {
    if (this.adapter.templateData().disabled) return;

    this.setValue(item.value);
    this.focusedIndex.set(index);
    listRef.focusItemAtIndex(index);
  }

  protected valueChanged(event: Event) {
    const value = (event as CustomEvent).detail.value;
    this.setValue(value);
  }

  protected setValue(value: OptionValue) {
    this.adapter.valueChanged(value);
  }

  protected onFocusChange(event: Event) {
    const index = (event as CustomEvent).detail.index;
    this.focusedIndex.set(index);
  }

  protected onUpdateItems(event: Event) {
    const items = (event as CustomEvent).detail;
    this.listItems.set(items ? [...items] : []);
  }

  protected onRangeChange(event: Event) {
    const { startIndex, endIndex } = (event as CustomEvent).detail;
    this.currentRange.set({ start: startIndex, end: endIndex });
  }
}

@let templateData = adapter.templateData();
@let itemRenderer = adapter.getItemRenderer(templateData.itemRenderer, defaultListItemRenderer);

<gui-label
  [targetElement]="listElementRef().nativeElement"
  [uid]="widget.uid"
  [label]="templateData.label"
  [hint]="templateData.hint"
  [errors]="templateData.errors"
  [touched]="templateData.touched"
  [required]="templateData.validator?.required"
></gui-label>

<div class="gui-field">
  <gui-list
    #listRef
    [id]="widget.uid"
    [uid]="widget.uid"
    [errors]="templateData.errors"
    [touched]="templateData.touched"
    [required]="templateData.validator?.required"
    [disabled]="templateData.disabled"
    [readonly]="templateData.readonly"
    [value]="templateData.value ?? ''"
    [valueField]="templateData.valueField"
    [items]="templateData.items"
    [itemHeight]="templateData.itemHeight"
    [height]="templateData.height"
    (blur)="adapter.onBlur()"
    (change)="valueChanged($event)"
    (gui-update-items)="onUpdateItems($event)"
    (gui-range-change)="onRangeChange($event)"
    (gui-focus-change)="onFocusChange($event)"
  >
    @for (item of visibleItems(); track $index) {
      @let absoluteIndex = currentRange().start + $index;

      <!-- eslint-disable-next-line @angular-eslint/template/click-events-have-key-events -->
      <div
        role="option"
        tabindex="-1"
        class="gui-list__item-wrapper"
        [id]="widget.uid + '-item-' + absoluteIndex"
        [style.height.px]="templateData.itemHeight || 40"
        [attr.aria-selected]="templateData.value === item.value"
        [attr.aria-disabled]="templateData.disabled"
        (click)="onClickItem(item, absoluteIndex, listRef)"
      >
        <ng-container
          *ngComponentOutlet="
            itemRenderer;
            inputs: {
              template: item.template,
              value: item.value,
              disabled: templateData.disabled,
              selected: templateData.value === item.value,
              focused: focusedIndex() === absoluteIndex,
              index: $index,
            }
          "
        >
        </ng-container>
      </div>
    }
  </gui-list>
</div>

<gui-errors [errors]="templateData.errors" [touched]="templateData.touched"></gui-errors>
