// apps/vue-playground/src/app/pages/dx-form/DxFormPage.vue
<script setup lang="ts">
import { buildKitchenSinkDx, initializeI18n, onFormEvent } from '@golemui/apps-shared';
import type { FormHealth } from '@golemui/core';
import type { GuiFormInitConfig } from '@golemui/gui-shared';
import { GuiForm } from '@golemui/gui-vue';
import snarkdown from 'snarkdown';
import { h, ref } from 'vue';
import AirportItemRenderer from '../../item-renderers/AirportItemRenderer.vue';
import ComplexListItemRenderer from '../../item-renderers/ComplexListItemRenderer.vue';
import CountryItemRenderer from '../../item-renderers/CountryItemRenderer.vue';
import ProductItemRenderer from '../../item-renderers/ProductItemRenderer.vue';

const localization = initializeI18n({});

const ks = buildKitchenSinkDx({
  widgetLoaders: {
    heading: async () => (await import('../../custom-fields/heading/HeadingComponent.vue')).default,
  },
  itemRenderers: {
    complexListItemRenderer: ComplexListItemRenderer,
    productItemRenderer: ProductItemRenderer,
    airportItemRenderer: AirportItemRenderer,
    countryItemRenderer: CountryItemRenderer,
  },
  dependencies: {
    markdown: {
      parse: (md: string) => snarkdown(md),
    },
  },
  // Vue-flavored Renderer example — the `render` function is called with the
  // form API and returns a VNode produced by Vue's `h()`.
  rendererExample: (api: any) =>
    h('h1', `Client name: ${api?.$form?.rendererClientName || 'unknown'}`),
});

const config: GuiFormInitConfig = {
  formDef: ks.formDef,
  data: ks.data,
  formSelectors: ks.formSelectors,
  formConfig: ks.formConfig,
  customValidators: ks.customValidators,
  localization,
};

const errors = ref<string[]>([]);

function onFormHealth(event: FormHealth) {
  if (event.status === 'errored') {
    errors.value = [...errors.value, event.message];
  }
}
</script>

<template>
  <div>
    <div
      v-if="errors.length"
      style="border: 2px solid red; padding: 8px 12px; margin-bottom: 12px; color: red"
    >
      <ul style="margin: 0; padding-left: 20px">
        <li v-for="(error, i) in errors" :key="i">{{ error }}</li>
      </ul>
    </div>
    <GuiForm :config="config" @form-event="onFormEvent" @form-health="onFormHealth" />
  </div>
</template>

// apps/rob-demo/src/app/dx-form.page.tsx
import { buildKitchenSinkDx, initializeI18n, onFormEvent } from '@golemui/apps-shared';
import type { FormHealth } from '@golemui/core';
import { GuiForm } from '@golemui/gui-react';
import { useCallback, useState } from 'react';
import snarkdown from 'snarkdown';
import { AirportItemRenderer } from './item-renderers/AirportItemRenderer';
import { ComplexListItemRenderer } from './item-renderers/ComplexListItemRenderer';
import { CountryItemRenderer } from './item-renderers/CountryItemRenderer';
import { ProductItemRenderer } from './item-renderers/ProductItemRenderer';

const localization = initializeI18n({});

const ks = buildKitchenSinkDx({
  widgetLoaders: {
    heading: async () =>
      (await import('./custom-fields/heading/heading.component')).HeadingComponent,
  },
  itemRenderers: {
    complexListItemRenderer: ComplexListItemRenderer,
    productItemRenderer: ProductItemRenderer,
    airportItemRenderer: AirportItemRenderer,
    countryItemRenderer: CountryItemRenderer,
  },
  dependencies: {
    markdown: {
      parse: (md: string) => snarkdown(md),
    },
  },
  rendererExample: (api: any) => (
    <h1>Client name: {api?.$form?.rendererClientName || 'unknown'}</h1>
  ),
});

const config = {
  formDef: ks.formDef,
  data: ks.data,
  formSelectors: ks.formSelectors,
  formConfig: ks.formConfig,
  customValidators: ks.customValidators,
  localization,
};

export function DxFormPage() {
  const [errors, setErrors] = useState<string[]>([]);

  const onFormHealth = useCallback((event: FormHealth) => {
    if (event.status === 'errored') {
      setErrors((prev) => [...prev, event.message]);
    }
  }, []);

  return (
    <div>
      {errors.length > 0 && (
        <div className="rob-errors">
          <ul>
            {errors.map((error, i) => (
              <li key={i}>{error}</li>
            ))}
          </ul>
        </div>
      )}
      <GuiForm config={config} formEvent={onFormEvent} formHealth={onFormHealth} />
    </div>
  );
}
