// apps/nextjs-playground/src/app/dx/kitchen-sink/page.tsx
'use client';

import {
  buildKitchenSinkDx,
  initializeI18n,
  mockUploadService,
  onFormEvent,
} from '@golemui/apps-shared';
import type { FormHealth } from '@golemui/core';
import { GuiForm } from '@golemui/gui-react';
import { useCallback, useState } from 'react';
import snarkdown from 'snarkdown';
import { customWidgetLoaders } from '../../../components/custom-widget-loaders';
import { AirportItemRenderer } from '../../../components/item-renderers/AirportItemRenderer';
import { ComplexListItemRenderer } from '../../../components/item-renderers/ComplexListItemRenderer';
import { CountryItemRenderer } from '../../../components/item-renderers/CountryItemRenderer';
import { ProductItemRenderer } from '../../../components/item-renderers/ProductItemRenderer';
import type { GuiFormInitConfig } from '@golemui/gui-shared';

const localization = initializeI18n({});

const ks = buildKitchenSinkDx({
  // Shared module-scope loaders: identical references to the ones preloaded in
  // GolemuiProvider, so the registry cache hits.
  widgetLoaders: customWidgetLoaders,
  itemRenderers: {
    complexListItemRenderer: ComplexListItemRenderer,
    productItemRenderer: ProductItemRenderer,
    airportItemRenderer: AirportItemRenderer,
    countryItemRenderer: CountryItemRenderer,
  },
  dependencies: {
    markdown: {
      parse: (md: string) => snarkdown(md),
    },
    uploadService: mockUploadService,
  },
  // React-flavored Renderer example — the `render` function is called with the
  // form API and returns a ReactNode (JSX).
  rendererExample: (api: any) => (
    <h1>Client name: {api?.$form?.rendererClientName || 'unknown'}</h1>
  ),
});

const config: GuiFormInitConfig = {
  // Stable id: with SSR the server and client must agree on the form id.
  formName: 'nextjs-dx-kitchen-sink',
  formDef: ks.formDef,
  data: ks.data,
  formSelectors: ks.formSelectors,
  formConfig: ks.formConfig,
  customValidators: ks.customValidators,
  localization,
};

export default function KitchenSinkDxPage() {
  const [errors, setErrors] = useState<string[]>([]);

  const onFormHealth = useCallback((event: FormHealth) => {
    if (event.status === 'errored') {
      setErrors((prev) => [...prev, event.message]);
    }
  }, []);

  return (
    <div>
      {errors.length > 0 && (
        <div
          style={{
            border: '2px solid red',
            padding: '8px 12px',
            marginBottom: '12px',
            color: 'red',
          }}
        >
          <ul style={{ margin: 0, paddingLeft: '20px' }}>
            {errors.map((error, i) => (
              <li key={i}>{error}</li>
            ))}
          </ul>
        </div>
      )}
      <GuiForm config={config} formEvent={onFormEvent} formHealth={onFormHealth} />
    </div>
  );
}

// apps/nuxt-playground/app/pages/json/kitchen-sink.vue
<script setup lang="ts">
import {
  allowedNames,
  commonLanguages,
  initializeI18n,
  kitchenSink,
  mockUploadService,
  onFormEvent,
} from '@golemui/apps-shared';
import {
  type FormEvent,
  type FormHealth,
  type FormSubmitEvent,
  type ValidateOn,
  devToolsMiddleware,
} from '@golemui/core';
import { GuiForm } from '@golemui/gui-vue';
import type { Dependencies, GuiFormInitConfig } from '@golemui/gui-shared';
import type { CustomValidatorSchemas } from '@golemui/gui-validators';
import type { VueItemRenderer } from '@golemui/vue';
import i18next from 'i18next';
import snarkdown from 'snarkdown';
import CustomFormHealthBoundary from '~/components/CustomFormHealthBoundary.vue';
import AirportItemRenderer from '~/components/item-renderers/AirportItemRenderer.vue';
import ComplexListItemRenderer from '~/components/item-renderers/ComplexListItemRenderer.vue';
import CountryItemRenderer from '~/components/item-renderers/CountryItemRenderer.vue';
import ProductItemRenderer from '~/components/item-renderers/ProductItemRenderer.vue';
import { customWidgetLoaders } from '~/utils/custom-widget-loaders';

const mock = kitchenSink;
const formData = mock.data;
const formMeta = mock.meta;
// i18next is a module level singleton. On the server every request re-initializes it with the
// same resources, which is fine for a playground; an app would scope the translator per request.
const localization = initializeI18n(mock.resources);
const languages = commonLanguages
  .filter(({ code }) => Object.keys(mock.resources).includes(code))
  .map(({ code, label, flag }) => ({
    value: code,
    label: `${flag} ${label}`,
  }));
const deps: Dependencies = {
  markdown: {
    parse: (md: string) => snarkdown(md),
  },
  uploadService: mockUploadService,
};
const middlewares = [devToolsMiddleware()];
const customValidators: CustomValidatorSchemas = {
  allowedNames,
};
const itemRenderers: Record<string, VueItemRenderer<any>> = {
  complexListItemRenderer: ComplexListItemRenderer,
  productItemRenderer: ProductItemRenderer,
  airportItemRenderer: AirportItemRenderer,
  countryItemRenderer: CountryItemRenderer,
};
const validateOn: ValidateOn = 'eager';
function formEventHandler(event: FormEvent) {
  if (mock.onFormEvent) mock.onFormEvent(event);
  onFormEvent(event);
}
function formSubmitHandler(event: FormSubmitEvent) {
  console.log('👉 onFormSubmit', event.data);
}

const config: GuiFormInitConfig = {
  // An explicit name keeps the form id identical on the server and the client.
  formName: 'json-kitchen-sink',
  formDef: mock.form,
  data: formData,
  meta: formMeta,
  customValidators,
  middlewares,
  itemRenderers,
  localization,
  dependencies: deps,
  functions: mock.functions,
  customWidgetLoaders,
  validateOn,
};

const onFormHealth = (formHealth: FormHealth) => {
  if (formHealth.status === 'errored') {
    console.log('GolemUI form health error:', formHealth.message);
  }
};

const onLanguageChanged = (event: Event) => {
  const code = (event as CustomEvent<{ value: string }>).detail.value;
  i18next.changeLanguage(code);
};
</script>

<template>
  <div>
    <div v-if="languages.length > 0">
      <!-- `.prop` keeps the options off the server markup; an attribute would stringify them. -->
      <gui-select
        label="Language picker"
        uid="language"
        value="en"
        :options.prop="languages"
        @gui-change="onLanguageChanged"
      ></gui-select>
    </div>
    <GuiForm
      :config="config"
      autocomplete="off"
      :form-health-boundary="CustomFormHealthBoundary"
      @form-health="onFormHealth"
      @form-event="formEventHandler"
      @form-submit="formSubmitHandler"
    />
  </div>
</template>
