// apps/vue-playground/src/app/custom-fields/heading/HeadingComponent.vue
<script setup lang="ts">
import type { DisplayWidget, WithWidget } from '@golemui/core';
import { useDisplayWidget } from '@golemui/vue';
import { computed, h } from 'vue';

type OwnWidgetProps = {
  text: string;
  level?: number;
};

const props = defineProps<WithWidget>();
const widget = props.widget as DisplayWidget;
const { uid, templateData } = useDisplayWidget<OwnWidgetProps>(widget);

const Heading = computed(() => {
  const level = templateData.value.level || 1;
  const tag = `h${level}`;
  return h(tag, { class: 'heading' }, templateData.value.text);
});
</script>

<template>
  <div class="gui-widget" :id="uid">
    <component :is="Heading" />
  </div>
</template>

<style scoped>
.heading {
  color: var(--gui-color-primary);
  margin: 0;
}
</style>

// apps/react-playground/src/app/custom-fields/heading/heading.component.tsx
import type { DisplayWidget, WithWidget } from '@golemui/core';
import { useDisplayWdiget } from '@golemui/react';
import { createElement, type PropsWithChildren } from 'react';
import styles from './heading.component.module.scss';

type OwnWidgetProps = {
  text: string;
  level?: number;
};

export function HeadingComponent(fieldInstance: WithWidget) {
  const field = fieldInstance.widget as DisplayWidget;
  const { uid, templateData } = useDisplayWdiget<OwnWidgetProps>(field);

  return (
    <div className="gui-widget" id={uid}>
      <DynamicHeading level={templateData.level || 1}>{templateData.text}</DynamicHeading>
    </div>
  );
}

function DynamicHeading({ level, children }: PropsWithChildren<{ level: number }>) {
  const HeadingTag = `h${level}`;

  return createElement(HeadingTag, { className: styles.heading }, children);
}

export default HeadingComponent;
