// libs/react-vanilla/src/lib/components/Tabs.tsx
import * as Core from '@golemui/core';
import { cn, useLayoutWidget, WidgetRenderer } from '@golemui/react';
import { createIntersectionObserver, TabsProps } from '@golemui/shared-vanilla';
import React, { useCallback, useEffect, useRef, useState } from 'react';

export function Tabs(widgetInstance: Core.WithWidget) {
  const containerRef = useRef<HTMLDivElement>(null);
  const widget = widgetInstance.widget as Core.LayoutWidget;
  const { uid, children, templateData, onChange } = useLayoutWidget<TabsProps>(widget);
  const tabRefs = useRef<HTMLButtonElement[]>([]);
  const startSentinelRef = useRef<HTMLLIElement>(null);
  const endSentinelRef = useRef<HTMLLIElement>(null);
  const [isStartVisible, setIsStartVisible] = useState(false);
  const [isEndVisible, setIsEndVisible] = useState(false);
  const [activeTab, setActiveTab] = useState(templateData.defaultOpen);

  useEffect(() => {
    const startSentinel = startSentinelRef.current;
    const endSentinel = endSentinelRef.current;

    const startObserver = createIntersectionObserver(startSentinel!, (isIntersecting) =>
      setIsStartVisible(isIntersecting),
    );
    const endObserver = createIntersectionObserver(endSentinel!, (isIntersecting) =>
      setIsEndVisible(isIntersecting),
    );

    return () => {
      startObserver.disconnect();
      endObserver.disconnect();
    };
  }, []);

  useEffect(() => {
    if (activeTab === undefined && templateData.tabs?.length > 0) {
      setActiveTab(templateData.tabs[0].uid);
    }
  }, [templateData.tabs, activeTab]);

  useEffect(() => {
    if (templateData.defaultOpen) {
      setActiveTab(templateData.defaultOpen);
    }
  }, [templateData.defaultOpen]);

  useEffect(() => {
    const tabs = templateData.tabs || [];
    const currentIndex = tabs.findIndex((tab) => tab.uid === activeTab);
    if (currentIndex > -1) {
      tabRefs.current[currentIndex].scrollIntoView();
    }
  }, [activeTab, templateData.tabs]);

  const handleTabChange = useCallback(
    (uid: string) => {
      setActiveTab(uid);
      onChange(uid);
    },
    [onChange],
  );

  const onKeyDown = useCallback(
    (event: React.KeyboardEvent) => {
      const currentIndex = templateData.tabs.findIndex((tab) => tab.uid === activeTab);
      const tabButtons = tabRefs.current;
      const isRTL = containerRef.current
        ? window.getComputedStyle(containerRef.current).direction === 'rtl'
        : false;

      switch (event.key) {
        case 'ArrowLeft': {
          const nextIndex = currentIndex + (isRTL ? 1 : -1);

          if (nextIndex >= 0 && nextIndex < templateData.tabs.length) {
            handleTabChange(templateData.tabs[nextIndex].uid);
            tabButtons[nextIndex]?.focus();
          }
          break;
        }
        case 'ArrowRight': {
          const nextIndex = currentIndex + (isRTL ? -1 : 1);

          if (nextIndex >= 0 && nextIndex < templateData.tabs.length) {
            handleTabChange(templateData.tabs[nextIndex].uid);
            tabButtons[nextIndex]?.focus();
          }
          break;
        }
        case 'Home':
          handleTabChange(templateData.tabs[0].uid);
          tabButtons[0]?.focus();
          break;
        case 'End':
          handleTabChange(templateData.tabs[templateData.tabs.length - 1].uid);
          tabButtons[templateData.tabs.length - 1]?.focus();
          break;
        default:
          return;
      }
    },
    [activeTab, templateData.tabs, handleTabChange],
  );

  const renderTabs = useCallback(() => {
    const tabs = templateData.tabs || [];
    return tabs.map((tab, index) => {
      return (
        <li role="presentation" key={`tab_${widget.uid}_${tab.uid}`}>
          <button
            ref={(el) => {
              tabRefs.current[index] = el!;
            }}
            type="button"
            role="tab"
            tabIndex={tab.uid === activeTab ? undefined : -1}
            data-cy={`tab_${widget.uid}_${index}`}
            id={`tab_${widget.uid}_${index}`}
            aria-controls={`tabpanel_${widget.uid}_${index}`}
            aria-selected={tab.uid === activeTab ? 'true' : 'false'}
            className={`${tab.uid === activeTab ? 'active' : ''}`}
            onClick={() => handleTabChange(tab.uid)}
            onKeyDown={(event: React.KeyboardEvent) => onKeyDown(event)}
            onFocus={(event: React.FocusEvent) => {
              event.target.scrollIntoView();
            }}
          >
            {tab.label}
          </button>
        </li>
      );
    });
  }, [templateData, activeTab, widget, tabRefs, handleTabChange, onKeyDown]);

  const renderWidgets = useCallback(() => {
    const activeSectionIndex = children.findIndex((section: any) => section.uid === activeTab);

    return children
      .filter((widget) => widget.uid === activeTab || templateData.renderMode !== 'activeOnly')
      .map((section) => (
        <section
          key={`tabpanel_${widget.uid}_${section.uid}`}
          role="tabpanel"
          data-cy={`tabpanel_${widget.uid}_${activeSectionIndex}`}
          id={`tabpanel_${widget.uid}_${activeSectionIndex}`}
          hidden={section.uid !== activeTab && templateData.renderMode !== 'activeOnly'}
          aria-labelledby={`tab_${widget.uid}_${activeSectionIndex}`}
        >
          <WidgetRenderer key={section.uid} widget={section as Core.NonFunctionWidget<string>} />
        </section>
      ));
  }, [children, activeTab, widget]);

  return (
    <div className="gui-tabs" style={{ flex: templateData.size }}>
      <nav
        className={cn({
          'gui-widget': true,
          'gui-widget--horizontal': true,
          'gui-tabs--start-shadow': !isStartVisible,
          'gui-tabs--end-shadow': !isEndVisible,
        })}
        id={uid}
      >
        <ul role="tablist">
          <li role="presentation" ref={startSentinelRef} className="gui-sentinel"></li>
          {renderTabs()}
          <li role="presentation" ref={endSentinelRef} className="gui-sentinel"></li>
        </ul>
      </nav>
      {renderWidgets()}
    </div>
  );
}

// libs/angular-vanilla/src/lib/components/tabs/tabs.component.ts
import { CommonModule } from '@angular/common';
import {
  AfterViewInit,
  Component,
  ElementRef,
  inject,
  OnDestroy,
  OnInit,
  signal,
  viewChild,
  viewChildren,
} from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import { createIntersectionObserver, TabsEventDetail, TabsProps } from '@golemui/shared-vanilla';

@Component({
  standalone: true,
  selector: 'gui-tabs-layout',
  imports: [CommonModule, Angular.WidgetDirective],
  providers: [Angular.LayoutWidgetAdapter],
  templateUrl: './tabs.component.html',
  host: {
    class: 'gui-tabs',
    '[style.flex]': 'this.adapter.templateData().size',
  },
})
export class TabsComponent implements OnInit, AfterViewInit, OnDestroy, Core.WithWidget {
  elementRef = inject(ElementRef);
  tabButtons = viewChildren<ElementRef>('tabButtonRef');
  startSentinel = viewChild.required<ElementRef>('startSentinel');
  endSentinel = viewChild.required<ElementRef>('endSentinel');
  widget!: Core.LayoutWidget;

  activeTab = signal('');
  isStartVisible = signal(false);
  isEndVisible = signal(false);

  protected adapter: Angular.LayoutWidgetAdapter<TabsProps> = inject(Angular.LayoutWidgetAdapter);
  private startObserver: IntersectionObserver | undefined;
  private endObserver: IntersectionObserver | undefined;

  ngOnInit(): void {
    const props: TabsProps = this.widget.props as TabsProps;
    this.adapter.init(this.widget);
    this.activeTab.set(props.defaultOpen ?? props.tabs[0].uid);

    this.startObserver = createIntersectionObserver(
      this.startSentinel().nativeElement,
      (isIntersecting: boolean) => this.isStartVisible.set(isIntersecting),
    );
    this.endObserver = createIntersectionObserver(
      this.endSentinel().nativeElement,
      (isIntersecting: boolean) => this.isEndVisible.set(isIntersecting),
    );
  }

  ngAfterViewInit() {
    // Scroll into view the active tab, just in case it's out of view
    const tabs = (this.widget.props as TabsProps).tabs;
    const currentIndex = tabs.findIndex((tab) => tab.uid === this.activeTab());
    this.tabButtons()[currentIndex].nativeElement.scrollIntoView();
  }

  onClickTab(uid: string) {
    this.activeTab.set(uid);
    this.adapter.change<TabsEventDetail>(uid);
  }

  onFocus(event: FocusEvent) {
    (event.target as Element).scrollIntoView();
  }

  onKeyDown($event: KeyboardEvent) {
    const tabs = (this.widget.props as TabsProps).tabs;
    const currentIndex = tabs.findIndex((tab) => tab.uid === this.activeTab());
    const isRTL = window.getComputedStyle(this.elementRef.nativeElement).direction === 'rtl';

    switch ($event.key) {
      case 'ArrowLeft': {
        const nextIndex = currentIndex + (isRTL ? 1 : -1);

        if (nextIndex >= 0 && nextIndex < tabs.length) {
          this.activeTab.set(tabs[nextIndex].uid);
          this.tabButtons()[nextIndex].nativeElement.focus();
        }
        break;
      }
      case 'ArrowRight': {
        const nextIndex = currentIndex + (isRTL ? -1 : 1);

        if (nextIndex >= 0 && nextIndex < tabs.length) {
          this.activeTab.set(tabs[nextIndex].uid);
          this.tabButtons()[nextIndex].nativeElement.focus();
        }
        break;
      }
      case 'Home':
        this.activeTab.set(tabs[0].uid);
        this.tabButtons()[0].nativeElement.focus();
        break;
      case 'End':
        this.activeTab.set(tabs[tabs.length - 1].uid);
        this.tabButtons()[tabs.length - 1].nativeElement.focus();
        break;
      default:
        return;
    }
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
    this.startObserver?.disconnect();
    this.endObserver?.disconnect();
  }
}

@let templateData = adapter.templateData();

<nav
  class="gui-widget gui-widget--horizontal"
  [class.gui-tabs--start-shadow]="!isStartVisible()"
  [class.gui-tabs--end-shadow]="!isEndVisible()"
  [id]="widget.uid"
>
  <ul role="tablist">
    <li role="presentation" #startSentinel class="gui-sentinel"></li>
    @for (tab of templateData.tabs; track tab.uid; let i = $index) {
      <li role="presentation">
        <button
          #tabButtonRef
          type="button"
          role="tab"
          [attr.data-cy]="'tab_' + widget.uid + '_' + i"
          [tabindex]="tab.uid === activeTab() ? null : -1"
          [id]="'tab_' + widget.uid + '_' + i"
          [attr.aria-controls]="'tabpanel_' + widget.uid + '_' + i"
          [attr.aria-selected]="tab.uid === activeTab() ? 'true' : 'false'"
          [class.active]="tab.uid === activeTab()"
          (click)="onClickTab(tab.uid)"
          (keydown)="onKeyDown($event)"
          (focus)="onFocus($event)"
        >
          {{ tab.label }}
        </button>
      </li>
    }
    <li role="presentation" #endSentinel class="gui-sentinel"></li>
  </ul>
</nav>

@for (child of templateData.children; track child.uid; let i = $index) {
  @if (child.uid === activeTab() || templateData.renderMode !== 'activeOnly') {
    <section
      role="tabpanel"
      tabindex="0"
      [hidden]="child.uid !== activeTab() && templateData.renderMode !== 'activeOnly'"
      [attr.data-cy]="'tabpanel_' + widget.uid + '_' + i"
      [id]="'tabpanel_' + widget.uid + '_' + i"
      [attr.aria-labelledby]="'tab_' + widget.uid + '_' + i"
    >
      <ng-container guiWidget [widget]="child" />
    </section>
  }
}
