// libs/angular-vanilla/src/lib/alert/alert.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import { AlertProps } from '@golemui/shared-vanilla';

@Component({
  standalone: true,
  selector: 'gui-alert',
  imports: [CommonModule],
  providers: [Angular.DisplayFieldAdapter],
  templateUrl: './alert.component.html',
  styleUrls: ['../styles.scss', './alert.component.scss'],
  host: {
    class: 'gui-alert',
  },
})
export class AlertComponent implements OnInit, OnDestroy, Core.WithField {
  field!: Core.DisplayField;

  protected adapter: Angular.DisplayFieldAdapter<AlertProps> = inject(Angular.DisplayFieldAdapter);

  ngOnInit(): void {
    this.adapter.init(this.field);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

@let templateData = adapter.templateData();

<div class="gui-field" [id]="field.uid">
  <div
    role="alert"
    class="gui-alert-notification"
    [ngClass]="`gui-alert-notification--${templateData.level || 'default'}`"
  >
    {{ templateData.text }}
  </div>
</div>

// libs/react-vanilla/src/lib/components/Alert.tsx
import * as Core from '@golemui/core';
import { useDisplayField } from '@golemui/react';
import { AlertProps } from '@golemui/shared-vanilla';

export function Alert(fieldInstance: Core.WithField) {
  const field = fieldInstance.field as Core.DisplayField;
  const { uid, templateData } = useDisplayField<AlertProps>(field);

  return (
    <div className="gui-alert">
      <div className="gui-field" id={uid}>
        <div
          role="alert"
          className={`gui-alert-notification gui-alert-notification--${templateData.level || 'default'}`}
        >
          {templateData.text}
        </div>
      </div>
    </div>
  );
}
