// libs/angular-vanilla/src/lib/components/alert/alert.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import { AlertProps } from '@golemui/shared-vanilla';

@Component({
  standalone: true,
  selector: 'gui-alert-display',
  imports: [CommonModule],
  providers: [Angular.DisplayWidgetAdapter],
  templateUrl: './alert.component.html',
  host: {
    class: 'gui-alert',
    '[style.flex]': 'this.adapter.templateData().size',
  },
})
export class AlertComponent implements OnInit, OnDestroy, Core.WithWidget {
  widget!: Core.DisplayWidget;

  protected adapter: Angular.DisplayWidgetAdapter<AlertProps> = inject(
    Angular.DisplayWidgetAdapter,
  );

  ngOnInit(): void {
    this.adapter.init(this.widget);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

@let templateData = adapter.templateData();

<div class="gui-widget" [id]="widget.uid">
  <div
    role="alert"
    class="gui-alert-notification"
    [ngClass]="`gui-alert-notification--${templateData.level || 'default'}`"
  >
    {{ templateData.text }}
  </div>
</div>

// libs/react-vanilla/src/lib/components/Alert.tsx
import * as Core from '@golemui/core';
import { useDisplayWdiget } from '@golemui/react';
import { AlertProps } from '@golemui/shared-vanilla';

export function Alert(widgetInstance: Core.WithWidget) {
  const widget = widgetInstance.widget as Core.DisplayWidget;
  const { uid, templateData } = useDisplayWdiget<AlertProps>(widget);

  return (
    <div className="gui-alert" style={{ flex: templateData.size }}>
      <div className="gui-field" id={uid}>
        <div
          role="alert"
          className={`gui-alert-notification gui-alert-notification--${templateData.level || 'default'}`}
        >
          {templateData.text}
        </div>
      </div>
    </div>
  );
}
