// libs/gui/vue/src/lib/components/Alert.vue
<script setup lang="ts">
import type { DisplayWidget, WithWidget } from '@golemui/core';
import { useDisplayWidget } from '@golemui/vue';
import type { AlertProps } from '@golemui/gui-shared';

const props = defineProps<WithWidget>();
const widget = props.widget as DisplayWidget;
const { uid, templateData } = useDisplayWidget<AlertProps>(widget);
</script>

<template>
  <div class="gui-alert gui-field" :style="{ flex: templateData.size }">
    <div class="gui-widget" :id="uid">
      <div
        role="alert"
        :class="`gui-alert-notification gui-alert-notification--${templateData.level || 'default'}`"
      >
        {{ templateData.text }}
      </div>
    </div>
  </div>
</template>

// libs/react-vanilla/src/lib/components/Alert.tsx
import * as Core from '@golemui/core';
import { useDisplayWdiget } from '@golemui/react';
import { AlertProps } from '@golemui/shared-vanilla';

export function Alert(widgetInstance: Core.WithWidget) {
  const widget = widgetInstance.widget as Core.DisplayWidget;
  const { uid, templateData } = useDisplayWdiget<AlertProps>(widget);

  return (
    <div className="gui-alert" style={{ flex: templateData.size }}>
      <div className="gui-field" id={uid}>
        <div
          role="alert"
          className={`gui-alert-notification gui-alert-notification--${templateData.level || 'default'}`}
        >
          {templateData.text}
        </div>
      </div>
    </div>
  );
}
