// libs/angular-vanilla/src/lib/checkbox/checkbox.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import * as Angular from '@formforge/angular';
import * as Core from '@formforge/core';
import { CheckboxProps } from '@formforge/shared-vanilla';

@Component({
  standalone: true,
  selector: 'ff-checkbox',
  imports: [CommonModule],
  providers: [Angular.ControlAdapter],
  templateUrl: './checkbox.component.html',
  host: {
    class: 'ff-checkbox',
    '[class.ff-checkbox--left]': 'adapter.templateData().checkboxPosition === "left"',
  },
})
export class CheckboxComponent implements OnInit, OnDestroy, Core.WithField {
  field!: Core.ControlField<string>;
  protected adapter: Angular.ControlAdapter<string, CheckboxProps> = inject(Angular.ControlAdapter);

  ngOnInit(): void {
    this.adapter.init(this.field);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }

  valueChanged(event: Event) {
    const target = event.target as HTMLInputElement;
    this.adapter.valueChanged(target.checked);
  }
}

@let templateData = adapter.templateData();

<label [for]="field.uid">{{
  templateData.label + (templateData.validator?.required ? ' *' : '')
}}</label>

<div class="gui-field gui-field--horizontal">
  <input
    type="checkbox"
    [id]="field.uid"
    [value]="templateData.value ?? false"
    [disabled]="templateData.disabled"
    [attr.aria-readonly]="templateData.readonly"
    [attr.aria-required]="templateData.validator?.required"
    [attr.aria-checked]="templateData.value ?? false"
    (click)="!templateData.readonly && valueChanged($event)"
    (blur)="adapter.onBlur()"
  />
</div>

// libs/react-vanilla/src/lib/components/Checkbox.tsx
import * as Core from '@golemui/core';
import { useControlField } from '@golemui/react';
import { CheckboxProps } from '@golemui/shared-vanilla';
import { useCallback } from 'react';
import '../styles.scss';
import { Errors } from './shared/Errors';

export function Checkbox(fieldInstance: Core.WithField) {
  const field = fieldInstance.field as Core.ControlField<boolean>;
  const {
    uid,
    validator,
    errors,
    value,
    isDisabled,
    isReadonly,
    label,
    onValueChanged,
    onBlur,
    props,
  } = useControlField<boolean, CheckboxProps>(field);

  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => !isReadonly && onValueChanged(e.target.checked),
    [onValueChanged, isReadonly],
  );

  const checkboxPosition = props.checkboxPosition;

  return (
    <div className={`gui-checkbox ${checkboxPosition === 'left' ? 'gui-checkbox--left' : ''}`}>
      <label htmlFor={uid}>{label + (validator?.required ? ' *' : '')}</label>

      <div className="gui-field gui-field--horizontal">
        <input
          type="checkbox"
          id={uid}
          checked={value ?? false}
          disabled={isDisabled}
          aria-checked={value ?? false}
          aria-readonly={isReadonly}
          onChange={handleChange}
          onBlur={onBlur}
        />
      </div>
      <Errors errors={errors} />
    </div>
  );
}
