// libs/gui/vue/src/lib/components/Checkbox.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/vue';
import type { CheckboxProps } from '@golemui/gui-shared';
import { computed } from 'vue';
import '@golemui/gui-components/checkbox';

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<boolean>;
const { uid, errors, value, isTouched, templateData, onValueChanged, onBlur } = useInputWidget<
  boolean,
  CheckboxProps
>(widget);

const handleChange = (e: Event) => onValueChanged((e as CustomEvent).detail.value);
const required = computed(() => (templateData.value.validator as Validator)?.required);
// Mirror Lit class-field default to avoid Vue coercing undefined → '' on the enum prop.
const checkboxPosition = computed(() => templateData.value.checkboxPosition || 'left');
</script>

<template>
  <div class="gui-checkbox gui-field" :style="{ flex: templateData.size }">
    <gui-checkbox
      :uid="uid"
      :label="templateData.label"
      :errors="errors"
      :touched="isTouched"
      :required="required"
      :disabled="templateData.disabled"
      :readOnly="templateData.readonly"
      :value="value"
      :hint="templateData.hint"
      :checkboxPosition.prop="checkboxPosition"
      @change="handleChange"
      @blur="onBlur"
    ></gui-checkbox>
  </div>
</template>

// libs/react-vanilla/src/lib/components/Checkbox.tsx
import * as Core from '@golemui/core';
import { useInputWidget } from '@golemui/react';
import { CheckboxProps } from '@golemui/shared-vanilla';
import { useCallback } from 'react';
import '../styles.scss';

export function Checkbox(widgetInstance: Core.WithWidget) {
  const widget = widgetInstance.widget as Core.InputWidget<boolean>;
  const { uid, errors, value, onValueChanged, onBlur, templateData, isTouched } = useInputWidget<
    boolean,
    CheckboxProps
  >(widget);

  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) =>
      onValueChanged((e.nativeEvent as CustomEvent).detail.value),
    [onValueChanged],
  );

  const label = templateData.label as string;
  const hint = templateData.hint;
  const checkboxPosition = templateData.checkboxPosition;
  const isDisabled = templateData.disabled as boolean;
  const isReadonly = templateData.readonly as boolean;
  const isRequired = (templateData.validator as Core.Validator)?.required;

  return (
    <div className={`gui-checkbox`} style={{ flex: templateData.size }}>
      <gui-checkbox
        uid={uid}
        label={label}
        errors={errors}
        touched={isTouched}
        required={isRequired}
        disabled={isDisabled}
        readOnly={isReadonly}
        value={value}
        hint={hint}
        checkboxPosition={checkboxPosition}
        onChange={handleChange}
        onBlur={onBlur}
      />
    </div>
  );
}
