// libs/gui/vue/src/lib/components/DatePicker.vue
<script setup lang="ts">
import type { InputWidget, Validator, WithWidget } from '@golemui/core';
import { useInputWidget } from '@golemui/vue';
import type { DatePickerProps } from '@golemui/gui-shared';
import { computed, onMounted, onUnmounted, ref, watch } from 'vue';
import Errors from './shared/Errors.vue';
import '@golemui/gui-components/date-input';
import '@golemui/gui-components/calendar';

const props = defineProps<WithWidget>();
const widget = props.widget as InputWidget<string>;
const {
  uid,
  errors,
  value,
  isTouched,
  templateData,
  onValueChanged,
  onBlur,
  injectValidationIssues,
} = useInputWidget<string, DatePickerProps>(widget);

const required = computed(() => (templateData.value.validator as Validator)?.required);
const showErrors = computed(() => isTouched.value && errors.value && errors.value.length > 0);

// Default to the same values as the Lit element's class-field initializers so
// we never pass undefined or '' (which Intl.DateTimeFormat rejects with a RangeError).
const dayFormat = computed(() => templateData.value.dayFormat || 'numeric');
const weekdayFormat = computed(() => templateData.value.weekdayFormat || 'narrow');
const monthFormat = computed(() => templateData.value.monthFormat || 'long');
const numberOfMonths = computed(() => templateData.value.numberOfMonths ?? 1);

const isCalendarOpen = ref(false);
const containerRef = ref<HTMLDivElement | null>(null);
const dateControlRef = ref<HTMLElement | null>(null);
const calendarControlRef = ref<HTMLElement | null>(null);

const dateChange = (e: Event) => {
  injectValidationIssues(null);
  onValueChanged((e as CustomEvent).detail.value);
};
const dateFocus = () => {
  isCalendarOpen.value = true;
};
const dateError = (e: Event) => {
  injectValidationIssues([(e as CustomEvent).detail.message]);
};
let currentDate: HTMLElement | null = null;
watch(dateControlRef, (el) => {
  if (currentDate) {
    currentDate.removeEventListener('change', dateChange);
    currentDate.removeEventListener('focus', dateFocus);
    currentDate.removeEventListener('blur', onBlur);
    currentDate.removeEventListener('inputError', dateError);
  }
  currentDate = el;
  if (el) {
    el.addEventListener('change', dateChange);
    el.addEventListener('focus', dateFocus);
    el.addEventListener('blur', onBlur);
    el.addEventListener('inputError', dateError);
  }
});

const calChange = (e: Event) => {
  injectValidationIssues(null);
  onValueChanged((e as CustomEvent).detail.value);
};
const calBlur = () => {
  onBlur();
  isCalendarOpen.value = false;
};
let currentCal: HTMLElement | null = null;
watch(calendarControlRef, (el) => {
  if (currentCal) {
    currentCal.removeEventListener('blur', calBlur);
    currentCal.removeEventListener('change', calChange);
  }
  currentCal = el;
  if (el) {
    el.addEventListener('blur', calBlur);
    el.addEventListener('change', calChange);
  }
});

const onDocumentClick = (event: MouseEvent) => {
  if (!isCalendarOpen.value) return;
  const path = event.composedPath();
  const inDate = dateControlRef.value && path.includes(dateControlRef.value);
  const inCal = calendarControlRef.value && path.includes(calendarControlRef.value);
  if (!inDate && !inCal) isCalendarOpen.value = false;
};

onMounted(() => document.addEventListener('click', onDocumentClick));
onUnmounted(() => {
  document.removeEventListener('click', onDocumentClick);
  currentDate?.removeEventListener('change', dateChange);
  currentDate?.removeEventListener('focus', dateFocus);
  currentDate?.removeEventListener('blur', onBlur);
  currentDate?.removeEventListener('inputError', dateError);
  currentCal?.removeEventListener('blur', calBlur);
  currentCal?.removeEventListener('change', calChange);
});

const onFocusOut = (event: FocusEvent) => {
  if (!isCalendarOpen.value) return;
  const newFocus = event.relatedTarget as Node;
  if (newFocus && containerRef.value?.contains(newFocus)) return;
  isCalendarOpen.value = false;
};

const toggleCalendar = (event: MouseEvent) => {
  const target = event.target as HTMLElement;
  const isInputClick = target.closest('.gui-date-input__part');
  const isCalendarClick = target.closest('gui-calendar');
  if (isInputClick || isCalendarClick) {
    if (!isCalendarOpen.value) isCalendarOpen.value = true;
  } else {
    isCalendarOpen.value = !isCalendarOpen.value;
  }
};

const onKeyUp = (event: KeyboardEvent) => {
  if (event.target !== event.currentTarget) return;
  if (event.key === 'Enter' || event.key === ' ') {
    isCalendarOpen.value = !isCalendarOpen.value;
  }
};
</script>

<template>
  <div
    ref="containerRef"
    class="gui-date-picker gui-field"
    :style="{ flex: templateData.size }"
    @focusout="onFocusOut"
  >
    <label v-if="templateData.label" class="gui-label" :for="uid" :data-cy="`${uid}_label`">
      {{ templateData.label }}{{ required ? ' *' : '' }}
      <div v-if="templateData.hint" class="gui-widget-hint" :id="`${uid}_hint`">
        {{ templateData.hint }}
      </div>
    </label>
    <div
      role="button"
      tabindex="-1"
      class="gui-widget"
      :aria-expanded="isCalendarOpen"
      @click="toggleCalendar"
      @keyup="onKeyUp"
    >
      <gui-date
        ref="dateControlRef"
        :uid="uid"
        :hint="templateData.hint"
        :showErrors="false"
        :errors="errors"
        :touched="isTouched"
        :required="required"
        :disabled="templateData.disabled"
        :readOnly="templateData.readonly"
        :value="value"
        :icon="templateData.icon"
        :localeId="templateData.lang"
      />
      <span class="gui-date-picker__arrow">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 256 256">
          <path
            d="M213.66,101.66l-80,80a8,8,0,0,1-11.32,0l-80-80A8,8,0,0,1,53.66,90.34L128,164.69l74.34-74.35a8,8,0,0,1,11.32,11.32Z"
          ></path>
        </svg>
      </span>
      <gui-calendar
        v-if="isCalendarOpen"
        ref="calendarControlRef"
        :uid="uid"
        :hint="templateData.hint"
        :touched="isTouched"
        :required="required"
        :disabled="templateData.disabled"
        :readOnly="templateData.readonly"
        :value="value"
        :prevMonthIcon="templateData.prevMonthIcon"
        :nextMonthIcon="templateData.nextMonthIcon"
        :prevMonthAriaLabel="templateData.prevMonthAriaLabel"
        :nextMonthAriaLabel="templateData.nextMonthAriaLabel"
        :dayFormat.prop="dayFormat"
        :weekdayFormat.prop="weekdayFormat"
        :monthFormat.prop="monthFormat"
        :minDate="templateData.minDate"
        :maxDate="templateData.maxDate"
        :disabledRanges="templateData.disabledRanges"
        :numberOfMonths.prop="numberOfMonths"
        :localeId="templateData.lang"
      />
    </div>
    <Errors v-if="showErrors" :errors="errors" :uid="uid" />
  </div>
</template>

// libs/react-vanilla/src/lib/components/DatePicker.tsx
import * as Core from '@golemui/core';
import { useInputWidget } from '@golemui/react';
import { DatePickerProps } from '@golemui/shared-vanilla';
import { useCallback, useEffect, useRef, useState } from 'react';
import '../styles.scss';
import { Errors } from './shared/Errors';

export function DatePicker(widgetInstance: Core.WithWidget) {
  const widget = widgetInstance.widget as Core.InputWidget<string>;
  const {
    uid,
    errors,
    value,
    isTouched,
    templateData,
    onValueChanged,
    onBlur,
    injectValidationIssues,
  } = useInputWidget<string, DatePickerProps>(widget);
  const [isCalendarOpen, setIsCalendarOpen] = useState(false);
  const dateControlRef = useRef<HTMLElement | null>(null);
  const calendarControlRef = useRef<HTMLElement | null>(null);

  const handleDateRef = useCallback(
    (node: HTMLElement | null) => {
      const target = node as any;
      const changeHandler = (e: CustomEvent) => {
        injectValidationIssues(null);
        onValueChanged(e.detail.value);
      };
      const errorHandler = (e: CustomEvent) => {
        injectValidationIssues([e.detail.message]);
      };
      const focusHandler = () => {
        setIsCalendarOpen(true);
      };

      dateControlRef.current = node;

      if (node) {
        target.addEventListener('change', changeHandler);
        target.addEventListener('focus', focusHandler);
        target.addEventListener('blur', onBlur);
        target.addEventListener('inputError', errorHandler);
      }

      return () => {
        target.removeEventListener('change', changeHandler);
        target.removeEventListener('focus', focusHandler);
        target.removeEventListener('blur', onBlur);
        target.removeEventListener('inputError', errorHandler);
      };
    },
    [onValueChanged, onBlur, injectValidationIssues],
  );

  const handleCalendarRef = useCallback(
    (node: HTMLElement | null) => {
      const target = node as any;
      const changeHandler = (e: CustomEvent) => {
        injectValidationIssues(null);
        onValueChanged(e.detail.value);
      };
      const blurHandler = (e: CustomEvent) => {
        onBlur();
        setIsCalendarOpen(false);
      };

      calendarControlRef.current = node;

      if (node) {
        target.addEventListener('blur', blurHandler);
        target.addEventListener('change', changeHandler);
      }

      return () => {
        target.addEventListener('blur', blurHandler);
        target.addEventListener('change', changeHandler);
      };
    },
    [onValueChanged, injectValidationIssues, onBlur],
  );

  useEffect(() => {
    const onDocumentClick = (event: MouseEvent) => {
      if (!isCalendarOpen) return;
      const path = event.composedPath();
      const clickedInsideDate = dateControlRef.current && path.includes(dateControlRef.current);
      const clickedInsideCalendar =
        calendarControlRef.current && path.includes(calendarControlRef.current);

      if (!clickedInsideDate && !clickedInsideCalendar) {
        setIsCalendarOpen(false);
      }
    };

    document.addEventListener('click', onDocumentClick);

    return () => {
      document.removeEventListener('click', onDocumentClick);
    };
  }, [isCalendarOpen]);

  const openCalendar = () => {
    if (!isCalendarOpen) setIsCalendarOpen(true);
  };

  const hint = templateData.hint;
  const icon = templateData.icon;
  const prevMonthIcon = templateData.prevMonthIcon;
  const nextMonthIcon = templateData.nextMonthIcon;
  const dayFormat = templateData.dayFormat;
  const weekdayFormat = templateData.weekdayFormat;
  const monthFormat = templateData.monthFormat;
  const showErrors = isTouched && errors && errors.length > 0;
  const isDisabled = templateData.disabled as boolean;
  const isReadonly = templateData.readonly as boolean;
  const isRequired = (templateData.validator as Core.Validator)?.required;
  const lang = templateData.lang;

  return (
    <div className="gui-date-picker" style={{ flex: templateData.size }}>
      {templateData.label && (
        <label className="gui-label" htmlFor={uid} data-cy={`${uid}_label`}>
          {templateData.label + (isRequired ? ' *' : '')}
          {hint && (
            <div className="gui-field-hint" id={`${uid}_hint`}>
              {hint}
            </div>
          )}
        </label>
      )}
      <div
        role="button"
        tabIndex={0}
        className="gui-field"
        onClick={openCalendar}
        onKeyUp={(event) => {
          if (event.key === 'Enter' || event.key === ' ') {
            openCalendar();
          }
        }}
        aria-expanded={isCalendarOpen}
      >
        <gui-date
          ref={handleDateRef}
          uid={uid}
          hint={hint}
          showErrors={false}
          errors={errors}
          touched={isTouched}
          required={isRequired}
          disabled={isDisabled}
          readOnly={isReadonly}
          value={value}
          icon={icon}
          localeId={lang}
        />

        {isCalendarOpen && (
          <gui-calendar
            ref={handleCalendarRef}
            uid={uid}
            hint={hint}
            touched={isTouched}
            required={isRequired}
            disabled={isDisabled}
            readOnly={isReadonly}
            value={value}
            prevMonthIcon={prevMonthIcon}
            nextMonthIcon={nextMonthIcon}
            dayFormat={dayFormat}
            weekdayFormat={weekdayFormat}
            monthFormat={monthFormat}
            localeId={lang}
          />
        )}
      </div>
      {showErrors && <Errors errors={errors} uid={uid} />}
    </div>
  );
}
