// libs/angular-vanilla/src/lib/components/dropdown/dropdown.component.ts
import { CommonModule } from '@angular/common';
import {
  Component,
  computed,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  HostListener,
  inject,
  OnDestroy,
  OnInit,
  signal,
  ViewChild,
} from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import { DropdownProps, ListItem } from '@golemui/shared-vanilla';
import { debounceTime, Subject, Subscription } from 'rxjs';
import { DefaultListItemRenderer } from '../list/default-list.item-renderer';

interface GuiListElement extends HTMLElement {
  focusItemAtIndex(index: number): void;
  scrollToSelectedIndex(): void;
}

@Component({
  standalone: true,
  selector: 'gui-dropdown-control',
  imports: [CommonModule],
  providers: [Angular.InputWidgetAdapter],
  templateUrl: './dropdown.component.html',
  host: {
    class: 'gui-dropdown',
    '[style.flex]': 'this.adapter.templateData().size',
  },
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class DropdownComponent implements OnInit, OnDestroy, Core.WithWidget {
  widget!: Core.InputWidget<string>;

  protected adapter: Angular.InputWidgetAdapter<string, DropdownProps<never>> = inject(
    Angular.InputWidgetAdapter,
  );
  private el = inject(ElementRef);

  @ViewChild('inputRef') inputRef!: ElementRef<HTMLInputElement>;
  @ViewChild('listRef') listRef!: ElementRef<GuiListElement>;

  protected defaultListItemRenderer: Angular.AngularItemRenderer<string> = DefaultListItemRenderer;

  protected currentRange = signal({ start: 0, end: 10 });
  protected listItems = signal<ListItem<never>[]>([]);
  protected focusedIndex = signal<number>(-1);
  protected isListVisible = signal(false);
  protected isFiltering = signal(false);

  protected selectedItem = signal<ListItem<never> | undefined>(undefined);
  protected filteredItems = signal<ListItem<never>[]>([]);

  protected asyncFiltering = computed(() => {
    return !!this.widget.on?.filter;
  });

  protected displayItems = computed(() => {
    const data = this.adapter.templateData();
    if (this.isFiltering() && !this.asyncFiltering()) {
      return this.filteredItems();
    }
    return data.items || [];
  });

  protected visibleItems = computed(() => {
    const items = this.listItems();
    const { start, end } = this.currentRange();
    return items.slice(start, end);
  });

  protected selectedItemValue = computed(() => {
    const data = this.adapter.templateData();
    const referenceField = data.labelField ?? data.valueField;
    return referenceField
      ? this.selectedItem()?.template[referenceField]
      : this.selectedItem()?.template;
  });

  protected debouncer = new Subject<string>();
  protected subscriptions: Subscription[] = [];

  ngOnInit(): void {
    this.adapter.init(this.widget);

    this.subscriptions.push(
      this.debouncer
        .pipe(debounceTime(this.adapter.templateData().inputDebounce ?? 500))
        .subscribe((value: string) => {
          this.inputValue(value);
        }),
    );
  }

  ngOnDestroy(): void {
    this.subscriptions.forEach((s) => s.unsubscribe());
    this.adapter.destroy();
  }

  @HostListener('document:click', ['$event'])
  onDocumentClick(event: MouseEvent) {
    if (!this.isListVisible()) return;

    if (!this.el.nativeElement.contains(event.target)) {
      this.closeList();
    }
  }

  protected onInputFocus() {
    this.isListVisible.set(true);

    setTimeout(() => {
      if (this.listRef?.nativeElement) {
        this.listRef.nativeElement.scrollToSelectedIndex();
      }
    }, 0);
  }

  protected onInputKeyDown(event: KeyboardEvent) {
    const key = event.key;

    switch (key) {
      case 'ArrowDown':
        event.preventDefault();
        this.isListVisible.set(true);

        setTimeout(() => {
          if (this.listRef?.nativeElement) {
            this.listRef.nativeElement.focus();
            this.listRef.nativeElement.scrollToSelectedIndex();
          }
        }, 0);
        break;
      case 'Enter':
        event.preventDefault();
        if (!this.inputRef.nativeElement.value) {
          // Field is empty and enter pressed, we clear the selection
          this.adapter.valueChanged(null);
          this.isListVisible.set(false);
          this.isFiltering.set(false);
        }
        break;
    }
  }

  protected onInput(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.debouncer.next(filterValue);
  }

  protected inputValue(filterValue: string) {
    const templateData = this.adapter.templateData();

    this.adapter.filterChanged(filterValue);

    if (filterValue && !this.asyncFiltering()) {
      this.isFiltering.set(true);
      this.isListVisible.set(true);

      const searchFields =
        templateData.searchFields ??
        ([templateData.labelField!, templateData.valueField!].filter(
          (field) => !!field,
        ) as string[]);
      const hasSearchFields = searchFields.length > 0;
      const items = templateData.items || [];
      const filtered = items.filter((item: any) => {
        const keys = Object.keys(item);

        // If it's a primitive value, we search by value
        const isPrimitiveValue = !keys.length;
        if (isPrimitiveValue) {
          return item.toString().toLowerCase().includes(filterValue.toLowerCase());
        }

        // Otherwise, we search by object
        const reduceFunc = (acc: boolean, prop: string) =>
          acc || item[prop].toString().toLowerCase().includes(filterValue.toLowerCase());

        return hasSearchFields
          ? keys.filter((prop: string) => searchFields.includes(prop)).reduce(reduceFunc, false)
          : keys.reduce(reduceFunc, false);
      });
      this.filteredItems.set(filtered);
    } else {
      this.isFiltering.set(false);
      this.filteredItems.set([...(templateData.items || [])]);
    }
  }

  protected onFocusOutInput(event: FocusEvent) {
    const newFocusTarget = event.relatedTarget as Node;

    if (newFocusTarget && this.el.nativeElement.contains(newFocusTarget)) {
      return;
    }

    this.closeList();
  }

  protected onClickItem(item: ListItem<never>, index: number) {
    const templateData = this.adapter.templateData();

    if (templateData.readonly) return;

    this.adapter.valueChanged(item.value);
    this.adapter.filterChanged('');

    this.focusedIndex.set(index);
    this.selectedItem.set(item);
    this.isFiltering.set(false);
    this.isListVisible.set(false);

    if (this.listRef?.nativeElement) {
      this.listRef.nativeElement.focusItemAtIndex(index);
    }
  }

  protected onFocusChange(event: Event) {
    const index = (event as CustomEvent).detail.index;
    this.focusedIndex.set(index);
  }

  protected onUpdateItems(event: Event) {
    const items = (event as CustomEvent).detail;
    this.listItems.set(items ? [...items] : []);
  }

  protected onRangeChange(event: Event) {
    const { startIndex, endIndex } = (event as CustomEvent).detail;
    this.currentRange.set({ start: startIndex, end: endIndex });
  }

  protected onListBlur() {
    this.closeList();
  }

  protected onValueChange(event: Event) {
    const value = (event as CustomEvent).detail.value;
    this.adapter.valueChanged(value);
    this.adapter.filterChanged('');
    this.selectedItem.set(this.listItems().find((item) => item.value === value));
    this.isListVisible.set(false);
    this.isFiltering.set(false);
  }

  private closeList() {
    this.adapter.onBlur();
    this.isListVisible.set(false);
    this.isFiltering.set(false);
  }
}

@let templateData = adapter.templateData();
@let itemRenderer = adapter.getItemRenderer(templateData.itemRenderer, defaultListItemRenderer);

<gui-label
  [targetElement]="[inputRef, listRef]"
  [uid]="widget.uid"
  [label]="templateData.label"
  [hint]="templateData.hint"
  [errors]="templateData.errors"
  [touched]="templateData.touched"
  [required]="templateData.validator?.required"
></gui-label>

<div class="gui-widget">
  <input
    #inputRef
    type="text"
    [id]="widget.uid"
    [required]="templateData.validator?.required"
    [disabled]="templateData.disabled"
    [readonly]="templateData.readonly"
    [placeholder]="templateData.placeholder ?? ''"
    [value]="selectedItemValue() ?? ''"
    (keydown)="onInputKeyDown($event)"
    (input)="onInput($event)"
    (focus)="onInputFocus()"
    (focusout)="onFocusOutInput($event)"
  />
  <gui-list
    #listRef
    [id]="widget.uid + '-list'"
    [uid]="widget.uid"
    [value]="templateData.value ?? ''"
    [valueField]="templateData.valueField"
    [items]="displayItems()"
    [itemHeight]="templateData.itemHeight"
    [height]="templateData.height"
    [required]="templateData.validator?.required"
    [touched]="templateData.touched"
    [disabled]="templateData.disabled"
    [readonly]="templateData.readonly"
    [hidden]="!isListVisible()"
    (gui-update-items)="onUpdateItems($event)"
    (gui-range-change)="onRangeChange($event)"
    (gui-focus-change)="onFocusChange($event)"
    (blur)="onListBlur()"
    (focus)="onInputFocus()"
    (focusout)="onFocusOutInput($event)"
    (change)="onValueChange($event)"
  >
    @for (item of visibleItems(); track $index) {
      @let absoluteIndex = currentRange().start + $index;

      <!-- eslint-disable-next-line @angular-eslint/template/click-events-have-key-events -->
      <div
        role="option"
        tabindex="-1"
        class="gui-list__item-wrapper"
        [id]="widget.uid + '-item-' + absoluteIndex"
        [style.height.px]="templateData.itemHeight || 40"
        [attr.aria-selected]="templateData.value === item.value"
        (click)="onClickItem(item, absoluteIndex)"
      >
        <ng-container
          *ngComponentOutlet="
            itemRenderer;
            inputs: {
              template: item.template,
              value: item.value,
              disabled: templateData.disabled,
              selected: templateData.value === item.value,
              focused: focusedIndex() === absoluteIndex,
              index: absoluteIndex,
            }
          "
        >
        </ng-container>
      </div>
    }
  </gui-list>
</div>

<gui-errors [errors]="templateData.errors" [touched]="templateData.touched"></gui-errors>

// libs/react-vanilla/src/lib/components/Dropdown.tsx
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import * as Core from '@golemui/core';
import { useControlField, useDebounceCallback, useItemRenderer } from '@golemui/react'; // Asumiendo que exportaste el hook que creamos
import { DropdownProps, ListItem, OptionValue } from '@golemui/shared-vanilla';
import { DefaultListItemRenderer } from './item-renderers/DefaultListItemRenderer';
import { ListItemRendererProps } from './item-renderers/props';

interface GuiListElement extends HTMLElement {
  focusItemAtIndex(index: number): void;
  scrollToSelectedIndex(): void;
}

interface GuiLabelElement extends HTMLElement {
  targetElement?: HTMLElement | HTMLElement[];
}

export function Dropdown(fieldInstance: Core.WithWidget) {
  const field = fieldInstance.widget as Core.InputWidget<string | null>;

  const { uid, errors, value, isTouched, templateData, onFilter, onValueChanged, onBlur } =
    useControlField<string | number | null, DropdownProps<never>>(field);

  const [range, setRange] = useState({ start: 0, end: 10 });
  const [listItems, setListItems] = useState<ListItem<never>[]>([]);
  const [filteredItems, setFilteredItems] = useState<ListItem<never>[]>([]);
  const [focusedIndex, setFocusedIndex] = useState<number>(-1);
  const [isFiltering, setIsFiltering] = useState(false);
  const [isListVisible, setIsListVisible] = useState(false);
  const [selectedItem, setSelectedItem] = useState<ListItem<never> | undefined>(undefined);

  const listRef = useRef<GuiListElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const labelRef = useRef<GuiLabelElement>(null);

  const visibleItems = useMemo(() => listItems.slice(range.start, range.end), [listItems, range]);

  const closeList = useCallback(() => {
    onBlur();
    setIsListVisible(false);
    setIsFiltering(false);
  }, [onBlur]);

  const handleValueChange = useCallback(
    (newValue: OptionValue | null) => {
      onValueChanged(newValue);

      if (inputRef.current) {
        const items = templateData.items || [];
        const selectedItem = items.find((item: any) =>
          templateData.valueField ? item[templateData.valueField] === newValue : item === newValue,
        );

        if (selectedItem) {
          const displayValue = templateData.valueField
            ? (selectedItem as any)[templateData.valueField]
            : selectedItem;

          inputRef.current.value = String(displayValue);
        } else if (!newValue) {
          inputRef.current.value = '';
        }
      }

      setIsListVisible(false);
      setIsFiltering(false);
    },
    [onValueChanged, templateData],
  );

  const handleClickItem = useCallback(
    (item: ListItem<never>, index: number) => {
      if (templateData.readonly) return;

      handleValueChange(item.value);
      onFilter('');
      setFocusedIndex(index);
      setSelectedItem(item);
      setIsFiltering(false);
      setIsListVisible(false);

      if (listRef.current) {
        listRef.current.focusItemAtIndex(index);
      }
    },
    [handleValueChange, onFilter, templateData.readonly],
  );

  useEffect(() => {
    const element = listRef.current;
    if (!element) return;

    const handleRangeChange = (e: Event) => {
      const { startIndex, endIndex } = (e as CustomEvent).detail;
      setRange({ start: startIndex, end: endIndex });
    };

    const handleUpdateItems = (e: Event) => {
      const items = (e as CustomEvent).detail;
      setListItems(items ? [...items] : []);
    };

    const handleFocusChange = (e: Event) => {
      const index = (e as CustomEvent).detail.index;
      setFocusedIndex(index);
    };

    const handleChange = (e: Event) => {
      const val = (e as CustomEvent).detail.value;
      handleValueChange(val);
      setSelectedItem(listItems.find((item) => item.value === val));
      setIsFiltering(false);
      setIsListVisible(false);
    };

    element.addEventListener('gui-range-change', handleRangeChange);
    element.addEventListener('gui-update-items', handleUpdateItems);
    element.addEventListener('gui-focus-change', handleFocusChange);
    element.addEventListener('change', handleChange);

    return () => {
      element.removeEventListener('gui-range-change', handleRangeChange);
      element.removeEventListener('gui-update-items', handleUpdateItems);
      element.removeEventListener('gui-focus-change', handleFocusChange);
      element.removeEventListener('change', handleChange);
    };
  }, [handleValueChange, listItems, onValueChanged]);

  useEffect(() => {
    const handleDocumentClick = (event: MouseEvent) => {
      if (!isListVisible) return;

      const target = event.target as Node;
      const clickedInput = inputRef.current && inputRef.current.contains(target);
      const clickedList = listRef.current && listRef.current.contains(target);

      if (!clickedInput && !clickedList) {
        closeList();
      }
    };

    document.addEventListener('click', handleDocumentClick);
    return () => document.removeEventListener('click', handleDocumentClick);
  }, [closeList, isListVisible]);

  useEffect(() => {
    const referenceField = templateData.labelField ?? templateData.valueField;
    const val = referenceField ? selectedItem?.template[referenceField] : selectedItem?.template;
    inputRef.current!.value = val ?? '';
  }, [selectedItem, templateData.labelField, templateData.valueField]);

  useEffect(() => {
    if (labelRef.current && inputRef.current && listRef.current) {
      labelRef.current.targetElement = [inputRef.current, listRef.current];
    }
  }, []);

  const handleInputKeyDown = async (event: React.KeyboardEvent<HTMLInputElement>) => {
    const key = event.key;

    switch (key) {
      case 'ArrowDown':
        event.preventDefault();

        setIsListVisible(true);

        setTimeout(() => {
          if (listRef.current) {
            listRef.current.focus();
            listRef.current.scrollToSelectedIndex();
          }
        }, 0);
        break;
      case 'Enter':
        if (!inputRef.current?.value) {
          handleValueChange(null);
        }
        break;
    }
  };

  const filterItems = useCallback(
    (filterValue: string) => {
      const asyncFiltering = !!field.on?.filter;

      onFilter(filterValue);

      if (filterValue && !asyncFiltering) {
        setIsFiltering(true);
        setIsListVisible(true);

        const searchFields =
          templateData.searchFields ??
          ([templateData.labelField, templateData.valueField].filter(
            (field) => !!field,
          ) as string[]);
        const hasSearchFields = searchFields.length > 0;
        const items = templateData.items || [];
        const filteredItems = items.filter((item: any) => {
          const keys = Object.keys(item);

          // If it's a primitive value, we search by value
          const isPrimitiveValue = !keys.length;
          if (isPrimitiveValue) {
            return item.toString().toLowerCase().includes(filterValue.toLowerCase());
          }

          // Otherwise, we search by object
          const reduceFunc = (acc: boolean, prop: string) =>
            acc || item[prop].toString().toLowerCase().includes(filterValue.toLowerCase());

          return hasSearchFields
            ? keys.filter((prop: string) => searchFields.includes(prop)).reduce(reduceFunc, false)
            : keys.reduce(reduceFunc, false);
        });

        setFilteredItems(filteredItems);
      } else {
        setIsFiltering(false);
        setFilteredItems([...(templateData.items || [])]);
      }
    },
    [
      field.on?.filter,
      onFilter,
      templateData.items,
      templateData.labelField,
      templateData.searchFields,
      templateData.valueField,
    ],
  );

  const debouncedFilter = useDebounceCallback(filterItems, templateData.inputDebounce ?? 500);

  const handleInputFilter = (event: React.FormEvent<HTMLInputElement>) => {
    const filterValue = (event.target as HTMLInputElement).value;

    if (!isListVisible) {
      setIsListVisible(true);
    }

    debouncedFilter(filterValue);
  };

  const handleInputFocus = () => {
    setIsListVisible(true);

    setTimeout(() => {
      if (listRef.current) {
        listRef.current.scrollToSelectedIndex();
      }
    }, 0);
  };

  const handleFocusOut = (e: React.FocusEvent) => {
    const newFocusTarget = e.relatedTarget as Node;
    const isGoingToInput = inputRef.current && inputRef.current.contains(newFocusTarget);
    const isGoingToList = listRef.current && listRef.current.contains(newFocusTarget);

    if (isGoingToInput || isGoingToList) {
      return;
    }

    closeList();
  };

  const ItemRenderer = (useItemRenderer(templateData.itemRenderer as string) ||
    DefaultListItemRenderer) as React.ComponentType<ListItemRendererProps<any>>;
  const label = templateData.label as string;
  const isRequired = (templateData.validator as Core.Validator)?.required;
  const isDisabled = templateData.disabled as boolean;
  const isReadOnly = templateData.readonly as boolean;
  const asyncFiltering = !!field.on?.filter;

  return (
    <div className="gui-dropdown" style={{ flex: templateData.size }}>
      <gui-label
        ref={labelRef}
        uid={uid}
        label={label}
        hint={templateData.hint}
        errors={errors}
        touched={isTouched}
        required={isRequired}
      ></gui-label>

      <div className="gui-field">
        <input
          ref={inputRef}
          type="text"
          id={uid}
          data-cy={`${uid}_textinput`}
          defaultValue={value ?? ''}
          required={isRequired}
          disabled={isDisabled}
          readOnly={isReadOnly}
          placeholder={templateData.placeholder ?? ''}
          onKeyDown={handleInputKeyDown}
          onInput={handleInputFilter}
          onFocus={handleInputFocus}
          onBlur={handleFocusOut}
        />

        <gui-list
          ref={listRef}
          id={`${uid}-list`}
          uid={uid}
          value={value ?? ''}
          valueField={templateData.valueField as string}
          items={isFiltering && !asyncFiltering ? filteredItems : templateData.items}
          itemHeight={templateData.itemHeight}
          height={templateData.height}
          required={isRequired}
          touched={isTouched}
          disabled={isDisabled || isReadOnly}
          readOnly={isReadOnly}
          hidden={!isListVisible}
          onFocus={handleInputFocus}
          onBlur={handleFocusOut}
        >
          {visibleItems.map((item, index) => {
            const absoluteIndex = range.start + index;
            const isSelected = value === item.value;
            const isFocused = focusedIndex === absoluteIndex;

            return (
              <div
                key={absoluteIndex}
                role="option"
                tabIndex={-1}
                className="gui-list__item-wrapper"
                id={`${uid}-item-${absoluteIndex}`}
                style={{ height: `${templateData.itemHeight || 40}px` }}
                aria-selected={isSelected}
                onClick={() => handleClickItem(item, absoluteIndex)}
              >
                <ItemRenderer
                  template={item.template}
                  value={item.value}
                  index={absoluteIndex}
                  selected={isSelected}
                  disabled={isDisabled || isReadOnly}
                  focused={isFocused}
                />
              </div>
            );
          })}
        </gui-list>
      </div>

      <gui-errors errors={errors} touched={isTouched}></gui-errors>
    </div>
  );
}
