// libs/angular-vanilla/src/lib/components/form/form.component.ts
import { CommonModule } from '@angular/common';
import { Component, computed, input, output, Type } from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import { vanillaSchemaToFieldMap } from '@golemui/shared-vanilla';
import {
  CustomValidatorSchemas,
  initValidators,
  jsonSchemaValidators,
} from '@golemui/validators-vanilla';
import { vanillaWidgetLoaders } from '../../widget.loaders';

@Component({
  imports: [CommonModule, Angular.FormCoreComponent],
  selector: 'gui-form',
  templateUrl: './form.component.html',
})
export class FormComponent {
  formDef = input.required<string | Record<string, any>>();
  widgetLoaders = input.required<Core.WidgetLoaders<Type<Core.WithWidget>>>({});
  data = input<Record<string, any>>({});
  middlewares = input<Core.Middleware<Core.State, Core.Action>[]>([]);
  validators = input<CustomValidatorSchemas>({});
  validateOn = input<Core.ValidateOn>('eager');
  itemRenderers = input<Record<string, Angular.AngularItemRenderer<any>>>({});
  localization = input<Core.I18nTranslator>();
  direction = computed(() => {
    return Core.getDirectionFromLanguage(this.localization()?.lang ?? 'en');
  });

  protected customWidgetLoaders = computed(() => ({
    ...vanillaWidgetLoaders,
    ...this.widgetLoaders(),
  }));
  protected customValidators = computed(() => initValidators({ ...this.validators() }));
  protected customMiddlewares = computed(() => [
    Core.jsonSchemaMiddleware(vanillaSchemaToFieldMap(jsonSchemaValidators)),
    ...this.middlewares(),
  ]);

  formHealth = output<Core.FormHealth>();
  formEvent = output<Core.FormEvent>();
}

<gui-core-form
  [attr.dir]="direction()"
  [formDef]="formDef()"
  [data]="data()"
  [widgetLoaders]="customWidgetLoaders()"
  [middlewares]="customMiddlewares()"
  [validators]="customValidators()"
  [validateOn]="validateOn()"
  [itemRenderers]="itemRenderers()"
  [localization]="localization()"
  (formHealth)="formHealth.emit($event)"
  (formEvent)="formEvent.emit($event)"
></gui-core-form>

// libs/react-vanilla/src/lib/components/Form.tsx
import * as Core from '@golemui/core';
import * as React from '@golemui/react';
import { ReactItemRenderer } from '@golemui/react';
import { vanillaSchemaToFieldMap } from '@golemui/shared-vanilla';
import {
  CustomValidatorSchemas,
  initValidators,
  jsonSchemaValidators,
} from '@golemui/validators-vanilla';
import { ComponentType } from 'react';
import { vanillaWidgetLoaders } from '../widget.loaders';

export interface ReactFormComponentProps {
  formDef: string | Record<string, any>;
  // TODO: this should be customWidgetLoaders
  widgetLoaders?: Core.WidgetLoaders<ComponentType<Core.WithWidget>>;
  itemRenderers?: Record<string, ReactItemRenderer<any>>;
  localization?: Core.I18nTranslator;
  validators?: CustomValidatorSchemas;
  middlewares?: Core.Middleware<Core.State, Core.Action>[];
  validateOn?: Core.ValidateOn;
  data?: Record<string, any>;
  formName?: string;
  formEvent?: (event: Core.FormEvent) => void;
  formHealth?: (formHealth: Core.FormHealth) => void;
}

export const FormComponent = ({
  formDef,
  data = undefined,
  widgetLoaders = {},
  itemRenderers = {},
  localization,
  validators = {},
  middlewares = [],
  validateOn = 'eager',
  formHealth = undefined,
  formEvent = undefined,
}: ReactFormComponentProps) => {
  // TODO: this should be customWidgetLoaders
  const customWidgetLoaders = { ...vanillaWidgetLoaders, ...widgetLoaders };
  const customItemRenderers = { ...itemRenderers };
  const customValidators = initValidators({ ...validators });
  const customMiddlewares = [
    Core.jsonSchemaMiddleware(vanillaSchemaToFieldMap(jsonSchemaValidators)),
    ...middlewares,
  ];
  const direction = Core.getDirectionFromLanguage(localization?.lang ?? 'en');
  return (
    <React.FormComponent
      direction={direction}
      formDef={formDef}
      data={data}
      widgetLoaders={customWidgetLoaders}
      middlewares={customMiddlewares}
      itemRenderers={customItemRenderers}
      localization={localization}
      validators={customValidators}
      validateOn={validateOn}
      formHealth={formHealth}
      formEvent={formEvent}
    />
  );
};
