// libs/angular-vanilla/src/lib/number/number.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import { NumberinputProps } from '@golemui/shared-vanilla';

@Component({
  standalone: true,
  selector: 'gui-number',
  imports: [CommonModule],
  providers: [Angular.ControlFieldAdapter],
  templateUrl: './number.component.html',
  styleUrl: '../styles.scss',
  host: {
    class: 'gui-number',
  },
})
export class NumberComponent implements OnInit, OnDestroy, Core.WithField {
  field!: Core.ControlField<number>;
  protected adapter: Angular.ControlFieldAdapter<number, NumberinputProps> = inject(
    Angular.ControlFieldAdapter,
  );

  ngOnInit(): void {
    this.adapter.init(this.field);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }

  valueChanged(event: Event) {
    const target = event.target as HTMLInputElement;
    this.adapter.valueChanged(target.valueAsNumber);
  }
}

@let templateData = adapter.templateData();
@let showErrors = templateData.touched && templateData.errors && templateData.errors.length > 0;

<label [for]="field.uid">
  {{ templateData.label + (templateData.validator?.required ? ' *' : '') }}
  @if (templateData.hint) {
    <div class="gui-field-hint" [attr.id]="field.uid + '_hint'">{{ templateData.hint }}</div>
  }
</label>
<div class="gui-field">
  <input
    type="number"
    inputmode="numeric"
    [id]="field.uid"
    [class]="{
      'gui-number--icon': templateData.icon,
      'gui-number--icon-right': templateData.iconPosition === 'right',
    }"
    [value]="templateData.value ?? ''"
    [disabled]="templateData.disabled"
    [readOnly]="templateData.readonly"
    [attr.placeholder]="templateData.placeholder"
    [attr.min]="templateData.min"
    [attr.max]="templateData.max"
    [attr.step]="templateData.step"
    (input)="valueChanged($event)"
    (blur)="adapter.onBlur()"
    [attr.aria-invalid]="showErrors"
    [attr.aria-errormessage]="showErrors ? field.uid + '_errors' : undefined"
    [attr.aria-required]="templateData.validator?.required"
    [attr.aria-describedby]="templateData.hint ? field.uid + '_hint' : undefined"
  />

  @if (templateData.icon) {
    <span
      class="gui-field-icon"
      [class.gui-field-icon--right]="templateData.iconPosition === 'right'"
      [ngClass]="templateData.icon"
    ></span>
  }
</div>

@if (showErrors) {
  <ul class="gui-validator" [id]="field.uid + '_errors'">
    @for (error of templateData.errors; track $index) {
      <li class="gui-validator__error" role="status">{{ error }}</li>
    }
  </ul>
}

// libs/react-vanilla/src/lib/components/Number.tsx
import * as Core from '@golemui/core';
import { useControlField } from '@golemui/react';
import { NumberinputProps } from '@golemui/shared-vanilla';
import { useCallback } from 'react';
import '../styles.scss';
import { Errors } from './shared/Errors';

export function NumberInput(fieldInstance: Core.WithField) {
  const field = fieldInstance.field as Core.ControlField<number>;
  const {
    uid,
    validator,
    errors,
    value,
    isDisabled,
    isReadonly,
    isTouched,
    label,
    props,
    onValueChanged,
    onBlur,
  } = useControlField<number, NumberinputProps>(field);

  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => onValueChanged(e.target.valueAsNumber),
    [onValueChanged],
  );

  const hint = props.hint;
  const placeholder = props.placeholder;
  const step = props.step;
  const icon = props.icon;
  const iconPosition = props.iconPosition;
  const showErrors = isTouched && errors && errors.length > 0;

  return (
    <div className="gui-number">
      <label htmlFor={uid}>
        {label + (validator?.required ? ' *' : '')}
        {hint && (
          <div className="gui-field-hint" id={`${uid}_hint`}>
            {hint}
          </div>
        )}
      </label>
      <div className="gui-field">
        <input
          type="number"
          inputMode="numeric"
          id={uid}
          className={`${icon ? 'gui-number--icon' : ''} ${iconPosition === 'right' ? 'gui-number--icon-right' : ''}`}
          required={validator?.required}
          value={value ?? ''}
          disabled={isDisabled}
          readOnly={isReadonly}
          step={step}
          placeholder={placeholder ?? undefined}
          onInput={handleChange}
          onBlur={onBlur}
          aria-invalid={showErrors}
          aria-errormessage={showErrors ? `${uid}_errors` : undefined}
          aria-required={validator?.required}
          aria-describedby={hint ? `${uid}_hint` : undefined}
        />
        {icon && (
          <span
            className={`${icon} gui-field-icon ${iconPosition === 'right' ? 'gui-field-icon--right' : ''}`}
          ></span>
        )}
      </div>
      {showErrors && <Errors errors={errors} uid={uid} />}
    </div>
  );
}
