// libs/angular-vanilla/src/lib/radiogroup/radiogroup.component.ts
import { CommonModule } from '@angular/common';
import { Component, effect, inject, OnDestroy, OnInit } from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import {
  createOptionMapper,
  inferOptionValue,
  isOption,
  isOptionValue,
  isProtoOption,
  OptionValue,
  RadiogroupProps,
} from '@golemui/shared-vanilla';

@Component({
  standalone: true,
  selector: 'gui-radiogroup',
  imports: [CommonModule],
  providers: [Angular.ControlFieldAdapter],
  templateUrl: './radiogroup.component.html',
  styleUrl: '../styles.scss',
  host: {
    class: 'gui-radiogroup',
  },
})
export class RadiogroupComponent implements OnInit, OnDestroy, Core.WithField {
  field!: Core.ControlField<string>;
  protected adapter: Angular.ControlFieldAdapter<string, RadiogroupProps> = inject(
    Angular.ControlFieldAdapter,
  );
  protected optionsLoading = false;
  protected hasMatchingValue = false;

  constructor() {
    effect(() => {
      const opts = this.adapter.templateData().options;
      if (Array.isArray(opts) && opts.length > 0) {
        if (isOption(opts[0])) {
          // nothing to do
        } else if (isOptionValue(opts[0])) {
          this.adapter.templateData.update((current) => ({
            ...current,
            options: (current.options as unknown as OptionValue[]).map((opt) => ({
              label: opt.toString(),
              value: opt,
            })),
          }));
        } else if (isProtoOption(opts[0], this.field.props as RadiogroupProps)) {
          const optionMapper = createOptionMapper(opts[0], this.field.props as RadiogroupProps);
          this.adapter.templateData.update((current) => ({
            ...current,
            options: current.options.map(optionMapper),
          }));
        } else {
          throw new Error('Invalid option shape');
        }
        const selection = this.adapter.templateData().value;
        this.hasMatchingValue =
          this.adapter.templateData().options.find(({ value }) => value === selection) !==
          undefined;
      }
    });
  }

  ngOnInit(): void {
    this.adapter.init(this.field);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }

  valueChanged(event: Event) {
    if (this.adapter.templateData().readonly) {
      event.preventDefault();
    } else {
      const target = event.target as HTMLInputElement;
      this.adapter.valueChanged(
        inferOptionValue(target.value, this.adapter.templateData().options),
      );
    }
  }
}

@let templateData = adapter.templateData();
@let showErrors = templateData.touched && templateData.errors && templateData.errors.length > 0;

<label [for]="field.uid" class="gui-field__label">
  {{ templateData.label + (templateData.validator?.required ? ' *' : '') }}
  @if (templateData.hint) {
    <div class="gui-field-hint" [attr.id]="field.uid + '_hint'">{{ templateData.hint }}</div>
  }
</label>
<div class="gui-field">
  @if (optionsLoading === true) {
    <span>Loading...</span>
  } @else {
    @for (opt of templateData.options; track opt.value; let i = $index) {
      <label [for]="field.uid + '_' + i">
        <input
          type="radio"
          [id]="field.uid + '_' + i"
          [name]="field.uid"
          [value]="opt.value"
          [checked]="hasMatchingValue && opt.value === templateData.value"
          [disabled]="templateData.disabled || templateData.readonly"
          [attr.aria-readonly]="templateData.disabled || templateData.readonly"
          (change)="valueChanged($event)"
          (blur)="adapter.onBlur()"
        />
        {{ opt.label }}
      </label>
    }
  }
</div>

@if (showErrors) {
  <ul class="gui-validator" [id]="field.uid + '_errors'">
    @for (error of templateData.errors; track $index) {
      <li class="gui-validator__error" role="status">{{ error }}</li>
    }
  </ul>
}

// libs/react-vanilla/src/lib/components/RadioGroup.tsx
import * as Core from '@golemui/core';
import { useControlField } from '@golemui/react';
import {
  createOptionMapper,
  inferOptionValue,
  isOption,
  isOptionValue,
  isProtoOption,
  Option,
  OptionValue,
  RadiogroupProps,
  SelectProps,
} from '@golemui/shared-vanilla';
import { useCallback, useEffect, useState } from 'react';
import '../styles.scss';
import { Errors } from './shared/Errors';

export function RadioGroup(fieldInstance: Core.WithField) {
  const field = fieldInstance.field as Core.ControlField<string>;
  const {
    uid,
    validator,
    errors,
    value,
    isDisabled,
    isReadonly,
    isTouched,
    label,
    props,
    onValueChanged,
    onBlur,
  } = useControlField<OptionValue, RadiogroupProps>(field);

  const hint = props.hint;

  const [optionsLoading, setOptionsLoading] = useState(false);
  const [hasMatchingValue, setHasMatchingValue] = useState(false);
  const [options, setOptions] = useState<Option[]>([]);

  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      onValueChanged(inferOptionValue(e.target.value, options));
    },
    [onValueChanged, options],
  );

  useEffect(() => {
    let opts = props.options;
    if (Array.isArray(opts) && opts.length > 0) {
      if (isOption(opts[0])) {
        // Nothing to do here, It's an option already
      } else if (isOptionValue(opts[0])) {
        // It's a flat array: string[] | number[]
        opts = (opts as unknown as OptionValue[]).map((opt) => ({
          label: opt.toString(),
          value: opt,
        }));
      } else if (isProtoOption(opts[0], props as SelectProps)) {
        const optionMapper: (item: unknown) => Option = createOptionMapper(opts[0], props);
        opts = opts.map(optionMapper);
      } else {
        throw new Error('Invalid option shape');
      }
      setOptions(opts);

      const matching = opts.find((opt) => opt.value === value) !== undefined;
      setHasMatchingValue(matching);
    }
  }, [props, value]);

  const showErrors = isTouched && errors && errors.length > 0;

  return (
    <div className="gui-radiogroup">
      <label htmlFor={uid} className="gui-field__label">
        {label + (validator?.required ? ' *' : '')}
        {hint && (
          <div className="gui-field-hint" id={`${uid}_hint`}>
            {hint}
          </div>
        )}
      </label>
      <div className="gui-field">
        {optionsLoading ? (
          <span>Loading...</span>
        ) : (
          (options || []).map((opt, index) => (
            <label htmlFor={`${uid}_${index}`} key={`k-${opt.value}`}>
              <input
                type="radio"
                id={`${uid}_${index}`}
                name={uid}
                value={opt.value}
                checked={hasMatchingValue && opt.value === value}
                disabled={isDisabled || isReadonly}
                onChange={handleChange}
                onBlur={onBlur}
              />
              {opt.label}
            </label>
          ))
        )}
      </div>
      {showErrors && <Errors errors={errors} uid={uid} />}
    </div>
  );
}
