// libs/angular-vanilla/src/lib/components/renderer/renderer.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, OnDestroy, OnInit, Type } from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import { RendererProps } from '@golemui/shared-vanilla';

@Component({
  standalone: true,
  selector: 'gui-renderer-component',
  imports: [CommonModule],
  providers: [Angular.DisplayFieldAdapter],
  templateUrl: './renderer.component.html',
  host: {
    class: 'gui-renderer',
  },
})
export class RendererComponent implements OnInit, OnDestroy, Core.WithField {
  field!: Core.DisplayField;

  protected adapter: Angular.DisplayFieldAdapter<RendererProps<Type<any>>> = inject(
    Angular.DisplayFieldAdapter,
  );

  ngOnInit(): void {
    this.adapter.init(this.field);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

@let templateData = adapter.templateData();

<div class="gui-field" [id]="field.uid">
  <ng-container *ngComponentOutlet="templateData.render"></ng-container>
</div>

// libs/react-vanilla/src/lib/components/Renderer.tsx
import * as Core from '@golemui/core';
import { useDisplayField } from '@golemui/react';
import { RendererProps } from '@golemui/shared-vanilla';
import { ReactNode } from 'react';

export function Renderer(fieldInstance: Core.WithField) {
  const field = fieldInstance.field as Core.DisplayField;
  const { uid, templateData } = useDisplayField<RendererProps<ReactNode>>(field);
  const renderedElement = templateData?.render;
  return (
    <div className="gui-renderer">
      <div className="gui-field" id={uid}>
        {renderedElement}
      </div>
    </div>
  );
}
