// libs/angular-vanilla/src/lib/components/select/select.component.ts
import { CommonModule } from '@angular/common';
import { Component, effect, inject, OnDestroy, OnInit } from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import {
  createOptionMapper,
  inferOptionValue,
  isOption,
  isOptionValue,
  isProtoOption,
  OptionValue,
  SelectProps,
} from '@golemui/shared-vanilla';
import { LabelComponent } from '../../utils/templates/label.component';
import { ErrorsComponent } from '../../utils/templates/errors.component';
import { IconComponent } from '../../utils/templates/icon.component';
import { GuiAriaDirective } from '../../directives/aria.directive';

@Component({
  standalone: true,
  selector: 'gui-select',
  imports: [CommonModule, LabelComponent, ErrorsComponent, IconComponent, GuiAriaDirective],
  providers: [Angular.ControlFieldAdapter],
  templateUrl: './select.component.html',
  host: {
    class: 'gui-select',
  },
})
export class SelectComponent implements OnInit, OnDestroy, Core.WithField {
  field!: Core.ControlField<string>;
  protected adapter: Angular.ControlFieldAdapter<string, SelectProps> = inject(
    Angular.ControlFieldAdapter,
  );
  protected optionsLoading = false;
  protected hasMatchingValue = false;

  constructor() {
    effect(() => {
      const opts = this.adapter.templateData().options;
      if (Array.isArray(opts) && opts.length > 0) {
        if (isOption(opts[0])) {
          // nothing to do
        } else if (isOptionValue(opts[0])) {
          this.adapter.templateData.update((current) => ({
            ...current,
            options: (current.options as unknown as OptionValue[]).map((opt) => ({
              label: opt.toString(),
              value: opt,
            })),
          }));
        } else if (isProtoOption(opts[0], this.field.props as SelectProps)) {
          const optionMapper = createOptionMapper(opts[0], this.field.props as SelectProps);
          this.adapter.templateData.update((current) => ({
            ...current,
            options: current.options.map(optionMapper),
          }));
        } else {
          throw new Error('Invalid option shape');
        }
        const selection = this.adapter.templateData().value;
        this.hasMatchingValue =
          this.adapter.templateData().options.find(({ value }) => value === selection) !==
          undefined;
      }
    });
  }

  ngOnInit(): void {
    this.adapter.init(this.field);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }

  valueChanged(event: Event) {
    if (this.adapter.templateData().readonly) {
      event.preventDefault();
    } else {
      const target = event.target as HTMLSelectElement;
      this.adapter.valueChanged(
        inferOptionValue(target.value, this.adapter.templateData().options),
      );
    }
  }
}

@let templateData = adapter.templateData();
@let showErrors = templateData.touched && templateData.errors && templateData.errors.length > 0;

<label gui-label [for]="field.uid" [uid]="field.uid" [templateData]="templateData"></label>

<div class="gui-field">
  <select
    guiAria
    [uid]="field.uid"
    [attr.data-cy]="field.uid + '_select'"
    [templateData]="templateData"
    [id]="field.uid"
    [class]="{
      'gui-select--icon': templateData.icon,
      'gui-select--icon-right': templateData.iconPosition === 'right',
    }"
    [required]="templateData.validator?.required"
    [value]="templateData.value ?? ''"
    [disabled]="templateData.disabled || templateData.readonly"
    (change)="valueChanged($event)"
    (blur)="adapter.onBlur()"
  >
    @if (optionsLoading === true) {
      <option [value]="">Loading...</option>
    } @else {
      <option value="" [attr.selected]="!hasMatchingValue ? '' : null" disabled>
        {{ templateData.placeholder ?? 'Select an option' }}
      </option>

      @for (opt of templateData.options; track opt.value) {
        <option
          [value]="opt.value"
          [attr.selected]="hasMatchingValue && opt.value === templateData.value ? '' : null"
        >
          {{ opt.label }}
        </option>
      }
    }
  </select>

  @if (templateData.icon) {
    <span gui-icon [templateData]="templateData"></span>
  }
</div>

@if (showErrors) {
  <ul gui-errors [uid]="field.uid" [templateData]="templateData"></ul>
}

// libs/react-vanilla/src/lib/components/Select.tsx
import * as Core from '@golemui/core';
import { cn, useControlField } from '@golemui/react';
import {
  createOptionMapper,
  inferOptionValue,
  isOption,
  isOptionValue,
  isProtoOption,
  Option,
  OptionValue,
  SelectProps,
} from '@golemui/shared-vanilla';
import { useCallback, useEffect, useState } from 'react';
import '../styles.scss';
import { Errors } from './shared/Errors';

export function Select(fieldInstance: Core.WithField) {
  const field = fieldInstance.field as Core.ControlField<string>;
  const {
    uid,
    validator,
    errors,
    value,
    isDisabled,
    isReadonly,
    isTouched,
    label,
    props,
    onValueChanged,
    onBlur,
  } = useControlField<OptionValue, SelectProps>(field);

  const hint = props.hint;
  const placeholder = props.placeholder;
  const icon = props.icon;
  const iconPosition = props.iconPosition;

  const [optionsLoading, setOptionsLoading] = useState(false);
  const [hasMatchingValue, setHasMatchingValue] = useState(false);
  const [options, setOptions] = useState<Option[]>([]);
  const [safeValue, setSafeValue] = useState<OptionValue | undefined>();

  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLSelectElement>) => {
      onValueChanged(inferOptionValue(e.target.value, options));
    },
    [onValueChanged, options],
  );

  useEffect(() => {
    let opts = props.options;
    if (Array.isArray(opts) && opts.length > 0) {
      if (isOption(opts[0])) {
        // Nothing to do here, It's an option already
      } else if (isOptionValue(opts[0])) {
        // It's a flat array: string[] | number[]
        opts = (opts as unknown as OptionValue[]).map((opt) => ({
          label: opt.toString(),
          value: opt,
        }));
      } else if (isProtoOption(opts[0], props as SelectProps)) {
        const optionMapper: (item: unknown) => Option = createOptionMapper(opts[0], props);
        opts = opts.map(optionMapper);
      } else {
        throw new Error('Invalid option shape');
      }
      setOptions(opts);
      // If value is not one of your real options, map it back to "" so that the placeholder becomes selected.
      const matching = opts.find((opt) => opt.value === value) !== undefined;
      setHasMatchingValue(matching);
      setSafeValue(matching ? value : '');
    }
  }, [props, value]);

  const showErrors = isTouched && errors && errors.length > 0;

  return (
    <div className="gui-select">
      <label htmlFor={uid}>
        {label + (validator?.required ? ' *' : '')}
        {hint && (
          <div className="gui-field-hint" id={`${uid}_hint`}>
            {hint}
          </div>
        )}
      </label>
      <div className="gui-field">
        <select
          id={uid}
          className={cn({
            'gui-select--icon': !!icon,
            'gui-select--icon-right': iconPosition === 'right',
          })}
          required={validator?.required}
          value={safeValue ?? ''}
          disabled={isDisabled || isReadonly}
          aria-invalid={showErrors}
          aria-readonly={isDisabled || isReadonly}
          aria-errormessage={showErrors ? `${uid}_errors` : undefined}
          aria-required={validator?.required}
          aria-describedby={hint ? `${uid}_hint` : undefined}
          onChange={handleChange}
          onBlur={onBlur}
        >
          {optionsLoading ? (
            <option value="">Loading...</option>
          ) : (
            <>
              <option value="" disabled key="select-an-option">
                {placeholder ?? 'Select an option'}
              </option>

              {(options || []).map((opt) => (
                <option value={opt.value} key={`k-${opt.value}`}>
                  {opt.label}
                </option>
              ))}
            </>
          )}
        </select>

        {icon && (
          <span
            className={cn(icon, 'gui-field-icon', {
              'gui-field-icon--right': iconPosition === 'right',
            })}
          ></span>
        )}
      </div>
      {showErrors && <Errors errors={errors} uid={uid} />}
    </div>
  );
}
