// libs/angular-vanilla/src/lib/components/stack/stack.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import { StackProps } from '@golemui/shared-vanilla';

@Component({
  standalone: true,
  selector: 'gui-stack-layout',
  imports: [CommonModule, Angular.FieldDirective],
  providers: [Angular.LayoutFieldAdapter],
  templateUrl: './stack.component.html',
  host: {
    class: 'gui-stack',
    '[style.flex]': 'this.adapter.templateData().size',
  },
})
export class StackComponent implements OnInit, OnDestroy, Core.WithWidget {
  widget!: Core.LayoutWidget;

  protected adapter: Angular.LayoutFieldAdapter<StackProps> = inject(Angular.LayoutFieldAdapter);

  ngOnInit(): void {
    this.adapter.init(this.widget);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

@let templateData = adapter.templateData();

<div
  class="gui-stack__field"
  [class.gui-stack__field--horizontal]="templateData.direction === 'horizontal'"
  [id]="widget.uid"
>
  @for (child of templateData.children; track child.uid) {
    <ng-container guiField [field]="child" />
  }
</div>

// libs/react-vanilla/src/lib/components/Stack.tsx
import * as Core from '@golemui/core';
import { useLayoutWidget, WidgetRenderer } from '@golemui/react';
import { StackProps } from '@golemui/shared-vanilla';
import { useCallback } from 'react';
import '../styles.scss';

export function Stack(widgetInstance: Core.WithWidget) {
  const widget = widgetInstance.widget as Core.LayoutWidget;
  const { uid, children, templateData } = useLayoutWidget<StackProps>(widget);

  const renderWidgets = useCallback(() => {
    return children.map((widget) => (
      <WidgetRenderer key={widget.uid} widget={widget as Core.NonFunctionWidget<string>} />
    ));
  }, [children]);

  const direction = templateData.direction === 'horizontal' ? 'gui-stack__field--horizontal' : '';
  return (
    <div className="gui-stack" style={{ flex: templateData.size }}>
      <div className={`gui-stack__widget ${direction}`} id={uid}>
        {renderWidgets()}
      </div>
    </div>
  );
}
