// libs/angular-vanilla/src/lib/stack/stack.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import { StackProps } from '@golemui/shared-vanilla';

@Component({
  standalone: true,
  selector: 'gui-stack',
  imports: [CommonModule, Angular.FieldDirective],
  providers: [Angular.LayoutFieldAdapter],
  templateUrl: './stack.component.html',
  styleUrls: ['../styles.scss', './stack.component.scss'],
  host: {
    class: 'gui-stack',
  },
})
export class StackComponent implements OnInit, OnDestroy, Core.WithField {
  field!: Core.LayoutField;

  protected adapter: Angular.LayoutFieldAdapter<StackProps> = inject(Angular.LayoutFieldAdapter);

  ngOnInit(): void {
    this.adapter.init(this.field);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

@let templateData = adapter.templateData();

<div
  class="gui-stack__field"
  [class.gui-stack__field--horizontal]="templateData.direction === 'horizontal'"
  [id]="field.uid"
>
  @for (child of templateData.children; track child.uid) {
    <ng-container guiField [field]="child" />
  }
</div>

// libs/react-vanilla/src/lib/components/Stack.tsx
import * as Core from '@golemui/core';
import { FieldRenderer, useLayoutField } from '@golemui/react';
import { StackProps } from '@golemui/shared-vanilla';
import { useCallback } from 'react';
import '../styles.scss';

export function Stack(fieldInstance: Core.WithField) {
  const field = fieldInstance.field as Core.LayoutField;
  const { uid, children, props } = useLayoutField<StackProps>(field);

  const renderFields = useCallback(() => {
    return children.map((field) => <FieldRenderer key={field.uid} field={field} />);
  }, [children]);

  const direction = props.direction === 'horizontal' ? 'gui-stack__field--horizontal' : '';
  return (
    <div className="gui-stack">
      <div className={`gui-stack__field ${direction}`} id={uid}>
        {renderFields()}
      </div>
    </div>
  );
}
