// libs/angular-vanilla/src/lib/components/toggle/toggle.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import * as Angular from '@golemui/angular';
import * as Core from '@golemui/core';
import { ToggleProps } from '@golemui/shared-vanilla';
import { LabelComponent } from '../../utils/templates/label.component';
import { ErrorsComponent } from '../../utils/templates/errors.component';
import { GuiAriaDirective } from '../../directives/aria.directive';

@Component({
  standalone: true,
  selector: 'gui-toggle',
  imports: [CommonModule, LabelComponent, ErrorsComponent, GuiAriaDirective],
  providers: [Angular.ControlFieldAdapter],
  templateUrl: './toggle.component.html',
  host: {
    class: 'gui-toggle',
    '[class.gui-toggle--left]': 'adapter.templateData().togglePosition === "left"',
  },
})
export class ToggleComponent implements OnInit, OnDestroy, Core.WithField {
  field!: Core.ControlField<string>;
  protected adapter: Angular.ControlFieldAdapter<string, ToggleProps> = inject(
    Angular.ControlFieldAdapter,
  );

  ngOnInit(): void {
    this.adapter.init(this.field);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }

  valueChanged(event: Event) {
    const target = event.target as HTMLInputElement;
    this.adapter.valueChanged(target.checked);
  }
}

@let templateData = adapter.templateData();
@let showErrors = templateData.touched && templateData.errors && templateData.errors.length > 0;

<label gui-label [for]="field.uid" [uid]="field.uid" [templateData]="templateData">
  @if (showErrors) {
    <ul
      gui-errors
      [uid]="field.uid"
      [templateData]="templateData"
      [attr.data-cy]="field.uid + '_validator-errors'"
    ></ul>
  }
</label>

<div class="gui-field gui-field--horizontal gui-toggle--switch">
  <input
    type="checkbox"
    guiAria
    [uid]="field.uid"
    [templateData]="templateData"
    [value]="templateData.value ?? false"
    [id]="field.uid"
    [attr.data-cy]="field.uid + '_switch'"
    [checked]="templateData.value ? true : undefined"
    [required]="templateData.validator?.required"
    [disabled]="templateData.disabled"
    [readonly]="templateData.readonly"
    (click)="!templateData.readonly && valueChanged($event)"
  />

  <span class="gui-toggle--slider" role="presentation"></span>
</div>

// libs/react-vanilla/src/lib/components/Toggle.tsx
import * as Core from '@golemui/core';
import { useControlField } from '@golemui/react';
import { ToggleProps } from '@golemui/shared-vanilla';
import { useCallback } from 'react';
import '../styles.scss';
import { Errors } from './shared/Errors';

export function Toggle(fieldInstance: Core.WithField) {
  const field = fieldInstance.field as Core.ControlField<boolean>;
  const { uid, errors, value, onValueChanged, onBlur, templateData, isTouched } = useControlField<
    boolean,
    ToggleProps
  >(field);

  const hint = templateData.hint;
  const togglePosition = templateData.togglePosition;
  const showErrors = isTouched && errors && errors.length > 0;
  const isRequired = (templateData.validator as Core.Validator)?.required;
  const isDisabled = templateData.disabled as boolean;
  const isReadonly = templateData.readonly as boolean;

  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => !isReadonly && onValueChanged(e.target.checked),
    [onValueChanged, isReadonly],
  );

  return (
    <div className={`gui-toggle ${togglePosition === 'left' ? 'gui-toggle--left' : ''}`}>
      <label className="gui-label" htmlFor={uid}>
        {templateData.label + (isRequired ? ' *' : '')}
        {hint && (
          <div className="gui-field-hint" id={`${uid}_hint`}>
            {hint}
          </div>
        )}
        {showErrors && <Errors errors={errors} uid={uid} />}
      </label>

      <div className="gui-field gui-field--horizontal gui-toggle--switch">
        <input
          type="checkbox"
          id={uid}
          data-cy={`${uid}_toggle`}
          checked={value ?? false}
          required={isRequired}
          disabled={isDisabled}
          readOnly={isReadonly}
          aria-readonly={isReadonly}
          onChange={handleChange}
          onBlur={onBlur}
        />

        <span className="gui-toggle--slider" role="presentation"></span>
      </div>
    </div>
  );
}
