// libs/react-vanilla/src/lib/components/Repeater.tsx
import * as Core from '@golemui/core';
import { FieldRenderer, RepeaterIndexContext, useControlField } from '@golemui/react';
import { RepeaterProps } from '@golemui/shared-vanilla';
import { useCallback } from 'react';
import '../styles.scss';

export function Repeater(fieldInstance: Core.WithField) {
  const field = fieldInstance.field as Core.ControlField<Record<string, unknown>[]>;
  const { uid, value, onValueChanged, templateData } = useControlField<
    Record<string, unknown>[],
    RepeaterProps
  >(field);

  const addItem = useCallback(
    (value: Record<string, unknown>[]) => {
      const newValue = [...(value ?? []), {}];
      onValueChanged(newValue);
    },
    [onValueChanged],
  );

  const removeItem = useCallback(
    (value: Record<string, unknown>[], index: number) => {
      const arr = [...(value ?? [])];
      arr.splice(index, 1);
      onValueChanged(arr);
    },
    [onValueChanged],
  );

  const renderFields = useCallback(() => {
    return value?.map((_, index) => {
      return (
        <RepeaterIndexContext.Provider value={index} key={`${uid}-${index}`}>
          <div className={'card'}>
            <FieldRenderer
              key={`${uid}-${index}`}
              field={templateData.template}
              repeaterIndex={index}
            />
            <button type="button" className="gui-button" onClick={() => removeItem(value, index)}>
              {templateData.removeLabel ?? 'Remove'}
            </button>
          </div>
        </RepeaterIndexContext.Provider>
      );
    });
  }, [templateData, value, uid, removeItem]);

  return (
    <div className="gui-repeater">
      <div id={uid}>
        {templateData.label && <h2 key={`${uid}-title`}>{templateData.label as string}</h2>}
        {renderFields()}
        <button
          type="button"
          className="gui-button"
          onClick={() => addItem(value || [])}
          disabled={templateData.limit ? templateData.limit === (value?.length ?? 0) : false}
        >
          {templateData.addLabel ?? 'Add'}
        </button>
      </div>
    </div>
  );
}

// libs/angular-vanilla/src/lib/repeater/repeater.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, OnDestroy, OnInit } from '@angular/core';
import * as Angular from '@formforge/angular';
import * as Core from '@formforge/core';
import { RepeaterProps } from '@formforge/shared-vanilla';

@Component({
  standalone: true,
  selector: 'ff-repeater',
  imports: [CommonModule, Angular.RepeaterFieldDirective],
  providers: [Angular.ControlAdapter, Angular.RepeaterFieldDirective],
  templateUrl: './repeater.component.html',
  styleUrls: ['../styles.scss', './repeater.component.scss'],
  host: {
    class: 'ff-repeater',
  },
})
export class RepeaterComponent implements OnInit, OnDestroy, Core.WithField {
  field!: Core.ControlField<Record<string, unknown>[]>;
  protected adapter: Angular.ControlAdapter<Record<string, unknown>[], RepeaterProps> = inject(
    Angular.ControlAdapter,
  );

  ngOnInit(): void {
    this.adapter.init(this.field);
  }

  addItem() {
    this.adapter.valueChanged([...(this.adapter.templateData().value ?? []), {}]);
  }

  removeItem(index: number) {
    const arr = [...(this.adapter.templateData().value ?? [])];
    arr.splice(index, 1);
    this.adapter.valueChanged(arr);
  }

  ngOnDestroy(): void {
    this.adapter.destroy();
  }
}

@let templateData = adapter.templateData();

<div [id]="field.uid">
  @if (templateData.label) {
    <h2>{{ templateData.label }}</h2>
  }
  @if (templateData.template && templateData.value) {
    @for (_ of templateData.value; track $index) {
      <div class="card">
        <ng-container
          ffRepeaterField
          [repeaterIndex]="$index"
          [field]="templateData.template"
        />
        <button type="button" (click)="removeItem($index)">
          {{ templateData.removeLabel ?? 'Remove' }}
        </button>
      </div>
    }
  }
  <button
    type="button"
    (click)="addItem()"
    [disabled]="
    templateData.limit
      ? templateData.limit === (templateData.value?.length ?? 0)
      : false
  "
  >
    {{ templateData.addLabel ?? 'Add' }}
  </button>
</div>
